### ISSUE TITLE
:[attribute-name] attribute position rule no longer enforced?

### ISSUE THREAD

**Issue by ajelcocks** [vuejs/eslint-plugin-vue#1002]
**Tell us about your environment**	
Windows 10

* **ESLint version:**	
5.16.0

* **eslint-plugin-vue version:**	
6.0.0 or 6.0.1

* **Node version:**	
10.15.0

**Please show your full configuration:**

```json
module.exports = {
  env: {
    browser: true,
    es6: true
  },
  extends: ["eslint:recommended", "plugin:vue/recommended"],
  globals: {
    Atomics: "readonly",
    SharedArrayBuffer: "readonly"
  },
  parser: "vue-eslint-parser",
  parserOptions: {
    ecmaVersion: 2018,
    parser: "babel-eslint",
    sourceType: "module",
    allowImportExportEverywhere: true,
    ecmaFeatures: {
      experimentalObjectRestSpread: true
    }
  },
  plugins: ["vue"],
  rules: {}
};
```

**What did you do?**	
1: Create project (Vue CLI v4.1.1 was used)
```
npx @vue/cli create vue-example
```
Accept default (babel, eslint)

package.json contains:
"eslint": "^5.16.0",
"eslint-plugin-vue": "^5.0.0",

2: Change HellowWorld.vue to 
```javascript
<template>
  <div class="hello">
    <p>
      <a
        target="_blank"
        rel="noopener"
        :href="cli"
      >vue-cli documentation</a>.
    </p>
  </div>
</template>

<script>
export default {
  name: "HelloWorld",
  props: {
  },
  data: function() {
    return {cli:"https://cli.vuejs.org"}
  }
};
</script>
```

3: Remove the eslintConfig item from package.json and create .eslintrc with the following content:

```javascript
module.exports = {
  env: {
    browser: true,
    es6: true
  },
  extends: ["eslint:recommended", "plugin:vue/recommended"],
  globals: {
    Atomics: "readonly",
    SharedArrayBuffer: "readonly"
  },
  parser: "vue-eslint-parser",
  parserOptions: {
    ecmaVersion: 2018,
    parser: "babel-eslint",
    sourceType: "module",
    allowImportExportEverywhere: true,
    ecmaFeatures: {
      experimentalObjectRestSpread: true
    }
  },
  plugins: ["vue"],
  rules: {}
};
```
4: install vue-eslint-parser and eslint@latest
```
npm install --save-dev vue-eslint-parser eslint@latest
```

5: add a script to package.json
```javascript
"eslint": "node_modules/.bin/eslint **/HelloWorld.vue"
```

6: Run eslint
```
npm run eslint
```

This yields a warning.
```
 7:9  warning  Attribute ":href" should go before "rel"  vue/attributes-order
 ```

7: Update eslint-plugin-vue to the latest

```
npm install --save-dev eslint-plugin-vue@latest
```

8: Re-run eslint
```
npm run eslint
```
Warning is no longer reported.

```vue
<template>
  <div class="hello">
    <p>
      <a
        target="_blank"
        rel="noopener"
        :href="cli"
      >vue-cli documentation</a>.
    </p>
  </div>
</template>

<script>
export default {
  name: "HelloWorld",
  props: {},
  data: function() {
    return { cli: "https://cli.vuejs.org" };
  }
};
</script>
```

**What did you expect to happen?**
I should see a warning: Attribute ":href" should go before "rel"  vue/attributes-order

**What actually happened?**
There is no output
```
C:\vue-example>npm run eslint
> vue-example@0.1.0 eslint C:\vue-example
> eslint **/HelloWorld.vue
C:\vue-example>
```

This behaviour changed between eslint-plugin-vue@5.2.3 and @6.0.0
Is it intentional? I looked in the release notes and don't see anything mentioned.

**Comment by ota-meshi** [comment]
Thank you for this issue.

Not reporting an error is not a bug.

You probably used vue-eslint-parser@7 and eslint-plugin-vue@5 when you performed step 4, but the two are not compatible.
I think it was a false positive because of incompatibility.

You probably used vue-eslint-parser@7 and eslint-plugin-vue@6 when you performed step 8, the two are compatible.
So the last state is working properly.

**Comment by ota-meshi** [comment]
If the problem remains, reopen this issue.
