### ISSUE TITLE
order-in-components fix failed

### ISSUE THREAD

**Issue by otherlite** [vuejs/eslint-plugin-vue#1028]
**Tell us about your environment**	
* **ESLint version:**	6.8.0
* **eslint-plugin-vue version:**	6.1.1
* **Node version:**	8.12.0

**Please show your full configuration:**

```json
{
    "extends": [
        "plugin:vue/recommended",
    ],
    "plugins": [],
    "env": {
      "browser": true
    },
    "parserOptions": {
      "parser": "babel-eslint"
    }
}
```

**What did you do?**	

```shell
./node_modules/eslint/bin/eslint.js ./test.vue --fix
/Users/otherlite/work/2haohr/test.vue
  14:11  error  The "created" property should be above the "methods" property on line 8  vue/order-in-components

✖ 1 problem (1 error, 0 warnings)
```

**What did you expect to happen?**
auto fix

**What actually happened?**

still report error, problem can be reproduced on the [demo](https://mysticatea.github.io/vue-eslint-demo/#eJxNUttqwzAM/RVhBkkgSVkfs60v+4QN+mIoJlYSU0c2ttOtC/n3OUmbFozMkc7RkS8jq41EVrF3Xztlw4GT6q1xAU7QONNDoo0UvkveOHHC36UksRGDDjByAugxdEb6akUAnSCp8VOr+lzBqQydMyFoTJuB6qAMpdmNCFAb8kZjqU2bJvWsgDs9yVbStOxTPkcpgkizu4/DMDiCrdmPcWdvRY1+tu2FTUOnfPnig3FY+iAClg9O2V+PG8jym9nixSmu9912HxEE7K2ODUALaj84s0PLWSw9NZyl3SscnxJzatBra63SS9EYF8WbBhQ9Tc1ZPNr4SJQkeoRpmeXuf2A5c4NGz6qRXQbckSniJTaDV9QWi0GMqmHVPl/qxkl0haLIiq9KSCFK91POFMkIvtQfLtwVfl/t/BUW++hkhfPoYgK9dYhs+gd4q8Dd)

**Comment by otherlite** [comment]
```js
/*
 * Result `true` if the node is sure that there are no side effects
 *
 * Currently known side effects types
 *
 * node.type === 'CallExpression'
 * node.type === 'NewExpression'
 * node.type === 'UpdateExpression'
 * node.type === 'AssignmentExpression'
 * node.type === 'TaggedTemplateExpression'
 * node.type === 'UnaryExpression' && node.operator === 'delete'
 *
 * @param  {ASTNode} node target node
 * @param  {Object} visitorKeys sourceCode.visitorKey
 * @returns {Boolean} no side effects
 */
```

Can we customize the side effects strategy

**Comment by ota-meshi** [comment]
Thank you for this issue.

The `order-in-components` rule does not autofix the problem if it cannot determine that it has no side effects.

It cannot be customized. Please fix the problem yourself.
