### ISSUE TITLE
Rename double negations.

### ISSUE THREAD

**Issue by mysticatea** [vuejs/eslint-plugin-vue#103]
I have made a ton of rules which have double negation in their name, e.g. `vue/no-invalid-v-for`.
However, double negations are a bad choice.

Do we have the chance that we rename those rules before the official release?
For example:

- `vue/no-invalid-v-for` → `vue/validate-v-for` or something like.

Though, I'm not sure that it's valuable even if compatibility confusion happens... :thinking:

**Comment by michalsnik** [comment]
Given that it's still in beta (with all those rules) and when we release it officially it will be `v4.0.0` I think we can change the naming. In fact it's the last moment we can do it without bigger consequences, but we should add a table in Readme with mappings to 3.x names
