### ISSUE TITLE
 The "Welcome" component has been registered but not used (vue/no-unused-components) at src\App.vue

### ISSUE THREAD

**Issue by arpimodi** [vuejs/eslint-plugin-vue#1030]
components: {
  22 |     HelloWorld,
> 23 |     Welcome,
     |     ^
  24 |     Users,
  25 |   },
  26 | }

**Comment by armano2** [comment]
can you give a little more context?

**Comment by fullstackdev39** [comment]
<template>
  <div id="app">
    <img alt="Vue logo" src="./assets/logo.png">
    <Welcome msg="Welcome to Your Vue.js App"/> --------- you can't miss to add welcome component in this part
  </div>
</template>

<script>
import Welcome from './components/Welcome'

export default {
  name: 'app',
  components: {
    Welcome
  }
}
</script>

**Comment by ota-meshi** [comment]
I don't know what you are saying.
Please give me detailed information according to the issue template.
