### ISSUE TITLE
What does this do?

### ISSUE THREAD

**Issue by corysimmons** [vuejs/eslint-plugin-vue#105]
I have ESLint and Prettier and all kinds of stuff going on and working fine, but I'm new to Vue.

I'm using Single File Components spread across a couple files like so:

![image](https://user-images.githubusercontent.com/224636/28498011-a9ad04e4-6f62-11e7-929f-59d8b2f9197f.png)

I have Atom's ESLint plugin and get warnings when I'm not adhering to my config, but I don't see any warnings with this plugin.

```js
// package.json
"eslintConfig": {
    "plugins": ["prettier"],
    "rules": {
      "prettier/prettier": "error"
    },
    "extends": ["plugin:vue/recommended", "prettier-standard"],
    "env": {
      "browser": true,
      "jquery": true
    },
    "globals": {
      "axios": true,
      "Vue": true
    }
  },
```

Would really appreciate knowing how to get this working. I think it'd help me from making silly mistakes with Vue. Thanks.

**Comment by mysticatea** [comment]
Thank you for this issue.

Could you confirm that `eslint` works as intended on CLI?

    $ ./node_modules/.bin/eslint "path/to/your.vue"

If yes, maybe you have to configure Atom's ESLint plugin to check the `.vue` files (maybe by file extensions).
I'm not sure the way :cry: since I'm not familiar with Atom.

**Comment by michalsnik** [comment]
Hey @corysimmons , you need to turn `Lint HTML Files` option in `linter-eslint` atom package settings. Feel free to reopen this issue if you still have problems. I use eslint in atom and it works :)

**Comment by corysimmons** [comment]
Thanks guys, sorry I fell asleep.

@michalsnik I did that.

Here's a simple .vue

```vue
<style src="./CompanyLogo.scss" lang="scss" scoped></style>

<template>
  <figure class="company-logo" :style="{
    width: size,
    height: size,
    backgroundImage: `url(${src})`
  }"></figure>
</template>

<script src="./CompanyLogo.js"></script>
```

What's a good way to break that to confirm the plugin is working now?

**Comment by armano2** [comment]
Remove figure and there should be error with no invalid root template

**Comment by armano2** [comment]
Also I don't think that script with sec is supported in Vue files

**Comment by michalsnik** [comment]
Scripts in plain JS files are supported @armano2 I think I know the real problem here. It looks like the atom's 'linter-eslint' lints the .vue file only when something inside script tag changes. I need to investigate what we can do about it.. But it's rather an upstream issue if any

**Comment by corysimmons** [comment]
@michalsnik I suspected this might be the issue. My use case is Prettier + SingleFileComponents split up. No rush whatsoever, just wanted to check to make sure I wasn't missing some sweet ruleset. 🏄

Maybe re-open/re-title though?
