### ISSUE TITLE
Rule Proposal: template-no-target-blank

### ISSUE THREAD

**Issue by sosukesuzuki** [vuejs/eslint-plugin-vue#1054]
**Please describe what the rule should do:**

This rule should warn when `rel='noreferrer noopener'` does not exist in attributes of an anchor tag with `target="_blank"`.

**What category should the rule belong to?**

- [ ] Enforces code style
- [x] Warns about a potential error
- [ ] Suggests an alternate way of doing something
- [ ] Other (please specify:)

**Provide 2-3 code examples that this rule should warn about:**
```vue
<template>
  <a href="http://example.com" target="_blank">link</a>
</template>
```

**Additional context**

ref: https://developers.google.com/web/tools/lighthouse/audits/noopener?hl=en
A rule does exist for this problem in [eslint-plugin-react](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-target-blank.md)

**Comment by sosukesuzuki** [comment]
To any maintainer. Can I work on this?

**Comment by ota-meshi** [comment]
Thank you for this rule proposal.

I think it is good to add this rule to `eslint-plugin-vue`.
I'm not familiar with [this vulnerability](https://mathiasbynens.github.io/rel-noopener/), so I'm not sure about the rule details.
