### ISSUE TITLE
Allow underscore prefix to disable no-unused-vars

### ISSUE THREAD

**Issue by fiesh** [vuejs/eslint-plugin-vue#1058]
If one wants to repeat a block `n` times, a `v-for="i in n"` comes in handy.

Now `vue/no-unused-vars` will rightfully complain that `i` is unused.

In TypeScript, there's a similar issue with function arguments that are not used on purpose.  These are ignored as unused if prefixed with a `_`.

How about allowing this for `no-unused-vars` as well?  So that `v-for="_i in n"` would not warn, while `v-for="i in n"` would.

**Comment by IWANABETHATGUY** [comment]
I think `_` is better, which is same as other lint rule, i can provide a pr for this

**Comment by IWANABETHATGUY** [comment]
okey, I no-unused-var is not only contains `v-for` stuff, so your proposal is better,    👍
