### ISSUE TITLE
max-attributes-per-line doesn't support CRLF

### ISSUE THREAD

**Issue by sanyarnd** [vuejs/eslint-plugin-vue#1062]
* **ESLint version:**	6.8.0
* **eslint-plugin-vue version:** ^2.18.0
* **Node version:** 12.13.1

There is a following issue with `max-attributes-per-line`:
if diagnostic is enabled and it happens to modify the source code, then new lines' encoding is LF, even though original encoding was CRLF.

Before lint:
![image](https://user-images.githubusercontent.com/6544384/75783389-8b6bb200-5d71-11ea-8b76-c9b974aa6107.png)
After lint:
![image](https://user-images.githubusercontent.com/6544384/75783331-7727b500-5d71-11ea-8e49-d7f16feeb5c8.png)

**Comment by ota-meshi** [comment]
Hello. 

All the rules of this plugin cannot change the line-feed code.
I think you can solve this problem by using [linebreak-style](https://eslint.org/docs/rules/linebreak-style).

**Comment by sanyarnd** [comment]
@ota-meshi thanks a lot for the tip
```
'linebreak-style': ['error', (process.platform === 'win32' ? 'windows' : 'unix')]
```
did the trick
