### ISSUE TITLE
How to make parser work on plain js files.

### ISSUE THREAD

**Issue by armano2** [vuejs/eslint-plugin-vue#109]
I looked into my projects and i found out one missing functionality here, sometimes we can create abstract components in js files with no template, with or without render function and in that case eslint is not going to work with this file because he don't know that this is a component.

**Solution:**
I propose to add a way to instruct parser to treat files with comment `/* @vue/component */` as vue components.

**Comment by michalsnik** [comment]
I like this idea 👍 We're not able to catch all scenarios and this would definitely help.
