### ISSUE TITLE
how do i install vue-recommended for vue2.x?

### ISSUE THREAD

**Issue by chovy** [vuejs/eslint-plugin-vue#1092]
The docs only show vue3.x

I'm using v2.

How do I configure eslintrc.js to have vue2-recommended rules?

**Comment by ota-meshi** [comment]
See the following documentation if you are using v6.2.2.
https://github.com/vuejs/eslint-plugin-vue/blob/v6.2.2/docs/rules/README.md

See the following documentation if you are using `@next`.
https://eslint.vuejs.org/rules/#priority-c-recommended-minimizing-arbitrary-choices-and-cognitive-overhead-for-vue-js-2-x
