### ISSUE TITLE
question: difference to eslint-plugin-html ?

### ISSUE THREAD

**Issue by mgrybyk** [vuejs/eslint-plugin-vue#11]
Hello,

https://www.npmjs.com/package/eslint-plugin-html already supports vue files. What are the key differences  of eslint-plugin-vue? 

Thank you!

**Comment by chrisvfritz** [comment]
We use `eslint-plugin-html` for `.vue` support and also currently include a rule for better JSX support. See [this issue](https://github.com/vuejs/eslint-plugin-vue/issues/10) for other future plans.
