### ISSUE TITLE
eslint报错

### ISSUE THREAD

**Issue by aslrz-club** [vuejs/eslint-plugin-vue#1104]
Failed to load plugin 'vue' declared in 'demo\package.json': Cannot find module 'eslint-plugin-vue' 最近新创建的项目会这样，依赖是  
  "@vue/cli-plugin-babel": "~4.3.0",
    "@vue/cli-plugin-eslint": "~4.3.0",
    "@vue/cli-plugin-router": "~4.3.0",
    "@vue/cli-plugin-vuex": "~4.3.0",
    "@vue/cli-service": "~4.3.0",
    "@vue/compiler-sfc": "^3.0.0-beta.1",
    "@vue/eslint-config-standard": "^5.1.2",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-import": "^2.20.2",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-promise": "^4.2.1",
    "eslint-plugin-standard": "^4.0.0",
    "eslint-plugin-vue": "^7.0.0-alpha.0",
    "sass": "^1.26.3",
    "sass-loader": "^8.0.2",
    "vue-cli-plugin-vue-next": "~0.1.2"

**Comment by ota-meshi** [comment]
Would you please use English and issue templates? I don't know what you are saying.
