### ISSUE TITLE
Multiple Custom Parsers

### ISSUE THREAD

**Issue by MentalGear** [vuejs/eslint-plugin-vue#1126]
**Please describe what the rule should do:**

Allow usage with multiple custom parsers. ATM I'm trying to use more than one parser. Example:
    "parser": "vue-eslint-parser",
    "parserOptions": {
      "parser": ["babel-eslint", "eslint-plugin-coffee"]
    },

**What category should the rule belong to?**

- [ ] Enforces code style
- [ ] Warns about a potential error
- [x] Suggests an alternate way of doing something
- [ ] Other (please specify:)

**Comment by ota-meshi** [comment]
Thank you for posting this issue.

Why do you need to use multiple parsers in one repository?

If your directories are separated by monorepo etc., you may be able to use `overrides` in the eslint configuration.

https://eslint.org/docs/user-guide/configuring#configuration-based-on-glob-patterns

**Comment by MentalGear** [comment]
Hi there,
I wanted to use the babel eslint parser together with the coffee eslint parser, that's why.
