### ISSUE TITLE
ETA / roadmap / remaining issues for v7

### ISSUE THREAD

**Issue by aberonni** [vuejs/eslint-plugin-vue#1176]
I'm looking forward to release v7 for a few new rules that I have my eye on, but I'm refraining from upgrading now because I'd like to wait for v7 to be released as stable.

For this reason, I'm wondering whether there is a list of remaining issues somewhere that I can possibly give a hand with to accelerate the release?

I'm guessing that maybe creating a new v7 [milestone](https://github.com/vuejs/eslint-plugin-vue/milestones) might be the easiest way to solve this for everyone in my situation.

**Comment by ota-meshi** [comment]
Thank you for your question. I'm glad to know that you're looking forward to it.

I have the following plans for v7.

- Supports ESLint v7
  As far as I know, this task has been completed.

- Supports Vue.js v3
  Most tasks have been completed. #1035
  As far as I know, the remaining issue is #1134.
  However, I'm not sure about Vue3's APIs other than RFCs, so there may be additional issues. Also, in order for the rules for Vue3 to be stable, we may need to wait for the GA of Vue3.

- Supports ES2020
  At least I want to support popular Optional Chaining and Nullish Coalescing.
  ESLint does not yet support Optional Chaining. After ESLint supports Optional Chaining I need to change this plugin to work.
  Also, Optional Chaining may require breaking changes to the AST. In some cases we may need to drop support for ESLint v6.

These plans are subject to change. Thank you for your understanding.

**Comment by aberonni** [comment]
Thanks for the swift response.

I don't have intention of upgrading my project to Vue3 anytime soon. I mention that because, if the main issues left are Vue3 related, maybe the best thing I can do now is upgrade to the latest alpha and do some testing to see if I get any issues.

I'll give that a go and let you know how it goes next week.

In the meantime, feel free to close this issue if you wish.

**Comment by dimitropoulos** [comment]
ESLint landed optional chaning support in [v7.5.0](https://github.com/eslint/eslint/releases/tag/v7.5.0) on July 18th and nullish coalescing was released in [v7.2.0](https://github.com/eslint/eslint/releases/tag/v7.2.0) on June 5th.  Both of these happened after this plugin released ESLint 7 support (in version [v7.0.0-alpha.2](https://github.com/vuejs/eslint-plugin-vue/releases/tag/v7.0.0-alpha.2) on May 10th) so I wanted to let you know in case you weren't yet aware.

As far as I know that means @ota-meshi all of the criteria is met for a new major release for this plugin.  My apologies if there's somewhere else where the status of a release is discussed but I haven't yet seen it if such a place exists.

**Comment by ota-meshi** [comment]
I just released v7🚀
https://github.com/vuejs/eslint-plugin-vue/releases/tag/v7.0.0
