### ISSUE TITLE
[tools] use ESLint class instead of CLIEngine

### ISSUE THREAD

**Issue by tyankatsu0105** [vuejs/eslint-plugin-vue#1215]
Since version 7.0.0, ESLint supports `ESLint` class instead of `CLIEngine` class.
https://github.com/eslint/eslint/pull/12939
https://github.com/eslint/rfcs/pull/40

So, if it's possible, let's use `ESLint` class!

**Comment by ota-meshi** [comment]
Thank you for your suggestions!

But we will still support ESLint v6. So we may not need to replace it now.

However, I think it is possible to replace the CLIEngine of scripts that are not related to test cases at now.

**Comment by tyankatsu0105** [comment]
@ota-meshi 
Oh sorry.
I overlooked [supports version](https://github.com/vuejs/eslint-plugin-vue/blob/master/package.json#L53).
Umm...
Can I replace around `tools`?

**Comment by ota-meshi** [comment]
> Can I replace around `tools`?

Yes. I think we can replace it.

**Comment by tyankatsu0105** [comment]
Great! Thanks for checking.
I will send PR😉
