### ISSUE TITLE
allow object syntax for vue/valid-v-on

### ISSUE THREAD

**Issue by uncleGena** [vuejs/eslint-plugin-vue#1219]
please add object syntax as shown in vuejs api docs
![image](https://user-images.githubusercontent.com/11743243/85410886-524d8c80-b570-11ea-9c25-6e59a6e0b896.png)

[vuejs api](https://vuejs.org/v2/api/#v-on)
[your rule](https://github.com/vuejs/eslint-plugin-vue/blob/v4.7.1/docs/rules/valid-v-on.md)

**Comment by ota-meshi** [comment]
Yes. Already allowed.
