### ISSUE TITLE
Please make a new alpha release or backport a bugfix

### ISSUE THREAD

**Issue by Amndeep7** [vuejs/eslint-plugin-vue#1221]
I'm running into the bug fixed here at https://github.com/vuejs/eslint-plugin-vue/blob/b33c708d8df9543315467d7a684ee207d784b971/lib/rules/no-unused-components.js#L88-L90 where the linter tries to access a property of an object that's null in the no-unused-components rule.  

Currently builds for a project of mine are failing due to the linter crashing.  I validated this by manually adding the fix to the local copy of this library in my node_modules, which allowed the build to proceed as usual.  

I would really appreciate it if you could either backport the fix to the 5.2.x and/or 6.2.x lines (I can make the PR if necessary) or make a new alpha release.

**Comment by ota-meshi** [comment]
Thank you for this issue.

I will merge some PRs and release v7.0.0.alpha if I can spare time this weekend.

I can't take the time to check the behavior of each version, so I won't backport.
Thank you for your understanding.

**Comment by Amndeep7** [comment]
Yeah, a new release is completely fine.  I'll close the issue when it's out.  Thank you!

**Comment by ota-meshi** [comment]
I have released a new version so close this issue.

**Comment by Amndeep7** [comment]
Thanks!
