### ISSUE TITLE
Enable to lint .html templates (not SFC)

### ISSUE THREAD

**Issue by RyochanUedasan** [vuejs/eslint-plugin-vue#1247]
I saw some issues that claim it's impossible to lint .html templates,

https://github.com/vuejs/eslint-plugin-vue/issues/490
https://github.com/vuejs/eslint-plugin-vue/issues/531

but I'm using vue-cli-service (+ eslint plugin) and able to lint `.html` (like below) templates.

```index.html
<v-app-bar color="light-blue darken-4" dense fixed>
  <v-btn color="white" text @click="click">Button</v-btn>
  <v-spacer></v-spacer>
  <v-icon large color="white">account_box</v-icon>
</v-app-bar>
```

To add parser options for `.html` files in prettier configuration, you can format `.html` files.

```.prettierrc
{
  "semi": false,
  "singleQuote": true,
  "overrides": [
    {
      "files": "*.html",
      "options": {
        "parser": "html"
      }
    }
  ]
}
```

if you use `vue-cli-service lint`, add `--ext` option  like `vue-cli-service lint --ext .js,.jsx,.ts,.tsx,.vue,.html` and you can lint them.

Can anyone tell me that this is a good way or not to do that?

**Comment by ota-meshi** [comment]
Hi @RyochanUedasan 
Prettier and `eslint-plugin-vue` are unrelated. 
`eslint-plugin-vue` does not work with HTML files. I don't know if other plugins are linting your HTML files.
