### ISSUE TITLE
Compatibility with eslint@7

### ISSUE THREAD

**Issue by haiarha** [vuejs/eslint-plugin-vue#1266]
Is it OK to use `eslint-plugin-vue@6.2.2` with `eslint@7.5.0`, or should i downgrade `eslint`?

I using `eslint` in my `nuxt.js` app.

**Please show your full configuration:**
Some relevant `package.json` dev deps:
```json
{
    "babel-eslint": "^10.1.0",
    "core-js": "^3.6.5",
    "eslint": "^7.5.0",
    "eslint-loader": "^4.0.2",
    "eslint-plugin-vue": "^6.2.2",
}
```

**What did you do?**	
`npm install`

**What did you expect to happen?**
Install all the packages without any warnings

**What actually happened?**
```
npm WARN eslint-plugin-vue@6.2.2 requires a peer of eslint@^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
```

**Comment by ota-meshi** [comment]
eslint-plugin-vue v6.x does not support ESLint 7.x. The next version of eslint-plugin-vue v7.x will support ESLint 7.x.

https://github.com/vuejs/eslint-plugin-vue/releases/tag/v7.0.0-alpha.2
