### ISSUE TITLE
v-slot

### ISSUE THREAD

**Issue by shzhiheng1** [vuejs/eslint-plugin-vue#1278]
**Checklist**

- [ ] I checked the [FAQ](https://eslint.vuejs.org/user-guide/#faq).

**Tell us about your environment**

- **ESLint version:** 
- **eslint-plugin-vue version:** 
- **Node version:** 
- **Operating System:** 

**Please show your full configuration:**

```
'v-slot' directive doesn't support any modifier

```

**What did you do?**	

```
   <template v-slot:item.ratio="{item}">
          {{ item.ratio[1] }}
        </template>
```

**What did you expect to happen?**

**What actually happened?**

**Repository to reproduce this issue**

**Comment by ota-meshi** [comment]
I don't know what you want to say so I close this issue.
