### ISSUE TITLE
no-side-effects-in-computed false positives

### ISSUE THREAD

**Issue by andrei-gheorghiu** [vuejs/eslint-plugin-vue#1282]
**What rule do you want to change?**
https://github.com/vuejs/eslint-plugin-vue/blob/master/docs/rules/no-side-effects-in-computed-properties.md

**Does this change cause the rule to produce more or fewer warnings?**
Produces more warnings (false positives).

**How will the change be implemented? (New option, new default behavior, etc.)?**
It should not consider

     computed: {
        reversed() {
           return [...this.items].reverse()
        }
     }

a side effect, as it's not. It's pretty much the same as `this.items.slice(0).reverse()`.

**Comment by ota-meshi** [comment]
Thank you for this issue.

However, it seems to be fixed in v7.0.0-beta. Please you use v7.0.0-beta.
Perhaps it was unintentionally fixed by refactoring #1154, that change to uses the same logic as `no-mutating-props` rule.
