### ISSUE TITLE
"vue/valid-v-bind-sync" is not accounting for "is" attribute

### ISSUE THREAD

**Issue by rq-tgriffin** [vuejs/eslint-plugin-vue#1284]
Errors are being shown for sync modifiers on "HTML" elements even if they have a valid "is" attribute, indicating it is a component.

To reproduce, simply add a prop and a sync modifier to the table/tr example found on the Vue documentation for the "is" special attribute: https://vuejs.org/v2/api/#is

**Comment by ota-meshi** [comment]
I'm not sure what you are saying.
Would you please include all details requested in the issue template in the issue?
