### ISSUE TITLE
error: 'const' is not defined (no-undef) - only in .vue file, not in .ts - with @typescript-eslint/parser@4.x

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuejs/eslint-plugin-vue#1293]
**Checklist**

- [x] I checked the [FAQ](https://eslint.vuejs.org/user-guide/#faq).

**Tell us about your environment**

- **ESLint version:** 7.8.0
- **eslint-plugin-vue version:** 6.2.2, 7.0.0-beta.3
- **@typescript-eslint/parser:** 4.0.1
- **Node version:** 12.10.0
- **Operating System:** windows 10

**Please show your full configuration:**

```js
module.exports = {
  root: true,
  env: {
    browser: true,
    es6: true,
    node: true,
    jest: true
  },
  parserOptions: {
    sourceType: 'module',
    parser: '@typescript-eslint/parser'
  },
  extends: [
    'standard',
    'plugin:@typescript-eslint/recommended',
    'plugin:vue/recommended',
    '@vue/typescript/recommended'
  ],
  plugins: [
    'vue'
  ]
}
```

**What did you do?**	

```vue
<script lang="ts">
console.log({
  test: 5 as const
})
</script>
```

**What did you expect to happen?**
no error

**What actually happened?**

![image](https://user-images.githubusercontent.com/15625235/91848851-63470800-ec5b-11ea-96fb-acd5186ee30a.png)

**Repository to reproduce this issue**
https://github.com/jacekkarczmarczyk/rachunek/tree/github/eslint-bug (note the `github/eslint-bug` branch, not the `master`)

To reproduce the error just clone the repo and run `git checkout github/eslint-bug && yarn && yarn lint` - you'll see the error in .vue file, but not in .ts one (`main.ts`)

Not sure if this is `eslint-plugin-vue` bug though

### Notes
It shows the error with `typescript-eslint@4.0`, but works fine with 3.x

**Comment by vvscode** [comment]
Btw I have the same in `.ts` files

**Comment by jacekkarczmarczyk** [comment]
@vvscode can you make a reproduction (maybe based on mine repo)? If it happens in `.ts` file as well it would be rather typescript-eslint issue, not sure why it fails only with .vue file in my repo

**Comment by vvscode** [comment]
Sure https://github.com/vvscode/ts--eslint-parser-error-demo

**Comment by roychoo** [comment]
whats the solution to this?

**Comment by jacekkarczmarczyk** [comment]
afair just upgrade typescript-eslint
<https://github.com/typescript-eslint/typescript-eslint/issues/2462>
