### ISSUE TITLE
 I can't disable  'vue/require-v-for-key': 0 in my eslintrc file

### ISSUE THREAD

**Issue by sgehrman** [vuejs/eslint-plugin-vue#1294]
This just started happening today which is weird. 

I tried to disable:

    'vue/require-v-for-key': 0,
 
in my eslintrc, but it still gives me an error. I'm in VSCode.  Latest eslint package.

**Comment by ota-meshi** [comment]
Please refer to the FAQ.

**Comment by sgehrman** [comment]
@ota-meshi  very annoying you would tell me to look at the FAQ rather than giving me the answer.

I found out I have Vetur installed and I had to add

  "vetur.validation.template": false,

to my settings.

**Comment by klesun** [comment]
Bump, and here is the SO post with 60+ upvotes of other people suffering from undisablable `v-for` `:key` requirement in `eslint-plugin-vue`:

https://stackoverflow.com/questions/47608379/vue-language-server-elements-in-iteration-expect-to-have-v-bindkey-directiv/53726204

**Comment by ota-meshi** [comment]
Please report the issue using the issue template. Also, don't ignore the template checkboxes.
