### ISSUE TITLE
Wrong rule on options example of vue/no-potential-component-option-typo rule

### ISSUE THREAD

**Issue by rarysson** [vuejs/eslint-plugin-vue#1307]
Hi, I'm not sure if it's right or wrong, but when I was reading [vue/no-potential-component-option-typo](https://eslint.vuejs.org/rules/no-potential-component-option-typo.html), I saw that on the beginning the example of config was:

```json5
{
  "vue/no-potential-component-option-typo": ["error", {
    "presets": ["all"],
    "custom": ["test"]
  }]
}
```

but after reading it, when I came to the [options](https://eslint.vuejs.org/rules/no-potential-component-option-typo.html#options) part, the example was:

```json5
{
  "vue/no-unsed-vars": ["error", {
    "presets": ["vue"],
    "custom": [],
    "threshold": 1
  }]
}
```

The "vue/no-unsed-vars" over "vue/no-potential-component-option-typo" was intended? 

**Checklist**

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have read the [FAQ](https://eslint.vuejs.org/user-guide/#faq) and my problem is not listed.

**What did you expect to happen?**

I was expecting to see "vue/no-potential-component-option-typo" as the rule and not "vue/no-unsed-vars".

**Comment by ota-meshi** [comment]
thank you!
