### ISSUE TITLE
plugin:vue/vue3-essential  includes  rule  "vue/no-v-model-argument" ?

### ISSUE THREAD

**Issue by BoBoooooo** [vuejs/eslint-plugin-vue#1309]
Here's my config
``` eslintrc.js
module.exports = {
  root: true,
  env: {
    node: true,
  },
  extends: [
    'plugin:vue/vue3-essential'
  ],
  parserOptions: {
    ecmaVersion: 2020,
  },
  rules: {
    'no-console': process.env.NODE_ENV === 'production' ? 'warn' : 'off',
    'no-debugger': process.env.NODE_ENV === 'production' ? 'warn' : 'off',
  },
};
```
``` package.json

{
  "name": "test",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "ant-design-vue": "^2.0.0-beta.9",
    "core-js": "^3.6.5",
    "vue": "^3.0.0-0",
    "vue-class-component": "^8.0.0-0",
    "vue-router": "^4.0.0-0",
    "vuex": "^4.0.0-0"
  },
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^2.33.0",
    "@typescript-eslint/parser": "^2.33.0",
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "4.5.6",
    "@vue/cli-plugin-router": "~4.5.0",
    "@vue/cli-plugin-typescript": "~4.5.0",
    "@vue/cli-plugin-vuex": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/compiler-sfc": "^3.0.0-0",
    "@vue/eslint-config-typescript": "5.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-import": "^2.20.2",
    "eslint-plugin-vue": "^7.0.0-beta.4",
    "node-sass": "^4.12.0",
    "sass-loader": "^8.0.2",
    "typescript": "~3.9.3"
  }
}
```

When i use like " v-model:propName "  in vue 3.x  ,  eslint prompt this error ... 

![image](https://user-images.githubusercontent.com/25972237/94125593-213f6980-fe89-11ea-9f20-d2a22d2da961.png)

How to fix it ..

**Comment by ota-meshi** [comment]
Thank you for this issue.

However, the `vue/no-v-model-argument` rule is not included in` vue3-essential`.
https://github.com/vuejs/eslint-plugin-vue/blob/v7.0.0-beta.4/lib/configs/vue3-essential.js

The warning displayed in your image is a warning displayed by Vetur, so it may be a Vetur problem.  
(The gray `eslint-plugin-vue` warning on VS Code is the warning that Vetur is outputting. The warning output by vscode-eslint is displayed as `eslint`.)  

As a workaround, you can also turn off the validation of eslint-plugin-vue built into Vetur.
https://eslint.vuejs.org/user-guide/#trouble-with-visual-studio-code

**Comment by BoBoooooo** [comment]
@ota-meshi Thank you for your answer , I figure it out .

a. when I open vue3 project in VS Code by workspace with another vue2.x project , this warning displayed .
b. but When I open it in single window , everything is fine ..  

as you said , it may be a Vetur problem or VSCode problem .  anyway thank u !

**Comment by Developer27149** [comment]
@BoBoooooo 你好，可是我根本没有vetur插件，也没有vue2项目，还是有这个警告。我都打算关闭这一条规则了
