### ISSUE TITLE
no-useless-escape should be false by default

### ISSUE THREAD

**Issue by kamran-12** [vuejs/eslint-plugin-vue#1310]
**What rule do you want to change?**
no-useless-escape

**Does this change cause the rule to produce more or fewer warnings?**
Fewer errors

**How will the change be implemented? (New option, new default behavior, etc.)?**
New default behavior: {
        "no-useless-escape": false
    }

**Please provide some example code that this change will affect:**
See [this](https://github.com/vuejs/vue-cli/issues/5913) for example code

**What does the rule currently do for this code?**
Answered in the last link provided

**What will the rule do after it's changed?**
Nothing

**Comment by ota-meshi** [comment]
Thank you for this issue.

However, we do not include any rules other than those provided by eslint-plugin-vue, in configurations provided by eslint-plugin-vue.

You are free to turn off the `no-useless-escape` rule in your configuration. You can also share your configuration.
https://eslint.org/docs/developer-guide/shareable-configs

Thank you for your understanding.
