### ISSUE TITLE
Rule for Props is too strict

### ISSUE THREAD

**Issue by duongvanle** [vuejs/eslint-plugin-vue#1320]
After I updated this repo up to 7.* I see that it warns me to change prop from child component.
Let me explain more clearly.
I have a parent component P. P has a child component C. P pass data to C .ex: INFOR = {a: 1, b: 2}
And of course C has Props property corresponding.
I want that if child component C change INFOR, only change value of a or b property, NOT add new or delete current property, it also change same thing in the parent component P. In short like data-two-way binding. I want to take advantage of the reference of object property, Or value of element in an array, also not add or delete any element. This one also happens even with VueX.

Vue also say about this problem
![Screenshot_2020-10-07 Props — Vue js](https://user-images.githubusercontent.com/54653284/95339824-b0fc0380-08de-11eb-8c09-4645a25a3655.png)

This way help me to save time instead of writing $emit event, and code look more simply. 
Why is this one prevented from this version 7.*
Can you explain to me why I shouldn't do it while I think I can take advantage of the reference

**Comment by ota-meshi** [comment]
I don't know which rule you're talking about, but it's probably the same issue as #1314.
You are free to turn off the rules in your configuration.
