### ISSUE TITLE
Dynamic slot names marked as "same slot"

### ISSUE THREAD

**Issue by sugoidesune** [vuejs/eslint-plugin-vue#1348]
**Tell us about your environment**
    "eslint": "^4.19.1",
    "eslint-friendly-formatter": "^4.0.1",
    "eslint-loader": "^2.1.1",
    "eslint-plugin-vue": "^4.0.0",

- **Node version:** 12
- **Operating System:**  Windows

**Please show your full configuration:**
```json5
module.exports = {
  root: true,
  env: {
    browser: true,
    node: true
  },
  parserOptions: {
    parser: 'babel-eslint'
  },
  extends: [
    // https://github.com/vuejs/eslint-plugin-vue#priority-a-essential-error-prevention
    // consider switching to `plugin:vue/strongly-recommended` or `plugin:vue/recommended` for stricter rules.
    'plugin:vue/essential'
  ],
  // required to lint *.vue files
  plugins: [
    'vue'
  ],
  // add your custom rules here
  rules: {}
}

```

**What did you do?**	

```vue

<template v-for="col in editables" v-slot:[col.slot]="{ item }" >
          <span :key="col.value">{{col.edit}}</span>
        </template>

        <template v-for="col in checkmarks"  v-slot:[col.slot]="{ item }">
          <span :key="col.value">
{{col.checkmark}}
          </span>
        </template>

```
![image](https://user-images.githubusercontent.com/20317691/97516488-7ba17d80-1993-11eb-825d-c884877c22be.png)

**What did you expect to happen?**
No error, the slot names are infact different, but the API is the same for looping through them.

**What actually happened?**
`An element cannot have multiple '<template>' elements which are distributed to the same slot.`
![image](https://user-images.githubusercontent.com/20317691/97516180-de464980-1992-11eb-8646-b14c4640aa47.png)

**Repository to reproduce this issue**

**Comment by ota-meshi** [comment]
Thank you for this issue.
I can't reproduce your problem. Would you please share a reproducible repository?

**Comment by ota-meshi** [comment]
Sorry. my misunderstanding. I was able to reproduce the problem. I think it's a bug.

**Comment by ibrain20** [comment]
![Screenshot (2)](https://user-images.githubusercontent.com/46008568/100907018-d4cf6600-3497-11eb-9ded-dc3032d696bb.png)

vuetify

**Comment by heyakyra** [comment]
Is anyone else hitting this again? Just updated our dependencies and hitting this exact problem

_Edit: I had to switch from `standard` to `@vue/eslint-config-standard-with-typescript` and place it towards the top (at a lower priority)._
