### ISSUE TITLE
FATAL ERROR: invalid array length Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by qianjin1017** [vuejs/eslint-plugin-vue#1351]
window：

What should I do to solve it that's bothering me right now.

Reference:  #1095   have no effect!!!

eslint-plugin-vue：version 5.22
THK

@brettz9 @philippbosch @flyerhzm @kazupon @LukeShu

**Comment by qianjin1017** [comment]
![image](https://user-images.githubusercontent.com/19699178/98763609-568e1f80-2415-11eb-9889-78947fce9481.png)

**Comment by ota-meshi** [comment]
It works fine on my PC. I can't look directly at your PC, so I can't help your problem.
So I close this issue.
