### ISSUE TITLE
How to output junit report to a file?

### ISSUE THREAD

**Issue by cawoodm** [vuejs/eslint-plugin-vue#1352]
Sorry for posting this here - I've read all the docs and can't find a solution.

When running eslint via the vue-cli (or directly with `npx eslint`) using a `junit` output format there seems to be no option to output to a file. Similar to [this issue](https://github.com/vuejs/vue-cli/issues/2360) we need to support a `-o` parameter.

## What doesn't work
In all these cases the output is on `stdout` instead of to a file:
* `vue-cli-service lint --format junit -o output.xml`
* `vue-cli-service lint --format junit --output-file output.xml`
* `npx eslint --format junit -o output.xml`
* `npx eslint --format junit --output-file output.xml`
* `npx eslint --format junit --out output.xml`

## What sometimes works
Redirecting with `>` only works if there are errors reported in XML format. If there are no errors the XML contains plain text and is therefore invalid:
* `npx eslint --format junit > output.xml`
* ` DONE  No lint errors found!`
* `   Done in 24.30s.`

Any help would be much appreciated.

**Comment by cawoodm** [comment]
Seems to be a feature request for the vue-cli:
https://github.com/vuejs/vue-cli/pull/4850

**Comment by ota-meshi** [comment]
eslint-plugin-vue doesn't do anything about the output format, so I close this issue. Follow vue-cli issue.
