### ISSUE TITLE
eslint not work

### ISSUE THREAD

**Issue by dengshenkk** [vuejs/eslint-plugin-vue#1353]
**Checklist**

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have read the [FAQ](https://eslint.vuejs.org/user-guide/#faq) and my problem is not listed.

**Tell us about your environment**

- *vue-cli version*: *@vue/cli 4.5.8*
- *ESLint version*:*v6.8.0* 
- *eslint-plugin-vue version*:*6.2.2* 
- *Node version*:*v14.5.0* 
- *Operating System*:*MacOS* 

**Please show your full configuration:**

```json5
no .eslintrc file
```

**What did you do?**	

vue create app 

┌─────────────────────────────────────────┐
│                                         │
│   New version available 4.5.8 → 4.5.9   │
│    Run npm i -g @vue/cli to update!     │
│                                         │
└─────────────────────────────────────────┘

? Please pick a preset: (Use arrow keys)
❯ Default ([Vue 2] babel, eslint) 
  Default (Vue 3 Preview) ([Vue 3] babel, eslint) 
  Manually select features 

```vue
// App.vue

<template>
  <div id="app">
    <img
      alt="Vue logo"
      src="./assets/logo.png"
    >
    <HelloWorld msg="Welcome to Your Vue.js App" />
  </div>
</template>

<script>
import HelloWorld from './components/HelloWorldNotFound.vue'

export default {
  name: 'App',
  components: {
    HelloWorld
  }
}
</script>
<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>
```

**What did you expect to happen?**
HelloWorld component not found, npm run lint have error or warnning

**What actually happened?**

 DONE  No lint errors found!
**Repository to reproduce this issue**
https://github.com/dengshenkk/vue-cli-bug-app

**Comment by ota-meshi** [comment]
Do you expect an import path existence check? eslint-plugin-vue doesn't provide that rule. You need to install another ESLint plugin for import or another checker.

**Comment by ota-meshi** [comment]
I close this issue. Please let me know if I misunderstand the content.

**Comment by dengshenkk** [comment]
@ota-meshi stk, which one plugin can to this?

**Comment by ota-meshi** [comment]
There are many, for example, eslint-plugin-import.
