### ISSUE TITLE
ESLint: The template root disallows 'v-for' directives：看3.0的介绍说是支持多个root，那么请问支持在root component上用v-for吗

### ISSUE THREAD

**Issue by leeboo** [vuejs/eslint-plugin-vue#1359]
![image](https://user-images.githubusercontent.com/1256745/100618005-35568a00-3356-11eb-846a-0bfe2c89a371.png)

**Comment by ota-meshi** [comment]
I don't understand the language you are using. So I close this issue.
Open a new issue using the issue template and English.
