### ISSUE TITLE
Make vue/custom-event-name-casing fixable

### ISSUE THREAD

**Issue by sapphi-red** [vuejs/eslint-plugin-vue#1395]
**Tell us about your environment**

- **ESLint version:** 7.16.0
- **eslint-plugin-vue version:** 7.4.0
- **Node version:** 14.15.3

**The problem you want to solve.**

**Your take on the correct solution to problem.**
Make vue/custom-event-name-casing fixable.

**Additional context**

Are there any concerns?

**Comment by ota-meshi** [comment]
Thank you for this issue!

However, we do not implement autofix in this rule, as autofix with this rule can break the user's application.
If an event you have already subscribed to is renamed, that event will no longer work.

**Comment by sapphi-red** [comment]
In vue2 it will break, but in vue3 I think it will not break since there is a automatic case transformation.
https://v3.vuejs.org/guide/component-custom-events.html#event-names

Is it not possible to auto-fix coditionally?
How about splitting this rule to two rules, one for vue2 which kebab-case with no autofix, and one for vue3 with autofix?

**Comment by sapphi-red** [comment]
@ota-meshi (mentioning in case you may haven't noticed)

**Comment by dz85** [comment]
but when I use:
```json
{
  "vue/v-on-event-hyphenation":
  [
    "error",
    "always",
    {
      "autofix": true,
      "ignore": []
    }
  ]
}
```
I also need `vue/custom-event-name-casing` to auto-fix, e.p. in such case:
```js
this.$emit('thisEventNeedAutofixToKebabCase')
```
