### ISSUE TITLE
Vue files eslint errors detected, can't be fixed via --fix

### ISSUE THREAD

**Issue by coljung** [vuejs/eslint-plugin-vue#14]
I have a project with some .js files and some .vue files.

I recently upgraded the linting rules and while I successfully applied to .js files, im having trouble doing the same with the .vue ones.

running eslint ... src/... *.vue detects all the 'errors', mostly indent, single quotes and semicolons. If i try to run the same command with --fix, it does nothing.

Is there some kind of limitation to this ? unfortunately it is a big project and i get over 5000 errors, so to do this manually would be too much.

And i would think my configuration is fine because the linter is finding the errors to begin with on all .vue files.

As a side note, I use ATOM, and have it setup so that it highlights any eslint errors i have. For some reason, on vue files, the errors are not highlighted.

**Comment by michalsnik** [comment]
Hey @coljung,

First of all this plugin is meant to be used internally by vuejs libraries and was just moved to https://github.com/vuejs/eslint-plugin-vue-libs

Second of all this plugin does not use the `vue-eslint-parser` so it cannot deal with `.vue` files.

Last but not least this plugin has only one rule, which is made to work with JSX, plus it has no `fix` method implemented.

Other settings that you get by using config related to this plugin (vue-libs) use rules from other plugins and they clearly don't support parsing `.vue` files as well.

Right now I think it's rather not fixable. Future versions of this plugin may handle this, but I guess rather not in the near future.

**Comment by chrisvfritz** [comment]
We do use [eslint-plugin-html](https://github.com/BenoitZugmeyer/eslint-plugin-html/) for `.vue` file support here, which [should support `--fix`](https://github.com/BenoitZugmeyer/eslint-plugin-html/issues/23). @coljung Are you by chance using ESLint 4?

**Comment by chrisvfritz** [comment]
@michalsnik Oh, and to clarify, we _do_ want this repo to be the user-facing one going forward. Previously, it sort of served both purposes (while esling-config-vue was _solely_ for internal use).

**Comment by michalsnik** [comment]
Yes @chrisvfritz I know, but the question is actually about current `eslint-plugin-vue-libs` as the new version of `eslint-plugin-vue` is not yet ready and published and what's in this repository right now is kind of legacy (or should be treated like so). All internal plugins use already `eslint-plugin-vue-libs` and this repository will hopefully sooner than later contain completely different plugin (the user facing one based on `eslint-plugin-vue-trial`)

**Comment by chrisvfritz** [comment]
@michalsnik Don't we expect the new version to be a superset of this plugin's current features though? Right now, we only have support for JSX and single-file components and I can't imagine we'll drop either now that it's user-facing only. From that perspective, I'm not sure this is actually a migration, but simply an upgrade. It's only a migration from the perspective of an official Vue lib maintainer. Does that makes sense?

**Comment by michalsnik** [comment]
Yes, but as I mentioned in the last PR we can't be sure it will be 100% backwards compatible, because we might reevaluate some rules in the meanwhile before releasing v3.0.0. Anyway I'd leave this topic at least until we integrate `eslint-plugin-vue-trial` @chrisvfritz

**Comment by yyx990803** [comment]
@chrisvfritz the new plugin will include more rules and a recommended config though, so the purpose of this repo kinda have changed - the user would just install this plugin to get everything they need for ESLint with Vue, instead of just some enhancements on top of a separate config.

Regardless I think going 3.0 is probably the reasonable jump.

**Comment by chrisvfritz** [comment]
Yep, I think we're in the same page. 🙂

**Comment by mysticatea** [comment]
We have released `eslint-plugin-vue@beta` which can fix errors. Can we close this issue?

**Comment by michalsnik** [comment]
I'm closing this issue. @coljung feel free to reopen if it doesn't solve your issue. I checked it myself and fixes worked as expected :)

**Comment by coljung** [comment]
Perfect, thx!
