### ISSUE TITLE
Parsing error: Unexpected token return

### ISSUE THREAD

**Issue by vporton** [vuejs/eslint-plugin-vue#1402]
**Checklist**

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have read the [FAQ](https://eslint.vuejs.org/user-guide/#faq) and my problem is not listed.

**Tell us about your environment**

- **ESLint version:** 6.8.0
- **eslint-plugin-vue version:** 7.4.0
- **Node version:** 12.16.2
- **Operating System:** Ubuntu 20.10

**Please show your full configuration:**
_no such file_

**What did you do?**	

```vue
<script>
    function isAddressValid() {
        return true;
    }
</script>
```

**What actually happened?**
```
/home/porton/Projects/donations/donations-widget-vue/html/test.vue
  3:9  error  Parsing error: Unexpected token return
```

`.eslintrc`:
```json
{
  "parser": "@typescript-eslint/parser",
  "extends": [
    "standard",
    "standard-react",
    "plugin:prettier/recommended",
    "prettier/standard",
    "prettier/react",
    "plugin:@typescript-eslint/eslint-recommended",
    "plugin:vue/recommended"
  ],
  "env": {
    "node": true
  },
  "parserOptions": {
    "ecmaVersion": 2020,
    "ecmaFeatures": {
      "legacyDecorators": true,
      "jsx": true
    }
  },
  "settings": {
    "react": {
      "version": "16"
    }
  },
  "rules": {
    "space-before-function-paren": 0,
    "react/prop-types": 0,
    "react/jsx-handler-names": 0,
    "react/jsx-fragments": 0,
    "react/no-unused-prop-types": 0,
    "import/export": 0
  }
}
```

**Comment by LinusBorg** [comment]
That config doesn'tuse eslint-plugin-vue.

Why do you think it is an issue with this library?

**Comment by vporton** [comment]
@LinusBorg I've added `"plugin:vue/recommended"` but it does not help!

**Comment by ota-meshi** [comment]
It doesn't work because you have a parser specified.  Check out the faq.
