### ISSUE TITLE
Explain rule in docs: vue/no-boolean-default

### ISSUE THREAD

**Issue by aranoe** [vuejs/eslint-plugin-vue#1418]
I don't really understand why the `vue/no-boolean-default` rule is recommended.

You could just change your prop names to acheive the same results as before, e.g:
```js
props: {
  isOpen: { type: Boolean, default: true }
}
```
Renaming the prop and removing the default value will keep the logic the same:

```js
props: {
  isClosed: { type: Boolean }
}
```
So that isn't really a problem, I just want to know why this is recommended

**How to resolve this issue?**
Add explanation in the docs to:
https://eslint.vuejs.org/rules/no-boolean-default.html#vue-no-boolean-default

**Comment by ota-meshi** [comment]
In general HTML, you cannot give false to the attribute. If you want that convention to apply to vue as well, turn on the rule. If you don't like it, don't use this rule.
