### ISSUE TITLE
multiline-html-element-content-newline causes blank spaces

### ISSUE THREAD

**Issue by Edge00** [vuejs/eslint-plugin-vue#1424]
### source code
```
<div class="line">
  <div class="nav">
    时间
  </div>
  <div class="content">
    {{ config.act_time }}
  </div>
</div>
```

### after compile
![image](https://user-images.githubusercontent.com/23715779/105825812-f746b100-5ffa-11eb-8587-1ae4fadc7a47.png)

**Comment by ota-meshi** [comment]
I don't know what you think is the problem. If you don't like a rule, you are free to turn off.

**Comment by Edge00** [comment]
my fault. wrong style cause by
```css
.content {
  white-space: pre-wrap;
}
```
not this rule
