### ISSUE TITLE
{variable} is defined but never used (no-unused-vars)

### ISSUE THREAD

**Issue by abdulsalamalmahdi** [vuejs/eslint-plugin-vue#1427]
**Tell us about your environment**
I have the server files in the main project root  and vue files too.
- **ESLint version:** 
- **eslint-plugin-vue version:** 
- **Node version:** 

**The problem you want to solve.**
it detects the unused vars in the server files too

**Your take on the correct solution to problem.**

**Additional context**

**Comment by ota-meshi** [comment]
I don't know what your problem is.
