### ISSUE TITLE
Add "ignores" list to "prop-name-casing" rule

### ISSUE THREAD

**Issue by yassilah** [vuejs/eslint-plugin-vue#1438]
**What rule do you want to change?**
`vue/prop-name-casing`

**Does this change cause the rule to produce more or fewer warnings?**
Fewer if the "ignores" option is used.

**How will the change be implemented? (New option, new default behavior, etc.)?**
Using a new "ignores" option, similar to what the `vue/custom-event-name-casing` offers.

**Please provide some example code that this change will affect:**

```vue
// Parent.vue
<template>
  <custom-component @click:custom="doSomething" />
</template>
```

```vue
// CustomComponent.vue
<template>
  <div @click="$emit('click:custom')" :class="{ 'cursor-pointer': hasCustomClick }">
    Some button
  </div>
</template>

<script lang="ts">
import { computed, defineComponent } from "vue";

export default defineComponent({
  props: {
    'onClick:custom': { 
        type: Function, 
        required: false,
        default: undefined,
      }
  },
  emits: {
      'onClick:custom': () => true
  },
  setup(props) {
      const hasCustomClick = computed(() => props['onClick:custom'])
      
      return { hasCustomClick }
  }
})
</script>
```

**What does the rule currently do for this code?**
Throws error: "Prop "onClick:custom" is not in camelCase."

**What will the rule do after it's changed?**
No error will be thrown after changing the `vue/prop-name-casing` rule to:

```json
"rules": {
  "vue/prop-name-casing": [
      "error",
      "camelCase",
      {
        "ignores": [
          "on[A-Z].*?:.*?" // Pattern for events passed as props
        ]
      }
  ]
}
```

The `ignores` list can be extended to match other specific patterns. 

**Additional context**

This rule is useful when using Vue 3 as the documentation specifically indicates that `It is highly recommended that you document all of the events emitted by each of your components using emits.` (https://v3.vuejs.org/guide/migration/emits-option.html#migration-strategy), yet also mentions that `Events listed in the emits option will not be inherited by the root element of the component and also will be excluded from the $attrs property.`, which makes it impossible to know whether an event listener was passed onto the component - unless it is also added to the `props` option list.

**Comment by ota-meshi** [comment]
Thank you for this issue.
Your source code looks like magic to me. Was its usage specified in the Vue documentation?
I don't want to add options to support it source code.

**Comment by yassipad** [comment]
Hi! What do you mean it looks like magic aha? I put the link to the Vue 3 docs regarding the `emits` option in the issue. The idea is simply to allow for non-camelCased `propName` depending on a regex pattern (in this case, the `event` pattern, which I assume would be something like `on[A-Z].*?:.*?`).

**Comment by ota-meshi** [comment]
Is there any documentation on how to use props name with the same name as the event name?

**Comment by yassipad** [comment]
I see what you mean, but I would argue that there is no reason for Vue to change that behaviour in the future as they have repeatedly stated that events will be handled as regular attributes internally, thus treating the event listeners as regular props just like any other data passed to a component. The only missing information in the docs (as far as I could read) is the `propName` of said events, which will always be `on{EventName}` but this isn't clearly stated in the docs.
