### ISSUE TITLE
How do I format code with single quotes?

### ISSUE THREAD

**Issue by Sendoo** [vuejs/eslint-plugin-vue#1447]
**Checklist**

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have read the [FAQ](https://eslint.vuejs.org/user-guide/#faq) and my problem is not listed.

**Tell us about your environment**

- **ESLint version: 6.8.0** 
- **eslint-plugin-vue version: 6.2.2** 
- **Node version: 14.16.0** 
- **Operating System: Windows 10 Home 20H2** 

**Please show your full configuration:**

```js
module.exports = {
  root: true,
  env: {
    browser: true,
    node: true
  },
  extends: [
    'plugin:vue/base',
    'plugin:vue/essential',
    'plugin:vue/strongly-recommended',
    'plugin:vue/recommended',
    'airbnb-base'
  ],
  plugins: ['vue'],
  parserOptions: {
    ecmaVersion: 2019,
    parser: 'babel-eslint',
    sourceType: 'module'
  },
  rules: {
    'consistent-return': 'off',
    'default-case': 0,
    eqeqeq: 'off',
    'func-names': 'off',
    'global-require': 0,
    'import/prefer-default-export': 'off',
    'linebreak-style': 0,
    'max-len': ['error', { code: 200 }],
    'no-console': process.env.NODE_ENV === 'production' ? 'error' : 'off',
    'no-debugger': process.env.NODE_ENV === 'production' ? 'error' : 'off',
    'no-fallthrough': 0,
    'no-param-reassign': 0,
    'no-plusplus': 'off',
    'no-shadow': ['error', { allow: ['state'] }],
    'no-underscore-dangle': 0,
    'vue/require-default-prop': 0,
    'vue/no-v-html': 0,
    'vue/html-self-closing': [
      'error',
      {
        html: {
          void: 'always',
          normal: 'never'
        }
      }
    ]
  },
  settings: {
    'import/resolver': {
      nuxt: {
        extensions: ['.js', '.vue']
      }
    },
    'import/core-modules': ['vue', 'vuex']
  }
};
```

**What is my problem?**

How do I format a plugin vue-i18n variable with single quotes?
For the rest of the code, it works on saving, except for the values inside the tag 

VS Code settings:
```json
{
  "eslint.validate": ["vue", "javascript", "javascriptreact"],
  "editor.formatOnSave": false,
  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": true,
    "source.fixAll.stylelint": true
  },
  "vetur.validation.template": true,
}
```

**What did you do?**	
```vue
<div>
  {{ $t("text") }}
</div>
```

**What did you expect to happen?**
```vue
<div>
  {{ $t('text') }}
</div>
```

**Comment by ota-meshi** [comment]
Thank you for this issue.
Currently, there are no rules to force quotes in the interpolation. I think it's a good to add rule to this plugin.

**Comment by ota-meshi** [comment]
If you want a new rule, could you open an issue that suggests a rule to make it easier for someone to work on it? Or could you open a PR to add a rule?

**Comment by thany** [comment]
@ota-meshi Has this ever been added/fixed, to your knowledge? It's just that I'm running into this as well and this issue is like 8 months old. So I was wondering what the status is as far as a fix or a new rule goes...

Surely you haven't been waiting 8 months for someone else to create an issue just so someone can start implementing this, right? 🙂
