### ISSUE TITLE
babel-eslint is deprecated

### ISSUE THREAD

**Issue by mariusa** [vuejs/eslint-plugin-vue#1459]
https://github.com/vuejs/eslint-plugin-vue/blob/3128c113f9117cda60dd35cbf55179a89093a19f/package.json#L68

babel-eslint gives
npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.

Please reference `@babel/eslint-parser` instead.

**Comment by ota-meshi** [comment]
You don't need to use babel-eslint because devDependencies are defined in babel-eslint.

**Comment by mariusa** [comment]
Hi, I don't understand. If I don't install  babel-eslint, it gives an error in vscode complaining it doesn't find it.

If I install babel-eslint, it gives
npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.

What I'm asking is to replace babel-eslint (in devDependencies) with the new `@babel/eslint-parser`

**Comment by napter** [comment]
When I uninstall babel-eslint I get "Parsing error: Cannot find module 'babel-eslint'"
