### ISSUE TITLE
vue/component-tags-order - Could it be made fixable?

### ISSUE THREAD

**Issue by Ariane-B** [vuejs/eslint-plugin-vue#1463]
**What rule do you want to change?**

`vue/component-tags-order`

**Does this change cause the rule to produce more or fewer warnings?**

No

**How will the change be implemented? (New option, new default behavior, etc.)?**

I wish this rule could be auto-changed on `--fix`

**Please provide some example code that this change will affect:**

None. Rule stays the same.

**What does the rule currently do for this code?**

No changes.

**What will the rule do after it's changed?**

On --fix, it will swap a single-file component's main tags around so they're in the order prescribed by the rule.

**Additional context**

I've been thinking of putting together a regex that would allow me to run a mass replacement on my project to ensure all tags are in the proper order, and it seems like it's probably possible. If a regex can do it, it makes me think that it's probably possible too, and easier, for a tool that "understands" the code like ESLint.

**Comment by l-zoy** [comment]
Can I handle this?

**Comment by Ariane-B** [comment]
I certainly wouldn't complain.

**Comment by FloEdelmann** [comment]
@l-zoy Sure, go for it! Please don't use regexes though, but an AST-based solution. That might make implementation more difficult, but you can give it a try.
