### ISSUE TITLE
Unexpected token after `async` 

### ISSUE THREAD

**Issue by willin** [vuejs/eslint-plugin-vue#147]
**Tell us about your environment**

* **ESLint Version:** 4.3
* **eslint-plugin-vue Version:** 3.11.0
* **Node Version:** 8.1.4

**Please show your full configuration:**

```js
module.exports = {
  root: true,
  extends: [
    'dwing',
    'plugin:vue/recommended'
  ],
  rules: {
    'global-require': 0,
    'import/extensions': [2, 'always', { js: 'never', vue: 'never' }]
  },
  settings: {
    'import/resolver': {
      webpack: {
        config: 'build/webpack.config.js'
      }
    }
  }
};

```

**What did you do? Please include the actual source code causing the issue.**

```js
const actions = {
  async getAllData({ commit }) {
    await this.getAllData();
  }
};

export default actions;
```

```js
// or this 
export const getAllData = async ({ commit }) => {
   await this.getAllData();
}
```

**What did you expect to happen?**

**What actually happened? Please include the actual, raw output from ESLint.**

```js
file: 'file:///Users/willin/Desktop/vuetify-demo/src/store/actions.js' severity: '错误' message: 'Parsing error: Unexpected token getAllData' at: '2,9' source: 'eslint'
```

**Comment by armano2** [comment]
@willin you have to add to `parserOptions:` `ecmaVersion: 7`

**Comment by willin** [comment]
ofcourse.

**Comment by mysticatea** [comment]
Async functions are added in ECMAScript 2017. You have to have `ecmaVersion: 2017` or `ecmaVersion: 8`.

**Comment by JounQin** [comment]
@mysticatea Are you sure? I'm always using `ecmaVersion: 2017`, but this error still occurs.

**Comment by mysticatea** [comment]
@JounQin I'm sure because I implemented it.

**Comment by JounQin** [comment]
@mysticatea Please check https://github.com/JounQin/eslint-plugin-vue/tree/async_issue , just run `npn run test`

``` log
/local/GitHub/eslint-plugin-vue/tests/integrations/eslint-plugin-import/a.vue
  6:15  warning  Parse errors in imported module './b.vue': Unexpected token test (8:10)  import/namespace
  6:15  warning  Parse errors in imported module './b.vue': Unexpected token test (8:10)  import/default

✖ 2 problems (0 errors, 2 warnings)
```

**Comment by mysticatea** [comment]
@JounQin [ES2015](https://github.com/JounQin/eslint-plugin-vue/blob/6dc792c1eccaf234a733d2fcc931f79f984201ab/tests/integrations/eslint-plugin-import/.eslintrc.json#L5) does not support async functions.

**Comment by JounQin** [comment]
Emm... OK, I found out maybe there is something error in my eslint  configuration. thx any way
