### ISSUE TITLE
Are there rules to lint empty content template?

### ISSUE THREAD

**Issue by yoyo837** [vuejs/eslint-plugin-vue#1488]
**Tell us about your environment**

- **ESLint version: latest
- **eslint-plugin-vue version:7.9.0
- **Node version:14.x

**The problem you want to solve.**
Sometimes vue-loader reject empty template tag,  I hope `lint` can spot this problem in advance

**Your take on the correct solution to problem.**

**Additional context**

**Comment by ota-meshi** [comment]
Please see to the documentation.
https://eslint.vuejs.org/rules/no-empty-component-block.html

**Comment by yoyo837** [comment]
Ok, Thanks!

**Comment by yoyo837** [comment]
![image](https://user-images.githubusercontent.com/6134547/117422146-dd99fb80-af51-11eb-8913-241e563808c4.png)

Actually it's a bit different from what I wanted. 🤔
