### ISSUE TITLE
vue/no-duplicate-attr-inheritance does not recognize Vue class components

### ISSUE THREAD

**Issue by iliubinskii** [vuejs/eslint-plugin-vue#1490]
**Checklist**

**Tell us about your environment**

"eslint": "^7.25.0",
"eslint-plugin-vue": "^7.9.0",
Node 14.13.0
Windows 10

**Please show your full configuration:**
...
"vue/no-duplicate-attr-inheritance": "warn",
...

**What did you do?**	

1:

<script>
@Component export default class MyComponent extends Vue { inheritAttrs = false; }
</script>
<template>
<mycomponent v-bind="$attrs" />
</template>

2:

<script>
@Component({ inheritAttrs: false }) export default class MyComponent extends Vue {}
</script>
<template>
<mycomponent v-bind="$attrs" />
</template>

3:

<script>
export default { inheritAttrs: false };
</script>
<template>
<mycomponent v-bind="$attrs" />
</template>

**What did you expect to happen?**

I expect no linting error in all 3 samples above, because I have added "inheritAttrs" in all of them.

I expect this rule to work with Vue class component.

**What actually happened?**

In first 2 cases I get linting error:
Set "inheritAttrs" to false

In case 3 error disappears.

This rule is not yet tuned to work with Vue class components.

**Repository to reproduce this issue**

**Comment by FloEdelmann** [comment]
Vue Class Component is no longer actively maintained and not recommended for Vue 3: https://class-component.vuejs.org/

> This library is no longer actively maintained. It is no longer recommend to use Class-based components in Vue 3. The recommended way to use Vue 3 in large applications is Single-File Components, Composition API, and `<script setup>`.

So I suggest to not invest time in eslint-plugin-vue to start supporting this.
