### ISSUE TITLE
Publish typings

### ISSUE THREAD

**Issue by kddeisz** [vuejs/eslint-plugin-vue#1491]
Hello!

I maintain https://github.com/vue-a11y/eslint-plugin-vuejs-accessibility. I'd like to convert my development over to TypeScript to avoid some errors I've been having assuming things were certain types when they weren't. Would you consider publishing the typings directory that you have? Either as a declaration file in the shipped package or a separate `@types/*` package? It would be very helpful.

Thanks!

**Comment by ota-meshi** [comment]
Thank you for posting this issue.

If the files in [`typings`] are helpful to you, I think it's a good idea to publish them.
However, since the type definitions here were supposed to be used as JSDoc in this repository, they include type definitions in unusual ways, such as adding node types globally.

Perhaps we need to clean up the type definitions we publish.

[`typings`]: https://github.com/vuejs/eslint-plugin-vue/tree/master/typings

**Comment by kddeisz** [comment]
It could also just be a subset of the available types. I really only need `ParserServices.defineTemplateBodyVisitor` and then all of the AST types.

**Comment by kddeisz** [comment]
Is there something I could do to help? I'm not overly familiar with `eslint-plugin-vue` but would be happy to take a crack at it.

**Comment by ota-meshi** [comment]
If you need to define AST and `defineTemplateBodyVisitor`, you may need to expose the type from `vue-eslint-parser`.
However, the problem remains that `eslint` type definitions do not currently accept custom ASTs.
Are you going to do strict type checking in combination with `eslint` type definitions?

**Comment by kddeisz** [comment]
Ahh I didn't realize `vue-eslint-parser` shipped with the type information, thanks! That ended up being enough.

Here's the PR if you're curious: https://github.com/vue-a11y/eslint-plugin-vuejs-accessibility/pull/148/files.

**Comment by NiccoMlt** [comment]
Hi, I was about to open a new issue about a similar problem, but then I found this issue.

I'm working on an extension of this plugin (mainly to leverage `vue-eslint-parser` and Vue ESLint rules to lint a superset of Vue SFC) and I think having full typing available would be very cool.

I tried importing `typings` as a subtree on the repo, but as it was pointed out sometimes types are declared in "unusal" ways and doesn't go along well with my TypeScript setup.

Would you still consider publishing the typings directory, maybe after a clean up?

**Comment by kddnewton** [comment]
Hey @NiccoMlt you should be able to use the same types I ended up using in that PR. Link: https://github.com/vue-a11y/eslint-plugin-vuejs-accessibility.

**Comment by NiccoMlt** [comment]
I will surely give a try, thank you! But taking a quick look at that PR it seems like `eslint-plugin-vue` is never imported directly; am I missing something?

If I need to leverage i.e. the utils declared in the project, I will still need to declare typings for that, or copy the files over (which is still sub-optimal in my opinion)

**Comment by kddnewton** [comment]
Yeah that's true. I ended up rewriting them mostly. You're welcome to use the utilities in my plugin.
