### ISSUE TITLE
vue/no-side-effects-in-computed-properties does not work with vue-demi

### ISSUE THREAD

**Issue by jesusgn90** [vuejs/eslint-plugin-vue#1495]
**Checklist**

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have read the [FAQ](https://eslint.vuejs.org/user-guide/#faq) and my problem is not listed.

**Tell us about your environment**

- **ESLint version:** v7.26.0
- **eslint-plugin-vue version:** ^7.9.0
- **Node version:** v14.15.4
- **Operating System:** ubuntu 20.04 LTS

**Please show your full configuration:**

```json5
// PRIVATE CONFIG BUT USING plugin:vue/recommended
```

**What did you do?**	

```vue
<script lang="ts">
import { computed, defineComponent, ref } from 'vue-demi'

export default defineComponent({
  ...
  setup () {
    const foo = ref(0)
    const bar = computed(() => {
      foo.value = 1 // SIDE EFFECT
      return true
    })
  }
})
</script>

```

**What did you expect to happen?**

Fire `vue/no-side-effects-in-computed-properties` rule as it's marked as `error` and after debugging it a bit seems like not parsing computed fields as computed nodes.

![image](https://user-images.githubusercontent.com/8860227/118794110-8a04a780-b899-11eb-862b-db07e76b2c1a.png)

**Comment by FloEdelmann** [comment]
Should be fixed by now, see the demo in https://eslint.vuejs.org/rules/no-side-effects-in-computed-properties.html
