### ISSUE TITLE
Make `eqeqeq`/`vue/eqeqeq` enabled by default

### ISSUE THREAD

**Issue by TheDutchCoder** [vuejs/eslint-plugin-vue#1503]
**Tell us about your environment**

- **ESLint version:** 7.27.0
- **eslint-plugin-vue version:** 7.10.0
- **Node version:** 16.0.0

**The problem you want to solve.**
I think `eqeqeq` should be enabled in one of the profiles as it's a pretty standard best practice in my experience.

**Your take on the correct solution to problem.**
Add `eqeqeq` and `vue/eqeqeq` to one of the profiles. (Maybe `plugin:vue/vue3-recommended`?)

**Additional context**

Ran into it today by accident when I realized strict equal checking wasn't enabled which I found surprising.

**Comment by ota-meshi** [comment]
We do not include that rule in the presets provided by this plugin. If you need that rule, enable it yourself or use a shareable configuration published by someone.
