### ISSUE TITLE
`vue/no-unused-refs` doesn't take Vue 2 Composition API plugin into account

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuejs/eslint-plugin-vue#1504]
**Checklist**

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have read the [FAQ](https://eslint.vuejs.org/user-guide/#faq) and my problem is not listed.

**Tell us about your environment**

- **ESLint version:** 7.27.0
- **eslint-plugin-vue version:** 7.10.0
- **Node version:** 4.15.5
- **Operating System:** win10

**Please show your full configuration:**

```js
module.exports = {
  extends: [
    'plugin:vue/recommended',
  ],
  plugins: ['vue'],
  rules: {
    'vue/no-unused-refs': 'error',
  },
};
```

**What did you do?**	

```vue
<template>
  <div ref="r" />
</template>

<script>
import { defineComponent, ref, watchEffect } from '@vue/composition-api';

export default defineComponent({
  setup () {
    const r = ref();
    watchEffect(() => console.log(r.value));
    return { r };
  },
});
</script>

```

**What did you expect to happen?**
no error

**What actually happened?**

`ESLint: 'r' is defined as ref, but never used.(vue/no-unused-refs)`

**Repository to reproduce this issue**

**Comment by ota-meshi** [comment]
This issue was fixed in #1556, so close it.
