### ISSUE TITLE
vue3 project Tips：The template root requires exactly one element？

### ISSUE THREAD

**Issue by dabaii** [vuejs/eslint-plugin-vue#1516]
Use Vue/CLI to create a vue3 project.

App.vue
~~~
<template>
  <div id="nav">
    <router-link to="/">Home</router-link> |
    <router-link to="/about">About</router-link>
  </div>  
  <router-view />
</template>
~~~

error message
~~~
[vue/valid-template-root]
The template root requires exactly one element.eslint-plugin-vue
~~~

Vue3 allows multiple roots, But the Eslint prompt only allows one root.

Adding .Eslintrc. JS configuration does not take effect.
~~~
 rules: {
    'vue/valid-template-root': 'off'
  },
~~~

😂😂😂

**Comment by ota-meshi** [comment]
You need to specify `"plugin:vue/vue3-essential"`, `"plugin:vue/vue3-strongly-recommended"` or `"plugin:vue/vue3-recommended"` for `extends`.


https://eslint.vuejs.org/rules/#priority-a-essential-error-prevention-for-vue-js-3-x
https://eslint.vuejs.org/rules/#priority-b-strongly-recommended-improving-readability-for-vue-js-3-x
https://eslint.vuejs.org/rules/#priority-c-recommended-minimizing-arbitrary-choices-and-cognitive-overhead-for-vue-js-3-x

**Comment by ota-meshi** [comment]
Also, you're probably using an older version of eslint-plugin-vue. 
You need to upgrade eslint-plugin-vue.

**Comment by ota-meshi** [comment]
The next time you post an issue, be sure to use the issue template.

**Comment by dabaii** [comment]
This ELINT plugin Vue from the @ Vue / cli 4.5.13 generator.
