### ISSUE TITLE
defineProps and defineEmits throw "no-undef" warning

### ISSUE THREAD

**Issue by davidbernegger** [vuejs/eslint-plugin-vue#1573]
**Checklist**

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have read the [FAQ](https://eslint.vuejs.org/user-guide/#faq) and my problem is not listed.

**Tell us about your environment**

- **ESLint version: 7.30.0** 
- **eslint-plugin-vue version: 7.13.0** 
- **Node version: 14.16.0** 
- **Operating System: Windows** 

**Please show your full configuration:**

```json5
{
	"parserOptions": {
		"ecmaVersion": 2021
	},
	"env": {
        "browser": true,
        "node": true
    },
	"extends": [
		"eslint:recommended",
		"plugin:vue/vue3-recommended"
	],
	"rules": {
		"semi": ["error", "never"],
		"quotes": ["error", "single"],      
		"indent": ["error", 4],
		"no-unused-vars": "off",
        "newline-per-chained-call": ["error", { "ignoreChainWithDepth": 2 }]
	},
	"ignorePatterns": ["index.html"]
}
```

defineProps and defineEmits are compiler macros (they get imported automatically) in @vue/compiler-sfc, using script setup and no longer need to be imported - eslint still has a (no-undef) warning

![image](https://user-images.githubusercontent.com/16232537/126009176-7b9fd4b2-0e62-43b7-a297-522f08aec951.png)

**Comment by ota-meshi** [comment]
please use global variables.

https://eslint.vuejs.org/user-guide/#compiler-macros-such-as-defineprops-and-defineemits-are-warned-by-no-undef-rule
