### ISSUE TITLE
![image](https://user-images.githubusercontent.com/609138/122051043-70954380-cde4-11eb-8841-937eaf51f716.png)

### ISSUE THREAD

**Issue by mellester** [vuejs/eslint-plugin-vue#1580]
![image](https://user-images.githubusercontent.com/609138/122051043-70954380-cde4-11eb-8841-937eaf51f716.png)

My problem is I have a `<script setup async>` block and I get parsing errors if I use the 'await' keyword.
Edit:Spelling

_Originally posted by @mellester in https://github.com/vuejs/eslint-plugin-vue/issues/1248#issuecomment-861450402_

**Comment by mellester** [comment]
I cant seem to disable this parsing error

**Comment by ota-meshi** [comment]
You need to read the docs and FAQ.
