### ISSUE TITLE
Detects merge conflict prompt strings

### ISSUE THREAD

**Issue by zzzzzzboy** [vuejs/eslint-plugin-vue#1585]
**Tell us about your environment**

- **ESLint version:** ^3.5.1
- **eslint-plugin-vue version:** ^5.2.2
- **Node version:** 10.24.1

**The problem you want to solve.**
When resolving merge conflicts, You might forget to delete the merge conflict prompt code string, this rule will help you detect these strings.
As shown below, it can only detect strings like "<<<" and throw an error, but it can't detect" >>>".
![](https://user-images.githubusercontent.com/42526781/127421789-cd1d2a33-ed84-473a-baa1-f8f57a6bd4dc.png)

**Your take on the correct solution to problem.**
show up a parsing error.

**Additional context**

![image](https://user-images.githubusercontent.com/42526781/127443557-58ce4b00-4186-4f10-a272-a9c6e24084d7.png)
![image](https://user-images.githubusercontent.com/42526781/127443587-8bba4328-c3e8-4a99-be29-f80127f6c10e.png)

**Comment by ota-meshi** [comment]
Thank you for posting this issue.

I don't want to add it rule. 
Even if we can implement the rule well, you can't solve the problem with files other than vue.
Therefore, I think it is difficult to implement with the eslint plugin.

**Comment by zzzzzzboy** [comment]
@ota-meshi 
For now, I just want to detect the string(">>>>") in the vue file. Other files are not in my consideration.

**Comment by ota-meshi** [comment]
You can create an eslint plugin for yourself and implement it rule.
