### ISSUE TITLE
vue/no-unused-properties doesn't recognize unused methods inside other method

### ISSUE THREAD

**Issue by Alex-Sokolov** [vuejs/eslint-plugin-vue#1589]
**Checklist**

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have read the [FAQ](https://eslint.vuejs.org/user-guide/#faq) and my problem is not listed.

**Tell us about your environment**

- **ESLint version:** 7.31.0
- **eslint-plugin-vue version:** 7.14.0
- **Node version:** 14.17.1
- **Operating System:** WIndows 10

**Please show your full configuration:**

```json5
module.exports = {
    extends: [
       'eslint:recommended',
       'plugin:vue/recommended',
    ],
    rules: {
       'vue/no-unused-properties': [
        'warn',
        {
          groups: ['props', 'data', 'computed', 'methods', 'setup']
        }
      ]
    }
}
```

**What did you do?**	

```vue
<template>
  <div class="hello">
    <input type="file" ref="input" multiple class="hidden" />
    <button type="button" @click="attachFiles">TEST</button>
  </div>
</template>

<script>
export default {
    name: 'HelloWorld',
    data() {
      return {
        maxFileSize: 25
      }
    },
    methods: {
      attachFiles() {
        const files = Array.from(this.$refs.input.files)
  
        // NOT EXIST METHOD convertBytesToMB
        if (files.some(file => this.convertBytesToMB(file.size) > this.maxFileSize)) {
          return
        }
  
        this.$emit('input', files)
      },
    }
};
</script>

```

**What did you expect to happen?**
Method convertBytesToMB marked as unused

**What actually happened?**
No errors

**Comment by ota-meshi** [comment]
I can't reproduce your problem. Could you share the smallest repository to reproduce your problem?

**Comment by ota-meshi** [comment]
I misunderstood. The `no-unused-properties` rule warns you if the defined property is unused. `convertBytesToMB` is not defined in your vue file, so will not be warned.

See the documentation for details.
https://eslint.vuejs.org/rules/no-unused-properties.html
