### ISSUE TITLE
4.0.0 - Official release roadmap

### ISSUE THREAD

**Issue by michalsnik** [vuejs/eslint-plugin-vue#159]
@mysticatea @armano2 @chrisvfritz 

I think it's about time to think about preparing first official release of this plugin. We've done a great job here and people should be able to take advantage of it and write better code :)

My plan for upcoming release is as follows:
1. ✅ Finish all issues added to `Official Release` milestone
2. ✅ Fix any bugs that may arise at any time
3. ✅ Extensively test all rules in living projects
4. ✅ Recommend more rules by default and remove deprecated ones
5. ✅ Release `4.0.0-beta.0` and tag it as next
6. ✅ Share a word with public (vue chat, twitter and so on) to get final feedback and fix last prominent issues
7.  ✅ In the meanwhile we don't add any new rules (we can work on them but we won't add anything expect bug fixes)
8. ✅ Realease offical `v4.0.0`
9. Add `eslint-plugin-vue` to [vuejs webpack template](https://github.com/vuejs-templates/webpack)

Right now we're at the first step. I'm going to update this PR as we progress.

What do you think guys? Do you see anything worth adding in the first official release? If yes please let us now so we can mark those accordingly and ship them alongside other main rules.

**Comment by chrisvfritz** [comment]
@michalsnik Excellent! 😄  I'll reprioritize Style Guide work then, so that we can release these at the same time.

**Comment by armano2** [comment]
@michalsnik ok, I'm going to focus less on new rules and more on testing and fixing issues

_Sent from my Xiaomi Redmi 4A using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by armano2** [comment]
@michalsnik we are missing tag for `3.11.0`,

**Comment by LinusBorg** [comment]
Hey gang! Is this plugin compatible with eslint 4? I want to bump the eslint version in the webpack template to `4.*`, but want to ensure compatibility to this plugin once its released.

**Comment by michalsnik** [comment]
@LinusBorg this plugin is compatible with eslint 4, there was however an issue with `indent` rule from eslint 4, that has problem with initial offset in `<script>` tag (re #118) but AFAIK @mysticatea is on it

**Comment by LinusBorg** [comment]
Thanks. Will track this issue / the PR and bump to eslint 4 once I see this was successfully solved.

**Comment by michalsnik** [comment]
Alright folks!

We're at the point number 5. Check 4.0 milestone [here](https://github.com/vuejs/eslint-plugin-vue/milestone/2).

I'm going to finally release first beta of 4.0 now 🎉 

@LinusBorg This plugin is compatible with Eslint 4.x. The only thing about `indent` I mentioned above is that this rule has been rewritten in eslint and is more strict now, thus it expects the indentation in `<script>` tag to start at index 0. `indent` rule in eslint 3.x allowed it to have initial indentation increased. We're going to work on custom `indent` rules, but it's not a part of 4.0 release :) It's not a bug, or anything and it works very good, but if you'd like to use old indentation rule you can use `indent-legacy` instead, they included it in eslint 4.x :)

**Comment by michalsnik** [comment]
`eslint-plugin-vue@4.0.0-beta.0` released 🚀 🍾

I tagged it as `next` on npm, so you can install latest version by executing:
```
npm install eslint-plugin-vue@next --save-dev
```

One last PR: https://github.com/vuejs/eslint-plugin-vue/pull/244 and we're going to share this info in the community :)

Huge kudos to @mysticatea @chrisvfritz and @armano2 💪 We wouldn't get that far it wasn't for you :)

**Comment by chrisvfritz** [comment]
Also thank YOU @michalsnik for your considerable hard work on this. 😻 I'm so excited about what we've built together and already have half a dozen teams using it to be much more productive!

**Comment by michalsnik** [comment]
First tweet is out https://twitter.com/michalsnik/status/934340597720154113
We could use your help @yyx990803 to reach more people :) It's important to get as much feedback as possible in order to go through beta period flawlessly.

**Comment by yyx990803** [comment]
@michalsnik thanks so much for the great work!

**Comment by michalsnik** [comment]
I'm happy to close this issue now :D Good job everyone 🎉  We're only missing the last part about adding it to webpack template, but @LinusBorg is on it :)

**Comment by LinusBorg** [comment]
It's already on the develop branch, will publish tomorrow. The only thing that kept me from it where that CI tests failed - appears melt for memory reasons. Have to switch to circleci 2.0 asap.
