### ISSUE TITLE
Rule for formatting emit names

### ISSUE THREAD

**Issue by kwiksilver3441** [vuejs/eslint-plugin-vue#1595]
**Tell us about your environment**

- **ESLint version 7.22.0
- **eslint-plugin-vue version:** 
- "eslint-plugin-nuxt": "^2.0.0",
    "eslint-plugin-vue": "^7.7.0",
- **Node version: 14.17.4

**The problem you want to solve.**
Consistent formatting of the $emit method.

**Your take on the correct solution to problem.**
When naming what the emit is called, you could use camel case, pascal case. Doesn't matter. I find most often people use hyphenated names for emit ex: $emit('name-to-call') This is the format I would prefer, but when I'm writing, I often finding myself resorting to typical camelcase. Explicitly creating a rule to add this would make it cleaner and more formatted. 
Truly, you could make the rule have an attribute that allowed one to pick what formatting they prefer, but I would say hyphenated should be default. 

**Additional context**

**Comment by kwiksilver3441** [comment]
This is too closely related to the rule "attribute-hyphenation" so I'm going to close it.

**Comment by ota-meshi** [comment]
Please provide the source code example according to the issue template.

**Comment by ota-meshi** [comment]
I think you want the following rules:
https://eslint.vuejs.org/rules/v-on-event-hyphenation.html
https://eslint.vuejs.org/rules/custom-event-name-casing.html
If not, please provide source code examples.
