### ISSUE TITLE
vue/no-deprecated-scope-attribute does not work correctly

### ISSUE THREAD

**Issue by lovetingyuan** [vuejs/eslint-plugin-vue#1613]
**Checklist**

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have read the [FAQ](https://eslint.vuejs.org/user-guide/#faq) and my problem is not listed.

**Tell us about your environment**

- **ESLint version:** v7.32.0 
- **eslint-plugin-vue version:** 7.16.0
- **Node version:** 12.18.4
- **Operating System:** Darwin Kernel Version 19.6.0

**Please show your full configuration:**

```json5
{
  "env": {
    "browser": true,
    "es2020": true,
    "node": false,
    "commonjs": false
  },
  "globals": {},
  "parser": null,
  "parserOptions": {
    "ecmaVersion": 2020,
    "ecmaFeatures": {
      "jsx": true,
      "legacyDecorators": false
    }
  },
  "plugins": [
    "vue"
  ],
  "rules": {
    "import/extensions": [
      "error",
      "always",
      {
        "js": "never",
        "mjs": "never",
        "jsx": "never",
        "ts": "never",
        "tsx": "never"
      }
    ],
    "no-process-env": [
      "error"
    ],
    "global-require": [
      "error"
    ],
    "no-shadow": [
      "error"
    ],
    "no-loss-of-precision": [
      "error"
    ],
    "vue/no-deprecated-scope-attribute": [
      "error"
    ],
    "vue/no-deprecated-slot-attribute": [
      "warn"
    ],
    "vue/no-deprecated-slot-scope-attribute": [
      "warn"
    ]
  },
  "settings": {
    "import/external-module-folders": [
      "node_modules",
      "node_modules/@types"
    ],
    "import/extensions": [
      ".js",
      ".ts",
      ".jsx",
      ".tsx",
      ".d.ts"
    ]
  },
  "ignorePatterns": []
}

```

**What did you do?**	

```vue
<template>
    <div>
        <comp-a
            slot="df"
            slot-scope="sdfs"
            scope="sdfs"
            :a="sdfs"
        />
    </div>
</template>

```

**What did you expect to happen?**

```bash
/vite-vue/packages/eslint-plugin/example/src/c.vue
  4:13  warning  `slot` attributes are deprecated   vue/no-deprecated-slot-attribute
  5:13  warning  `slot-scope` are deprecated        vue/no-deprecated-slot-scope-attribute
  6:13  error    `scope` attributes are deprecated  vue/no-deprecated-scope-attribute
```

**What actually happened?**

```bash
/vite-vue/packages/eslint-plugin/example/src/c.vue
  4:13  warning  `slot` attributes are deprecated  vue/no-deprecated-slot-attribute
  5:13  warning  `slot-scope` are deprecated       vue/no-deprecated-slot-scope-attribute

```
**Repository to reproduce this issue**
https://github.com/vuejs/eslint-plugin-vue/blob/80ca3ea1f8c421c57169f279463299b3096f73b3/lib/rules/syntaxes/scope-attribute.js#L26
I think "scope" attribute is just an attribute, it is not a directive, so why use `VAttribute[directive=true] > VDirectiveKey[name.name='scope']` to detect it?

**Comment by ota-meshi** [comment]
The `scope` attribute is *now*  just an attribute, as you say.
However, the `scope attribute existed as a special attribute in the past.

https://vuejs.org/v2/api/#scope-removed

If you don't need the rule, turn it off.

**Comment by ota-meshi** [comment]
Maybe I misunderstood what you were saying.

The special attribute `scope` had to be used with `<template>`.

https://eslint.vuejs.org/rules/no-deprecated-scope-attribute.html#vue-no-deprecated-scope-attribute

So the scope attribute you used is just an attribute and will not be reported.

**Comment by lovetingyuan** [comment]
Yes, I make a mistake, this rule is right.
