### ISSUE TITLE
Rule `vue/script-setup-uses-vars` doesn't work well with `eslint@typescript-eslint/no-unused-vars`

### ISSUE THREAD

**Issue by Jackie1210** [vuejs/eslint-plugin-vue#1617]
**Checklist**

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have read the [FAQ](https://eslint.vuejs.org/user-guide/#faq) and my problem is not listed.

**Tell us about your environment**

- **ESLint version:** 7.32.0
- **eslint-plugin-vue version:** 7.16.0
- **Node version:** 14.17.5
- **Operating System:** macOS

**Please show your full configuration:**

```json5
module.exports = {
  root: true,
  globals: {
    Sentry: true,
    defineProps: 'readonly',
    defineEmits: 'readonly',
    defineExpose: 'readonly',
    withDefaults: 'readonly'
  },
  env: {
    browser: true,
    node: true
  },
  parserOptions: {
    parser: '@typescript-eslint/parser',
    sourceType: 'module'
  },
  parser: 'vue-eslint-parser',
  extends: [
    'eslint:recommended',
    'plugin:vue/vue3-recommended',
    'plugin:@typescript-eslint/recommended',
    'standard',
    '@vue/standard',
    '@vue/typescript/recommended'
  ],
  plugins: ['vue'],
  rules: {
    'arrow-parens': ['error', 'as-needed'],
    'quote-props': ['error', 'as-needed'],
    'no-debugger': process.env.NODE_ENV === 'production' ? 2 : 0,
    'max-len': ['warn', { code: 80 }],
    'object-curly-spacing': ['error', 'always'],
    'arrow-spacing': ['error', { before: true, after: true }],
    'array-bracket-spacing': ['error', 'never'],
    'no-console': process.NODE_ENV === 'production' ? 'error' : 'warn',
    'no-unused-vars': 'off',
    '@typescript-eslint/member-delimiter-style': ['error', {
      multiline: {
        delimiter: 'none',
        requireLast: false
      },
      singleline: {
        delimiter: 'semi',
        requireLast: false
      }
    }],
    '@typescript-eslint/no-unused-vars': 'error',
    'vue/script-setup-uses-vars': 'error',
    '@typescript-eslint/explicit-module-boundary-types': 'off',
    '@typescript-eslint/semi': ['error', 'never'],
    '@typescript-eslint/no-extra-semi': ['error'],
    '@typescript-eslint/type-annotation-spacing': ['error', {
      before: false,
      after: true,
      overrides: {
        arrow: { before: true, after: true }
      }
    }]
  }
}

```

**What did you do?**	

```vue
<script setup lang='ts'>
defineProps<{
  msg: string
}>()

const fn = () => {
  // eslint-disable-next-line no-console
  console.log(123)
}
</script>
<template>
  <div @click="fn">123</div>
</template>

```

**What did you expect to happen?**
ignore `'fn' is assigned a value but never used.`

**What actually happened?**

Rule **eslint@typescript-eslint/no-unused-vars** remind me `'fn' is assigned a value but never used.`

**Repository to reproduce this issue**

**Comment by Liwoj** [comment]
I also started getting `@typescript-eslint/no-unused-vars` after switching to a `script setup` syntax. The advice in the [faq](https://eslint.vuejs.org/user-guide/#the-variables-used-in-the-template-are-warned-by-no-unused-vars-rule) helped me - after adding `'vue/script-setup-uses-vars': 'error',` to the config, the errors went away...

But it seems strange as per [rule documentation](https://eslint.vuejs.org/rules/script-setup-uses-vars.html) the rule should be already included in `"plugin:vue/vue3-recommended"` I was using

After changing the order of plugins/configs in the `extend` section of `.eslintrc.js` the errors went away **without explicitly enabling the rule**

Before:
```
extends: [   
    'plugin:vue/vue3-recommended',
    '@vue/standard',
    '@vue/typescript/recommended',
  ],
```
...note this is the default eslint config the Vue CLI 4.5.13 is generating for a new TS/Vue 3 projects

After:
```
extends: [
    '@vue/typescript/recommended',
    'plugin:vue/vue3-recommended',
    '@vue/standard',
  ],
```

**Comment by wsw70** [comment]
Sorry if this is a basic question, but I am a bit lost between the question and the answer. 

@Jackie1210 mentions in the question

```
 extends: [
    'eslint:recommended',
    'plugin:vue/vue3-recommended',
    'plugin:@typescript-eslint/recommended',
    'standard',
    '@vue/standard',
    '@vue/typescript/recommended'
  ],
```

and then @Liwoj says that a working setup is

```
extends: [
    '@vue/typescript/recommended',
    'plugin:vue/vue3-recommended',
    '@vue/standard',
  ],
```

If I am not mistaken, the elements in `extends` are different, right? Adding them to my `.eslintrc.js` yields
    Error: Failed to load config "@vue/typescript/recommended" to extend from.

(the version in the question works, but with the mentioned issues)

**How can I install the new(?) or missing(?) components?**

**Comment by wsw70** [comment]
Sorry if this is a basic question, but I am a bit lost between the question and the answer. 

@Jackie1210 mentions in the question

```
 extends: [
    'eslint:recommended',
    'plugin:vue/vue3-recommended',
    'plugin:@typescript-eslint/recommended',
    'standard',
    '@vue/standard',
    '@vue/typescript/recommended'
  ],
```

and then @Liwoj says that a working setup is

```
extends: [
    '@vue/typescript/recommended',
    'plugin:vue/vue3-recommended',
    '@vue/standard',
  ],
```

The first three entries in the question ( `'eslint:recommended', 'plugin:vue/vue3-recommended', 'plugin:@typescript-eslint/recommended'`) are the ones I had in my Quasar install. They worked, but with the issues mentioned in the question.

The solution however brings in three new (these are also the last three in the question) that I apparently do not have because I get 

    Error: Failed to load config "@vue/typescript/recommended" to extend from.

**How can I install them?**

**Comment by Jackie1210** [comment]
@wsw70 try `@vue/eslint-config-typescript`

**Comment by wsw70** [comment]
Thank you @Jackie1210 - running

```
npm i @vue/eslint-config-typescript
npm i @vue/eslint-config-standard
```

fixed the issues as far as I can tell.

**Comment by xinlei3166** [comment]
mark
