### ISSUE TITLE
Unknown parsing error: The type cast expression is expected to be wrapped with parenthesis

### ISSUE THREAD

**Issue by arishojaei** [vuejs/eslint-plugin-vue#1640]
**Checklist**

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have read the [FAQ](https://eslint.vuejs.org/user-guide/#faq) and my problem is not listed.

**Tell us about your environment**

- **ESLint version: ^6.7.2** 
- **eslint-plugin-vue version: ^6.2.2** 
- **Node version: 14.17.0** 
- **Operating System: macOS** 

**Please show your full configuration:**

```json5
module.exports = {
  root: true,
  env: {
    node: true,
  },
  extends: [
    'plugin:vue/base',
    'plugin:vue/essential',
    'plugin:vue/strongly-recommended',
    'plugin:vue/recommended',
    '@vue/airbnb',
    '@vue/typescript/recommended',
  ],
  parserOptions: {
    parser: 'babel-eslint',
    ecmaVersion: 2020,
  },
  rules: {
    indent: ['error', 2],
    'no-multiple-empty-lines': ['error', { max: 1 }],
    'import/no-extraneous-dependencies': 0,
    'max-len': ['error', { code: 180 }],
    'vue/no-v-html': 0,
    'linebreak-style': 0,
  },
  overrides: [
    {
      files: [
        '**/__tests__/*.{j,t}s?(x)',
        '**/tests/unit/**/*.spec.{j,t}s?(x)',
        '**/src/**/*.test.{j,t}s?(x)',
      ],
      env: {
        jest: true,
      },
    },
  ],
};

```

**What did you do?**	

```ts
// *.ts
methods: {
  selectTab(tabIndex:number) {
    console.log(tabIndex);
  }
}
```

**What did you expect to happen?**
Obviously, I don't expect to get this error! I couldn't any reason or solution to fix it

**What actually happened?**
```
  29:21  error  Parsing error: The type cast expression is expected to be wrapped with parenthesis.

  27 |
  28 | methods: {
> 29 |   selectTab(tabIndex:number) {
     |                     ^
  30 |     console.log(tabIndex);
  31 |   }
  32 | }
```

**Comment by ota-meshi** [comment]
I think you need to specify the `"@typescript-eslint/parser"` in `parserOptions.parser` or remove the `babel-eslint` specification from `parserOptions.parser` and respect `@vue/typescript/recommended`.

```diff
  parserOptions: {
-    parser: 'babel-eslint',
    ecmaVersion: 2020,
  },
```

**Comment by ota-meshi** [comment]
If that doesn't work, share a repository that can reproduce the problem.

**Comment by arishojaei** [comment]
> I think you need to specify the `"@typescript-eslint/parser"` in `parserOptions.parser` or remove the `babel-eslint` specification from `parserOptions.parser` and respect `@vue/typescript/recommended`.
> 
> ```diff
>   parserOptions: {
> -    parser: 'babel-eslint',
>     ecmaVersion: 2020,
>   },
> ```

Thanks, It's ok now.
