### ISSUE TITLE
Use only public APIs of ESLint

### ISSUE THREAD

**Issue by mysticatea** [vuejs/eslint-plugin-vue#171]
Link: https://github.com/eslint/eslint/issues/9193.

`vue-eslint-parser` has been depending on the private API to traverse `<template>`'s AST, so we have to fix it to work on ESLint v4.6.0.

**Comment by not-an-aardvark** [comment]
Is it possible to fix this with ESLint's public API? If not, I can revert the change in ESLint until there is a better solution.

**Comment by mysticatea** [comment]
Yes, I can. I will fix it ASAP. Thank you!

**Comment by LinusBorg** [comment]
Quick question about this: I'm maintiaining our vue webpack template and was thinking about bumping eslint to the latest version (the template is currently on eslint 3.*). Should I wait until this is fixed? What'S the estimated timeline on this?

**Comment by mysticatea** [comment]
> Should I wait until this is fixed?

I recommend that you wait for either:

- ESLint team decides to revert that commit in https://github.com/eslint/eslint/issues/9193.
- Or we release the next version of `eslint-plugin-vue` which includes #172.

I can't promise the time of the releasing since I don't have the permission to release.

@michalsnik Could you take a look this?

**Comment by michalsnik** [comment]
Fixed in `v3.13.0` 🚀  thanks @mysticatea 🥇
