### ISSUE TITLE
Allow uppercase first letter with attribute-hyphenation enabled

### ISSUE THREAD

**Issue by sqal** [vuejs/eslint-plugin-vue#1711]
**Checklist**

- [ ] I have tried restarting my IDE and the issue persists.
- [x] I have read the [FAQ](https://eslint.vuejs.org/user-guide/#faq) and my problem is not listed.

**Tell us about your environment**

- **ESLint version: 8.2.0** 
- **eslint-plugin-vue version: 8.0.3** 
- **Node version: N/A** 
- **Operating System: N/A** 

**Please show your full configuration:**

[Reproduction on the plugin's playground](https://ota-meshi.github.io/eslint-plugin-vue-demo/#eJyNV8uO3TYM/RXjbiYBogzQZZDkI4rumi5kmbbVkSVXku+jQf69h/K1Lb/SYIA71iFF8036+0W5ii6fLp+D8rqPRaA49F+/2aLQXe98LL4XbfGjqL3ripfrQC8Z6Q9ZGnqSPr6m08eJRTkbYvG7uxVfinfviy9fi/bdS/QvH4o/mVykY4XjS+3cy3vG/sLv59dRD2iAQ6SuNzJS0ufz+LpPkPnl2wW/3y7F61e+krHx3+XDxQ+GwuXT9wvUeVWu68hGUWlPKuorzP3tQ6L8He5iCBTEVfowo91gohY35yuBq72zfNnKjhYW64T03t1EPViIhK1CW3GTUbUrnvCwiiksZ4hUid67nnzUa1kHZL5VyShztop6WCCZkUnClX/DIMDKSC9ZjTNuCtG7B56Mrkk9lKEzTmcgC2whkiUfhOz1z1mDgspVMC7+jJmucOLPGGptIvkz4tPL0ogp1iecbeyMIEMp4DqccGlrtKX/k8XBCABqiYQQsT0V5x2Cx06zbyLKJl08YU3eEjJGr8vh9M3szV9j+jV5V1FqixvIxlOOU+uuwlmkPxeO6Fyla30ap5F16Ep4Y2I9FTsQ8t7WuhFv9OAutOYcYBcIe/CK+AYSut5QjGbBiy9WN+nOHYuLauwvIvW5nGOuDCFrjqa8SR1zhm6IcIIdw7sS3qN7MIHQElau8VSjBwiuaWmrNSWQv8INWxNnwu4tSeM5KVHQg4qDX4U8tNJT3rW2HSToigTVsDSGX+hLU4Gwlmv8HvEmCZ+EKFW7UmKwaKmZEuGAuOq3DAeOq67FTccWT/XajyCjn4dFn+Mgp3srpTkfVavNyvepTR9G2dM/A4ZE5sCsKiYiu0rER5/SdwxDpu3E5clWkO8RNG931Ge7DMv82LFE1zRIRm1TzCISKOhVi58YR6vzCM0UaXQ1N7BVVxr1OkqBxwEPdTqGUZzMjc1r6WCQjlFFCOgu1eLlWS3uwUn0MWldASPJIvNE1Optg89B985t3zR2vx2ojJNbMfvekuM7ME/TCeMJtAMPBOqtaVfRUef2IDrjXmCWBwuk9hr2fo+F1t32oDnwG9d5ArNMFwFNeDSb8+65VD31aSjGddbPWxCi2Wn4lu6khimJePeRALMVJswEIwPXSNDNLIqTFY0HadCIf8m7Bcd427JC5SNMoqyZf6mmkYINyUDzhu4TWFE5NA355WwoclktCA8k6ZuwAkbNEc1yGn8TJc+u3ZBbjTF2y4Qit59lOR3Q1OAuxb5OL1sTe8lRmG2j+8YNiKqXonTOkLT8primBBTlhNTSmNhiw2naGULP2khsjCuxnK3B8SthC1qslYfx1nZMuxSCfkY9zgMvmrdWo9/3Us1+MQ5udjUnudIhiyYSDaZVPJNPHNXpO69QLA05huSJspyJlm7YlbrSmRlx1qkIC6G47vCfgpL9rAgWcbjRmFlCYp4OyPzo0sAoB2y5ejEZwzo5ghYAtj/VmjDMvnrjxHBUZhj+Fb5IPK8GWnFHX75ZmMxbCierl0u+8VIrSkIhU1bXaU6jCS8HBISSyPRtxMvzQsMeACeXJoOCrAkbPfZ189igqFyZF94Tdv1zv4cobRG4hZ4WBiNLWty73SKyFaGU6g1rF2H+LokyEdX8gZaB61DyApKepyH60PRcH3ic6WDls/WOcwdhdUtzn/cS0T76luxk6o8f/wGShliF)

**What did you do?**	

```vue
<script setup>
  import { h } from 'vue'
  import Table from './Table.vue'
  const Row = () => h('tr', [
    h('td', 'foo')
  ])
</script>

<template>
  <Table :Row="Row" />
</template>
```

**What did you expect to happen?**
No error is shown for vue/attribute-hyphenation when prop name starts with a capital letter.

**What actually happened?**

```[7:16]: Attribute ':Row' must be hyphenated. ( vue/attribute-hyphenation )```

When vue/attribute-hyphenation is enabled, I can't pass a prop to a component which name starts with a capital letter. I know I can use ignore option but that's not ideal and can easily break somebody else code when he uses different settings for this rule.

**Comment by ota-meshi** [comment]
If you want to use props that start with a capital letter, you need to turn off the `vue/attribute-hyphenation` rule.
