### ISSUE TITLE
template-curly-spacing TypeError: Cannot read property 'range' of null

### ISSUE THREAD

**Issue by kind-hearted** [vuejs/eslint-plugin-vue#1733]
**Checklist**

- [ ] I have tried restarting my IDE and the issue persists.
- [ ] I have read the [FAQ](https://eslint.vuejs.org/user-guide/#faq) and my problem is not listed.

**Tell us about your environment**

- **ESLint version: ^6.7.2
- **eslint-plugin-vue version: ^6.2.2
- **Node version: 12.16.1
- **Operating System: windows 10 19042.631

**Please show your full configuration:**

```json5
module.exports = {
  root: true,
  parserOptions: {
    parser: 'babel-eslint',
    sourceType: 'module'
  },
  env: {
    browser: true,
    node: true,
    es6: true,
  },
  extends: ['plugin:vue/recommended', 'eslint:recommended'],

  // add your custom rules here
  //it is base on https://github.com/vuejs/eslint-config-vue
  rules: {
    "vue/max-attributes-per-line": [2, {
      "singleline": 10,
      "multiline": {
        "max": 1,
        "allowFirstLine": false
      }
    }],
    "vue/attribute-hyphenation": "off",
    "vue/singleline-html-element-content-newline": "off",
    "vue/multiline-html-element-content-newline":"off",
    "vue/name-property-casing": ["error", "PascalCase"],
    "vue/no-v-html": "off",
    'accessor-pairs': 2,
    'arrow-spacing': [2, {
      'before': true,
      'after': true
    }],
    'block-spacing': [2, 'always'],
    'brace-style': [2, '1tbs', {
      'allowSingleLine': true
    }],
    'camelcase': [0, {
      'properties': 'always'
    }],
    'comma-dangle': [2, 'never'],
    'comma-spacing': [2, {
      'before': false,
      'after': true
    }],
    'comma-style': [2, 'last'],
    'constructor-super': 2,
    'curly': [2, 'multi-line'],
    'dot-location': [2, 'property'],
    'eol-last': 2,
    'eqeqeq': ["error", "always", {"null": "ignore"}],
    'generator-star-spacing': [2, {
      'before': true,
      'after': true
    }],
    'handle-callback-err': [2, '^(err|error)$'],
    'indent': [2, 2, {
      'SwitchCase': 1
    }],
    'jsx-quotes': [2, 'prefer-single'],
    'key-spacing': [2, {
      'beforeColon': false,
      'afterColon': true
    }],
    'keyword-spacing': [2, {
      'before': true,
      'after': true
    }],
    'new-cap': [2, {
      'newIsCap': true,
      'capIsNew': false
    }],
    'new-parens': 2,
    'no-array-constructor': 2,
    'no-caller': 2,
    'no-console': 'off',
    'no-class-assign': 2,
    'no-cond-assign': 2,
    'no-const-assign': 2,
    'no-control-regex': 0,
    'no-delete-var': 2,
    'no-dupe-args': 2,
    'no-dupe-class-members': 2,
    'no-dupe-keys': 2,
    'no-duplicate-case': 2,
    'no-empty-character-class': 2,
    'no-empty-pattern': 2,
    'no-eval': 2,
    'no-ex-assign': 2,
    'no-extend-native': 2,
    'no-extra-bind': 2,
    'no-extra-boolean-cast': 2,
    'no-extra-parens': [2, 'functions'],
    'no-fallthrough': 2,
    'no-floating-decimal': 2,
    'no-func-assign': 2,
    'no-implied-eval': 2,
    'no-inner-declarations': [2, 'functions'],
    'no-invalid-regexp': 2,
    'no-irregular-whitespace': 2,
    'no-iterator': 2,
    'no-label-var': 2,
    'no-labels': [2, {
      'allowLoop': false,
      'allowSwitch': false
    }],
    'no-lone-blocks': 2,
    'no-mixed-spaces-and-tabs': 2,
    'no-multi-spaces': 2,
    'no-multi-str': 2,
    'no-multiple-empty-lines': [2, {
      'max': 1
    }],
    'no-native-reassign': 2,
    'no-negated-in-lhs': 2,
    'no-new-object': 2,
    'no-new-require': 2,
    'no-new-symbol': 2,
    'no-new-wrappers': 2,
    'no-obj-calls': 2,
    'no-octal': 2,
    'no-octal-escape': 2,
    'no-path-concat': 2,
    'no-proto': 2,
    'no-redeclare': 2,
    'no-regex-spaces': 2,
    'no-return-assign': [2, 'except-parens'],
    'no-self-assign': 2,
    'no-self-compare': 2,
    'no-sequences': 2,
    'no-shadow-restricted-names': 2,
    'no-spaced-func': 2,
    'no-sparse-arrays': 2,
    'no-this-before-super': 2,
    'no-throw-literal': 2,
    'no-trailing-spaces': 2,
    'no-undef': 2,
    'no-undef-init': 2,
    'no-unexpected-multiline': 2,
    'no-unmodified-loop-condition': 2,
    'no-unneeded-ternary': [2, {
      'defaultAssignment': false
    }],
    'no-unreachable': 2,
    'no-unsafe-finally': 2,
    'no-unused-vars': [2, {
      'vars': 'all',
      'args': 'none'
    }],
    'no-useless-call': 2,
    'no-useless-computed-key': 2,
    'no-useless-constructor': 2,
    'no-useless-escape': 0,
    'no-whitespace-before-property': 2,
    'no-with': 2,
    'one-var': [2, {
      'initialized': 'never'
    }],
    'operator-linebreak': [2, 'after', {
      'overrides': {
        '?': 'before',
        ':': 'before'
      }
    }],
    'padded-blocks': [2, 'never'],
    'quotes': [2, 'single', {
      'avoidEscape': true,
      'allowTemplateLiterals': true
    }],
    'semi': [2, 'never'],
    'semi-spacing': [2, {
      'before': false,
      'after': true
    }],
    'space-before-blocks': [2, 'always'],
    'space-before-function-paren': [2, 'never'],
    'space-in-parens': [2, 'never'],
    'space-infix-ops': 2,
    'space-unary-ops': [2, {
      'words': true,
      'nonwords': false
    }],
    'spaced-comment': [2, 'always', {
      'markers': ['global', 'globals', 'eslint', 'eslint-disable', '*package', '!', ',']
    }],
    'template-curly-spacing': [2, 'never'],
    'use-isnan': 2,
    'valid-typeof': 2,
    'wrap-iife': [2, 'any'],
    'yield-star-spacing': [2, 'both'],
    'yoda': [2, 'never'],
    'prefer-const': 2,
    'no-debugger': process.env.NODE_ENV === 'production' ? 2 : 0,
    'object-curly-spacing': [2, 'always', {
      objectsInObjects: false
    }],
    'array-bracket-spacing': [2, 'never']
  }
}
```

**What did you do?**	

```vue
<template>
  <div id="app">
    <img
      alt="Vue logo"
      src="./assets/logo.png"
    >
    <HelloWorld msg="Welcome to Your Vue.js App" />
  </div>
</template>

<script>
import HelloWorld from './components/HelloWorld.vue'

export default {
  name: 'App',
  components: {
    HelloWorld
  },
  data() {
    return {
      array: [],
      object: {
        name: ''
      }
    }
  },
  methods: {
    test() {
      this.array?.forEach(
        (x) => {
          console.log(`${x.a}-${x.b}-${x.c}`)
        }
      )
    }
  }
}
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>
```

**What did you expect to happen?**
No Error

**What actually happened?**

[Error - 上午11:24:12] ESLint stack trace:
[Error - 上午11:24:12] TypeError: Cannot read property 'range' of null
Occurred while linting D:\Tests\use-vue2\src\App.vue:31
    at SourceCode.getTokenBefore (D:\Tests\use-vue2\node_modules\eslint\lib\source-code\token-store\index.js:298:18)
    at checkSpacingBefore (D:\Tests\use-vue2\node_modules\eslint\lib\rules\template-curly-spacing.js:60:42)
    at TemplateElement (D:\Tests\use-vue2\node_modules\eslint\lib\rules\template-curly-spacing.js:119:17)
    at D:\Tests\use-vue2\node_modules\eslint\lib\linter\safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (D:\Tests\use-vue2\node_modules\eslint\lib\linter\safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (D:\Tests\use-vue2\node_modules\eslint\lib\linter\node-event-generator.js:254:26)
    at NodeEventGenerator.applySelectors (D:\Tests\use-vue2\node_modules\eslint\lib\linter\node-event-generator.js:283:22)
    at NodeEventGenerator.enterNode (D:\Tests\use-vue2\node_modules\eslint\lib\linter\node-event-generator.js:297:14)
    at CodePathAnalyzer.enterNode (D:\Tests\use-vue2\node_modules\eslint\lib\linter\code-path-analysis\code-path-analyzer.js:634:23)

**Repository to reproduce this issue**

It is a project by create @vue/cli, I only changed App.vue.
When I use optional chaining operator to operate array, and use template string in callback,  the problem must come up.
I try remove eslint template-curly-spacing, still have problems.

[Error - 上午11:40:50] ESLint stack trace:
[Error - 上午11:40:50] TypeError: Cannot read property 'range' of null
Occurred while linting D:\Tests\use-vue2\src\App.vue:12
    at OffsetStorage.setDesiredOffset (D:\Tests\use-vue2\node_modules\eslint\lib\rules\indent.js:340:45)
    at D:\Tests\use-vue2\node_modules\eslint\lib\rules\indent.js:1358:29
    at Array.forEach (<anonymous>)
    at Object.TemplateLiteral [as listener] (D:\Tests\use-vue2\node_modules\eslint\lib\rules\indent.js:1350:34)
    at D:\Tests\use-vue2\node_modules\eslint\lib\rules\indent.js:1596:55
    at Array.forEach (<anonymous>)
    at Program:exit (D:\Tests\use-vue2\node_modules\eslint\lib\rules\indent.js:1596:26)
    at D:\Tests\use-vue2\node_modules\eslint\lib\linter\safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (D:\Tests\use-vue2\node_modules\eslint\lib\linter\safe-emitter.js:45:38)

**Comment by FloEdelmann** [comment]
6.2.2 is a really old version, currently we're at 8.1.1. Can you please test with that version if the error persists and link a reproduction repo then?

**Comment by kind-hearted** [comment]
Thanks reply, I try install 8.1.1, the problem still exists. 
I don't have a reproduction repo.
It is a project by create @vue/cli, I only changed App.vue.
This is my package.json. 

```json5
{
  "name": "use-vue2",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "core-js": "^3.6.5",
    "vue": "^2.6.11"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^8.1.1",
    "vue-template-compiler": "^2.6.11"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/essential",
      "eslint:recommended"
    ],
    "parserOptions": {
      "parser": "babel-eslint"
    },
    "rules": {}
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not dead"
  ]
}
```

**Comment by FloEdelmann** [comment]
Maybe you can push that preliminary state to a public repo on GitHub, so we can have a look at the whole picture?

**Comment by FloEdelmann** [comment]
Also, I just noticed that this doesn't really have something to do with eslint-plugin-vue: `template-curly-spacing` is a core ESLint rule.

Please also update ESLint to the latest version (your version 6.2.2 is also much older than the current 8.3.0).

**Comment by kind-hearted** [comment]
Thanks reply, I try install eslint-plugin-vue^8.1.1, @vue/cli-plugin-eslint^5.0.0-rc.1, eslint^8.3.0, throw error.

 ERROR  TypeError: Module.createRequire is not a function

repo
https://github.com/kind-hearted/use-vue2.git

I solved it by modifying my project code.

```js
this.array || this.array.forEach(
  (x) => {
     console.log(`${x.a}-${x.b}-${x.c}`)
})
```

I close this issue, and waiting for @vue/cli new update, see if the problem exists.
