### ISSUE TITLE
Abandon `multi-word-component-names`

### ISSUE THREAD

**Issue by abitwhy** [vuejs/eslint-plugin-vue#1745]
**What rule do you want to change?**

`multi-word-component-names`

**Does this change cause the rule to produce more or fewer warnings?**

I'm not sure because I don't know if there are other rules that depend on "multi-word-component-names".

**How will the change be implemented? (New option, new default behavior, etc.)?**

As the steps required to abandon the general rules.

**Please provide some example code that this change will affect:**

Because it is proposed to abandon this rule, I don’t think it is necessary to provide example code.

**What does the rule currently do for this code?**

Report an error if it is not disabled.

**What will the rule do after it's changed?**

Less maintenance, better user experience.

**Additional context**

Reason for obsolescence (why is there no option to explain the reason in the above options):

0. If `Vue.js` does not perform case conversion of  single word component name when compiling components, that is: `<Component /> != <component />`, then the possible conflicts will be solved.
1. Conflicts between common component names and built-in component names or native label names: common component names can be avoided by following capitalized initials.
2. The name of the routing component can be kept in lower case and will not cause the above conflicts, because the routing component will not appear in the template.

**Comment by ota-meshi** [comment]
If you don't like the rule, you are free to turn it off.
https://eslint.org/docs/user-guide/configuring/rules
