### ISSUE TITLE
extension `.vue` less in sfc is not recommended

### ISSUE THREAD

**Issue by FoundTheWOUT** [vuejs/eslint-plugin-vue#1751]
**Checklist**

- [ ] I have tried restarting my IDE and the issue persists.
- [X] I have read the [FAQ](https://eslint.vuejs.org/user-guide/#faq) and my problem is not listed.

**What did you expect to happen?**
`import Foo from 'components/Foo'` -> Bad
`import Foo from 'components/Foo.vue'` -> Good

**Reference**
https://github.com/vuejs/vue-cli/issues/6064
Vue cli 5 will *drop support of extension-less Vue SFC imports*.
Vite also [not allow](https://github.com/vitejs/vite/issues/178#issuecomment-630138450) extension-less natively.

**Comment by ota-meshi** [comment]
I think you can use eslint-plugin-import.

https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/extensions.md

See the eslint-plugin-import documentation to use it.
