### ISSUE TITLE
`defineEmits` and `no-unused-types` issues with Typescript

### ISSUE THREAD

**Issue by spacedawwwg** [vuejs/eslint-plugin-vue#1758]
**Checklist**

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have read the [FAQ](https://eslint.vuejs.org/user-guide/#faq) and my problem is not listed.

**Tell us about your environment**

- **ESLint version:** 8.6.0
- **eslint-plugin-vue version:** 8.3.0
- **Node version:** v16.13.0
- **Operating System:** macOS 12.1 

**Please show your full configuration:**

```json5
{
  root: false,
  env: {
    browser: true,
    commonjs: true,
    es2021: true,
    node: true,
    'vue/setup-compiler-macros': true
  },
  extends: [
    'airbnb-base',
    'prettier',
    'plugin:vue/vue3-strongly-recommended',
    'prettier',
    'plugin:vue/vue3-strongly-recommended',
    'prettier'
  ],
  ignorePatterns: [ 'dist', 'node_modules' ],
  parser: 'vue-eslint-parser',
  parserOptions: {
    ecmaVersion: 2021,
    sourceType: 'module',
    parser: '@typescript-eslint/parser'
  },
  plugins: [ '@typescript-eslint', 'prettier', 'simple-import-sort' ],
  rules: {
    'import/extensions': 'off',
    'no-console': 'error',
    'no-debugger': 'error',
    'prettier/prettier': 'error',
    'simple-import-sort/imports': 'error',
    'simple-import-sort/exports': 'error',
    'vue/script-setup-uses-vars': 'error'
  },
  settings: { 'import/resolver': { typescript: {} } }
}
```

**What did you do?**	
```vue
<script setup lang="ts">
import { defineProps, reactive, toRefs, withDefaults } from 'vue';

import type { ExampleProps } from './Example.types';

const props = withDefaults(
  defineProps<{
    label: ExampleProps['label'];
  }>(),
  {
    label: 'Default counter label',
  }
);

const emit = defineEmits<(e: 'increase', value: number) => void>();

const { label } = toRefs(props);
const state = reactive({ count: 0 });

function increaseCount() {
  const increase = state.count + 1;
  emit('increase', increase);
  return increase;
}
</script>

<template>
  <button type="button" class="c-example" @click="increaseCount">
    {{ label }} {{ state.count }}
  </button>
</template>

<style src="./Example.css" lang="postcss"></style>
```

**What did you expect to happen?**
ESLint is valid (as per https://eslint.vuejs.org/rules/valid-define-emits.html)

**What actually happened?**

```SH
/Example.vue
  15:27  error  'e' is defined but never used      no-unused-vars
  15:42  error  'value' is defined but never used  no-unused-vars

✖ 2 problems (2 errors, 0 warnings)
```

![image](https://user-images.githubusercontent.com/1691867/149554256-900d26f7-e96f-42ed-b887-a5c23e0101f0.png)

**Repository to reproduce this issue**

TODO

**Comment by FloEdelmann** [comment]
This is not a `eslint-plugin-vue` rule, but a core ESLint rule: [`no-unused-vars`](https://eslint.org/docs/rules/no-unused-vars).

It is expected that some core ESLint rules don't work well with TypeScript. Please either disable the rule, or use [`@typescript-eslint/eslint-plugin`](https://typescript-eslint.io/)'s [`recommended` config](https://typescript-eslint.io/docs/linting/), which disables the rule, and enabled its own [`no-unused-vars`](https://typescript-eslint.io/rules/no-unused-vars) rule.

**Comment by spacedawwwg** [comment]
@FloEdelmann It's glaringly obvious what I missed now. Sorry, it's been a long day 🙈
