### ISSUE TITLE
Reactivity Transform RFC not working

### ISSUE THREAD

**Issue by essarn** [vuejs/eslint-plugin-vue#1793]
**Checklist**

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have read the [FAQ](https://eslint.vuejs.org/user-guide/#faq) and my problem is not listed.

**Tell us about your environment**

- **ESLint version:** ^8.5.0
- **eslint-plugin-vue version:** ^8.5.0
- **Node version:** v16.13.1
- **Operating System:** Windows 11

**Please show your full configuration:**

```json5
/* eslint-env node */
require('@rushstack/eslint-patch/modern-module-resolution')

module.exports = {
  root: true,
  extends: [
    'plugin:vue/vue3-essential',
    'eslint:recommended',
    '@vue/eslint-config-typescript/recommended',
    '@vue/eslint-config-prettier',
  ],
  env: {
    'vue/setup-compiler-macros': true,
  },
}

```

**What did you do?**	

```ts
// vite.config.ts
import vue from '@vitejs/plugin-vue'
import { fileURLToPath, URL } from 'url'
import { defineConfig } from 'vite'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [vue({ reactivityTransform: true })],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url)),
    },
  },
})

```

```ts
// env.d.ts

/// <reference types="vite/client" />
/// <reference types="vue/macros-global" />

```

```vue
// src/components/HelloWorld.vue

<script setup lang="ts">
  import { ref } from 'vue'

  const data = $ref(false)

  const { msg = 'test' } = defineProps<{
    msg: string
  }>()
</script>
```

**What did you expect to happen?**
The ref syntax and props destructuring should work as peer https://github.com/vuejs/rfcs/discussions/369

**What actually happened?**

```
[{
	"resource": "/home/isak/code/vue-3-pnpm/src/components/HelloWorld.vue",
	"owner": "eslint",
	"code": {
		"value": "no-undef",
		"target": {
			"$mid": 1,
			"external": "https://eslint.org/docs/rules/no-undef",
			"path": "/docs/rules/no-undef",
			"scheme": "https",
			"authority": "eslint.org"
		}
	},
	"severity": 8,
	"message": "'$ref' is not defined.",
	"source": "eslint",
	"startLineNumber": 2,
	"startColumn": 16,
	"endLineNumber": 2,
	"endColumn": 20
}]
Destructuring the `props` will cause the value to lose reactivity.eslint[vue/no-setup-props-destructure]
```
```
[{
	"resource": "/home/isak/code/vue-3-pnpm/src/components/HelloWorld.vue",
	"owner": "eslint",
	"code": {
		"value": "vue/no-setup-props-destructure",
		"target": {
			"$mid": 1,
			"external": "https://eslint.vuejs.org/rules/no-setup-props-destructure.html",
			"path": "/rules/no-setup-props-destructure.html",
			"scheme": "https",
			"authority": "eslint.vuejs.org"
		}
	},
	"severity": 8,
	"message": "Destructuring the `props` will cause the value to lose reactivity.",
	"source": "eslint",
	"startLineNumber": 4,
	"startColumn": 9,
	"endLineNumber": 4,
	"endColumn": 25
}]
```

**Repository to reproduce this issue** https://github.com/essarn/eslint-reactivity-transform

**Comment by ota-meshi** [comment]
> "no-undef"

eslint-plugin-vue doesn't yet support Vue's experimental features. We will work on it once the RFCs have been merged.
Until then, you need to specify global in your configuration.
https://eslint.org/docs/user-guide/configuring/language-options#specifying-globals

> "vue/no-setup-props-destructure"

I just learned that the compilation result of props destructuring has changed since Vue v3.2.25.
We need to change the rule.

**Comment by ota-meshi** [comment]
> >"vue/no-setup-props-destructure"
>
> I just learned that the compilation result of props destructuring has changed since Vue v3.2.25.
We need to change the rule.

I checked it again and it seems that we need to enable the experimental feature flag to change the compilation result. This means that the `vue/no-setup-props-destructure` rule will not change until the RFCs are merged.

**Comment by essarn** [comment]
> Until then, you need to specify global in your configuration. https://eslint.org/docs/user-guide/configuring/language-options#specifying-globals

That's was I ended up doing, and it works just fine.

> I checked it again and it seems that we need to enable the experimental feature flag to change the compilation result. This means that the `vue/no-setup-props-destructure` rule will not change until the RFCs are merged.

Until then, I'll keep that rule turned off.

**Comment by ota-meshi** [comment]
> Until then, I'll keep that rule turned off.

I think that's good. When RFC Reactive props destructure is realized, there is almost no need to check with `vue/no-setup-props-destructure` rule.
https://github.com/vuejs/rfcs/blob/reactivity-transform/active-rfcs/0000-reactivity-transform.md#reactive-props-destructure

**Comment by essarn** [comment]
> When RFC Reactive props destructure is realized, there is almost no need to check with `vue/no-setup-props-destructure` rule.

Yes, there should be no need for this rule. Maybe it could be good to add a section in the docs explaining how to support the RFC until then?

**Comment by ota-meshi** [comment]
RFCs (experimental features) can change frequently, so I think it difficult to maintain documentation about RFCs 😅
