### ISSUE TITLE
Is it possible to ignore top level await only in <script setup> ?

### ISSUE THREAD

**Issue by zorn-v** [vuejs/eslint-plugin-vue#1795]
Currently you can disable "top level await" globally by `parserOptions: {ecmaVersion: 2022}`.
But what if I need to allow it only in `<script setup>` blocks - it wrapped by function anyway https://v3.vuejs.org/api/sfc-script-setup.html#top-level-await

**Comment by ota-meshi** [comment]
I think you can use the `overrides` configuration to specify options that apply only to `*.vue`.
https://eslint.org/docs/user-guide/configuring/configuration-files#configuration-based-on-glob-patterns
