### ISSUE TITLE
Reactivity Transform macros missing

### ISSUE THREAD

**Issue by AndreasNasman** [vuejs/eslint-plugin-vue#1798]
**Tell us about your environment**

- **ESLint version:** 8.8.0
- **eslint-plugin-vue version:** 8.4.1
- **Node version:** 16.14.0/17.5.0

**The problem you want to solve.**
The new [Reactivity Transform](https://vuejs.org/guide/extras/reactivity-transform.html) macros are missing from `vue/setup-compiler-macros` environment option. I'd like to add them since they are available globally when using `script setup`.

**Your take on the correct solution to problem.**
Explicitly importing the macros as mentioned just above [this section header](https://vuejs.org/guide/extras/reactivity-transform.html#destructuring-with). 👇

<img width="707" alt="image" src="https://user-images.githubusercontent.com/17124245/153725570-2e23ae27-e5bd-4868-aabe-62dd0db1848d.png">

**Additional context**

Reactivity Transform is still an experimental feature, but I still think it would be nice to include in this plugin for those who want to try it out.

**Comment by ota-meshi** [comment]
I wrote a comment.
https://github.com/vuejs/eslint-plugin-vue/pull/1799#issuecomment-1038582067
