### ISSUE TITLE
"Vue.js Style Guide" URL is stale

### ISSUE THREAD

**Issue by stdedos** [vuejs/eslint-plugin-vue#1802]
https://github.com/vuejs/eslint-plugin-vue/blob/62f577dcfcb859c24c6e0d4615ad880f5e1d4688/docs/rules/attributes-order.md?plain=1#L17

**Comment by FloEdelmann** [comment]
This applies to all links to the style guide, and actually most links to `vuejs.org`. I'll fix all of them at once. Thanks for reporting!
