### ISSUE TITLE
Feature request: Script setup support for pug

### ISSUE THREAD

**Issue by Blissful89** [vuejs/eslint-plugin-vue#1810]
**Tell us about your environment**
Project is a monorepo using the following:
* TurboRepo
* Vue 3 (script setup)
* Typescript
* ESLint
* Pug

- **ESLint version:** 7.32.0
- **eslint-plugin-vue version:** 8.4.1
- **Node version:** 17

**The problem you want to solve.**
With normal html templating, eslint-plugin-vue correctly verifies used/unused components in the script setup tag.
<img width="311" alt="image" src="https://user-images.githubusercontent.com/41540849/155838514-4ea134a3-df83-4a82-a8b3-9fb474eb1755.png">

With pug templating, eslint-plugin-vue does not support the templating and thus it cannot verify whether a component is used or not.
<img width="319" alt="image" src="https://user-images.githubusercontent.com/41540849/155838591-bb32d96d-50b1-4201-9532-42fe37fd3541.png">

**Your take on the correct solution to problem.**
In `Additional context` There is an sfc plugin in the making, but I would much rather see eslint-plugin-vue support this.

**Additional context**

The following plugin is working on fixing this issue.
https://github.com/Shinigami92/eslint-plugin-vue-pug-sfc
However, I can not seem to get the plugin working, nor do I want to have an additional plugin just for this support

**Comment by juzser** [comment]
+1 
I'm using pug and also get the problem.
