### ISSUE TITLE
Feature request: make order-in-components and sort-keys auto-fixable

### ISSUE THREAD

**Issue by ilyub** [vuejs/eslint-plugin-vue#1813]
**What rule do you want to change?**

order-in-components, sort-keys

**Does this change cause the rule to produce more or fewer warnings?**

same

**How will the change be implemented? (New option, new default behavior, etc.)?**

Add auto-fixing

**Comment by ota-meshi** [comment]
`vue/order-in-components` rule already supports auto-fix.
Unless the ESLint core `sort-keys` rule supports auto-fix, the `vue/sort-keys` rule will not support auto-fix either.
