### ISSUE TITLE
Add suggestion(s) to `vue/match-component-file-name`

### ISSUE THREAD

**Issue by FloEdelmann** [vuejs/eslint-plugin-vue#1816]
**What rule do you want to change?**
[vue/match-component-file-name](https://eslint.vuejs.org/rules/match-component-file-name.html)

**Does this change cause the rule to produce more or fewer warnings?**
Same.

**How will the change be implemented? (New option, new default behavior, etc.)?**
New [suggestions](https://eslint.org/docs/developer-guide/working-with-rules#providing-suggestions) that can be applied by the user via the editor:

* "Rename component to match file name." (without file extension)
* "Rename file to match component name." (not sure if ESLint suggestions can rename files though)

Note that we can't add an auto-fix here because the user intent is not clear.

**Please provide some example code that this change will affect:**

```js
// file name: "MySuperCoolComponent.vue"
export default {
  name: 'MyAwesomeComponent',
}
```

**What does the rule currently do for this code?**
Report, but no auto-fix and no suggestions.

**What will the rule do after it's changed?**
Report, still no auto-fix, but suggestions.

* Rename component to match file name.
  ```js
  // file name: "MySuperCoolComponent.vue"
  export default {
    name: 'MySuperCoolComponent',
  }
  ```
* Rename file to match component name.
  ```js
  // file name: "MyAwesomeComponent.vue"
  export default {
    name: 'MyAwesomeComponent',
  }
  ```

**Comment by ota-meshi** [comment]
I think it's a good idea to add suggestions 👍 

> not sure if ESLint suggestions can rename files though

As far as I know, we can't rename files with the ESLint API 😅
