### ISSUE TITLE
Rule "vue/no-deprecated-slot-attribute" doesn't allow me to use slot on web components

### ISSUE THREAD

**Issue by Spronghi** [vuejs/eslint-plugin-vue#1823]
Hi,
The rule involved is `vue/no-deprecated-slot-attribute`

Example code:
```vue
<template>
  <my-web-component>
    <div slot="my-custom-slot">something here</div>
  </my-web-component>
</template>
```

The `slot="my-custom-slot"` will be highlighted as an error because of the `vue/no-deprecated-slot-attribute` rule, but from the [web component documentation](https://vuejs.org/guide/extras/web-components.html#slots) I see that the only way of using slots is using the named slot.

This version (suggested from the linter and wrote above) will not work for web components:

```vue
<template>
  <my-web-component>
    <template #my-custom-slot>
      <div>something here</div>
    </template>
  </my-web-component>
</template>
```

Is there a way to avoiding this from happens? Am I missing something?

I didn't open a bug or a rule improvement because I am not sure that's the right scope of this issue.

Thanks a lot!

**Comment by FloEdelmann** [comment]
If working with web components that way, I think it's best to disable this rule.

**Comment by Spronghi** [comment]
I cannot see any other way of using slots with web component in the official vue documentation

**Comment by FloEdelmann** [comment]
There is no way to know for this ESLint plugin whether a tag is a Vue component or a web component. Using the `slot` attribute with web components is fine, it's just not possible to check this with this ESLint plugin. So I suggest disabling the rule when working with web components.

**Comment by Spronghi** [comment]
Thanks a lot!
