### ISSUE TITLE
order-in-components does not autofix 

### ISSUE THREAD

**Issue by BoYuanSu** [vuejs/eslint-plugin-vue#1841]
**Checklist**

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have read the [FAQ](https://eslint.vuejs.org/user-guide/#faq) and my problem is not listed.

**Tell us about your environment**

- **ESLint version:** 
   ^8.12.0
- **eslint-plugin-vue version:** 
   ^8.6.0
- **Node version:** 
   v14.17.0
- **Operating System:** 
   macOS 10.15.7

**Please show your full configuration:**

```json5
module.exports = {
    extends: [
      // add more generic rulesets here, such as:
      // 'eslint:recommended',
      'plugin:vue/recommended',
      // 'plugin:vue/recommended' // Use this if you are using Vue.js 2.x.
    ],
    parser:'vue-eslint-parser',
    rules: {
      // override/add rules settings here, such as:
      // 'vue/no-unused-vars': 'error'
    }
  }

```

**What did you do?**	

// src/components/Test.vue
```vue
import { mapState } from "vuex";

export default {
  name: 'Test',
  computed:{
    ...mapState(['count']),
    aaa(){
      return '123'
    }
  },
  data:()=>({
    data:'132'
  })
}
```

**What did you expect to happen?**
save file and auto fix eslint vue/order-in-components warning

**What actually happened?**

vue/order-in-components does not autofix 

```
yarn run v1.22.15
$ eslint --print-config path::String
{
  "env": {
    "browser": true,
    "es6": true
  },
  "globals": {},
  "parser": "/Users/ohbot-frontend/Projects/ohbot/test-eslint/node_modules/vue-eslint-parser/index.js",
  "parserOptions": {
    "ecmaVersion": 2020,
    "sourceType": "module"
  },
  "plugins": [
    "vue"
  ],
  "rules": {
    "vue/attributes-order": [
      "warn"
    ],
    "vue/component-tags-order": [
      "warn"
    ],
    "vue/no-lone-template": [
      "warn"
    ],
    "vue/no-multiple-slot-args": [
      "warn"
    ],
    "vue/no-v-html": [
      "warn"
    ],
    "vue/order-in-components": [
      "warn"
    ],
    "vue/this-in-template": [
      "warn"
    ],
    "vue/attribute-hyphenation": [
      "warn"
    ],
    "vue/component-definition-name-casing": [
      "warn"
    ],
    "vue/first-attribute-linebreak": [
      "warn"
    ],
    "vue/html-closing-bracket-newline": [
      "warn"
    ],
    "vue/html-closing-bracket-spacing": [
      "warn"
    ],
    "vue/html-end-tags": [
      "warn"
    ],
    "vue/html-indent": [
      "warn"
    ],
    "vue/html-quotes": [
      "warn"
    ],
    "vue/html-self-closing": [
      "warn"
    ],
    "vue/max-attributes-per-line": [
      "warn"
    ],
    "vue/multiline-html-element-content-newline": [
      "warn"
    ],
    "vue/mustache-interpolation-spacing": [
      "warn"
    ],
    "vue/no-multi-spaces": [
      "warn"
    ],
    "vue/no-spaces-around-equal-signs-in-attribute": [
      "warn"
    ],
    "vue/no-template-shadow": [
      "warn"
    ],
    "vue/one-component-per-file": [
      "warn"
    ],
    "vue/prop-name-casing": [
      "warn"
    ],
    "vue/require-default-prop": [
      "warn"
    ],
    "vue/require-prop-types": [
      "warn"
    ],
    "vue/singleline-html-element-content-newline": [
      "warn"
    ],
    "vue/v-bind-style": [
      "warn"
    ],
    "vue/v-on-style": [
      "warn"
    ],
    "vue/v-slot-style": [
      "warn"
    ],
    "vue/multi-word-component-names": [
      "error"
    ],
    "vue/no-arrow-functions-in-watch": [
      "error"
    ],
    "vue/no-async-in-computed-properties": [
      "error"
    ],
    "vue/no-computed-properties-in-data": [
      "error"
    ],
    "vue/no-custom-modifiers-on-v-model": [
      "error"
    ],
    "vue/no-dupe-keys": [
      "error"
    ],
    "vue/no-dupe-v-else-if": [
      "error"
    ],
    "vue/no-duplicate-attributes": [
      "error"
    ],
    "vue/no-multiple-template-root": [
      "error"
    ],
    "vue/no-mutating-props": [
      "error"
    ],
    "vue/no-parsing-error": [
      "error"
    ],
    "vue/no-reserved-keys": [
      "error"
    ],
    "vue/no-reserved-props": [
      "error",
      {
        "vueVersion": 2
      }
    ],
    "vue/no-shared-component-data": [
      "error"
    ],
    "vue/no-side-effects-in-computed-properties": [
      "error"
    ],
    "vue/no-template-key": [
      "error"
    ],
    "vue/no-textarea-mustache": [
      "error"
    ],
    "vue/no-unused-components": [
      "error"
    ],
    "vue/no-unused-vars": [
      "error"
    ],
    "vue/no-use-v-if-with-v-for": [
      "error"
    ],
    "vue/no-useless-template-attributes": [
      "error"
    ],
    "vue/no-v-for-template-key": [
      "error"
    ],
    "vue/no-v-model-argument": [
      "error"
    ],
    "vue/require-component-is": [
      "error"
    ],
    "vue/require-prop-type-constructor": [
      "error"
    ],
    "vue/require-render-return": [
      "error"
    ],
    "vue/require-v-for-key": [
      "error"
    ],
    "vue/require-valid-default-prop": [
      "error"
    ],
    "vue/return-in-computed-property": [
      "error"
    ],
    "vue/use-v-on-exact": [
      "error"
    ],
    "vue/valid-next-tick": [
      "error"
    ],
    "vue/valid-template-root": [
      "error"
    ],
    "vue/valid-v-bind-sync": [
      "error"
    ],
    "vue/valid-v-bind": [
      "error"
    ],
    "vue/valid-v-cloak": [
      "error"
    ],
    "vue/valid-v-else-if": [
      "error"
    ],
    "vue/valid-v-else": [
      "error"
    ],
    "vue/valid-v-for": [
      "error"
    ],
    "vue/valid-v-html": [
      "error"
    ],
    "vue/valid-v-if": [
      "error"
    ],
    "vue/valid-v-model": [
      "error"
    ],
    "vue/valid-v-on": [
      "error"
    ],
    "vue/valid-v-once": [
      "error"
    ],
    "vue/valid-v-pre": [
      "error"
    ],
    "vue/valid-v-show": [
      "error"
    ],
    "vue/valid-v-slot": [
      "error"
    ],
    "vue/valid-v-text": [
      "error"
    ],
    "vue/comment-directive": [
      "error"
    ],
    "vue/jsx-uses-vars": [
      "error"
    ],
    "vue/script-setup-uses-vars": [
      "error"
    ]
  },
  "settings": {},
  "ignorePatterns": []
}
Done in 0.53s.

```

**Repository to reproduce this issue**
https://github.com/BoYuanSu/test-eslint-order-in-component

**Comment by BoYuanSu** [comment]
related to #724

**Comment by ota-meshi** [comment]
Thank you for posting issue.

The rule does not auto-fix because changing the order of method calls can have side effects. The rule cannot check what the method is.

**Comment by carl-jin** [comment]
If you have ton of files need to re-order, you can try with gogocode, here is the example that I used in my project [gogocode example](https://play.gogocode.io/#code/N4IglgdgDgrgLgYQPYBMCmIBcIA8c0C2UANgIb4B8AOhAAS04pgBuFOA9E6zR-kWZRo8AzgGMATmChxaZCAHMAvFRBxhK6hDBEk4mcFroAZpDTIdENBBkBfWkfFICtFcxhoVAbhpoAHlF0ZY1IYYiC0E0tzAMtrAApgGhc6WlEnGKs1TFpgGwAaJNooRyhhbNyClJRyUjiAShzC+nE0OBhxOlzvFPymiFICNGyVfGE4FUr6NKJ4NBRyptoxgE9iNAARGvrGlPpm1vbOm2692l6eydoCJBhrOe2KwsG4AAtUMp3TgDofglIoACCojgYCQEGEcRgwjQAKgUAAynBdGg8rQANoqFrXZgwuETFwgFAwEhgUTkXFQfEqYnVfCwqAASQgRiQKgAunVLlNiKSANb0h7nehC2gAd3Iohe5RFhDAWXRKklpAUHhAbMqNjq3Q4Ykk0k0IDyIFFul5yHQWBARluwNBdDg4mVwhZ4gIcRMayZLNR-zAqKQ0jtwgaiRSaXBMgAJLRFLRfV95EhE2l0IVw2MljdxKI0DH7GBPcykF9hFmc2mwRnSBnY5G4qX2jnUaHTlBSOJoQB5QOV8qyZXyGCkeRDWgAcjcaDHqIb2bQABVllBR2PrkS1mOzpdNRWI0sJFIZLHq3AvpEUHExzhdYe2Owb-qx3VCg-xrtaF8WiRSDnL34AnohgRCEYRAZEZjpGCmQJJGsGatOtBxH8cCSg0igUJ8pxXBKLxomOsGwWObIloEcRxGsRhwKikjyC8cBoRhLZYVMlYyLo6AdnmxQBsInbiBx9SLKcawyBRcAAHIDLmsZiV8vJoMsXz9IMQl7CJtA0XRkmDHmmmnvJinKR477Ca0sgRHATLoL4ebsWgHZfJA1mdkY5EWdpaDPiZalmXpVl+LZ-H2cIjkQM5rl6R5XmqfsbQdOZlH+TZAC0GlgLRllhX4qk7hAqnqdxpTmtJ2Eobh+EEURXx-FAZGFQxtB1vVCZWPZ5L1NF3ktHFdAAAb-oEYEgeE4HRFB8TAJGwCFcIxVfAAVkgkBxDF455GOql1DYmq9YsuXfCOliOvggkpOw7AaQc8XLFmtAOk6LqDCgqSoLmLz2cZsWHHGYwtUd7VeTYQjMjaIJgkUJS8UF4gPIU530HRcClJg53yHKLwwAARl80zsJO83COwaDCDy1jJSQMBoxAyWTuwmPEEgmPsAAjAATAALKIogAMwAOzMwAbOzACsKCY5jwsC6QAAcAAMKAoKImOiNLmNGHzpBGALERcygsvs+z7A8kz4ihMT7B2eIyWQMl0wZNYIUEwAxAAMsz7OFN130Yu+8PwmA6C0AAokYRhoMCwiIQ66UjpxERhxHtA3GoAe5q8uZ2+N9GLGOaDENOwOnPDADiDOY6QxC0AC4otJYwiR3ELQAI4wGALSR7yEBIKKawoCOtCYwpYLPenL0WJkXmnGORkF++Y4GQh8MurQ4kwL4b5T22tdwLPizw2NsQyIuy6IUqKqR6PcBLrmSBGHd71j-b2dz9aEC2mCFe777F3zoQ374LQAAsqgMAJhgqnxeAOYm99czimWHdP+AhoHtgzukAscxJ57DwugHkBA5TBQQmOaYgwHZEUqHvH+iDyS0HWGgZcWU35gGgXEas0I1C0ChHMWgkAYEIP4OSTB9A8KZ0PsIQhTAWi2hxGI1EY4PT4A7GQwuex96QWEHKO0iFBjiBHJHQq9kQTQMgEiXhAYwbgkEeOPw+AwoyJzng3wkA7HvjwtxZgqdCGQHmuHHe6paBL10LQAAau4BakdWZfAibLAA1Mo+g8MAAKw5czdnMQ3ERmRLpZRaM9ascYNLJ3skUZJlixwACVOwAFV5xBzKQAfWLpUgEZT1jwkXhdZeITcxlMKeIHOZAbrwHafYQJq9172IDigNYNcpyogCeIFea8N57AnBXAO5JhnLzGcs+gY5dRIGIMQecSBjlQE2aMpZOd7rgg0WCc5Cztn9KQKQJgCh7mLPGXlb+tAmQKKMD+XMcRR7GPsv8nMd0kC8IydYUpkB3qSDgACOADpnFTzXHnWepxXGQ0ITNTYcBSBKLnrKNQ7yulhNoNzL4vg4n+IuuJJA+BMAUNoPOB+vU2HEl6knHsdAwCR0gKIYgMB0DPR4aPFQY11HmJUKkckiZxDLC5HSge8BeGD0ge4wJt9eEcoOFAblZjNHN1bu3XhxhIC3LoDqlQvzQUAomCy0sYpczFAiEUkxsAZCjz1W0A1PLzFxkoh6h+tq7jiDBaqL4OdOVnLmR0wJXTKXUtpfDF2SAySV0RNQ8iGaK6XR-CCHEEMAwGKYcGHO1Zlhv3xYS+NIyHmXLnrSOtOcw5lXeY8ue70XmdqbVPO2swUBfyLhdIOOIHanwrsQcuoheQXxorHLhmN4EtELSwXMaAJ1qFKeKDtyqxx7slAARXcIqvtnysWqTHIPF0Zg134ExVhIhD65hPqnre5EwDbg72Vbs64P631-vHJ+lolSoC0lmdemk5Jh3AbHOu5gsH30rPQIh5D8HQNoEqRAAD1gyWhIJsmml3kxy3Dw-gODKrOmEcjlSkjzEb0RGRLQsYjhlgod2egNjSBlhAevbXDi85HRzqA9RxNtHiMCasEJxdH0qPzOCZJ+j177KOHEAgf4cUxOKfJURiJwsvgxMWOqVN9KwTJTKWgRDuYEklDLcwpxBK36uvs3oct3Csr0PQNYJOd9R5rqkXKeBwhlhjEIKU54bwUDOJZVZ7JkB5BRwfugIV7ZyAbqAq+TROrR7QrYvAL1li8J8H-rM8cgn7JEqnpV8QQdxDqafcRIwAhTpAwgIacA0B4AuwHJaScnXIHCDs60Qx4gsAOncEaO2KDOyFfgBN02KIQDCCxkEphopj4YGwDNloIAbBAA)
