### ISSUE TITLE
template 中无法支持typescript类型定义

### ISSUE THREAD

**Issue by francyfrees** [vuejs/eslint-plugin-vue#1868]
**Checklist**

- [ ] I have tried restarting my IDE and the issue persists.
- [ ] I have read the [FAQ](https://eslint.vuejs.org/user-guide/#faq) and my problem is not listed.

**Tell us about your environment**

- **ESLint version:** v8.10.0
- **eslint-plugin-vue version:** v8.5.0
- **Node version:** v14.17.5
- **Operating System:** mac12.3.1

**Please show your full configuration:**

const { defineConfig } = require('eslint-define-config')

module.exports = defineConfig({
  root: true,
  env: {
    browser: true,
    commonjs: true,
    es6: true,
    node: true
  },

  globals: {
    defineEmits: true,
    document: true,
    localStorage: true,
    GLOBAL_VAR: true,
    window: true,
    defineProps: true,
    defineExpose: true,
    $ref: true
  },
  plugins: ['@typescript-eslint', 'prettier', 'import'],
  extends: [
    'eslint:recommended',
    'plugin:@typescript-eslint/recommended',
    'plugin:vue/vue3-recommended',
    'prettier',
    './.eslintrc-auto-import.json'
  ],
  parserOptions: {
    parser: '@typescript-eslint/parser',
    ecmaVersion: 'latest', // 支持的es版本
    sourceType: 'module', // 代模块类型，默认为script，我们设置为module
    ecmaFeatures: {
      jsx: true,
      tsx: true
    }
  },
  rules: {
    'no-undef': 'off', // 关掉，与ts冲突，使用ts检查
    'no-console': 'off',
    'no-plusplus': 'off',
    'no-useless-escape': 'off',
    'no-bitwise': 'off',
    'no-async-promise-executor': 'off',
    'no-param-reassign': ['off'],

    'import/no-unresolved': [0],
    'import/extensions': 'off',
    'import/no-absolute-path': 'off',
    'import/no-extraneous-dependencies': 'off',

    'vue/multi-word-component-names': 'off',
    'vue/no-deprecated-router-link-tag-prop': 'off',
    'vue/no-setup-props-destructure': ['off'],
    'vue/script-setup-uses-vars': ['off'],
    'vue/no-multiple-template-root': 'off',
    'vue/html-self-closing': 'off',
    'vue/v-on-event-hyphenation': 'error',
    // 'vue/no-parsing-error': [
    //   0,
    //   { 'missing-semicolon-after-character-reference': false }
    // ],

    '@typescript-eslint/no-explicit-any': ['off'],
    '@typescript-eslint/explicit-module-boundary-types': ['off'],
    '@typescript-eslint/ban-ts-comment': ['off'],
    '@typescript-eslint/no-empty-function': ['off'],
    '@typescript-eslint/no-unused-vars': [0]
  }
})

```json5

```

**What did you do?**	

```vue


```
<img width="604" alt="WechatIMG194" src="https://user-images.githubusercontent.com/33947113/165211828-5ab66964-16a0-436a-9fb4-7de04511f24e.png">
<img width="586" alt="WechatIMG195" src="https://user-images.githubusercontent.com/33947113/165211846-2577d790-a282-4345-a681-9c8b619b5fcf.png">

**What did you expect to happen?**
编译通过

**What actually happened?**

编译不通过

**Repository to reproduce this issue**

**Comment by ota-meshi** [comment]
I don't understand Chinese. Please write the issue in English. Also, please provide the complete source code in text. The image does not allow us to reproduce your problem.
