### ISSUE TITLE
v9.0.0: regression in unused variables in script setup

### ISSUE THREAD

**Issue by cexbrayat** [vuejs/eslint-plugin-vue#1893]
**Checklist**

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have read the [FAQ](https://eslint.vuejs.org/user-guide/#faq) and my problem is not listed.

**Tell us about your environment**

- **ESLint version:** 
- **eslint-plugin-vue version:** 
- **Node version:** 
- **Operating System:** 
```
  System:
    OS: macOS 12.3.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 31.83 GB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.volta/tools/image/node/16.15.0/bin/node
    Yarn: 1.22.17 - ~/.volta/tools/image/yarn/1.22.17/bin/yarn
    npm: 8.10.0 - ~/.volta/tools/image/npm/8.10.0/bin/npm
  npmPackages:
    eslint: ^8.5.0 => 8.15.0
    eslint-plugin-vue: 9.0.0 => 9.0.0
    vue: ^3.2.33 => 3.2.33
```

**Please show your full configuration:**

```json5
/* eslint-env node */
require("@rushstack/eslint-patch/modern-module-resolution");

module.exports = {
  "root": true,
  "extends": [
    "plugin:vue/vue3-essential",
    "eslint:recommended",
    "@vue/eslint-config-typescript/recommended"
  ],
  "env": {
    "vue/setup-compiler-macros": true
  }
}
```

**What did you do?**	

```vue
<script setup lang="ts">
import { ref } from 'vue';
import HelloWorld from './components/HelloWorld.vue'
import TheWelcome from './components/TheWelcome.vue'
const val = ref('Hello')
</script>

<template>
  <header>
    <img alt="Vue logo" class="logo" src="./assets/logo.svg" width="125" height="125" />

    <div class="wrapper">
      <HelloWorld msg="You did it!" />
    </div>
  </header>

  <main>
    <TheWelcome />
    {{ val }}
  </main>
</template>
```

**What did you expect to happen?**
No lint warning for the variables defined in script setup

**What actually happened?**
```
/Users/cedric/Code/temp/eslint-plugin-vue-v9/src/App.vue
  3:8  warning  'HelloWorld' is defined but never used    @typescript-eslint/no-unused-vars
  4:8  warning  'TheWelcome' is defined but never used    @typescript-eslint/no-unused-vars
  5:7  warning  'val' is assigned a value but never used  @typescript-eslint/no-unused-vars
```

**Repository to reproduce this issue**

This can be reproduced in a repository created with `create-vue`, where `eslint-plugin-vue` is bumped to v9:
```
npm init vue@3 -- --typescript --eslint eslint-plugin-vue-v9
cd eslint-plugin-vue-v9
npm install
# lint is ok
npm run lint 
# bump eslint-plugin-vue to v9.0.0
npm install
# lint fails
npm run lint 
```

See https://github.com/cexbrayat/eslint-plugin-vue-v9

**Comment by ota-meshi** [comment]
Thank you for posting this issue.
It seems that vue-eslint-parser v8 is used in your environment.
You need to explicitly install vue-eslint-parser v9 and use it.

run:

```bash
yarn add -D vue-eslint-parser@latest
```

& edit .eslintrc.cjs

```diff
  "env": {
    "vue/setup-compiler-macros": true
  },
+  parser: 'vue-eslint-parser',
```

Also, report to the package that has vue-eslint-parser v8 as a dependency to update it.

**Comment by cexbrayat** [comment]
Thanks @ota-meshi 

I'll open a PR on https://github.com/vuejs/eslint-config-typescript to bump `vue-eslint-parser` then 👍

**Comment by ota-meshi** [comment]
Has been fixed in eslint-config-typescript v11 so I close this issue.

**Comment by vsalahkar** [comment]
Hi,

I have the same issue on my Nuxt3 project, even with correct packages version as [described here](https://eslint.vuejs.org/user-guide/#does-not-work-well-with-script-setup):
- eslint: ^8.27.0
- eslint-plugin-vue: ^9.7.0
- vue-eslint-parser: ^9.1.0
- nuxt: ^3.0.0

Here is my `.eslint.rc` file

```js
// .eslintrc.js
module.exports = {
  ...
  extends: [
    'eslint:recommended',
    'plugin:vue/vue3-recommended',
    'plugin:storybook/recommended',
    'plugin:@intlify/vue-i18n/recommended',
    'plugin:nuxt/recommended',
    'plugin:prettier/recommended',
  ],
  parser: 'vue-eslint-parser',
  parserOptions: {
    ecmaVersion: 'latest',
    sourceType: 'module',
  },
  ...
}
```

and the very simple component that causes the issue

```vue
<template>
  <button class="baseSubtleButton">
    <cp-icon v-if="iconBefore" class="baseSubtleButton__icon" :type="iconBefore" />
    <span><slot /></span>
    <cp-icon v-if="iconAfter" class="baseSubtleButton__icon" :type="iconAfter" />
  </button>
</template>

<script setup>
const props = defineProps({
  iconBefore: {
    type: String,
    default: '',
  },
  iconAfter: {
    type: String,
    default: '',
  },
})
</script>

<style lang="scss">
@import 'index';
</style>
```

with the following errors:
```bash
10:7  error  'props' is assigned a value but never used  no-unused-vars
```

Thanks in advance for your help, available for any additional information

**Comment by jacekkarczmarczyk** [comment]
You're not using `props` variable anywhere in your code

**Comment by vsalahkar** [comment]
> You're not using `props` variable anywhere in your code

That's what `vue-eslint-parser` is all about, isn't it? ([see FAQ](https://eslint.vuejs.org/user-guide/#does-not-work-well-with-script-setup))

![Screenshot 2022-11-17 at 21 09 34](https://user-images.githubusercontent.com/8925597/202549075-f954ab90-ac80-4d71-a0b2-fb5c9fa80790.png)

That's how we're supposed to declare props in the script setup (cf. [Vue 3 doc](https://vuejs.org/api/sfc-script-setup.html#defineprops-defineemits)) & there is no reason to use `props` variables anywhere but properties it defines instead (`iconBefore` & `iconAfter`) 🤔 

What are we suppose to do then? I guess we're lot facing this issue.

**Comment by jacekkarczmarczyk** [comment]
remove `const props = `
