### ISSUE TITLE
Rule proposition: prop-specificity

### ISSUE THREAD

**Issue by chrisvfritz** [vuejs/eslint-plugin-vue#19]
A rule to require a certain level of prop specificity could be useful. Two levels of specificity that come to mind:

1. At least type(s) (e.g. `myProp: String` or `myProp: [String, Number]`) - object value for `props`
2. At least definition object (e.g. `myProp: { type: String }`), making it easier to add other restrictions (e.g. `required`, `validate`) - requires object value for `props` and also for any properties on that object

**Comment by michalsnik** [comment]
Sounds legit, but I'd consider this as purely stylistic rule, not necessarily a good practice as it's a matter of preference. What do you think @mysticatea ?

**Comment by chrisvfritz** [comment]
I thinks it's a grey area. Greater specificity catches more errors, but errors are not inevitable with lower specificity.

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by armano2** [comment]
Validation of props helps to catch issues easier and its highly recommend for bigger projects due to a lot of components and often inexperienced developers.

We should have this rule but it's should not be enabled by default.
