### ISSUE TITLE
[Question] How to validate multiline elements of attribute

### ISSUE THREAD

**Issue by Satont** [vuejs/eslint-plugin-vue#1921]
Hi, i have i question, didn't found rule for that and tryed to use recommended, still not validated.

```
 <h6
    class="
    text-gray-500
    font-semibold
    text-sm
    py-2
    px-4
    block
    w-full
    whitespace-nowrap
    bg-transparent
  "
  >
Variables
</h6>
 ```
 
 I wan't this to be validated and expect oneliner for class, like 
 ```
<h6 class="text-gray-500 font-semibold text-sm py-2 px-4 block w-full whitespace-nowrap bg-transparent">
  Variables
</h6>
```

**Comment by ota-meshi** [comment]
There are no rules to validate the line break style for class attributes.

**Comment by Satont** [comment]
> There are no rules to validate the line break style for class attributes.

Can it be added as feature request? I can create new issue.

**Comment by ota-meshi** [comment]
Yeah. Please open the issue according to the template.
