### ISSUE TITLE
Quotes on style and script tags aren't auto fixed

### ISSUE THREAD

**Issue by whaaaley** [vuejs/eslint-plugin-vue#1927]
**Checklist**

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have read the [FAQ](https://eslint.vuejs.org/user-guide/#faq) and my problem is not listed.

**Tell us about your environment**

- **ESLint version:** ^8.5.0
- **eslint-plugin-vue version:** ^9.0.0
- **Node version:** 18.1.0
- **Operating System:** Debian

**Please show your full configuration:**

```json5
{
  "root": true,
  "env": {
    "vue/setup-compiler-macros": true
  },
  "parserOptions": {
    "ecmaVersion": 2022,
    "impliedStrict": true,
    "sourceType": "module",
    "ecmaFeatures": {
      "jsx": true
    }
  },
  "extends": [
    "eslint:recommended",
    "plugin:vue/vue3-essential",
    "standard"
  ],
  "plugins": [
    "react"
  ],
  "rules": {
    "react/jsx-indent": ["error", 2],
    "react/jsx-newline": ["error", { "prevent": true }],
    "react/jsx-uses-vars": "error",
    "jsx-quotes": ["error", "prefer-single"],
    "vue/html-quotes": [ "error", "single", { "avoidEscape": true } ],
    "vue/multi-word-component-names": 0
  }
}

```

**What did you do?**	

```vue
<style lang="scss">
.grid {
  display: grid;
  grid: auto / 1fr 2fr;
  gap: 24px;
}
</style>
```

![image](https://user-images.githubusercontent.com/7419947/177844202-5d8cb804-0145-4c28-a836-3176d3940b23.png)

**What did you expect to happen?**

Double quotes are not auto fixed to single quotes on script and style tags or vise verse, but all other tags are.

**What actually happened?**

I think this was already provided above.

**Repository to reproduce this issue**

N/A

**Comment by whaaaley** [comment]
Hi. Was this fixed?

**Comment by whaaaley** [comment]
I think this is still broken on the latest version. What kind of repro are you looking for? Would any vue/vite preset do? @ota-meshi

**Comment by FloEdelmann** [comment]
A minimal repository just highlighting that issue with the newest version of eslint-plugin-vue would be best. A vue/vite setup is fine for that.
