### ISSUE TITLE
Multi-word-component-names and no-reserved-component-names

### ISSUE THREAD

**Issue by best-lucky1030** [vuejs/eslint-plugin-vue#1930]
I made the `.vue` file like this syntax.

```
<script>
export default {
  name: "Badge",
}
</script>

<template>
  <div :class="$style.wrapper">
    <slot />
  </div>
</template>

<style module>
.wrapper {
  display: flex;
  align-items: center;
  height: 20px;
  border-radius: 6px;
  background: var(--opacity-10);
  font-size: 11px;
  font-weight: 600;
  white-space: nowrap;
  color: var(--text-primary);
  padding: 0 6px;
}
</style>
```

But it shows the error like this:

![image](https://user-images.githubusercontent.com/89365150/178173948-320af670-5003-417e-9b94-79ab9cb80253.png)

Seeing the doc, it shows component name `Badge` conflicts to HTML elements, but there is solution if we add component name to `ignore` array like this:

![image](https://user-images.githubusercontent.com/89365150/178174140-e43b33ae-47ef-4cd8-80d9-dccd6812f81f.png)

But I can't find the `json` in the project folder and structure.

https://eslint.vuejs.org/rules/multi-word-component-names.html#options
https://eslint.vuejs.org/rules/no-reserved-component-names.html

I'd like to know which json file do I have to put.

**Comment by ota-meshi** [comment]
I think you need to check the eslint documentation.

https://eslint.org/docs/latest/user-guide/configuring/rules
