### ISSUE TITLE
ERESOLVE Peer dependencies

### ISSUE THREAD

**Issue by frederikheld** [vuejs/eslint-plugin-vue#1931]
**Checklist**

- [x] I have tried restarting my IDE and the issue persists. --> issue has nothing to do with the IDE
- [x] I have read the [FAQ](https://eslint.vuejs.org/user-guide/#faq) and my problem is not listed.

**Tell us about your environment**

- **ESLint version:**  ^7.32.0
- **eslint-plugin-vue version:**  ^8.0.3
- **Node version:** v16.16.0
- **Operating System:** Ubuntu 21.10

This is an issue with the installation of ESLint, so I deleted the template, as the issue has nothing to do with how ESLint is configured or works with my source code.

This is what I did:

I have a Vue 2 project that was set up using `vue-cli` a couple of days ago. It had all ESLint stuff configured and it worked well enough to be useful (I'm not gonna rant about how messed up the whole process of setting up ESLint with Vue & VSCode is).

Today I tried to install a totally unrelated package via `npm install` and got this:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @vue/eslint-config-standard@6.1.0
npm ERR! Found: eslint-plugin-vue@8.7.1
npm ERR! node_modules/eslint-plugin-vue
npm ERR!   dev eslint-plugin-vue@"^8.0.3" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer eslint-plugin-vue@"^7.0.0" from @vue/eslint-config-standard@6.1.0
npm ERR! node_modules/@vue/eslint-config-standard
npm ERR!   dev @vue/eslint-config-standard@"^6.1.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: eslint-plugin-vue@7.20.0
npm ERR! node_modules/eslint-plugin-vue
npm ERR!   peer eslint-plugin-vue@"^7.0.0" from @vue/eslint-config-standard@6.1.0
npm ERR!   node_modules/@vue/eslint-config-standard
npm ERR!     dev @vue/eslint-config-standard@"^6.1.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```
> no, it really doesn't have anything to do with this package that I tried to install. I tried it again with some other packages with the same outcome

This is what I tried to fix it:

As `vue-cli` doesn't seem to have a remove command, I deleted all packages that were mentioned in this error log as well as everything else that was related to eslint from my `package.json`, removed `package-lock.json` and the `node_modules` directory. Then I ran `npm install` (which ran through without an error) and `vue-cli add @vue/cli-plugin-eslint` (as recommended in the [Vue docs](https://eslint.vuejs.org/user-guide/#installation)). During the installation process I selected "Standard" config. The installation ran though without any errors. Except for an "duplicate key" error because I did not delete my `.eslintrc.js` before, which I resolved manually.

ESLint works as good (or bad) as before. But the above error persists: whenever I try to install anything else via `npm install`, the peer dependency error about ESLint is thrown.

As a workaround for installing new packages, I remove everything related to ESLint, install the package, and then add it via `vue add` again.

Please let me know which additional info you need to help me fix this problem.

**Comment by frederikheld** [comment]
The error seems to be related with a recent update in `npm` that does a check if the dependency tree in `package-lock.json` is valid.

Here's a (kinda heated) discussion about the issue: https://github.com/npm/cli/issues/4664

And a comment on how to "fix" it: https://github.com/npm/cli/issues/4664#issuecomment-1086096726

If I understand this correctly, this is not really a fix but a way to force npm to be as neglectful about dependency trees as it was before. So IMHO there still is an issue with how `vue add @vue/cli-plugin-eslint` pulls in dependencies that needs to be fixed. Or a missing hint in the docs about this workaround at least.

Side note: It might be a good idea to add "npm version" to the environment info of the bug template. Because that would have been the most relevant info to understand this issue.

**Comment by ota-meshi** [comment]
I don't think it's a problem with eslint-plugin-vue. So I close this issue.

**Comment by frederikheld** [comment]
What is it then?

You answer feels a bit like a lot of website admins would answer: I don't think that the certificate warning in your browser is our fault. It worked before, so how can it be our fault?

Yeah, well, but the browser enforces stricter security rules now. You approach was bad before, but now you're being pointed out.

It's still your peer dependencies that are somewhat messed up and now npm points you out 🤷

**Comment by frederikheld** [comment]
IMHO this is an issue with the way vue-cli installs the multiple related packages when installing eslint-plugin-vue via vue-cli. I filed this bug here, because some official docs about installing eslint-plugin-vue via vue-cli pointed to this repo.

So if you're not responsible for fixing this, maybe it's a bad link then that points to the wrong repo?

**Comment by frederikheld** [comment]
@ota-meshi So you're not going to do ANYTHING about it? I just hat the same issue with a fresh Vue3 project. So if you don't feel responsible, where should I submit the issue then?

**Comment by frederikheld** [comment]
Reproduction:

1. Create new vue3 project with `vue-cli` (had the issue with vue2 before as well9
2. Delete `node_modules` directory
3. Run `npm install`

Will throw the following error:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @vue/eslint-config-standard@6.1.0
npm ERR! Found: eslint-plugin-vue@8.7.1
npm ERR! node_modules/eslint-plugin-vue
npm ERR!   dev eslint-plugin-vue@"^8.0.3" from the root project
npm ERR!   peer eslint-plugin-vue@"^8.0.1" from @vue/eslint-config-typescript@9.1.0
npm ERR!   node_modules/@vue/eslint-config-typescript
npm ERR!     dev @vue/eslint-config-typescript@"^9.1.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer eslint-plugin-vue@"^7.0.0" from @vue/eslint-config-standard@6.1.0
npm ERR! node_modules/@vue/eslint-config-standard
npm ERR!   dev @vue/eslint-config-standard@"^6.1.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: eslint-plugin-vue@7.20.0
npm ERR! node_modules/eslint-plugin-vue
npm ERR!   peer eslint-plugin-vue@"^7.0.0" from @vue/eslint-config-standard@6.1.0
npm ERR!   node_modules/@vue/eslint-config-standard
npm ERR!     dev @vue/eslint-config-standard@"^6.1.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/frederik/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/frederik/.npm/_logs/2022-09-01T11_41_49_373Z-debug-0.log
```

This is the use case when someone clones the repo and tries to install it. So it is a very common one.
