### ISSUE TITLE
"attributes-order" rule ignores "v-bind" attribute

### ISSUE THREAD

**Issue by ilyub** [vuejs/eslint-plugin-vue#1944]
**Checklist**

- [+] I have tried restarting my IDE and the issue persists.
- [+] I have read the [FAQ](https://eslint.vuejs.org/user-guide/#faq) and my problem is not listed.

**Tell us about your environment**

- **ESLint version:** 8.21.0
- **eslint-plugin-vue version:** 9.3.0
- **Node version:** 18.4.0
- **Operating System:** Win 10

**Please show your full configuration:**

```json5
"vue/attributes-order": "error",
```

**What did you do?**	

```vue
<component class="flex" v-bind="$attrs"></component>
<component v-bind="$attrs" class="flex"></component>
```

**What did you expect to happen?**

At least one error

**What actually happened?**

No error

**Repository to reproduce this issue**

I will provide on demand.

**Comment by ota-meshi** [comment]
Thank you for posting issue.

That's the intentional behavior of the rule. Since `v-bind=obj` merges previous attributes/properties, changing the order may change the behavior of the component.
https://v3-migration.vuejs.org/breaking-changes/v-bind.html
So `v-bind=obj` is ignored.
