### ISSUE TITLE
Support for type-based prop declarations and default values

### ISSUE THREAD

**Issue by helmi77** [vuejs/eslint-plugin-vue#1947]
**What rule do you want to change?**
vue/no-setup-props-destructure

**Does this change cause the rule to produce more or fewer warnings?**
Change will produce fewer warnings

**How will the change be implemented? (New option, new default behavior, etc.)?**
New default behavior

**Please provide some example code that this change will affect:**

```vue
const {
    myProp = null
} = defineProps<{
    myProp: number | null
}>()
```

**What does the rule currently do for this code?**
It throws an error for default values in type-based prop declarations.

**What will the rule do after it's changed?**
It will support the default value syntax for type-based prop declarations [1].

**Additional context**
[1] https://vuejs.org/guide/typescript/composition-api.html#props-default-values

**Comment by ota-meshi** [comment]
Reactivity Transform is still an experimental feature, so eslint-plugin-vue does not support it.
