### ISSUE TITLE
Add support for Reactivity Transform

### ISSUE THREAD

**Issue by ota-meshi** [vuejs/eslint-plugin-vue#1948]
Lists the work this plugin needs to do to support Reactivity Transform.

> **Note**
> These changes will be released after the RFCs have been merged.

- [ ] Related to new compiler macros.
  - [ ] Provide an env with global variables listed.
         https://eslint.org/docs/latest/developer-guide/working-with-plugins#environments-in-plugins
- [ ] Related to the change of `defineProps()`.
  - [ ] Change `vue/no-setup-props-destructure` rule.
          Destructuring assignment immediately after defineProps() is allowed.
          However, Vue2 doesn't allow to use Reactivity Transform, so we may need to split rules.
  - [ ] Change `vue/require-valid-default-prop` rule.
  - [ ] Change `vue/require-default-prop` rule.
  - [ ] Change `vue/no-boolean-default` rule.
          We need to support a new way to specify defaults.

And more?

**Additional context**

Docs: https://vuejs.org/guide/extras/reactivity-transform.html
PR: https://github.com/vuejs/rfcs/pull/420
Discussion: https://github.com/vuejs/rfcs/discussions/369

**Comment by ota-meshi** [comment]
related to #1793, #1798, #1799, #1947

**Comment by sxzz** [comment]
Since Reactivity Transform is deprecated, so can we just close this issue?

**Comment by ota-meshi** [comment]
Thanks for letting me know! I will close this issue.

**Comment by bperel** [comment]
Reactivity Transform has been moved to a [Vue macro](https://vue-macros.sxzz.moe/features/reactivity-transform.html), would that make it reasonable to re-open this ticket, for developers who use this macro?

**Comment by sxzz** [comment]
@bperel Vue Macros will add ESLint support soon.
