### ISSUE TITLE
vue/attributes-order does not work in my project

### ISSUE THREAD

**Issue by Joshua-Leee** [vuejs/eslint-plugin-vue#1953]
**Checklist**

- [ ✓] I have tried restarting my IDE and the issue persists.
- [ ✓] I have read the [FAQ](https://eslint.vuejs.org/user-guide/#faq) and my problem is not listed.

**Tell us about your environment**

- **ESLint version:** 8.23.0
- **eslint-plugin-vue version:** 9.4.0
- **Node version:** 16.14.0
- **Operating System:** macos 10.15.7

**Please show your full configuration:**

```
{
  root: true,
  env: {
    node: true
  },
  extends: ['eslint:recommended', 'plugin:vue/vue3-recommended', 'prettier'],
  parserOptions: {
    ecmaVersion: 2020
  },
  globals: {
    RootState: true,
    UserMsg: true,
    UserInfo: true,
    DictionariesStore: true,
    OrganizationStore: true,
    SystemStore: true,
    defineProps: 'readonly',
    defineEmits: 'readonly',
    defineExpose: 'readonly',
    withDefaults: 'readonly'
  },
  rules: {
    'no-console': process.env.NODE_ENV === 'production' ? 'warn' : 'off',
    'no-debugger': process.env.NODE_ENV === 'production' ? 'warn' : 'off',
    'vue/no-unused-vars': 'error'
  }
}
```

**What did you do?**	

```
//This is a VUE3 project created using the Vite tool

<div class="info-item" :key="msg.sn" v-for="msg in data.msgData">
  ······
</div>

// Above is my business code, then press Ctrl + S to save
```

**What did you expect to happen?**
```
//I thought that after I hit Ctrl+ S to save, the code would automatically format and then the attributes would be reordered
//Expected performance, :key will be automatically sorted after V-for

<div class="info-item" v-for="msg in data.msgData"  :key="msg.sn">
  ······
</div>
```

**What actually happened?**
vue/attributes-order does not work.The code is still:
```
<div class="info-item" :key="msg.sn" v-for="msg in data.msgData">
  ······
</div>

```
ESLint outputs the following:
```
[Info  - 10:32:33 AM] ESLint server is starting
[Info  - 10:32:33 AM] ESLint server running in node v16.13.2
[Info  - 10:32:33 AM] ESLint server is running.
[Info  - 10:32:34 AM] ESLint library loaded from: /Users/Joshua/Desktop/project/shennong/hifrozen-scm/node_modules/eslint/lib/api.js

```

**Comment by ota-meshi** [comment]
I cannot reproduce the issue.
Please share a repository that reproduces your issue.

**Comment by Joshua-Leee** [comment]
https://github.com/Joshua-Leee/attributes-order-demo
It's up here. You can check it out

**Comment by Joshua-Leee** [comment]
> I cannot reproduce the issue. Please share a repository that reproduces your issue.

https://github.com/Joshua-Leee/attributes-order-demo
It's up here. You can check it out

**Comment by ota-meshi** [comment]
Your repository does not use `plugin:vue/vue3-recommended`. Use `plugin:vue/vue3-recommended` or turn on `vue/attributes-order`.

**Comment by Joshua-Leee** [comment]
Updated it like you said, but it still doesn't work

**Comment by Joshua-Leee** [comment]
Updated it like you said, but it still doesn't work
