### ISSUE TITLE
Duplicate keys detected: '2bb27d26-21aa-43ba-8266-07c2d6b9c02f'. This may cause an update error.

### ISSUE THREAD

**Issue by muthul07** [vuejs/eslint-plugin-vue#1962]
vue.runtime.esm.js:620 [Vue warn]: Duplicate keys detected: '2bb27d26-21aa-43ba-8266-07c2d6b9c02f'. This may cause an update error.

found in

---> <VDataTable>
       <TableList> at src/components/mixins-utils/AppTable.vue
         <InfiniteScroll> at infinite-scroll.vue
           <AppContentAuto> at src/components/mixins-utils/AppContentAuto.vue
             <Users> at src/views/dealer/templates/Index.vue
               <VMain>
                 <DealerHeader> at src/views/dealer/layout/Index.vue
                   <VApp>
                     <SideBar> at src/components/layout/Index.vue
                       <App> at src/App.vue
                         <Root>
                         

  ```
  <template v-slot:dealer="item">
              <span v-if="item.program.length > 0">
                <span
                  v-for="(program, index) in item.program"
                  :key="'program' + index"
                >
                  <span v-if="program.key == 'Dealer'">
                    {{ program.value }}
                  </span>
                </span>
              </span>
              <span v-if="item.program.length == 0">
                {{ "-" }}
              </span>
            </template>              
```       

im new to vue , when i try to implement in infinite scroll, im getting the above error. tried many ways to fix it but getting the same error.

**Comment by FloEdelmann** [comment]
This is not an issue in eslint-plugin-vue, but a runtime error/warning.

It happens when multiple elements have the same value for `key`. Note that using a loop index in the `key` (like in your code example) is likely not what you want, though the issue title suggests that you have duplicate IDs somewhere (but not in this code fragment).
