### ISSUE TITLE
Lint Style Guide

### ISSUE THREAD

**Issue by Snugug** [vuejs/eslint-plugin-vue#197]
**Please describe what the rule should do:**

Enforce the various new recommendations from the official [Vue Style Guide](https://vuejs.org/v2/style-guide/index.html). This is probably closer to an epic to track being able to lint the below, as opposed to a single rule request

**What category of rule is this?**

- [x] Enforces Code Style
- [x] Warns about a potential error
- [x] Suggests an alternative way of doing something
- [ ] Other (please specify)

**Provide 2-3 code examples that this rule will warn about**

- [ ] [Multi-word Component Names](https://vuejs.org/v2/style-guide/index.html#Multi-word-component-names-essential) (on/off)
- [x] [Component data](https://vuejs.org/v2/style-guide/index.html#Component-data-essential) (`no-shared-component-data`)
- [ ] [Prop Definitions](https://vuejs.org/v2/style-guide/index.html#Prop-definitions-essential) (require type?)
- [x] [Keyed `v-for`](https://vuejs.org/v2/style-guide/index.html#Keyed-v-for-essential) (valid-v-for)
- [ ] [`scoped` styling](https://vuejs.org/v2/style-guide/index.html#Component-style-scoping-essential) (on/off with component name/glob ignores)
- [ ] [Private property names](https://vuejs.org/v2/style-guide/index.html#Private-property-names-essential) - Not sure if this one is do-able? Maybe check to see if a method starts with `_`, `$`, or `$_` and lint for `$_PLUGIN_`
- [ ] [Component Files](https://vuejs.org/v2/style-guide/index.html#Component-files-strongly-recommended)
- [ ] [Single-file component filename casing](https://vuejs.org/v2/style-guide/index.html#Single-file-component-filename-casing-strongly-recommended)
- [ ] [Base component names](https://vuejs.org/v2/style-guide/index.html#Base-component-names-strongly-recommended) - Maybe by glob with a prefix?
- [ ] [Single-instance component names](https://vuejs.org/v2/style-guide/index.html#Single-instance-component-names-strongly-recommended) - Again, not sure if this is needed? Maybe lint to see if a component doesn't accept props, and if not, recommend that?
- [ ] [Tightly coupled component names](https://vuejs.org/v2/style-guide/index.html#Tightly-coupled-component-names-strongly-recommended) - Again, not entirely sure how to lint this. Maybe count places where a given component is used and recommend based on that?
- [ ] [Order of words in component names](https://vuejs.org/v2/style-guide/index.html#Order-of-words-in-component-names-strongly-recommended) - No idea how to actually do this
- [ ] [Self-closing components](https://vuejs.org/v2/style-guide/index.html#Self-closing-components-strongly-recommended) may be covered in [`html-self-closing`](https://github.com/vuejs/eslint-plugin-vue/blob/master/docs/rules/html-self-closing.md) but may not?
- [ ] [Component name casing in templates](https://vuejs.org/v2/style-guide/index.html#Component-name-casing-in-templates-strongly-recommended)
- [ ] [Component name casing in JS/JSX](https://vuejs.org/v2/style-guide/index.html#Component-name-casing-in-JS-JSX-strongly-recommended)
- [ ] [Abbreviations in component names](https://vuejs.org/v2/style-guide/index.html#Abbreviations-in-component-names-strongly-recommended) - Not sure how to actually do this
- [ ] [Prop name casing](https://vuejs.org/v2/style-guide/index.html#Prop-name-casing-strongly-recommended) partially in [`name-property-casing`](https://github.com/vuejs/eslint-plugin-vue/blob/master/docs/rules/name-property-casing.md). Default should be `camelCase`, and will need another for the actual HTML properties
- [ ] [Multi-attribute elements](https://vuejs.org/v2/style-guide/index.html#Multi-attribute-elements-strongly-recommended) - Probably needs [indent](https://github.com/vuejs/eslint-plugin-vue/pull/145) in place with updates to work
- [ ] [Complex expressions in templates](https://vuejs.org/v2/style-guide/index.html#Complex-expressions-in-templates-strongly-recommended)
- [ ] [Complex computed properties](https://vuejs.org/v2/style-guide/index.html#Complex-computed-properties-strongly-recommended)
- [x] [Quote attribute values](https://vuejs.org/v2/style-guide/index.html#Quoted-attribute-values-strongly-recommended) Resolved by [`html-quotes`](https://github.com/vuejs/eslint-plugin-vue/blob/master/docs/rules/html-quotes.md)
- [ ] [Directive shorthands](https://vuejs.org/v2/style-guide/index.html#Directive-shorthands-strongly-recommended)
- [ ] [Component/instance options order](https://vuejs.org/v2/style-guide/index.html#Component-instance-options-order-recommended)
- [ ] [Element attribute order](https://vuejs.org/v2/style-guide/index.html#Element-attribute-order-recommended)
- [ ] [Empty lines in component/instance options](https://vuejs.org/v2/style-guide/index.html#Empty-lines-in-component-instance-options-recommended)
- [ ] [Single-file component top-level element order](https://vuejs.org/v2/style-guide/index.html#Single-file-component-top-level-element-order-recommended)

**Comment by michalsnik** [comment]
Hey @Snugug, thanks for posting this issue, I completely agree.
But we already have a topic #77 started by the author of the style guide, so feel free to share your thoughts there, and I'm closing this issue in favour of the previous one :)

**Comment by Snugug** [comment]
Sorry about the duplicate! Guess I missed that in the top list of issues!
