### ISSUE TITLE
Support JSX/TSX in `vue/max-attributes-per-line`

### ISSUE THREAD

**Issue by jd-solanki** [vuejs/eslint-plugin-vue#1979]
**What rule do you want to change?**
[`vue/max-attributes-per-line`](https://eslint.vuejs.org/rules/max-attributes-per-line.html#vue-max-attributes-per-line)

**Does this change cause the rule to produce more or fewer warnings?**
No

**How will the change be implemented? (New option, new default behavior, etc.)?**
New default behavior: Linting JSX code

**Please provide some example code that this change will affect:**

```tsx
export default defineComponent({
  setup() {
    return () => <MyComponent lorem="1" ipsum="2" class={['a', 'b']} />
  }
})
```

**What does the rule currently do for this code?**
It doesn't lint the JSX code

**What will the rule do after it's changed?**
Will lint the JSX code just like template code

**Additional context**
N/A

**Comment by ota-meshi** [comment]
Thank you for posting the issue.
But I think you can probably check JSX using eslint-plugin-react.
https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-max-props-per-line.md

So I don't think the rule need to be changed. Also, changing the rule may conflict with `react/jsx-max-props-per-line`.
