### ISSUE TITLE
`vue/no-ref-as-operand` should not autofix when variable is `Ref | NotARef`

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuejs/eslint-plugin-vue#1980]
**Checklist**

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have read the [FAQ](https://eslint.vuejs.org/user-guide/#faq) and my problem is not listed.

**Tell us about your environment**

- **ESLint version:**  8.23.1
- **eslint-plugin-vue version:** 9.5.1
- **Node version:** 16.14.2
- **Operating System:** win

**Please show your full configuration:**

```js
module.exports = {
  extends: ['jkarczm/vuetify'],
  parserOptions: {
    project: 'tsconfig.json',
  },
}
```
(where `jkarczm/vuetify` is from https://github.com/jacekkarczmarczyk/eslint-config-jkarczm package, but probably including only `vue/no-ref-as-operand` matters)

**What did you do?**	

```ts
let foo: Ref<number> | undefined;

if (!foo) {
  foo = ref(5);
}

```

**What did you expect to happen?**

no error, no autofixing

**What actually happened?**

code was "fixed" to

```js
let foo: Ref<number> | undefined;

if (!foo.value) {
  foo.value = ref(5);
}
```

**Comment by ylavoie** [comment]
```
let foo;
foo = Reactive(bar)
```
triggers the same bug.
