### ISSUE TITLE
add `no-required-prop-with-default` rule to vue2 and vue3 presets

### ISSUE THREAD

**Issue by neferqiqi** [vuejs/eslint-plugin-vue#1986]
**Tell us about your environment**

- **ESLint version:** 8.23.0
- **eslint-plugin-vue version:** 9.4.0
- **Node version:** 16.3.0

**The problem you want to solve.**
Shell we add `no-required-prop-with-default` rule to vue2 and vue3 presets?

**Your take on the correct solution to problem.**
Add this rule to vue2 and vue3 presets.

**Additional context**

**Comment by FloEdelmann** [comment]
Done in https://github.com/vuejs/eslint-plugin-vue/pull/2640, will be released in v10.
