### ISSUE TITLE
`html-self-closing` with `--fix` doesn't normalise whitespace in opening tag

### ISSUE THREAD

**Issue by axelboc** [vuejs/eslint-plugin-vue#199]
* **ESLint version: 4.8.0**
* **eslint-plugin-vue version: 3.13.0**
* **Node version: 6.11.3**

```json
{
  "extends": [
    "eslint-config-airbnb",
    "plugin:vue/recommended"
  ],
  "rules": {
    "vue/attribute-hyphenation": "error",
    "vue/html-quotes": "error",
    "vue/html-self-closing": "error",
    "vue/mustache-interpolation-spacing": "error",
    "vue/no-dupe-keys": "error",
    "vue/no-duplicate-attributes": "error",
    "vue/no-multi-spaces": "error",
    "vue/no-reserved-keys": "error",
    "vue/no-shared-component-data": "error",
    "vue/no-template-key": "error",
    "vue/order-in-components": "error",
    "vue/require-prop-types": "error",
    "vue/require-render-return": "error",
    "vue/require-valid-default-prop": "error",
    "vue/return-in-computed-property": "error",
    "vue/v-bind-style": "error",
    "vue/v-on-style": "error"
  }
}
```

**Input**

```html
<input />
<slot />
<svg><use xlink:href="..."></use></svg>
```

**Expected output**

```html
<input>
<slot></slot>
<svg><use xlink:href="..." /></svg>
```

**Actual output**

```html
<input >
<slot ></slot>
<svg><use xlink:href="..."/></svg>
```

The rule just replaces `/>` with `>` (or `>` with `/>`) in the opening tag without considering that a space may need to be removed or added.

**Comment by michalsnik** [comment]
Good catch @axelboc , thank you for posting this issue :)

**Comment by mysticatea** [comment]
Yes, the rule does not consider spacing. Another rule should handle spacing. Maybe `vue/space-before-tag-closing` rule.

```json
"vue/space-before-tag-closing": ["error", {
    "afterTagName": "always"/"never",
    "afterAttributeName": "always"/"never",
    "afterEqual": "always"/"never",
    "afterAttributeValue": "always"/"never",
}]
```

**Comment by michalsnik** [comment]
Sounds like a good idea to me @mysticatea. Each rule should fix what it reports, but if we'd change the fix method here to apply proper spacing it would additionally fix something it wouldn't normally report.

Seems like there is a similar rule for JSX: https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-tag-spacing.md

I think we should do the same :) I'll create a dedicated proposal in separate issue. I also think it can land in 4.1

**Comment by michalsnik** [comment]
Closing in favor of #229
