### ISSUE TITLE
Does not work with webpack import/resolver

### ISSUE THREAD

**Issue by maoberlehner** [vuejs/eslint-plugin-vue#201]
* **ESLint Version:** 4.8.0
* **eslint-plugin-vue Version:** 3.13.0
* **Node Version:** 8.1.4

```json
{
  "root": true,
  "parserOptions": {
    "parser": "babel-eslint",
    "sourceType": "module"
  },
  "env": {
    "browser": true,
    "node": true
  },
  "extends": [
    "airbnb-base",
    "plugin:vue/recommended"
  ],
  "rules": {
    "indent": [2, 4],
    "max-len": [2, 120],
    "import/extensions": [2, "always", {
      "js": "never",
      "vue": "never"
    }],
    "import/prefer-default-export": 0,
    "import/no-extraneous-dependencies": [0, { "devDependencies": true }],
    "vue/require-prop-types": 2,
    "vue/max-attributes-per-line": [2, {
      "singleline": 1,
      "multiline": {
        "max": 1,
        "allowFirstLine": false
      }
    }]
  },
  "plugins": [
    "html"
  ],
  "settings": {
    "import/resolver": {
      "webpack": {
        "config": "build/webpack.base.conf.js"
      }
    }
  }
}

```

**What did you expect to happen?**
Linting should fail because there are Vue and default eslint related issues in the code.

**What actually happened? Please include the actual, raw output from ESLint.**
Linting passes without throwing an error.

When I'm removing the settings section from the eslint config, the linter throws errors again, but some imports can't be resolved. I could write my imports differently, so that this works without the webpack resolver, but the default Vue.js CLI webpack template is also using those options https://github.com/vuejs-templates/webpack/blob/develop/template/.eslintrc.js#L25 so I wonder if this might be an issue with another part of my config?

**Comment by maoberlehner** [comment]
**Update: I'm now at home and tested this on a private project. It seems that that this plugin just doesn't work at all for me.**

```json
{
  "root": true,
  "parserOptions": {
    "parser": "babel-eslint"
  },
  "env": {
    "browser": true,
    "node": true
  },
  "extends": [
    "@avalanche/eslint-config",
    "plugin:vue/recommended"
  ],
  "rules": {
    "import/prefer-default-export": 0,
    "vue/require-prop-types": 2,
    "vue/max-attributes-per-line": [2, {
      "singleline": 1,
      "multiline": {
        "max": 1,
        "allowFirstLine": false
      }
    }]
  },
  "plugins": [
    "html"
  ]
}
```

Steps to reproduce:
- Add (normal) linting error to file
- Run eslint (`eslint --ext .js,.vue --ignore-path .gitignore .`) -> linter exists with error
- add `"plugin:vue/recommended"`
- Run eslint -> linter exists without an error

You can see the full code in this repository https://github.com/maoberlehner/well-composed-frontend (although without the linting config you can see above, because I just test this local without commiting for obvious reasons)

**Comment by lbogdan** [comment]
@maoberlehner You have to remove the `html` plugin.

From [here](https://github.com/BenoitZugmeyer/eslint-plugin-html), bottom of the page:

> **Linting VUE files**
> Initially, `eslint-plugin-vue` was using `eslint-plugin-html` to lint code inside script tags. Since v3, `eslint-plugin-vue` is using its own parser, so it is incompatible with `eslint-plugin-html`. You should remove `eslint-plugin-html` from your dependencies if you still have this.

**Comment by michalsnik** [comment]
Hey @maoberlehner, thanks for posting this issue. However @lbogdan is right, and you should remove `eslint-plugin-html` - then everything should work as expected. Please let us know if it worked for you :)

**Comment by maoberlehner** [comment]
Thank you @lbogdan and @michalsnik for your answers – I will check this out during the day, but I guess this will be the solution to my problem.

What would you guys think of mentioning this incompatibility in the FAQ section? The default vue-cli templates do install eslint-html and I think this might help some others as well. If you don't mind I'd open a pull request the following days?

**Comment by michalsnik** [comment]
The template will most likely be updated and use eslint-plugin-vue once we
release v4 so there will be no problem then :) we’re still in beta phase :)

**Comment by maoberlehner** [comment]
I've got everything up and running after removing the html plugin. Thank you both for helping me out!
