### ISSUE TITLE
Rule Proposal: `vue/max-lines-per-tag`

### ISSUE THREAD

**Issue by avrelaun** [vuejs/eslint-plugin-vue#202]
**Please describe what the rule should do:**

This rule warns about the maximum lines permitted of the script, template & style tags.

**What category of rule is this? (place an "X" next to just one item)**

`[x]` Enforces code style
`[ ]` Warns about a potential error
`[ ]` Suggests an alternate way of doing something
`[ ]` Other (please specify:)

**Provide 2-3 code examples that this rule will warn about:**

vue/max-lines-per-tag: [ "warning", { "script": 100, "template": 80, "style": 120 } ];

It's pretty straightforward in terms of examples.

**Comment by avrelaun** [comment]
The use case in my team:
We have a 300 max lines rule for all files, but vue files tend to get larger and split components isn't always the way to go.
Limiting the number of js lines is a requirement, template too, but styling not as much, and some components are using a lot of css lines while others don't, making it harder for us to set a global value for the whole files.

**Comment by michalsnik** [comment]
I think it could be a quite useful rule. Though it might need a little bit extra work on vue-eslint-parser level to check number of lines in `style` tag.

**Comment by michalsnik** [comment]
I initially marked it as `accepted proposition`, but now after quite a while I see there was no particular interest in this rule in the community, so I'm going to close this proposal.
