### ISSUE TITLE
vue/multi-word-component-names

### ISSUE THREAD

**Issue by ang-e-l** [vuejs/eslint-plugin-vue#2030]
**What rule do you want to change?** vue/multi-word-component-names

**Does this change cause the rule to produce more or fewer warnings?** Fewer

**How will the change be implemented? (New option, new default behavior, etc.)?** add new option to disable the rule for components in a path, many paths may be provided in an array

**Please provide some example code that this change will affect:**

Actually rather than a code example, I'm using a plugin to make my vue-router routes based on the structure of the directory src/pages, I'd like to have an option to provide a path in which this rule won't be applied, because my Pages have names like "[id].vue", "Index.vue", "Delete.vue", etc.

**What does the rule currently do for this code?**
It stops me from using single named components for my pages, since the route generated depends on the name of the component
 I can't have URL segments with single words.

**What will the rule do after it's changed?**
Allow me to have paths where this rule is not used.

**Additional context**
N/A

**Comment by ota-meshi** [comment]
Thank you for posting issue.

However, you can already configure rules per path using glob. See the eslint documentation.

https://eslint.org/docs/latest/user-guide/configuring/configuration-files#configuration-based-on-glob-patterns
