### ISSUE TITLE
Add vue-typed-mixins support

### ISSUE THREAD

**Issue by Vsnegovik** [vuejs/eslint-plugin-vue#2038]
Will be nice to add support for https://github.com/ktsn/vue-typed-mixins

My project has using vue-typed-mixins library for vuejs 2.xx
I want to native support of linter instead this `// @vue/component`

**Comment by ota-meshi** [comment]
Adding support for vue-typed-mixins is a breaking change, and I think it's not common and will only increase false positives, so I don't want to add support for vue-typed-mixins with breaking changes.
You can still use `// @vue/component` comments. Thank you for your understanding.

**Comment by sybers** [comment]
Hey I'm having the same issue, I don't see how we can make `vue-typed-mixins` and `eslint-plugin-vue` work together.
Would you consider implementing this in the future ?

Does it have to be a breaking change necessarily, or can it just be an incremental change released as a minor version ?

Thanks!
