### ISSUE TITLE
vue/no-lifecycle-after-await: dosen't work with unplugin-auto-import

### ISSUE THREAD

**Issue by basil-gor** [vuejs/eslint-plugin-vue#2050]
**Checklist**

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have read the [FAQ](https://eslint.vuejs.org/user-guide/#faq) and my problem is not listed.

**Tell us about your environment**

- **ESLint version:** ^8.28.0
- **eslint-plugin-vue version:** ^9.8.0
- **Node version:** 16.13.1
- **Operating System:** macOS 13.0.1

**Please show your full configuration:**

```json5
/* eslint-env node */
require('@rushstack/eslint-patch/modern-module-resolution')

module.exports = {
  root: true,
  'extends': [
    'plugin:vue/vue3-essential',
    'eslint:recommended',
    '@vue/eslint-config-typescript',
    './.eslintrc-auto-import.json',
  ],
  parserOptions: {
    ecmaVersion: 'latest'
  },
  rules: {
    "vue/no-unused-properties": ["error", {
      "groups": ["props", "setup"]
    }]
  }
}
```

**What did you do?**	

```vue
<script lang="ts">
// import { onMounted } from 'vue';

const asyncFunction = async () => {
  // some async logic
}

export default defineComponent({
  async setup() {

    await asyncFunction();

    onMounted(() => {
      // some hook logic
    });
  }
})
</script>
```

**What did you expect to happen?**

In normal case, if I import hook in setup, I get eslint error.
![image](https://user-images.githubusercontent.com/22558332/205061121-5b02a5ef-494c-46b9-8a0e-f7f7f595ea96.png)

**What actually happened?**

If I import hook using `unplugin-auto-import`, I don't get an eslint error.
![image](https://user-images.githubusercontent.com/22558332/205061310-af9ac846-4db4-40c4-a376-0894ac799f4c.png)
And in browser console I get

> [Vue warn]: onMounted is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup(). If you are using async setup(), make sure to register lifecycle hooks before the first await statement. 
> at `<App>`

**Repository to reproduce this issue**
https://github.com/basil-gor/eslint-vue-lifecycle-after-await-example

**Comment by ota-meshi** [comment]
Thank you for posting the issue.
This plugin has no way of determining if the user is autoimporting `onMounted`.
So not checking unknown `onMounted` is the intentional behavior of this rule.
Either you turn off the rule or import `onMounted` explicitly.
