### ISSUE TITLE
Consider adding a policy about not supporting Nuxt. (In conclusion, we will continue to support Nuxt.)

### ISSUE THREAD

**Issue by ota-meshi** [vuejs/eslint-plugin-vue#2058]
I think we have been trying to support Nuxt as much as possible, but nuxt3 adds many unique features, so it seems that it is almost incompatible with eslint-plugin-vue.
Nuxt support should be left to eslint-plugin-nuxt and eslint-plugin-vue should consider whether it should focus on supporting vue core features.
https://github.com/nuxt/eslint-plugin-nuxt

**Comment by ota-meshi** [comment]
@FloEdelmann I would love to hear your opinion. Could you please comment when you have time?

**Comment by danielroe** [comment]
I will be watching with interest. I am very happy to support (e.g. maintain/contribute as you would value) this plugin from the Nuxt side if you would like to consolidate effort, where possible.

**Comment by ota-meshi** [comment]
Thank you for your comment. Whether this plugin supports Nuxt or leaves it to eslint-plugin-nuxt, we need help from the Nuxt team :smiley: 
I don't use Nuxt, but @FloEdelmann has already done a lot of work to make this plugin support Nuxt's features. 
I'm worried that if we continue to support Nuxt with only the current maintainers, we'll be asking Flo to do a lot of work again.

**Comment by ota-meshi** [comment]
Currently the relevant issues are #2057 and #1969.

**Comment by ota-meshi** [comment]
Yeah, but supporting it in the same way as defineComponent is a breaking change. I'm not sure if the major version of this plugin should be bumped for Nuxt at the moment.

**Comment by ota-meshi** [comment]
My current idea for defineNuxtComponent is to provide a way to specify the Vue options object from eslint-plugin-vue in settings etc. and use it from eslint-plugin-nuxt to extend it for Nuxt.
This does not require breaking changes for eslint-plugin-vue. Therefore, I think it is the fastest way for Nuxt users to be able to use ESLint without problems.
But doing this means that eslint-plugin-vue will stop supporting Nuxt and leave it to eslint-plugin-nuxt.
We need to consult with the eslint-plugin-nuxt maintainers about extension points like I mentioned earlier. This requires help from the Nuxt team.

**Comment by vedmant** [comment]
@ota-meshi 

> My current idea for defineNuxtComponent is to provide a way to specify the Vue options object from eslint-plugin-vue in settings etc. and use it from eslint-plugin-nuxt to extend it for Nuxt.

That makes a lot of sense, and allow to use multiple options, to use `defineComponent` and `defineNuxtComponent` in the same time.

**Comment by FloEdelmann** [comment]
Why would treating `defineNuxtComponent` the same as `defineComponent` be a breaking change?

My opinion on the whole topic: I think we should try to support Nuxt features that are working similarly to Vue core features. IMO, that includes both #2057 and #1969.

We could introduce a per-rule or [shared settings](https://eslint.org/docs/latest/user-guide/configuring/configuration-files#adding-shared-settings) that should be considered "Vue". E.g.:

```json5
{
    "settings": {
        "vuePackageNames": ["vue", "@vue/composition-api", "#imports"]
    }
}
```

So importing `ref` from one of those packages would be tracked, importing `ref` from some other package would not. The default settings could either include or exclude Nuxt packages. And we could allow a special value (e.g. `*`) to track all `ref`s, regardless from where they were imported, to support auto-imports.

**Comment by FloEdelmann** [comment]
Maybe we should clarify in the docs that a new minor (or even patch) version of eslint-plugin-vue could result in more reported lint issues. And that this is the case especially for users of Nuxt and other third-party frameworks built on top of Vue.

**Comment by vedmant** [comment]
All my Vue projects are actually based on Nuxt, and not supporting Nuxt for me will make this plugin basically pointless.
