### ISSUE TITLE
Rules/presets to enforce styles recommended by the official style guide

### ISSUE THREAD

**Issue by kaicataldo** [vuejs/eslint-plugin-vue#206]
Hi! I deleted the template because it didn't seem relevant to this issue - hope that's okay!

I was curious if the team would be amenable to creating rules/presets for the groups of rules recommended by the official style guide.

This would obviously need to be fleshed out, but I think it would be great for someone new to Vue to be able to just extend off of something like `plugin:vue/essential`, which would enforce [the essential rules recommended by the styleguide](https://vuejs.org/v2/style-guide/#Priority-A-Rules-Essential-Error-Prevention).

Would love to hear what others think!

**Comment by michalsnik** [comment]
Hey @kaicataldo, thanks for posting this issue. However we're already in the middle of the integration with official style guide. Please take a look at #77 :)

**Comment by matt-oconnell** [comment]
@michalsnik Does this mean development is underway for this or is there still room for discussion?

**Comment by kaicataldo** [comment]
Ah, missed that one! Thanks, will take the discussion over there. Apologies for the noise.
