### ISSUE TITLE
Enable the autofix of `vue/v-on-event-hyphenation` in `vue/vue3-recommended`

### ISSUE THREAD

**Issue by saschanaz** [vuejs/eslint-plugin-vue#2065]
**Checklist**

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have read the [FAQ](https://eslint.vuejs.org/user-guide/#faq) and my problem is not listed.

**Tell us about your environment**

- **ESLint version:** 8.30.0
- **eslint-plugin-vue version:** 9.8.0
- **Node version:** 19.2.0
- **Operating System:** Windows 11

**Please show your full configuration:**

```json5

module.exports = {
	root: true,
	env: {
		'node': false,
	},
	parser: 'vue-eslint-parser',
	parserOptions: {
		'parser': '@typescript-eslint/parser',
		tsconfigRootDir: __dirname,
		project: ['./tsconfig.json'],
		extraFileExtensions: ['.vue'],
	},
	extends: [
		'../shared/.eslintrc.js',
		'plugin:vue/vue3-recommended',
	],
	rules: {
		'@typescript-eslint/no-empty-interface': [
			'error',
			{
				'allowSingleExtends': true,
			},
		],
		'@typescript-eslint/prefer-nullish-coalescing': [
			'error',
		],
		// window の禁止理由: グローバルスコープと衝突し、予期せぬ結果を招くため
		// e の禁止理由: error や event など、複数のキーワードの頭文字であり分かりにくいため
		'id-denylist': ['error', 'window', 'e'],
		'no-shadow': ['warn'],
		'vue/attributes-order': ['error', {
			'alphabetical': false,
		}],
		'vue/no-use-v-if-with-v-for': ['error', {
			'allowUsingIterationVar': false,
		}],
		'vue/no-ref-as-operand': 'error',
		'vue/no-multi-spaces': ['error', {
			'ignoreProperties': false,
		}],
		'vue/no-v-html': 'warn',
		'vue/order-in-components': 'error',
		'vue/html-indent': ['warn', 'tab', {
			'attribute': 1,
			'baseIndent': 0,
			'closeBracket': 0,
			'alignAttributesVertically': true,
			'ignores': [],
		}],
		'vue/html-closing-bracket-spacing': ['warn', {
			'startTag': 'never',
			'endTag': 'never',
			'selfClosingTag': 'never',
		}],
		'vue/multi-word-component-names': 'warn',
		'vue/require-v-for-key': 'warn',
		'vue/no-unused-components': 'warn',
		'vue/valid-v-for': 'warn',
		'vue/return-in-computed-property': 'warn',
		'vue/no-setup-props-destructure': 'warn',
		'vue/max-attributes-per-line': 'off',
		'vue/html-self-closing': 'off',
		'vue/singleline-html-element-content-newline': 'off',
	},
	globals: {
		// Node.js
		'module': false,
		'require': false,
		'__dirname': false,

		// Vue
		'$$': false,
		'$ref': false,
		'$shallowRef': false,
		'$computed': false,

		// Misskey
		'_DEV_': false,
		'_LANGS_': false,
		'_VERSION_': false,
		'_ENV_': false,
		'_PERF_PREFIX_': false,
		'_DATA_TRANSFER_DRIVE_FILE_': false,
		'_DATA_TRANSFER_DRIVE_FOLDER_': false,
		'_DATA_TRANSFER_DECK_COLUMN_': false,
	},
};
```

**What did you do?**	

```vue
<FormSwitch v-model="$i.injectFeaturedNote" class="_formBlock" @update:model-value="onChangeInjectFeaturedNote">
```

**What did you expect to happen?**

An autofixable warning

**What actually happened?**

Non-autofixable warning

**Repository to reproduce this issue**

https://github.com/misskey-dev/misskey/tree/f1fd1d2585bd5230caea4c7b8814c2cf007e57cc

Docs imply the autofix is disabled by default for Vue 2 compatibility, but `vue/vue3-recommended` has no reason to keep it disabled as it's for Vue 3. 

https://github.com/vuejs/eslint-plugin-vue/blob/master/lib/configs/vue3-strongly-recommended.js is autogenerated with no options, it should somehow pass an option.

**Comment by FloEdelmann** [comment]
> https://github.com/vuejs/eslint-plugin-vue/blob/master/lib/configs/vue3-strongly-recommended.js is autogenerated with no options, it should somehow pass an option.

That's the difficult part. If we can find a clean solution to specify default options to be used in the configs, then this is fine. Otherwise, I prefer not having the rule autofixable.

**Comment by tanhh326** [comment]
https://eslint.vuejs.org/rules/v-on-event-hyphenation.html

I also want this feature, but I can look at the case on the official website, how to do it

**Comment by FloEdelmann** [comment]
I just noticed that we already have default options for specific Vue versions, see

https://github.com/vuejs/eslint-plugin-vue/blob/b3129f9f3551f1ac189a0ee84b43561b3d0e4cc2/lib/rules/no-reserved-props.js#L26-L28
