### ISSUE TITLE
Is any way to add to max-statements exclude setup in composition api?

### ISSUE THREAD

**Issue by sinneren** [vuejs/eslint-plugin-vue#2074]
"setup" is not in top level with composition-api. And rule of max statements so frustrating. 
Maybe create new ignore extend for rule "max-statements" like "ignoreTopLevelFunctions"?

**Comment by FloEdelmann** [comment]
Please add code examples to clarify your request.

**Comment by sinneren** [comment]
Code examples of what? setup in composition api? 

Abstraction example:

**Rule**
`'max-statements': ["warn", 1, { "ignoreTopLevelFunctions": true }],`

**Code:**
```
import {
  defineComponent,
  useFetch,
  useContext,
  ref,
} from '@nuxtjs/composition-api'

export default defineComponent({
  setup() {
    const posts = ref(null)
    const errors = ref('')

    const { $http } = useContext()
    
    useFetch(async () => {
      posts.value = await $http
        .$get('https://jsonplaceholder.typicode.com/posts')
        .then(posts => posts.slice(0, 20))
        .catch(err => errors.value = err)
    })

    return { posts }
  },
})
```
