### ISSUE TITLE
Cannot check for syntax errors when there are two script tags

### ISSUE THREAD

**Issue by LittleSource** [vuejs/eslint-plugin-vue#2088]
**Checklist**

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have read the [FAQ](https://eslint.vuejs.org/user-guide/#faq) and my problem is not listed.

**Tell us about your environment**

- **ESLint version:^7.32.0 || ^8.2.0** 
- **eslint-plugin-vue version:^9.9.0** 
- **Node version:v16.18.0** 
- **Operating System:mac os** 

**Please show your full configuration:**

```json5
"eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/essential",
      "eslint:recommended"
    ],
    "parserOptions": {
      "parser": "@babel/eslint-parser"
    },
    "rules": {}
  }

```

**What did you do?**	

```vue
<script>
export default {
  data() {
    return {
      a: 1,
      b: 2,
    }
  },
}
</script>

<script module="voice" lang="renderjs">
export default {
  data() {
      ddd
  },
}
</script>
```

**What did you expect to happen?**
Obviously, when I use uniapp's renderjs, I will write two scripts in one vue file, but eslint's syntax check will only take effect in the first script. In the second script, I write ddd in data without any error

**What actually happened?**
no error

**Repository to reproduce this issue**
https://github.com/LittleSource/eslint-test.git

**Comment by ota-meshi** [comment]
Thank you for posting issue.

I think your `.vue` file is not a valid `*.vue` file. So I think the parser is parsing it correctly.

https://sfc.vuejs.org/#eNqFUstu2zAQ/JUFc2kBPdIU7YFVC/jWL+hJl7W0YujyBXKl2A38713JdhAgCHLizHCHuzvgs9ql1CwzKa06Jp8cMv3qA0A32gXs+LNXmFKvNk1U6w2gY5H/zAQumtgrKHkQoWmxFOLSrmqTgrm6ulaeEtS1rxoILUO2iQXTMcXMMNKEs2N4Xk0jMn76fMEAmXjO4cYAUMOX6kb2Gh6u5LweZyECuvalwUsz8HGcHcmwS7QDyegOgxGaKYyUD2Ub+eN5hI/j+7345NYd7yS5i2OKgesJvXUnDbuFgs0V/Ca3ENsBK9hli66CgqHUhbKdfqyu+on2f60YV3fxMfKjDUYDBpZyi4XGS52P/+pYjm8KTcZTGdDRVsZ05Fp8JmgYKDDlTR6ii1nD3cPwlb7db5LHbGyoOSYN3+/TUcTLkttiqlLWrwnVHlNzKDHI59nW7K8XEqO+RSVRzxK0FvDInIpu2zIN65c7lCZm0wpq8iwreWqo+Hqf45NkIA/3aotYmqvzf4xR5ig=

**Comment by ota-meshi** [comment]
What is uniapp? Is it the framework you use?
I think you should ask the uniapp development team to create another eslint-plugin.

**Comment by LittleSource** [comment]
Yes,.my vue file is not a valid *.vue,Because he has two <script> tags，What I want to know is how to get eslint to parse correctly in a .vue file that has two <script> tags

**Comment by ota-meshi** [comment]
There is no option for that.
