### ISSUE TITLE
v-slot default shorthand valid error

### ISSUE THREAD

**Issue by winixt** [vuejs/eslint-plugin-vue#2091]
**Checklist**

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have read the [FAQ](https://eslint.vuejs.org/user-guide/#faq) and my problem is not listed.

**Tell us about your environment**

- **ESLint version:**  8.33.0
- **eslint-plugin-vue version:**  9.9.0
- **Node version:**  19.2.0
- **Operating System:**  Mac OS 13.2.1

**Please show your full configuration:**

```js
module.exports = {
    overrides: [
        {
            files: ['*.vue'],
            parser: 'vue-eslint-parser',
            parserOptions: {
                parser: '@typescript-eslint/parser',
            },
            rules: {
                'no-unused-vars': 'off',
                'no-undef': 'off',
                '@typescript-eslint/no-unused-vars': 'off',
            },
        },
    ],
    extends: [
        'plugin:vue/vue3-recommended',
        '@antfu/eslint-config-ts',
    ],
    rules: {
        'vue/max-attributes-per-line': 'off',
        'vue/no-v-html': 'off',
        'vue/require-prop-types': 'off',
        'vue/require-default-prop': 'off',
        'vue/multi-word-component-names': 'off',
        'vue/prefer-import-from-vue': 'off',

        // reactivity transform
        'vue/no-setup-props-destructure': 'off',

        'vue/component-tags-order': ['error', {
            order: ['script', 'template', 'style'],
        }],
        'vue/block-tag-newline': ['error', {
            singleline: 'always',
            multiline: 'always',
        }],
        'vue/component-name-in-template-casing': ['error', 'PascalCase'],
        'vue/component-options-name-casing': ['error', 'PascalCase'],
        'vue/custom-event-name-casing': ['error', 'camelCase'],
        'vue/define-macros-order': ['error', {
            order: ['defineProps', 'defineEmits'],
        }],
        'vue/html-comment-content-spacing': ['error', 'always', {
            exceptions: ['-'],
        }],
        'vue/no-restricted-v-bind': ['error', '/^v-/'],
        'vue/no-useless-v-bind': 'error',
        'vue/no-v-text-v-html-on-component': 'error',
        'vue/padding-line-between-blocks': ['error', 'always'],
        'vue/prefer-separate-static-class': 'error',

        // extensions
        'vue/array-bracket-spacing': ['error', 'never'],
        'vue/arrow-spacing': ['error', { before: true, after: true }],
        'vue/block-spacing': ['error', 'always'],
        'vue/brace-style': ['error', 'stroustrup', { allowSingleLine: true }],
        'vue/comma-dangle': ['error', 'always-multiline'],
        'vue/comma-spacing': ['error', { before: false, after: true }],
        'vue/comma-style': ['error', 'last'],
        'vue/dot-location': ['error', 'property'],
        'vue/dot-notation': ['error', { allowKeywords: true }],
        'vue/eqeqeq': ['error', 'smart'],
        // 'vue/func-call-spacing': ['off', 'never'],
        'vue/key-spacing': ['error', { beforeColon: false, afterColon: true }],
        'vue/keyword-spacing': ['error', { before: true, after: true }],
        'vue/no-constant-condition': 'warn',
        'vue/no-empty-pattern': 'error',
        'vue/no-extra-parens': ['error', 'functions'],
        'vue/no-irregular-whitespace': 'error',
        'vue/no-loss-of-precision': 'error',
        'vue/no-restricted-syntax': [
            'error',
            'DebuggerStatement',
            'LabeledStatement',
            'WithStatement',
        ],
        'vue/no-sparse-arrays': 'error',
        'vue/object-curly-newline': ['error', { multiline: true, consistent: true }],
        'vue/object-curly-spacing': ['error', 'always'],
        'vue/object-property-newline': ['error', { allowMultiplePropertiesPerLine: true }],
        'vue/object-shorthand': [
            'error',
            'always',
            {
                ignoreConstructors: false,
                avoidQuotes: true,
            },
        ],
        'vue/operator-linebreak': ['error', 'before'],
        'vue/prefer-template': 'error',
        'vue/quote-props': ['error', 'consistent-as-needed'],
        'vue/space-in-parens': ['error', 'never'],
        'vue/space-infix-ops': 'error',
        'vue/space-unary-ops': ['error', { words: true, nonwords: false }],
        'vue/template-curly-spacing': 'error',
    },
};

```

**What did you do?**	

```vue
<template>
    <FDraggable>
        <template #="{ item, index }">
            <div class="sort-item">
                {{ item }}
            </div>
        </template>
    </FDraggable>
</template>
```

**What did you expect to happen?**

The `v-slot` dedicated shorthand `#` can be parsed correctly.

**What actually happened?**

![image](https://user-images.githubusercontent.com/20717402/220099298-7ace2528-479c-4252-b21d-02f1e6e68683.png)

**Repository to reproduce this issue**

[eslint probleam](https://github.com/winixt/eslint-problem)

**Comment by FloEdelmann** [comment]
Is there documentation that `#="{…}"` is a valid shorthand? I only know `#default="{…}"`, which is also supported by eslint-plugin-vue.

**Comment by winixt** [comment]
sure, like this

**Comment by winixt** [comment]
sure, like this

https://sfc.vuejs.org/#eNqFU01v2zAM/SuciyEpENtp2m6dlwbYYdulGAa0GDDUPSg27aqRJUGSs2WZ//soO06cfXSXICT9nsjHx23wTutoXWOQBHObGa4dWHS1XqSSV1oZBx+YzDY33DoojKpgFMX7jAeOUjmPOyRhKHBYacEcUgQwP6ATpnlYG3GdBvSbBpBoNKFmJVLmbJoGLYAgPQGcUGELS5VvJlBbNJJVOAHBV2ih2X9PiJyvIRPMWgJwgg9qVNWLbccCTTOP/WSH0h5WoWMEW26APu4fIwD89Indm033Z0gyj+nxvvP4ePaDUBQfFSm0biMQbKY05pSJfAOw9bhCSRda/gMTmEZXWL31yUwJZRI4uZgtr67OKdW0unuSRTAJul2FFdPRk1WSttlSkRxtwaZB0pH7HG3Nx2nw6Jy2SRzbIvOrfLKRMmVM/yJTS8crjNBW4dKobyQIEafBZMARU3JNKzQoczRonuP87dM/eD0tTdTQKEfu+rctt2CwgGZnys6IqcyUJKtpo7SFa8ix4BI/+2h8P9r5bzSBUe+80cPpAeWd41HEO77vCnEMlcpWlKoUGTJntKMCXfbIZZlK6uiORFK1G49P4XrRKdzSRGsmaiSy+06wzoAJjG7bhcOtUM7Cx5rnSP30fqP6+zWT8FXVlG29lsBsCg3JnroByxfivqudMpz5eQb4T9Si4AzuUIua2mQHojMi8t08kM4TiqZTmvG5261Fb2zBYR3ygu7kRTeeQFm6x8Gd3SiWkyhRFPW3IPgRulBmd53AZSfS8IQtCUJfLbnM90cc7+9qxzWP25b+c0oAtejNLshHYVsP3UaTQFJJbA8KQLPct5zApf6+Sy1ZtiqNqmWeEFQiM2FpaDCUbnx+dpljOfEnmJ+/mcHs8iUFry5eY1GctvhWXRp29/aQn7a4f6RipuTS7+Ov754URdHT7S+8+QU7+9v2

@FloEdelmann

**Comment by ota-meshi** [comment]
The RFC says that syntax is not allowed. If you know when it changed, please share that information with us.

https://github.com/vuejs/rfcs/blob/master/active-rfcs/0002-slot-syntax-shorthand.md#:~:text=be%20simplified%20to-,%23%3D,-.%20For%20default

**Comment by FloEdelmann** [comment]
Let's close this then. Please comment or open a new issue once there is new information.

**Comment by jacekkarczmarczyk** [comment]
Not only `#` alone works, but also `:` and `@`

https://sfc.vuejs.org/#eNp9UctOwzAQ/JWVL26lNr5HoYILJw7cMYc03YBL/dDaCUJR/p11QqEpCJ9mx56xZnYQdyEUfYeiFFVsyIQEEVMXdtoZGzwluK9d8/FgYoKWvAVZqG8mC6V2beeaZLyD5mSaN1itYYD6hKxlOGpXqdmZPXlIaMOpTsgTQPXjnkc+5Y0WA7TelyAN1DZDuYF9TWeCoWRbcVbcTor5b6Yzq9i8Uhc/iY2Y42xtHYpj9I4DD/mp/rqIWpQwMZnjYHnW4jWlEEulYtvktMdYeHpRjArqXDIWC4x2uyf/HpHYWIvNhYdiskfaEroDEtJ/nldPf/lmWy5z5CiLBfyxuQO2xuEj+RBXT3IuUObanteLbVzt4mD63TB1D+MIjFjCqFL5YlGoGD8BC0fA+Q==

But I don't know whether it wasn't possible at the time of writing this RFC or it was changed later or it's just unintended feature

**Comment by FloEdelmann** [comment]
Hmm, I'd say if it is not documented, we should not support it yet. On the [Vue.js directives documentation page](https://vuejs.org/api/built-in-directives.html#v-on), the shorthands `@`, `:` and `#` are mentioned, but they could refer to the usage of those characters with a name. None of the examples uses them alone.

I think the best way would be to open an issue or pull request in the docs repository:
https://github.com/vuejs/docs/blob/main/src/api/built-in-directives.md

Once it is documented (or rejected), please comment the result here.

**Comment by ota-meshi** [comment]
Related to https://github.com/vuejs/docs/pull/2294
