### ISSUE TITLE
Auto move attribute in same/previous line if there's just single attribute with `vue/max-attributes-per-line`

### ISSUE THREAD

**Issue by jd-solanki** [vuejs/eslint-plugin-vue#2099]
**What rule do you want to change?**
When you have `vue/max-attributes-per-line` configured it's nice to have all attributes on different line for git diff and readability. However, if we have just one attribute then it's not acceptable.

In team, we write markup like below:
```html
<ABtn
  color="success"
  v-text="Button"
/>
```

Then one of the team member removes the `color="success"` and we have:
```html
<ABtn
  v-text="Button"
/>
```

Now there's no way to configure `vue/max-attributes-per-line` to move that single attribute on previous line so that it became like `<ABtn v-text="Button" />`.

**Does this change cause the rule to produce more or fewer warnings?**
N/A (I guess it doesn't have to do anything with warnings.)

**How will the change be implemented? (New option, new default behavior, etc.)?**
Maybe new option like:
```diff
 {
   "vue/max-attributes-per-line": ["error", {
     "singleline": {
       "max": 1
     },      
     "multiline": {
       "max": 1
+      "min": 2
     }
   }]
 }
```

Or else we can auto detect `min` value based on `max` to avoid things like: max: 1, min: 5 😜

**Please provide some example code that this change will affect:**

```html
<ABtn
  v-text="Button"
/>
```

**What does the rule currently do for this code?**
Nothing

**What will the rule do after it's changed?**
Move the attribute to previous line.

```html
<ABtn v-text="Button" />
```

**Additional context**
N/A

**Comment by vedmant** [comment]
That is the problem I also struggle, would be nice to see any solution here.

**Comment by ota-meshi** [comment]
Thank you for posting issue.

However I think you can achieve what you want by using the first-attribute-linebreak rule.

https://eslint.vuejs.org/rules/first-attribute-linebreak.html

Could you try using the `"singleline": "beside"` option?

**Comment by jd-solanki** [comment]
> _Could you try using the "singleline": "beside" option?_

Sure! Will let you know on Monday.

Thanks for your response 😇

**Comment by jd-solanki** [comment]
Hi @ota-meshi It does the job. Thanks for sharing.

Additionally out of context, I suggest we should make `"singleline": "beside"` default instead of `ignore`, What's your thought on this? Because, no one want new line for just single line 💯

**Comment by ota-meshi** [comment]
I'm not going to change the default.  It's a breaking change and users complain all the time.

**Comment by vedmant** [comment]
@ota-meshi `Could you try using the "singleline": "beside" option?` - this works only for 1 attribute, but doesn't work when I want 2 or 3 attributes force into single line. For example my config is `'vue/max-attributes-per-line': ['error', { singleline: { max: 3 }, multiline: { max: 1 } }],` this only turn into multiple lines.

So I still could not find any way to force turn:

```
           <InputGroup
              label="Name"
              type="text"
              placeholder="not specified"
            />
```

into

```
<InputGroup label="Name" type="text" placeholder="not specified" />
```
