### ISSUE TITLE
[Bug] `vue/no-export-in-script-setup` not working for TypeScript type exporting

### ISSUE THREAD

**Issue by wenfangdu** [vuejs/eslint-plugin-vue#2107]
![image](https://user-images.githubusercontent.com/28700378/226286783-e205b2b9-2d8c-4d7b-9ce6-b52f13eaa8ec.png)

[Repro Link](https://github.com/wenfangdu/vite-vue-3/tree/vue/no-export-in-script-setup)

**Comment by ota-meshi** [comment]
I'm not sure what you think is the bug.
Please post an issue according to the template.
Also, please paste the entire source code, not just an image.

**Comment by wenfangdu** [comment]
@ota-meshi

> I'm not sure what you think is the bug.
`export const a = 1` throws, and `export type A = string` doesn't.

> Please post an issue according to the template.
I've attached the repro link, there's really no need to go through that.

> Also, please paste the entire source code, not just an image.
There's a repro link after the image.
