### ISSUE TITLE
Support for `defineOptions`

### ISSUE THREAD

**Issue by ota-meshi** [vuejs/eslint-plugin-vue#2118]
**Tell us about your environment**

- **ESLint version:**  v8.36.0
- **eslint-plugin-vue version:** v9.10.0
- **Node version:** v18.12.1

**The problem you want to solve.**

Support for `defineOptions` macro.

See https://github.com/vuejs/core/blob/main/CHANGELOG.md#330-alpha6-2023-03-30

**Your take on the correct solution to problem.**

Parser and some rules are affected. However, we have not yet listed the affected rules.
I think that, first, we need to list the rules affected by defineOptions.

**Additional context**

Related to https://github.com/vuejs/vue-eslint-parser/issues/183

**Comment by jods4** [comment]
One affected rule is `vue/multi-word-component-names`. 
With `defineOptions({ name: 'UiForm' })` in a component `form.vue`, this rule should not trigger.

**Comment by ota-meshi** [comment]
I believe I've opened a PR to change the rules affected by the addition of defineOptions.
If you think there are other rules that have an affected, please comment.
