### ISSUE TITLE
vue/script-indent baseIndent default 0,It is suggested to change it to 1

### ISSUE THREAD

**Issue by wangxinxx** [vuejs/eslint-plugin-vue#2119]
**What rule do you want to change?**

**Does this change cause the rule to produce more or fewer warnings?**

**How will the change be implemented? (New option, new default behavior, etc.)?**

**Please provide some example code that this change will affect:**

```vue
<template>
  <div>xx</div>
</template>
<script lang="ts">
import xxx from 'abc';
const x = 0;
</script>
```

**What does the rule currently do for this code?**
In the default style, the code indentation template and script are different.
**What will the rule do after it's changed?**
```vue
<template>
  <div>xx</div>
</template>
<script lang="ts">
  import xxx from 'abc';
  const x = 0;
</script>
```

**Additional context**

**Comment by ota-meshi** [comment]
You are free to change your configuration.

**Comment by wangxinxx** [comment]
Yes. Because it is the default value, different IDEs treat it differently. Every project must set this value, so what is the value of the default value?
Isn't it a problem in itself to have two indentation styles for the same file?
In the way of <script lang="ts" setup>, a large number of lines are close to the left, which affects selection and reading in my opinion.
I wonder what is the advantage of setting it to 0 by default?

**Comment by FloEdelmann** [comment]
One less indentation level, and consistency with examples on https://vuejs.org, see e.g. https://vuejs.org/guide/scaling-up/sfc.html
