### ISSUE TITLE
Declaration for module

### ISSUE THREAD

**Issue by kovjogin** [vuejs/eslint-plugin-vue#2124]
I want to write my own rule specific to my project only. It should work vue script setup.
I write rules in typescript.

I need defineScriptSetupVisitor in my ts file.

```import { defineScriptSetupVisitor } from 'eslint-plugin-vue/lib/utils';```

or

```import utils from 'eslint-plugin-vue/lib/utils';```

I got message:

"TS7016: Could not find a declaration file for module 'eslint-plugin-vue/lib/utils'. 'eslint-plugin-vue/lib/utils/index.js' implicitly has an 'any' type.   Try `npm i --save-dev @types/eslint-plugin-vue` if it exists or add a new declaration (.d.ts) file containing `declare module 'eslint-plugin-vue/lib/utils';`"

Am I doing something wrong or is this package not usable with typescript?

**Comment by ota-meshi** [comment]
> this package not usable with typescript?

Yes.

**Comment by MartinX3** [comment]
@ota-meshi Did it change since we got `eslint.config.ts` with ESLint 9.9.0?

```
Vue: Could not find a declaration file for module eslint-plugin-vue.
path node_modules/.pnpm/ eslint-plugin-vue@9.27.0_eslint@9.9.0_jiti@1.21.6_/ node_modules/ eslint-plugin-vue/ lib/ index. js
implicitly has an any type.
Try npm i --save-dev @types/ eslint-plugin-vue if it exists or add a new declaration (.d. ts) file containing declare module 'eslint-plugin-vue';
```
