### ISSUE TITLE
Add support for Vue v3.3

### ISSUE THREAD

**Issue by ota-meshi** [vuejs/eslint-plugin-vue#2127]
This issue lists issues related to Vue 3.3.

- eslint-plugin-vue 
  - #2118
    - #2157
    - #2158
    - #2159
    - #2160
    - #2161
    - #2162
    - #2164
    - #2165
    - #2167
  - #2125
    - #2154
    - #2163
  - #2126
    - #2152
  - #2134
  - #2170
  - ~~#2130~~
  - ~~#2121~~
- vue-eslint-parser
  - vuejs/vue-eslint-parser#183
  - vuejs/vue-eslint-parser#184
    - vuejs/vue-eslint-parser#193
  - vuejs/vue-eslint-parser#182
  - ~~vuejs/vue-eslint-parser#186~~
    - vuejs/vue-eslint-parser#194

**Comment by ota-meshi** [comment]
https://blog.vuejs.org/posts/vue-3-3

**Comment by ota-meshi** [comment]
We have completed the intended task, so I will close this issue. @FloEdelmann Thanks for reviewing many PRs so quickly.

**Comment by FloEdelmann** [comment]
Thanks @ota-meshi for implementing the necessary changes!

For everyone following this issue: The changes are released now in https://github.com/vuejs/eslint-plugin-vue/releases/tag/v9.13.0. If you notice bugs or further improvements, please open new issues.
