### ISSUE TITLE
Support for `defineModel`

### ISSUE THREAD

**Issue by ota-meshi** [vuejs/eslint-plugin-vue#2130]
**Tell us about your environment**

- **ESLint version:**  v8.36.0
- **eslint-plugin-vue version:** v9.10.0
- **Node version:** v18.12.1

**The problem you want to solve.**

Add support for `defineModel` macro.

See https://github.com/vuejs/core/blob/main/CHANGELOG.md#330-alpha9-2023-04-08

**Your take on the correct solution to problem.**

Parser and some rules are affected. However, we have not yet listed the affected rules.
I think that, first, we need to list the rules affected by defineModel.

**Additional context**

Related to https://github.com/vuejs/vue-eslint-parser/issues/186

**Comment by ota-meshi** [comment]
Since it's still an experimental feature, eslint-plugin-vue won't support it yet until it's GA.

**Comment by JoseGoncalves** [comment]
> Since it's still an experimental feature, eslint-plugin-vue won't support it yet until it's GA.
> 
> https://blog.vuejs.org/posts/vue-3-3#experimental-features

It is now stable in Vue 3.4: https://blog.vuejs.org/posts/vue-3-4#definemodel-is-now-stable

**Comment by FloEdelmann** [comment]
Rules that need to be changed (feel free to edit and expand):

* `vue/no-unused-emit-declarations`
* `vue/compiler-macro-order`
