### ISSUE TITLE
[require-prop-comment] When I didn't use props, the rule took effect.

### ISSUE THREAD

**Issue by citrusjunoss** [vuejs/eslint-plugin-vue#2133]
**Checklist**

- [ ] I have tried restarting my IDE and the issue persists.
- [ ] I have read the [FAQ](https://eslint.vuejs.org/user-guide/#faq) and my problem is not listed.

**Tell us about your environment**

- **ESLint version:** 8.x
- **eslint-plugin-vue version:** 9.x 
- **Node version:** 16
- **Operating System:** macos12

**Please show your full configuration:**

```json5
    "require-prop-comment": [
      "error",
      {
        type: "JSDoc",
      },
    ],
```

**What did you do?**	

```vue
<script setup lang="ts">


</script>

```

**What did you expect to happen?**

**What actually happened?**

**Repository to reproduce this issue**

When I didn't use props, the rule took effect.
<img width="715" alt="image" src="https://user-images.githubusercontent.com/18432488/232645959-feb6034a-21c4-4ae8-b2b9-1a7d29222149.png">

**Comment by FloEdelmann** [comment]
You're missing the `vue/` prefix; the rule is called [`vue/require-prop-comment`](https://eslint.vuejs.org/rules/require-prop-comment.html).
