### ISSUE TITLE
Vue 3.3 update - Typings for new `defineEmits` syntax not working properly

### ISSUE THREAD

**Issue by Noxdor** [vuejs/eslint-plugin-vue#2176]
Before I start, I am not 100% sure if this is a problem with`eslint-plugin-vue` or `vue-eslint-parser`, since this is not really a problem with linting but with the types created by the new `defineEmits` syntax. I am guessing it is related to this repo, since I saw that here the changes for the new syntax were implemented.

**Checklist**

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have read the [FAQ](https://eslint.vuejs.org/user-guide/#faq) and my problem is not listed.

**Tell us about your environment**

- **ESLint version: v8.40.0** 
- **eslint-plugin-vue version: 9.13.0** 
- **Node version: v19.9.0** 
- **Operating System: Linux - 6.3.1-zen1-1-zen** 

**Please show your full configuration:**

From reproduction repo:
```json5
module.exports = {
  env: {
    browser: true,
    es2021: true,
  },
  extends: "plugin:vue/vue3-recommended",
  overrides: [],
  parser: "vue-eslint-parser",
  parserOptions: {
    parser: "@typescript-eslint/parser",
    ecmaVersion: "latest",
    sourceType: "module",
  },
  plugins: ["vue", "@typescript-eslint"],
  rules: {},
};
```

**What did you do?**	

Defining the emits with the new syntax doesn't type the emit arguments properly. If I do the following:
```typescript
// HelloWord.vue
const emit = defineEmits<{
  test: [name: string];
  // (e: "test2", name: string): void;
}>();
```
and then look at the typing of the`test` event in `App.vue`, I see:
![image](https://github.com/vuejs/eslint-plugin-vue/assets/64439978/21a4d2f5-df6f-4f42-ae27-5c00da2b31ec)

Now when I switch back to the old syntax like this:
```typescript
const emit = defineEmits<{
  // test: [name: string];
  (e: "test2", name: string): void;
}>();
```

I get the expected type definition looking at the event in `App.vue`:
![image](https://github.com/vuejs/eslint-plugin-vue/assets/64439978/c26931ed-2f8c-4e51-8761-e2c26ae98e09)

**What did you expect to happen?**

I expect the first version to show me the same typings for the event handler as the second (old syntax) version

**What actually happened?**

The output is improperly typed with an `any[]` for the payload/arguments of the event.

**Repository to reproduce this issue**

https://github.com/Noxdor/eslint-plugin-vue-bug

**Comment by ota-meshi** [comment]
The type definitions you see have nothing to do with eslint. Please open an issue in the appropriate repository for your editor.

**Comment by Noxdor** [comment]
Well that makes total sense, thank you. Thou I think this is not an issue of the editor but `volar` i.e. `vuejs/language-tools`. Gonna post the issue there.
