### ISSUE TITLE
npm run docs:watch not work

### ISSUE THREAD

**Issue by Terrency** [vuejs/eslint-plugin-vue#2184]
- **Node version:** 14.21.3
- **Operating System:** Win

I run npm run docs:watch after npm install,  vitepress run successful. browser console show:

eslint-plugin-vue/node_modules/@ota-meshi/site-kit-monaco-editor/lib/index.cjs?import&v=89571d5e' does not provide an export named 'loadMonacoEditor' (at MonacoEditor.vue:7:3)

is there any dependency not update?
i tried to update @ota-mesh/site-kit-monaco-editor to v0.1.1, but got same error.

**Comment by ota-meshi** [comment]
There was a bug in a dependency package. I fixed and released, please remove node_modules and install again.
