### ISSUE TITLE
vue/no-dupe-keys tips Duplicated key

### ISSUE THREAD

**Issue by laterdayi** [vuejs/eslint-plugin-vue#2192]
```

inteface PropsType {
loading :boolean
}

const {
  loading = false,
} = defineProps<PropsType>();
```

![图片](https://github.com/vuejs/eslint-plugin-vue/assets/122137647/46e040ec-e844-411e-8aa0-aa8cacadd53a)

**Comment by laterdayi** [comment]
In fact, loading is declared in interface

**Comment by FloEdelmann** [comment]
Already reported in https://github.com/vuejs/eslint-plugin-vue/issues/2096#issuecomment-1560430585 and being worked on in #2189.
