### ISSUE TITLE
[Bug] Can't use `@typescript-eslint/prefer-optional-chain`

### ISSUE THREAD

**Issue by wenfangdu** [vuejs/eslint-plugin-vue#2211]
https://github.com/wenfangdu/vite-vue-3/tree/conflict

`pnpm run lint`

Error log:
```
Oops! Something went wrong! :(

ESLint: 8.40.0

Error: Error while loading rule '@typescript-eslint/prefer-optional-chain': You have used a rule which requires parserServices to be generated. You must therefore provide a value for the "parserOptions.project" property for @typescript-eslint/parser.
```

But `@typescript-eslint/prefer-optional-chain` doesn't require type information: https://github.com/typescript-eslint/typescript-eslint/issues/4755#issuecomment-1080486616.

**Comment by FloEdelmann** [comment]
`typescript-eslint` rules are not provided by this project. Please open an issue in https://github.com/typescript-eslint/typescript-eslint instead.

**Comment by wenfangdu** [comment]
@FloEdelmann Sorry, I meant `@typescript-eslint/prefer-optional-chain` can't be used with [eslint-plugin-vue](https://github.com/vuejs/eslint-plugin-vue), please try https://github.com/wenfangdu/vite-vue-3/tree/conflict.

**Comment by FloEdelmann** [comment]
Please see https://eslint.vuejs.org/user-guide/#how-to-use-a-custom-parser for how to use `eslint-plugin-vue` with a different parser.

**Comment by wenfangdu** [comment]
@FloEdelmann Thanks, that's very helpful.
