### ISSUE TITLE
Rename `vue/component-tags-order` to `vue/block-order`

### ISSUE THREAD

**Issue by FloEdelmann** [vuejs/eslint-plugin-vue#2214]
We use the word "block" in rule names to refer to the top-level tags in Vue SFCs:

* [`vue/block-lang`](https://eslint.vuejs.org/rules/block-lang.html)
* [`vue/block-tag-newline`](https://eslint.vuejs.org/rules/block-tag-newline.html)
* [`vue/no-empty-component-block`](https://eslint.vuejs.org/rules/no-empty-component-block.html)
* [`vue/no-restricted-block`](https://eslint.vuejs.org/rules/no-restricted-block.html)
* [`vue/no-restricted-block`](https://eslint.vuejs.org/rules/padding-line-between-blocks.html)

However, the [`vue/component-tags-order`](https://eslint.vuejs.org/rules/component-tags-order.html) rule does not fit that schema. I suggest to rename the rule to `vue/block-order`:

1. In the next minor version, add `vue/block-order` as a copy of `vue/component-tags-order` and [deprecate](https://eslint.vuejs.org/rules/#deprecated) the latter.
2. In the next major version, remove `vue/component-tags-order` completely.

---

Are there other rules for which it would make sense to rename them for consistency and/or clarity?

**Comment by wenfangdu** [comment]
> Are there other rules for which it would make sense to rename them for consistency and/or clarity?

[`vue/padding-line-between-blocks`](https://eslint.vuejs.org/rules/padding-line-between-blocks.html) => `vue/newline-between-blocks`
[`vue/padding-line-between-tags`](https://eslint.vuejs.org/rules/padding-line-between-tags.html) => `vue/newline-between-tags`
[`vue/padding-lines-in-component-definition`](https://eslint.vuejs.org/rules/padding-lines-in-component-definition.html) => `vue/newlines-in-component-definition`

"newline" is more intuitive and easier to search on the rules page.

**Comment by FloEdelmann** [comment]
But it matches the core [`padding-line-between-statements`](https://eslint.org/docs/latest/rules/padding-line-between-statements) rule name, so I'd rather not change them.
