### ISSUE TITLE
[FR] `vue/attribute-hyphenation` and `vue/v-on-event-hyphenation` like rules for built-in elements

### ISSUE THREAD

**Issue by wenfangdu** [vuejs/eslint-plugin-vue#2216]
Currently, both `vue/attribute-hyphenation` and `vue/v-on-event-hyphenation` rules only work on custom components, are there similar rules that operate on built-in elements? If not, please consider this a feature request for adding such rules.

**Comment by FloEdelmann** [comment]
Native attributes and events are always a single word without the need for hyphenation. Also, please follow the feature request template and suggest some specific examples where these rules would report a lint issue.

**Comment by wenfangdu** [comment]
Closing in favor of https://github.com/vuejs/eslint-plugin-vue/issues/2218.
