### ISSUE TITLE
[Bug] `vue/no-console` affects code in `<script>`

### ISSUE THREAD

**Issue by wenfangdu** [vuejs/eslint-plugin-vue#2220]
`vue/no-console` is supposed to only check code in the `<template>`.

Repro: https://github.com/wenfangdu/vite-vue-3/tree/vue/no-console
![image](https://github.com/vuejs/eslint-plugin-vue/assets/28700378/8407355f-a515-42eb-b3f1-e960ba62b535)

**Comment by FloEdelmann** [comment]
Seems to have been overlooked in #2194. @ItMaga would you fancy to restrict the rule to the `<template>` block?

**Comment by ItMaga** [comment]
Yes, I'll fix that. Thank you!
