### ISSUE TITLE
After npm install, ESLint couldn't find the plugin "eslint-plugin-plugin:vue/vue3-recommended".

### ISSUE THREAD

**Issue by leegee** [vuejs/eslint-plugin-vue#2230]
**Checklist**

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have read the [FAQ](https://eslint.vuejs.org/user-guide/#faq) and my problem is not listed.

**Tell us about your environment**

- **ESLint version:** 8.44
- **eslint-plugin-vue version:** 
- **Node version:** 18.4.0
- **Operating System:** Win10 64-bit
- **vue-eslint-parser:** 9.3.0

**Please show your full configuration:**

```json5

module.exports = {
    root: true,
    parser: 'vue-eslint-parser',
    parserOptions: {
        parser: '@typescript-eslint/parser',
        tsconfigRootDir: __dirname,
        project: [ './tsconfig.app.json' ],
        extraFileExtensions: [ '.vue', ],
    },
    extends: [
        'eslint:recommended',
        'plugin:@typescript-eslint/recommended',
        'plugin:vue/vue3-recommended',
    ],
    ignorePatterns: ['dist/'],
    plugins: [ 
        '@typescript-eslint', 
        'plugin:vue/vue3-recommended',
    ],
    rules: {
        'vue/no-reserved-component-names': 'off',
        'vue/multi-word-component-names': 'off',
        '@typescript-eslint/no-explicit-any': 'off',
        '@typescript-eslint/ban-ts-comment': 'off',
    }
};

```

**What did you do?**	

I followed the npm installation instructions at the top of https://eslint.vuejs.org/user-guide/

Then ran eslint in the manner described therein:

```
$npm install --save-dev eslint eslint-plugin-vue
up to date, audited 2356 packages in 7s

$ eslint "src/**/*.{js,vue}"

Oops! Something went wrong! :(

ESLint: 8.44.0

ESLint couldn't find the plugin "eslint-plugin-plugin:vue/vue3-recommended".

(The package "eslint-plugin-plugin:vue/vue3-recommended" was not found when loaded as a Node module from the directory "S:\src\datatecnics-foresight\packages\client".)

It's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm install eslint-plugin-plugin:vue/vue3-recommended@latest --save-dev

The plugin "eslint-plugin-plugin:vue/vue3-recommended" was referenced from the config file in ".eslintrc.js".

If you still can't figure out the problem, please stop by https://eslint.org/chat/help to chat with the team.

$ ls ../../node_modules/eslint-plugin-vue/
lib  LICENSE  node_modules  package.json  README.md
$ 
```

**What did you expect to happen?**

No error

**What actually happened?**

As above.
**Repository to reproduce this issue**

Is this required ?

**Comment by FloEdelmann** [comment]
`extends` should contain `plugin:vue/vue3-recommended` (like you have it already).
`plugins` should only contain `vue`.

Or you could remove the line in `plugins` completely, since `plugin:vue/vue3-recommended` in `extends` implies the `vue` plugin.

**Comment by spaceemotion** [comment]
Quick head's up for those that come across this issue when upgrading to the latest v10 and got this error: instead of `plugin:vue/vue3-recommended` it's now just `plugin:vue/recommended` (the extra prefix got dropped).
