### ISSUE TITLE
ESlint error due to optional chaining on "no-restricted-component-names" rule on vue3

### ISSUE THREAD

**Issue by nirpan** [vuejs/eslint-plugin-vue#2233]
I have a vue3 project which was recently migrated from vue2 and since the migration, there is this error on the `.eslintrc.js` file which seems to happening due to the use of optional chaining used in the [no-restricted-component-names.js](https://github.com/vuejs/eslint-plugin-vue/blob/master/lib/rules/no-restricted-component-names.js#L119) and maybe the right parser is not being used. 

I have tried to disable the rule Manually commenting out the rule on the `.eslintrc.js` but that doesn't seem to work. The only thing that fixed the error was when I experimented with temporarily editing the node_modules directly to comment out [the rule here](https://github.com/vuejs/eslint-plugin-vue/blob/master/lib/index.js#L122) which obviously is not a viable solution.

Here is my `.eslintrc.js`:
```js
module.exports = {
    plugins: ['jest-dom'],
    extends: [
        'plugin:vue/vue3-recommended',
        'plugin:jest-dom/recommended',
    ],
    rules: {
        'indent': ['error', 4],
        'vue/html-indent': 'off',
        'jest-dom/prefer-checked': 'error',
        'jest-dom/prefer-enabled-disabled': 'error',
        'jest-dom/prefer-required': 'error',
        'jest-dom/prefer-to-have-attribute': 'error',
        'vue/no-restricted-component-names': 'off',
    },
}
```

My version details:
```
node: v16.20.1
npm: 8.19.4

vue: 3.3.4
vite: 4.3.9

eslint: 8.44.0
eslint-plugin-vue: 9.15.1
eslint-plugin-jest-dom: 4.0.3

@babel/eslint-parser: 7.22.7
@babel/plugin-transform-nullish-coalescing-operator:  7.22.5
@babel/plugin-transform-optional-chaining: 7.22.6
```

I have also tried the `babel-parser` as follows but still no luck:
```js
// .eslintrc.js
parserOptions: {
        parser: 'vue-eslint-parser',
        parserOptions: {
            parser: '@babel/eslint-parser',
            sourceType: 'module',
        }
    }
```
```js
// .babel.config.js
module.exports = {
    presets: [
        '@vue/cli-plugin-babel/preset'
    ],
    'plugins': [
        "@babel/plugin-proposal-nullish-coalescing-operator",
        "@babel/plugin-proposal-optional-chaining"
    ],
}
```
Based on a few answers I have seen, it shouldn't even require babel-parser but I am not sure what I am doing wrong here? ANy pointers would be appreciated. Thanks

**Comment by BerkanSezer** [comment]
I have same issue on my vue2 project

**Comment by FloEdelmann** [comment]
The ESLint rules are executed by Node.js directly, without being transpiled by Babel. Optional chaining is supported in Node.js v14+, so I'm not seeing where the issue could come from.

Note that the `parser` you define in the ESLint settings is only used for parsing the files to be linted.

Could you provide a link to a repository where the issue can be reproduced?

**Comment by nirpan** [comment]
@FloEdelmann I tried to recreate it locally but didn't manage to do so. I will try to see if I can recreate and post the repo. For now, I decided to downgrade `eslint-plugin-vue` to `8.7.1` which does not have the `no-restricted-component-names` [rules](https://github.com/vuejs/eslint-plugin-vue/blob/v8.7.1/lib/index.js#L116) and works for me.

**Comment by FloEdelmann** [comment]
Maybe it is related to `eslint-plugin-jest-dom`?

**Comment by nirpan** [comment]
@FloEdelmann You were right in in your first assumption. The issue was that the `node` version being used to process the `eslint` rules (in my case with PHPStorm/Webstorm) was indeed v12 which obviously would not work
<img width="749" alt="CleanShot 2023-07-12 at 09 35 51@2x" src="https://github.com/vuejs/eslint-plugin-vue/assets/3050657/7f64ed89-7f91-4427-a387-b35607c3929d">

Changing it to v14+ (in my case v16) has fixed this issue. Thank you for your help!
