### ISSUE TITLE
flowtype-errors and plugin-vue do not work together

### ISSUE THREAD

**Issue by sobolevn** [vuejs/eslint-plugin-vue#224]
**Tell us about your environment**

macOS 10.6

* **ESLint Version:** `v4.10.0",`
* **eslint-plugin-vue Version:** `v3.11.0`
* **Node Version:** `v8.8.0`
* **eslint-plugin-flowtype-errors:** `v3.3.5`

**Please show your full configuration:**

```
module.exports = {
  "extends": [
    "standard",
    "plugin:vue/recommended"
  ],
  "plugins": [
    "html",
    "vue",
    "flowtype-errors"
  ],
  "rules": {
    "import/no-unresolved": 0,
    "no-unused-vars": 0,
    "import/no-unassigned-import": 0,
    "import/no-extraneous-dependencies": 0,
    "import/prefer-default-export": "off",
    "object-curly-spacing": [2, "always"],
    "prefer-promise-reject-errors": 2,

    // allow paren-less arrow functions
    "arrow-parens": 0,
    // allow async-await
    "generator-star-spacing": 0,

    // raise flow errors
    "flowtype-errors/show-errors": 2
  },
  "parser": "babel-eslint",
  "parserOptions": {
    "ecmaVersion": 2017,
    "sourceType": "module"
  }
}
```

And my `.babelrc`:

```
{
  "presets": [
    ["vue-app", {
      "useBuiltIns": true
    }],
    "flow"
  ],
  "plugins": [
    ["module-resolver", {
      "root": ["./client"],
      "alias": {
        "client": "./client"
      }
    }]
  ]
}
```

I run my script as:

```
eslint --ext .js,.vue client
```

**What did you expect to happen?**

Linting should work properly: linting both `vue` and `flow`.

**What actually happened? Please include the actual, raw output from ESLint.**

This error happens: 

```
Error while loading rule 'vue/no-confusing-v-for-v-if': Cannot convert undefined or null to object
TypeError: Error while loading rule 'vue/no-confusing-v-for-v-if': Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.keys.forEach.ruleId (/Users/sobolev/Desktop/wemake-vue-template/node_modules/eslint/lib/linter.js:927:24)
    at Array.forEach (<anonymous>)
    at Linter._verifyWithoutProcessors (/Users/sobolev/Desktop/wemake-vue-template/node_modules/eslint/lib/linter.js:864:35)
    at preprocess.map.textBlock (/Users/sobolev/Desktop/wemake-vue-template/node_modules/eslint/lib/linter.js:993:35)
    at Array.map (<anonymous>)
    at Linter.verify (/Users/sobolev/Desktop/wemake-vue-template/node_modules/eslint/lib/linter.js:992:42)
    at localVerify (/Users/sobolev/Desktop/wemake-vue-template/node_modules/eslint-plugin-html/src/index.js:107:14)
    at Linter.eslint.verify (/Users/sobolev/Desktop/wemake-vue-template/node_modules/eslint-plugin-html/src/index.js:147:18)
    at Linter.verifyAndFix (/Users/sobolev/Desktop/wemake-vue-template/node_modules/eslint/lib/linter.js:1074:29)
```

Related: https://github.com/vuejs/eslint-plugin-vue/issues/186

**Comment by mysticatea** [comment]
Thank you for this report.

The cause of the error is you have "parser" option in the top level. Please move it into "parser-options". See also https://github.com/vuejs/eslint-plugin-vue#what-is-the-use-the-latest-vue-eslint-parser-error

**Comment by sobolevn** [comment]
Nope, that not the case. I have tried it, I have also tried to manually specify `vue-eslint-parser` at the top level, while moving `parser` into `parserOptions`.

It has different issue, it starts to ignore `vue` files and `flow` annotations. 

This issues is not solved.

**Comment by mysticatea** [comment]
I see.
Unfortunately, it's a known issue. It cannot be solved in `eslint-plugin-vue` side. See also https://github.com/mysticatea/vue-eslint-parser/issues/10 and https://github.com/amilajack/eslint-plugin-flowtype-errors/issues/95.
