### ISSUE TITLE
Config with all the rules

### ISSUE THREAD

**Issue by kvinlambert** [vuejs/eslint-plugin-vue#225]
Hi,

Is there a config that allows to have all the rules, and not only the recommended ones? If not, can somebody explain me why such config would be a bad idea?

Thanks!!

**Comment by mysticatea** [comment]
Thank you for the question.

At first, please see [Semantic Versioning] and [ESLint Semantic Versioning Policy].
ESLint and plugins should not break the CI build of users without major version up. We are using patch versions for bug fixing, minor versions for new rule/option adding. 

Now, if we postulate that a user uses the preset which includes all rules, the preset will be updated on every rule adding. The new rule would make new warnings, then it would break the CI build of the user. It's a breaking change which needs a major version!

So we update rules and presets in different timings. The former is in minor versions, the latter is in major versions.

[Semantic Versioning]: http://semver.org/
[ESLint Semantic Versioning Policy]: https://github.com/eslint/eslint#semantic-versioning-policy

**Comment by michalsnik** [comment]
I think @mysticatea explained it well. If you'll have any more questions please ask. If you'd like to follow what is about to change in terms of future rule sets please take a look at #205
