### ISSUE TITLE
Type only used in template is marked as unused

### ISSUE THREAD

**Issue by yuntian001** [vuejs/eslint-plugin-vue#2250]
**Checklist**

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have read the [FAQ](https://eslint.vuejs.org/user-guide/#faq) and my problem is not listed.

**Tell us about your environment**

- **ESLint version:**  8.40.0
- **eslint-plugin-vue version:**  9.15.1
- **Node version:**   16.18.1
- **Operating System:**  windows

**Please show your full configuration:**

```json5
{
 root: true,
  extends: [
    // add more generic rulesets here, such as:
    'eslint:recommended',
    'plugin:@typescript-eslint/recommended',
    'plugin:vue/vue3-essential',
    'plugin:vue/vue3-recommended',
    'prettier',
  ],
  parser: 'vue-eslint-parser',
  parserOptions: {
    parser: {
      // Script parser for `<script>`
      js: '@typescript-eslint/parser',

      // Script parser for `<script lang="ts">`
      ts: '@typescript-eslint/parser',
    },
    sourceType: 'module',
    project: ['./tsconfig.json', './tsconfig.node.json'],
    extraFileExtensions: ['.vue'],
  },
  overrides: [
    {
      files: ['*.vue'],
      rules: {},
    },
    {
      files: ['*.cjs'],
      rules: {},
    },
  ],
}

```

**What did you do?**	

I used 'TreeNodeData' in `<template>`, but @typescript-eslint/no-unused-vars still reports an error，But I'm not using setup syntax sugar, whether that's for that reason
issuse in 'vuejs/language-tools' [https://github.com/vuejs/language-tools/issues/3447](https://github.com/vuejs/language-tools/issues/3447)
![image](https://github.com/vuejs/eslint-plugin-vue/assets/43692243/83d0dd98-7f34-4e0e-a86f-98e467f94962)
![image](https://github.com/vuejs/eslint-plugin-vue/assets/43692243/9542351a-1757-4131-8843-0aa3d7854f2b)

**What did you expect to happen?**
No `@typescript-eslint/no-unused-vars` error
**What actually happened?**

```
  107:15  warning  'TreeNodeData' is defined but never used  @typescript-eslint/no-unused-vars
```
**Repository to reproduce this issue**

**Comment by FloEdelmann** [comment]
I think there is no way to use types (that are not used in the script itself) in the template if you are not using `<script setup>`. You can still disable the rule manually in this one line with

```ts
// eslint-disable-next-line @typescript-eslint/no-unused-vars -- used in template
import { TreeNodeData} from 'element-plus/es/components/tree/src/tree.typed'
```

**Comment by yuntian001** [comment]
> I think there is no way to use types (that are not used in the script itself) in the template if you are not using `<script setup>`. You can still disable the rule manually in this one line with
> 
> ```ts
> // eslint-disable-next-line @typescript-eslint/no-unused-vars -- used in template
> import { TreeNodeData} from 'element-plus/es/components/tree/src/tree.typed'
> ```

I think 'template' recognition type should be supported in non-' <script setup> ', would you consider adding this support

**Comment by FloEdelmann** [comment]
Not sure if this is the right place to implement that support, there are many involved parts:

* `eslint-parser-vue` → might maybe mark the type as used
* `eslint-plugin-vue` → might maybe mark the type as used
* `@typescript-eslint/parser` → might maybe mark the type as used
* `@typescript-eslint/plugin` → the rule that reports an issue here
* `vuejs/language-tools` → for type inference in VS Code

@ota-meshi do you know where this could be implemented and whether it would be correct to do so?
