### ISSUE TITLE
`prefer-define-options` should insert `defineOptions` after import expressions

### ISSUE THREAD

**Issue by fisker** [vuejs/eslint-plugin-vue#2263]
**What rule do you want to change?**

Imporve autofix.

**Does this change cause the rule to produce more or fewer warnings?**

Same.

**How will the change be implemented? (New option, new default behavior, etc.)?**

N/A

**Please provide some example code that this change will affect:**

```vue
<script setup>
import {ref} from 'vue'
</script>

<script>
export default {inheritAttrs: true}
</script>
```

**What does the rule currently do for this code?**

Currently fix to:

```vue
<script setup>
defineOptions({inheritAttrs: true})

import {ref} from 'vue'
</script>
```

**What will the rule do after it's changed?**

Expect fix to:

```vue
<script setup>
import {ref} from 'vue'

defineOptions({inheritAttrs: true})
</script>
```

**Additional context**

[Playground](https://ota-meshi.github.io/eslint-plugin-vue-demo/#eJx1lMFu2zAMhl8l8GWXCgV2DIoBe49eaJm2ucqSRklNvCLvvt92bcdZd0r0kabIn6Q+Khsars7VS7IqMZ8S5xJ/vHoZYtB8+lBub6dWw3D69l7426t/eV484YPD9p+vs3/DLRWH78T3rJJ/5qzpfMpa+Hb4tnqqtDhO1fkDKfgED5uDmlQia3X+/lS1ODWibLMEP5OOc2Y1ihR1IT4YSqO3JiJDSWz4yrYgzmq1BNiwdaQ0xUmbwVFK+DhJt4WyYYikbDx35g9r2Llv/nFFyl8x8nn2ly3rxZI1OGTe8XWFDdel61j3s+PM5p12Ai0MaZcOYMl84KFmPVrYoVhpD+yNx3snJ5ZwySTLSnmIeTwcjO0hl520ni87GiNNXdhq4+uDDHzNSqYOwTH56aZ8tCQeZCUtOZd7DaXrN1TQzmPEzoWa3ANcBvQReo+kv+q3+Hdy0iwtiBtVnAuczaWXzCmS3XRxATKHFqPFVtJdNzFoKK0R3/1PqEGu3Jg5GmYMw5Op3oyeLyaNQx3cRoIPNqNCJC4DfjlZilsiof4FGZ3bIszO6wGTn0Me0eq6iMuyl6y8CME7QO2faa0ssWsfRExfrVnqqQkXQGyqoOLGeBruwmBx0jSsSvu85V6SqRmLzHd7DUPxeCf2AxrCc8gBT4c48bzblAki1+4OJWrZtOIhyfhAsbl0v3ifOMQJQliEEo/G7faScK+jmnd5PyEWcUeQiTEONdk3vIis7PdBWY3YLNs/wmMrL5IXD+XfBW+bGYVdM5My7W7ytOS+DOvU1rAIhcf3Oc5XY0pQ/FrUlOLt9heqG/0r)

**Comment by FloEdelmann** [comment]
PR welcome :slightly_smiling_face:
