### ISSUE TITLE
vue/order-in-components computed内含有辅助函数无法自动修复

### ISSUE THREAD

**Issue by dongjinc** [vuejs/eslint-plugin-vue#2272]
**Checklist**

- [ ] I have tried restarting my IDE and the issue persists.
- [ ] I have read the [FAQ](https://eslint.vuejs.org/user-guide/#faq) and my problem is not listed.

**Tell us about your environment**

- **ESLint version:** 
- **eslint-plugin-vue version:** 
- **Node version:** 
- **Operating System:** 

**Please show your full configuration:**

```json5
const path = require("path");

module.exports = {
  root: true,
  env: {
    browser: true,
    node: true,
    es6: true,
  },
  globals: {
    __webpack_public_path__: true,
  },
  parserOptions: {
    ecmaVersion: 2022,
    sourceType: "module",
    ecmaFeatures: {
      jsx: true,
    },
  },
  plugins: ["prettier"],
  overrides: [
    {
      files: ["*.vue"],
      parser: "vue-eslint-parser",
      plugins: ["vue"],
      extends: ["plugin:vue/recommended", "plugin:prettier/recommended"],
      parserOptions: {
        ecmaVersion: 2022,
        sourceType: "module",
        ecmaFeatures: {
          jsx: true,
        },
      },
      rules: {
        "vue/require-default-prop": "off",
      },
    },
  ],
  extends: ["eslint:recommended", "plugin:import/recommended", "plugin:prettier/recommended"],
  rules: {
    "no-console": "off",
    "no-debugger": "off",
    "import/no-named-as-default": "off",
  },
  settings: {
    "import/core-modules": ["@nh/micro-base-service"],
    "import/resolver": {
      alias: {
        map: [
          ["@", path.resolve(__dirname, "./src")],
          ["@base-service", path.resolve(__dirname, "./micro/base-service")],
        ],
        extensions: [".js", ".vue"],
      },
    },
  },
};

```

**What did you do?**	

```vue



<template>
  <div class="nav-multi">
    <el-tabs
      class="nav-multi-tag"
      :value="$route.fullPath"
      type="card"
      :closable="multiTab.length !== 1"
      @tab-remove="handleClose"
      @tab-click="handleOpen"
    >
      <el-tab-pane
        v-for="tab in multiTab"
        :key="tab.fullPath"
        :name="tab.fullPath"
        :label="(tab.query?.patientName || '') + (tab.meta.customTitle || tab.meta.title)"
      />
    </el-tabs>
  </div>
</template>
<script>
import { mapGetters, mapActions } from "vuex";
import { findIndex } from "lodash-es";
export default {
  name: "NavMultiTab",
  watch: {
    $route(val) {
      this.addMultiTab(val);
    },
  },
  created() {
    this.addMultiTab(this.$route);
  },
// The "computed" property should be above the "watch" property on line 26.eslint[vue/order-in-components]
  computed: {
    ...mapGetters(["multiTab"]),
  },
  methods: {
    ...mapActions({ addMultiTab: "multiTab/add" }),
   
  },
};
</script>


```

**What did you expect to happen?**
1.computed内含有辅助函数时, 应该自动修复;

**What actually happened?**

1.computed内含有辅助函数无法自动修复, 请排查, 谢谢;

**Repository to reproduce this issue**

**Comment by FloEdelmann** [comment]
Well, the rule seems to work like expected. Please see https://eslint.vuejs.org/rules/order-in-components.html.

**Comment by Sapphire2k** [comment]
It doesn't look like that.

<img width="727" alt="image" src="https://github.com/vuejs/eslint-plugin-vue/assets/17328005/9da965b6-f5e0-4be1-b334-4d71c7977982">

**Comment by FloEdelmann** [comment]
Yes it is. The order in your screenshot it `computed, props, data`, the rule suggests `props, data, computed`.

If it doesn't work as specified in the [rule docs](https://eslint.vuejs.org/rules/order-in-components.html), please open a new issue following the issue template (including versions and a repository or Stackblitz or link to the [eslint-plugin-vue Playground](https://ota-meshi.github.io/eslint-plugin-vue-demo/) where the problem can be reproduced).

**Comment by Sapphire2k** [comment]
> Yes it is. The order in your screenshot it `computed, props, data`, the rule suggests `props, data, computed`.
> 
> If it doesn't work as specified in the [rule docs](https://eslint.vuejs.org/rules/order-in-components.html), please open a new issue following the issue template (including versions and a repository or Stackblitz or link to the [eslint-plugin-vue Playground](https://ota-meshi.github.io/eslint-plugin-vue-demo/) where the problem can be reproduced).

Thanks for replying.
Yes, i know this warning and it's correct, but the problem is it would not being fix by eslint (sort the life cycle), you can try to add `...mapStates(['test'])` inside the `computed`, you will see it.

**Comment by FloEdelmann** [comment]
So you agree that the rule is reporting the wrong sort order correctly, but you're only missing the autofix for it?

**Comment by Sapphire2k** [comment]
> So you agree that the rule is reporting the wrong sort order correctly, but you're only missing the autofix for it?

Yes, that's the problem.
