### ISSUE TITLE
Support for Vue.js 3.4

### ISSUE THREAD

**Issue by ota-meshi** [vuejs/eslint-plugin-vue#2326]
- [x] #2355
- [ ] #2130

**Comment by ota-meshi** [comment]
related to https://github.com/vuejs/vue-eslint-parser/issues/212

**Comment by brandonleichty** [comment]
Would definitely be nice to get this supported with the release of 3.4 today 🙌

**Comment by grandsong** [comment]
I want "v-bind shorthand" very much! I'm looking forward to this support!
