### ISSUE TITLE
assignment value in v-on ,the rule that named 《vue/space-infix-ops》 will make bug ，

### ISSUE THREAD

**Issue by lwq-js** [vuejs/eslint-plugin-vue#2347]
![image](https://github.com/vuejs/eslint-plugin-vue/assets/57469107/363ac25c-1d77-4112-aab1-1b1bda922e69)
when i save，it will be
![image](https://github.com/vuejs/eslint-plugin-vue/assets/57469107/52bb7f25-69a5-4180-bb25-47eaabe2e5e2)

**Comment by FloEdelmann** [comment]
Maybe there is a non-printable character after the `=` character? Anyway, please stick to the issue template and provide a reproduction repository.
