### ISSUE TITLE
[Suggestion] remove dynamic input type warning

### ISSUE THREAD

**Issue by HerringtonDarkholme** [vuejs/eslint-plugin-vue#238]
**Tell us about your environment**

* **ESLint Version:** 4.0.0
* **eslint-plugin-vue Version:** 3.14.0
* **Node Version:** 8.5.0

https://github.com/vuejs/vue/commit/f3fe012d5499f607656b152ce5fcb506c641f9f4

Vue 2.5 has already supported dynamic input type. 

It seems v-model dynamic type check isn't needed any more.

https://github.com/vuejs/eslint-plugin-vue/blob/master/lib/rules/valid-v-model.js#L97-L104

**Comment by michalsnik** [comment]
Thanks for pointing this @HerringtonDarkholme We're definitely going to update this rule :)
