### ISSUE TITLE
`vue/no-useless-v-bind` auto-fix adds extra whitespace

### ISSUE THREAD

**Issue by claneo** [vuejs/eslint-plugin-vue#2396]
**Checklist**

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have read the [FAQ](https://eslint.vuejs.org/user-guide/#faq) and my problem is not listed.

**Tell us about your environment**

- **ESLint version:** 8.56.0
- **eslint-plugin-vue version:** 9.21.1
- **Vue version:** 
- **Node version:** 
- **Operating System:** 

**Please show your full configuration:**

```json5
module.exports = {
    extends: ['plugin:vue/recommended'],
    rules: {
        'vue/no-useless-v-bind': 'error',
    },
};
```

**What did you do?**	

```vue
<template>
  <div 
    :title="
      'text'
    "
  />
</template>
```

**What did you expect to happen?**

```vue
<template>
  <div 
    title="text"
  />
</template>
```

**What actually happened?**

```vue
<template>
  <div 
    title="
      text
    "
  />
</template>
```

**Repository to reproduce this issue**

[Playground](https://ota-meshi.github.io/eslint-plugin-vue-demo/#eJx1lMFynDAMhl9lh0su8WSmx0zaJ8lFmB9QYmwq27tLM3n3Csga2KanXX2yhfRL8kdlQ4PquXpJGEZHCb9e/en00vD5NP85nZ4TJ4efr9Vqnk4PCdf0sForfdI7L08lQPVYSXaI1fNHdc54smEY4JNpWGATn/VzPx4Xz1u8mhwRzZkkLtQGH5Nkm4KYmEfIQlu1vm4Hv5AOKUGMIGVZiQ+G4uStGSUMHGFwhc0a5+a1pLCBdSQ0x4nF4ShGvRy5K6E055EExqMzfyBh477556im/B0jrXk+zyXr1ZMkOM28w/UGG9S56yCb7ZAwq1KIamFIungAa+YDhhpy9MBpsdwe2Dum/SHHVru1yHKj2sE0HQxje5XLzlovHzs6R5q7UGrD9U4GHRQhU4fgQH7+Urp5WnIu9RJy1xeUtXnH+50LNbk7yMMY5F5w9l5T/K677M/kuFkFHwsVtbMeNpeeE+JItqjggooaWh0kWI673ulYaSEN++5/snhcTJyGOrhCgg82aRGaGw/6i2hpLN8K9Zvq4lyJsBy+GTrKKaRJe1dndom3qgRrrdiAlmeWOsqhCNfe6RS/25vYUxMuCnX1WItqjKdhF0Y3Ic7TJ7QNUOo5mhq6mdgtqjqyb9BuhmqOJeSQtQDHHptPQKpj7XYoUgvTsldJpjuqq0j7TfrCYZyhCquh2GtvNr8+LY1xVGOT9wuW92ZGKhO04zXZd0ELgd9m4ebUVbH9PTy28sJpPSH4nfWxMhPDNQvJ8zJGT2vu6zzObQ1teQp3Yc+mZj9f/Pz8C+Aj6Ao=)

**Comment by FloEdelmann** [comment]
Thanks for the report! PRs are welcome :)
