### ISSUE TITLE
Add `slots` to `vue/order-in-components` default order

### ISSUE THREAD

**Issue by FloEdelmann** [vuejs/eslint-plugin-vue#2399]
**What rule do you want to change?**

`vue/order-in-components`

**Does this change cause the rule to produce more or fewer warnings?**

More.

**How will the change be implemented? (New option, new default behavior, etc.)?**

Add [`slots`](https://vuejs.org/api/options-rendering.html#slots) to default order. Currently, the default order is:

https://github.com/vuejs/eslint-plugin-vue/blob/e936a1524c3bde167e68a365bd6fcd1b86a059b2/lib/rules/order-in-components.js#L14-L76

I'd propose to add the `slots` option after `emits`, in the `Interface` category. This is probably a breaking change, but we could argue that the `slots` option (which was introduced in Vue 3.3) is not in use for long, so intentionally breaking might be okay.

@ota-meshi what do you think?

**Comment by ota-meshi** [comment]
I think we can do it in the next major version. #2153
Also, starting with the next major version, I would like to change our policy so that changes that support Vue and Nuxt features are not considered breaking changes for us.

**Comment by FloEdelmann** [comment]
Ah, I only checked open issues, not PRs. I linked the PR to this issue now.

**Comment by FloEdelmann** [comment]
Will be fixed in v10.
