### ISSUE TITLE
`sameNameShorthand` from `vue/v-bind-style` confuses hyphens with underscores

### ISSUE THREAD

**Issue by adamsol** [vuejs/eslint-plugin-vue#2409]
**Checklist**

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have read the [FAQ](https://eslint.vuejs.org/user-guide/#faq) and my problem is not listed.

**Tell us about your environment**

- **ESLint version:** 8.41.0
- **eslint-plugin-vue version:** 9.22.0
- **Vue version:** 3.4.20
- **Node version:** 14.19.3
- **Operating System:** Windows 10

**Please show your full configuration:**

```json5
module.exports = {
  extends: ['plugin:vue/vue3-recommended'],
  rules: {
    'vue/v-bind-style': [1, 'shorthand', { sameNameShorthand: 'always' }],
  },
  ignorePatterns: ['node_modules/'],
};
```

**What did you do?**	

```vue
<template>
  <div :test-value="test_value" />
</template>
```

```npm run lint```

**What did you expect to happen?**
No warning.

**What actually happened?**

```
/home/projects/vitejs-vite-uc4css/src/App.vue
  2:8  warning  Expected same-name shorthand  vue/v-bind-style

✖ 1 problem (0 errors, 1 warning)
  0 errors and 1 warning potentially fixable with the `--fix` option.
```

**Repository to reproduce this issue**

https://stackblitz.com/edit/vitejs-vite-uc4css?file=src%2FApp.vue

**Comment by FloEdelmann** [comment]
Thanks for the bug report. PRs welcome!
