### ISSUE TITLE
Offer suggestions in `vue/order-in-components` when autofix is not available

### ISSUE THREAD

**Issue by FloEdelmann** [vuejs/eslint-plugin-vue#2418]
In [`vue/order-in-components`](https://eslint.vuejs.org/rules/order-in-components.html), autofix is only enabled when we are sure that the things we are reordering are free of side effects, to not break the code. However, the automatic reordering is really useful.

I suggest to add the (unsafe) reordering as a suggestion, so the user can decide for themselves whether to automatically reorder the rule in this case.

*(Originially reported in #2272)*

**Comment by Sapphire2k** [comment]
i have a question, how to make it by default applying to automatic reordering, maybe i can change the options it like the order, thanks~
```{
  "vue/order-in-components": ["error", {
    "order": [
      "el",
      "name",
    ],
    "ignoreSideEffects": "1", // <----  here
  }]
}```

**Comment by FloEdelmann** [comment]
You can use the `order` option, please see the rule docs I linked above.
