### ISSUE TITLE
require-default-prop for optional props

### ISSUE THREAD

**Issue by stephanfriedrich** [vuejs/eslint-plugin-vue#2433]
Hi,
I hope you are doing well.
I have a question or if you like suggestion about the **require-default-prop** rule.

### request

It says that a `prop` must have a `default-value` set. 
I use an optional `string-prop` to hide my markup if its `undefined`.
Now I don`t want to switch off this `lint-rule` completely, but I am forced to some default-value.

Is there a best practice?

### prop which triggers the lint hint

```Javascript
    /**
     * optional Card Headline
     */
    cardHeadline: {
      type: String
    },
```

### The following notation feels wrong or not DRY:

```Javascript
    cardHeadline: {
     default: '',
      type: String
    },
// or
    cardHeadline: {
     default: undefined,
      type: String
    },
```

Thx,
have a sunny day.
Pukoo

**Comment by FloEdelmann** [comment]
Well, this rule forces you to define a default value explicitly, so it can either be `undefined` or `''`. If you don't like that rule, feel free to disable it.

I like to explicitly define props (e.g. setting `type`, `required`, and if not required: `default`). In fact, I wrote a small utility library simplifying this definition: https://github.com/FloEdelmann/vue-ts-types
