### ISSUE TITLE
how to configure for .vue with <script setup lang="ts"

### ISSUE THREAD

**Issue by hl037** [vuejs/eslint-plugin-vue#2445]
**Tell us about your environment**

- **ESLint version:** 8-9
- **eslint-plugin-vue version:** latest
- **Vue version:** na
- **Node version:** na

**The problem you want to solve.**
i suceeded to get the conf working, however, the rule component-tags-order (nor block-order) don't get fixed with --fix. Actually no rules in <script setup lang="ts" get fixed. How to set it up correctly?

**Comment by FloEdelmann** [comment]
Please see https://eslint.vuejs.org/user-guide/#faq

**Comment by hl037** [comment]
Well... I exactly did that before askin, but still not working

**Comment by FloEdelmann** [comment]
I can't spot any immediate mistakes from that screenshot. But it is extremely hard to remotely debug an issue with only a partly reflective screenshot and no reproduction code or specific version information. Please open a new issue following the bug template and provide a reproduction there.
