### ISSUE TITLE
Support for ESLint 9

### ISSUE THREAD

**Issue by BWrong** [vuejs/eslint-plugin-vue#2447]
What time support for ESLint 9？

**Comment by kolaente** [comment]
Trying to use this with eslint 9's flatfile config [as per the docs](https://eslint.vuejs.org/user-guide/#configuration-eslint-config-js) results in this error:

```
TypeError: pluginVue.configs.vue3-recommended is not iterable
```

**Comment by FloEdelmann** [comment]
Please read the docs again; it's `pluginVue.configs['flat/recommended']` not `pluginVue.configs.vue3-recommended`.

**Comment by kolaente** [comment]
Well that's kind of embarrassing. Thanks for the pointer!
