### ISSUE TITLE
Under default configuration, HelloWorld.vue in the vite ts template will be detected as an error

### ISSUE THREAD

**Issue by qq326943819** [vuejs/eslint-plugin-vue#2449]
**Checklist**

- [x] I have tried restarting my IDE and the issue persists.
- [ ] I have read the [FAQ](https://eslint.vuejs.org/user-guide/#faq) and my problem is not listed.

**Tell us about your environment**

- **ESLint version:^8.57.0** 
- **eslint-plugin-vue version:^9.25.0** 
- **Vue version:^3.4.21** 
- **Node version:20.11.1** 
- **Operating System:Windows 11 23H2** 

**Please show your full configuration:**

```js
import tseslint from "typescript-eslint";
import eslintConfigPrettier from "eslint-config-prettier";
import eslintPluginPrettierRecommended from "eslint-plugin-prettier/recommended";
import pluginVue from "eslint-plugin-vue";

export default [
  // ...tseslint.configs.recommended,
  ...pluginVue.configs["flat/recommended"],

  /**
   * keep end
   */
  // eslintPluginPrettierRecommended,
  // eslintConfigPrettier,
];

```

**What did you do?**	

```vue
<script setup lang="ts">
import { ref } from 'vue'

defineProps<{ msg: string }>()

const count = ref(0)
</script>

<template>
  <h1>{{ msg }}</h1>

  <div class="card">
    <button type="button" @click="count++">count is {{ count }}</button>
    <p>
      Edit
      <code>components/HelloWorld.vue</code> to test HMR
    </p>
  </div>

  <p>
    Check out
    <a href="https://vuejs.org/guide/quick-start.html#local" target="_blank"
      >create-vue</a
    >, the official Vue + Vite starter
  </p>
  <p>
    Install
    <a href="https://github.com/vuejs/language-tools" target="_blank">Volar</a>
    in your IDE for a better DX
  </p>
  <p class="read-the-docs">Click on the Vite and Vue logos to learn more</p>
</template>

<style scoped>
.read-the-docs {
  color: #888;
}
</style>

```

**What did you expect to happen?**
This file should not generate an error

**What actually happened?**

Eslint identified an error and I am not sure how it occurred. I am very concerned about inexplicable errors that may occur during the actual development process

![image](https://github.com/vuejs/eslint-plugin-vue/assets/32457006/b580e2e9-51de-43f9-a6d8-2dda9f703157)

**Repository to reproduce this issue**

https://github.com/qq326943819/bug-report-for-eslint-plugin-vue

**Comment by FloEdelmann** [comment]
TypeScript requires extra setup, see https://eslint.vuejs.org/user-guide/#what-is-the-use-the-latest-vue-eslint-parser-error. Please feel free to submit a PR to improve the docs in this regard, if you find them lacking.

**Comment by shrinktofit** [comment]
As eslint@v9.16.0, typescript-eslint@8.17.0, eslint-plugin-vue@9.32.0, the following works for me:
```js
import vue from 'eslint-plugin-vue';
import tsEslint from 'typescript-eslint';
import vueParser from 'vue-eslint-parser';

// concat these to your flat config
[
    vue.configs['flat/recommended'],
    {
      files: ['**/*.vue'],
      languageOptions: {
        parser: vueParser,
        parserOptions: {
          extraFileExtensions: ['.vue'],
          sourceType: 'module',
          parser: {
            ts: tsEslint.parser,
          },
        },
      },
    },
  ]
```
