### ISSUE TITLE
Some of my plugins don't work

### ISSUE THREAD

**Issue by dddssw** [vuejs/eslint-plugin-vue#2472]
**Tell us about your environment**

- **ESLint version:^8.57.0** 
- **eslint-plugin-vue version:^9.23.0** 
- **Vue version:^3.4.21** 

```vue
<script setup>
watch(
  () => props.initiallist,
  (newVal) => {
    newVal.forEach((item) => {
      child.value.newSelectedItems.set(item.materialCode, item)
      amountMap.value.set(item.materialCode, item.amount)
    })
    child.value.handleSubmit()
  }
)


      
const disabledCode = computed(() => {
  return sceneForm.tableData.map((item) => item.materialCode)
})
</script>
```

According to the style guide, watch should be placed after computed, but there is no eslint prompt

```js
// .eslintrc.cjs
/* eslint-env node */
require('@rushstack/eslint-patch/modern-module-resolution')

module.exports = {
  root: true,
  'extends': [
    'plugin:vue/vue3-essential',
    'plugin:vue/recommended',
    'eslint:recommended',
    '@vue/eslint-config-typescript',
    '@vue/eslint-config-prettier/skip-formatting'
  ],
  parserOptions: {
    ecmaVersion: 'latest'
  },
  rules: {
    'vue/new-line-between-multi-line-property': [
      'error',
      {
        minLineOfMultilineProperty: 2
      }
    ]
  }
}
```

[But I see that it is in the default rules, I don't know what went wrong](https://eslint.vuejs.org/rules/order-in-components.html)

However, the attribute on the component has a prompt
![image](https://github.com/vuejs/eslint-plugin-vue/assets/58782768/3476f0da-4d0e-4796-96cf-565a39ea1f2f)

**Comment by waynzh** [comment]
[This rule](https://github.com/vuejs/eslint-plugin-vue/blob/master/lib/rules/order-in-components.js#L364) seems to mainly enforce the declaration order of the Optional API. 
When using the `setup` Composition API, there isn't a strict requirement for the order of declaration for `watch` and `computed`.

**Comment by dddssw** [comment]
@waynzh [The property I set is also invalid under the setup syntax sugar](https://eslint.vuejs.org/rules/new-line-between-multi-line-property.html#further-reading)
Maybe this isn't supported?
![image](https://github.com/vuejs/eslint-plugin-vue/assets/58782768/f87906eb-4e28-4632-891c-8ada1f846896)

**Comment by waynzh** [comment]
You could use the [playground](https://ota-meshi.github.io/eslint-plugin-vue-demo/) to provide a reproduction of this issue.

**Comment by dddssw** [comment]
@waynzh  yes,this is a example
[example](https://ota-meshi.github.io/eslint-plugin-vue-demo/#eJzNVk2T4zQQ/SvCe0hSFSW1TBW1m8kEqOXCgRMUF7IH2W47YmXJSHJmQiq/giu/jl/CkxR/JDVz4cRlRnqv1ep+6m7nnBWmpGyTbT01rRKednvN2FbqtvPsyBuw6mmfxf2vQnW0z9g62eSd90azQgnnYCLKkicIJt8VShZfgB6ELhV9CjvAu+/Lkv1ifjDbdTL9b57ev+2qU4Mbb0rDlXR+n0UOrJJpwZBaZSyM5sFqyaQu6WWBfyzsf4QYbp/1tpsvdLr6W8lyxG8ukjgzOdJzZzYbaM5Lo2m2iXeswppdxiNDoiP7xL4aNr3hrrffulZo5CGr6Rnk+s/ff23Xgdyx8znd5enFs8vlqsJaySTWulNYbNeTt9+6wsrWM0e+a7GXTWusZ2dmqVqywjSoAyqXz8IXB3ZhlTUN22fHLsZXGO08G2sFCeDYHFS26NlB3yv522dQVacLL1ECk0eeL9g5RDkcWB2Dz1XbucP8nFKR5Yb9JPxhZXHONPPFypufvZW6nj98s1g5+KE5/7BYJvMg0IZVQjm6IkGYzSTidEckL4vw955C1CGdvb68HvX7/3/Y8e3mo8VyvnjandP7GEUrZeopOxvXM/i+DC+Z2u6TUcbCfV8acwjwtGMTD+xb3J0rESfABuvnA7oBJbF4DMWXCi6Wnj+pUIOrcQAkLYtwxwa1nqNP55N7gwfGWiO1J8vpSNq7wW46tRAD8pBeCjVDDDMdGhEhPEZFVsOoSPeFFY/RbFiwnFqFRk5WOTKqrel0ya8BviOq7m1T07954qHKP354eJxk+a6qrk6gzVWRbJnZTpHLNucsim+7whvLXdeSzTZfLzNMM15KS7EgI1KTD6JYNLJNiDZcuJMueIuulY44vVDRwU/PFgJgSZhdVgQ/biDCNMNhJ+vBVXhwYYlrqvmfZM2II717U4T8Gia0j/ZyiDox3hqFyGt66cGS8q6uyY57RZ74UYwItODC1u4GSJE31ORkbxlCO2F43mAY9FMj9CGmYpSlRzEp/elmw4sD5CqC1vGyW7IV4RWG3OjlTgY0shU8N2g8ocNNvmfQ78ofUC31YYAwcO7O18rkQt2BaWjfg1ojxNdeV2rMCFkmwdsBtdh3MOaxX/FBKQYVlIGopkIhUSHd5O1QVkikxCR7SxZNz9ydmtyoATHaFB5JIDbZ4D+5QrTDXSb/HbooNXiIxv0GpeyNP+Ht8k4qL8esLKVcaQSQHo95DEaOVHWnk3utb9xBlOYZIFpPIqmSa9FM3KATXKg+K8YC8gfpeE7oTJo0Kgj0P1XjBppTdNl0SEBJTSNnSUDHXE0gJyrildSQ5HSHohXFtJOusGkDCGHhCkNQ1yPfOdyrRE6jvFcQnTVCkInw4mF+4ZtNlvRYCz1ZhM/KPXj7lM/SJwtLf3QYVvwkSZUR6UIzOi1S7Kkew7OaJBR+YKzRSVZi+BNKz5ZXOQMRC1IT73/GTImoaavwAsr4cTxc2SM/+EYNSHSLdoizDR7xNRm4+JqgJpdcLv8CzKDTDQ==)

These two rules did not take effect

- https://cn.vuejs.org/style-guide/rules-recommended.html#component-instance-options-order
- https://cn.vuejs.org/style-guide/rules-recommended.html#empty-lines-in-component-instance-options

**Comment by FloEdelmann** [comment]
Both [`vue/order-in-components`](https://eslint.vuejs.org/rules/order-in-components.html) and [`vue/new-line-between-multi-line-property`](https://eslint.vuejs.org/rules/new-line-between-multi-line-property.html) only target components using the Option API, not `<script setup>`.

For `vue/order-in-components`, the request to also apply it for components using the Composition API was rejected, see https://github.com/vuejs/eslint-plugin-vue/issues/2055#issuecomment-1480909340. Also note that the style guide rule you linked does not mention whether it applies to Options API or Composition API.

For `vue/new-line-between-multi-line-property`, I also don't think it makes sense to extend it to components using the Composition API. It is quite specific to adding new lines between object properties. In `<script setup>` or in the `setup()` function, there are no "blocks" that can be separated by an ESLint rule. So I agree that the style guide rule should be followed manually while writing the code, but it can't be enforced by ESLint.

So I'll close this as won't fix.

**Comment by dddssw** [comment]
It is best to mark it in the document to avoid others having the same problem

**Comment by FloEdelmann** [comment]
PRs to improve the docs are always welcome :slightly_smiling_face:
