### ISSUE TITLE
I tried cloning the project and running, but something went wrong

### ISSUE THREAD

**Issue by dddssw** [vuejs/eslint-plugin-vue#2473]
After cloning the repository, I executed npm run docs:watch, but it did not proceed as expected. What should I do?
![image](https://github.com/vuejs/eslint-plugin-vue/assets/58782768/c5092157-b114-43d9-afce-24cea12db11c)

**Comment by FloEdelmann** [comment]
Did you install Node.js 20?

**Comment by dddssw** [comment]
I used node18 before, but I still got the same error when I switched to node20.
![image](https://github.com/vuejs/eslint-plugin-vue/assets/58782768/e75d82e9-0605-40d8-b980-ab4f0825b8fa)

**Comment by FloEdelmann** [comment]
Indeed, I can reproduce the issue albeit with a slightly different error message:

![grafik](https://github.com/vuejs/eslint-plugin-vue/assets/202916/5934dd23-d604-444a-8487-7bff4d9f0df8)

It might have something to do with the fact that `eslint` is shimmed in the docs build, so `eslint/use-at-your-own-risk` is undefined. @ota-meshi could you have a look at this please?

**Comment by ota-meshi** [comment]
Hmm. It works fine on my local machine 🤔 
Since the demo still uses ESLint v8, `new eslint.Linter().getRules()` should succeed and not try to load `eslint/use-at-your-own-risk`.

**Comment by FloEdelmann** [comment]
Oh right, with an `npm install` before `npm run docs:watch`, it also works for me. (I had the ESlint v9 testing branch checked out locally before.)

@dddssw, does that also resolve the issue for you?

**Comment by dddssw** [comment]
@FloEdelmann  emm,It works after I change the branch.I shouldn't use master branch to run it?

**Comment by ota-meshi** [comment]
I think it works on the `master` branch.
