### ISSUE TITLE
Rule proposal: `no-nested-components`

### ISSUE THREAD

**Issue by michalsnik** [vuejs/eslint-plugin-vue#249]
**Style guide:**
https://vuejs.org/v2/style-guide/#Tightly-coupled-component-names-strongly-recommended

**Description:**
This rule would warn about nested components, as it is recommended to keep `components` directory flat, for reasons explained in the style guide.

**Comment by chrisvfritz** [comment]
Hm, I'm not sure this rule would actually have value. We do mention in the detailed explanation that for larger applications, some limited nesting is probably OK, so it's not a "hard" rule. Also, it would be difficult to accidentally nest components and also difficult to miss nesting in a code review, so I'm guessing it would possibly take up more time to configure than it would save.

**Comment by michalsnik** [comment]
You're right @chrisvfritz
