### ISSUE TITLE
Rule proposal: `component-name-casing`

### ISSUE THREAD

**Issue by michalsnik** [vuejs/eslint-plugin-vue#251]
**Style guide:**
https://vuejs.org/v2/style-guide/#Component-name-casing-in-JS-JSX-strongly-recommended

**Description:**
We already have a rule called [name-property-casing](https://github.com/vuejs/eslint-plugin-vue/blob/master/docs/rules/name-property-casing.md) but it only checks a property `name`, and dosen't care about `Vue.component('TheComponent', ...)` case.

This rule could either extend the `name-property-casing` with extra checks or simply fill the gap and check only the second case, but if someone would want to change default casing he would need to do it in two places, and that's rather not what we want, so I'm leaning more towards one rule for both cases.

**Comment by mysticatea** [comment]
I agree with you.

But I think that the name `component-name-casing` causes confusing between definition's and reference's.

How about `component-definition-name-casing` and `component-reference-name-casing`?

**Comment by armano2** [comment]
i can take this one.

i like one rule approach more to. but i'm not sure about name?

`component-definition-name-casing` witch checks name property and `Vue.component('***'` seems good.

**Comment by armano2** [comment]
fixed in #646
