### ISSUE TITLE
useTemplateRef('*')  "*" is defined as ref, but never used.   =>   vue/no-unused-refs

### ISSUE THREAD

**Issue by rex-ll** [vuejs/eslint-plugin-vue#2547]
**What rule do you want to change?**

**Does this change cause the rule to produce more or fewer warnings?**

**How will the change be implemented? (New option, new default behavior, etc.)?**

**Please provide some example code that this change will affect:**

```vue

```

**What does the rule currently do for this code?**

**What will the rule do after it's changed?**

**Additional context**

**Comment by FloEdelmann** [comment]
There is already a fix for that in development, see #2541.
