### ISSUE TITLE
autofix for vue/no-empty-component-block

### ISSUE THREAD

**Issue by RedBlueKoi** [vuejs/eslint-plugin-vue#2564]
**What rule do you want to change?**
- Rule to change is vue/no-empty-component-block

**Does this change cause the rule to produce more or fewer warnings?**
- This change would not change the amount of errors/warnings

**How will the change be implemented? (New option, new default behavior, etc.)?**
- Preferably default behaviour

**Please provide some example code that this change will affect:**

```vue
<script setup lang="ts">
  defineProps<{...}>()
</script>

<template>
  <h1>My awesome title</h1>
</template>

<style scoped lang="postcss"></style>
```

**What does the rule currently do for this code?**
- Currently the rule marks the style tag as an error, but you would have to remove it manually

**What will the rule do after it's changed?**
- After change eslint will be able to remove the style tag with `pnpm eslint --fix`

**Additional context**

**Comment by FloEdelmann** [comment]
PRs welcome!

**Comment by RedBlueKoi** [comment]
@FloEdelmann got you, let me see if I can pull it off

**Comment by RedBlueKoi** [comment]
> PRs welcome!

Do you maybe have an example that I can reference?

**Comment by FloEdelmann** [comment]
I think [`vue/block-order`](https://eslint.vuejs.org/rules/block-order.html) might have a similar autofix. Please also add test cases.
