### ISSUE TITLE
Eslint plugin vue format sfc style tags

### ISSUE THREAD

**Issue by Falcomfr** [vuejs/eslint-plugin-vue#2569]
**Tell us about your environment**

- **ESLint version: 9** 
- **eslint-plugin-vue version: v9.28.0** 
- **Vue version: 3.5.10** 
- **Node version: v20.17.0** 

Hi,

Is there a solution to format the style tags of vue files with your package (or others)?

THANKS !

**Comment by FloEdelmann** [comment]
For formatting, I'd recommend Prettier. This is out of scope for eslint-plugin-vue.
