### ISSUE TITLE
Fix eslint on single quotes in html will be escaped.

### ISSUE THREAD

**Issue by adoin** [vuejs/eslint-plugin-vue#2587]
**Checklist**

- [ ] I have tried restarting my IDE and the issue persists.
- [ ] I have read the [FAQ](https://eslint.vuejs.org/user-guide/#faq) and my problem is not listed.

**Tell us about your environment**

- **ESLint version:** 
- **eslint-plugin-vue version:*latest* 
- **Vue version:*3.4.28* 
- **Node version:*18* 
- **Operating System:*windows* 

**Please show your full configuration:**

```
by default
```

**What did you do?**	

```vue

```

**What did you expect to happen?**

**What actually happened?**
```vue
<my-components  :title='t("1")' />
```
fix eslint
```vue
<my-components :title="t(&quot;&quot;)"/>
```
**Repository to reproduce this issue**

[repoduce](https://ota-meshi.github.io/eslint-plugin-vue-demo/#eJyNWM2O4zYSfhWtc/AMdjgNbC7ZTk9nF1kskHuQUwMBJZVspilSISm3nUY/Ra55ujxJviL1Q0n2ZE6SqopFsuqrP73uKlvT7n73EKjttAz0+GSK4kGZrg/FSbTg6k9Pu/j9k9Q9Pe2KuyRT9iFYU/yn0qp6hsxRmlrT9/wFoUpL70GVdS2SJIj3Rrb0aX+g8P/evHvancF92r3fP/63rosf7f/sw12STTv0elITbG2FVj487SIPXK3SS4FzNtZB6B1LfSiUqen8Ho+Cv3/AzfzTbpS9f6bLoO+jqmf6YiOFNdmSkfda7Ce2ELU1tL+Pe3zk9+JtXjIZZeZ+Kv4xfYyCj6P8g++kwT1Uk6/BXf/84/eHO2Y+Fq+vaa9A51C8vQ1WuNMqGeuu13h5uMsc+eArp7pQeAp9h+/KGh+KZH2c550P7v2nx/3PP+//idcnw8vTkrg4XDRr+Ti7sHjlrSqrrbvHaUtY+l3ifM+0998yu7PKBHKCTmSCn+RyEBXfFXtlVFBS74v7Ym/YlAAC1uNeHydnp/34TcTT3BcsmUuxK5JUKavng7O9qcVwwK+ImrVsctvNFV835b+/+frb7JZfNc2gBLYZLLL7sHO9Jr+7f92derqrbNvirqJWjqqgTgiof32InF/8WfSevDhJ5ydq2+ugxIt1vHHb4UBYzKExixgrpHP2RTS9gUo4TigjXmSojgsZfzEVc1hPH6gWnbMduaCWuqqj0rwZHGPCgrFdx+pqGWQuVlOHq0kWZJaw5S+4KcgIDSf5fLekCciyF7xp1VB1qTTdkrQauqLbyZDzQnbq86K+wpFrr234nHCC4WcEGqUB11vMwfxSizGwbkgeQ6sFaYpIUP6GlDJaGfo7XewMD0IjgRQRjjfVAb0catD5LII8xIU3RKO1hAzBKYTsrZ3Zml8m9GX6UvALhulNiZu3OwlrEBccUVyJVKNu+imJ9m0Ja4yiN9X2xKHQqINAMeACuJTscS8wtsQT/OsJSXrFQa6H4tkWi5V07qwLHFQptYqYjdcSUCsbdqV8kWoRoVPc3BJo+wATmeT8xdYdkg4zCJlkYThHDVKH4IhH0V5yPLkTfTYxTTJrI02MzUn8UbqF0nWC8aomQQ2uGvwX5LMxfvgIS/o5YCcJo/ggq+MClr1BKs4O4a8wF3mayZ42Z7nAJ89AJIWjrdfCXMPFiwpHEbuSFRtFw8+Hvw6YuG5xQ8Z2zOBLMb4sHjHxWDPfK5eKFeMqchAODYiqjfBsnG05MCa2o197lLPMZVmYjkw2iAiXLsYTEn1fhezKo5QjNGQOj9A7s+EO+dvPlW4jEuzhAPwrE1ESgFmvFjVnFEymyzExcaRW9ZRRF2kynesa6C5XZKhVwSd1Mr9s8j3cQGdZzVZO+06OjsG0YuJQXBKi4uusZTgllmHnBzSZK/qEG2ft+hgpGW+IlbZyrWab6nL6hpgjfaQxLjfEKwrV+moYO6i1WyLPIhtqhoKZVG1PCLhvaP5oX7ZEfcVuHGqRmOFceNSEdG1G3dD8DedBkx2WmJ+6NXizVbAtnanqRwhxKyZBzDoqPzF4/MBirw6TKoYqEh1gcBC/kbMzHdV2LYojX6NJBDUAId2FSxCStx9Pn0uwxjnaEgctncbdDnQeiTWV/eFAbv7WFDjsZgpXUOkOfkFId4O/y7Fej5wcf5uqvKi7bLiRCvQPYTt+IHPCoBV7I262ZHaS/WSWRM8FtRKltkN4xSK9MiEQ4aQordUkDZ8hjJxGah2OaM0Ox4mE3LZaf9C2RFe5JA7ZeEU0CYbR4N1EdfjuuQ9+OWKywYxYTVbQFka1DYO+UrlXATwct+am4IZZDL2MLRdmrXVaZwFrbBVwckBVtXiSr2Q3bY3JAMbQelIYhccPYD/YWDDKHm23mkGO9iBCn2YCbivitSYhFNBmZRx/LdDQbtSYnRwPH6rijD43MczmxojB6OSMJ+6yRUkIZcoiO3YGSMPzB1xAUWWc4ribn3noPGDWUmckLxvCiIEBQl9WVMSuzANrINtuGDigCkOyOcz82KJoWdJs3oHYOXWKsXAtnta9TdaL8AwcGwEyM3xGZjWNmxlx6W7udOL7WGgvioY+hSui8kYOCTpVJ7jeziVgrovHS3cks5wks26R62BMQtGRHG2jXViwUc5nUwuPQ1TCF3NRiz0S6lxsh0vg/pkCQ31y300hBmC+VxrzkGQxbvkllf87Zd1XpP3a27y9i7SI4mGfidPKc9YPii5NdfPhJrQtB81hpN/cZex/RfwX01kdTbu5TRwf+GdEFmdjRx4pCJL4gwTeBSI58GJ7fnXsm1qPFH4TCz7M2ki+GUbueWVsIq+5dYTUja4tMRGOKAMqrPqnTYc6s3gPTV9uynGE5Z8/GZFbPf61cBW6kb1ekcbmgfj29hfKL3mR)
on the line 3 name==>fix it

**Comment by ota-meshi** [comment]
I think the `avoidEscape` option will allow you to keep your preferred style.

https://eslint.vuejs.org/rules/html-quotes.html#double-avoidescape-true
