### ISSUE TITLE
Committing a `package-lock.json`

### ISSUE THREAD

**Issue by ixxie** [vuejs/eslint-plugin-vue#2588]
I'm considering packaging `eslint-plugin-vue` for [nixpkgs](https://github.com/NixOS/nixpkgs/tree/master), and I noticed the `eslint-plugin-vue` repo has no `package-lock.json` comitted. Is there a particular reason for this? The [npm docs for the lock file](https://docs.npmjs.com/cli/v10/configuring-npm/package-lock-json) recommend committing it for a variety of reasons. As a packager, I'm interested in it for facilitating reproducible builds of the package.

**Comment by ota-meshi** [comment]
We purposely do not use lock files.
https://github.com/eslint/eslint#why-doesnt-eslint-lock-dependency-versions
