### ISSUE TITLE
`vue/func-call-spacing` schema invalid

### ISSUE THREAD

**Issue by FloEdelmann** [vuejs/eslint-plugin-vue#2618]
Yesterday, tests in all PRs started to fail for the [`vue/func-call-spacing`](https://eslint.vuejs.org/rules/func-call-spacing.html) extension rule, e.g. here: https://github.com/vuejs/eslint-plugin-vue/actions/runs/11925499375/job/33237692823?pr=2611

> Error: Schema for rule func-call-spacing is invalid: default is ignored for: data1.allowNewlines

It is likely related to changes in [eslint-stylistic v2.11.0](https://github.com/eslint-stylistic/eslint-stylistic/releases/tag/v2.11.0), since with `@stylistic/eslint-plugin` v2.10.1, the tests still pass.
Relevant changes: [eslint-stylistic/eslint-stylistic@`v2.10.1...v2.11.0`#diff-b89bec3716](https://github.com/eslint-stylistic/eslint-stylistic/compare/v2.10.1...v2.11.0#diff-b89bec3716272ee4765225ade91fe19313aae05b64ce46acd13d1865d3a81ed9R45)

Unfortunately, I can't figure out how those changes influence our extension rule and tests, so @ota-meshi (or anyone else), could you please have a look at that?

**Comment by FloEdelmann** [comment]
Hmm, but their test cases also pass only one option: https://github.com/eslint-stylistic/eslint-stylistic/blob/main/packages/eslint-plugin/rules/function-call-spacing/function-call-spacing._js_.test.ts

**Comment by waynzh** [comment]
I haven't compared them in detail, but seems like `eslint-stylistic` uses `eslint-vitest-rule-tester`. I'm not sure if it has a pre-check for the schema like `eslint.RuleTester` does internally.

**Comment by FloEdelmann** [comment]
`default` inside `anyOf` is indeed actually invalid: https://ajv.js.org/guide/modifying-data.html#assigning-defaults

> With `useDefaults` option `default` keywords throws exception during schema compilation when used in:
>
> * not in `properties` or `items` subschemas
> * in schemas inside `anyOf`, `oneOf` and `not` (see [#42](https://togithub.com/ajv-validator/ajv/issues/42))
> * in `if` schema
> * in schemas generated by user-defined macro keywords

So I'll report this to eslint-stylistic. Thanks for your help investigating!

**Comment by FloEdelmann** [comment]
I've opened an issue and a PR in eslint-stylistic:

* https://github.com/eslint-stylistic/eslint-stylistic/issues/616
* https://github.com/eslint-stylistic/eslint-stylistic/pull/617

I'll leave this issue open until a fixed version of eslint-stylistic is released.
