### ISSUE TITLE
`vue/html-end-tags` rule goes out of control

### ISSUE THREAD

**Issue by mysticatea** [vuejs/eslint-plugin-vue#268]
**Tell us about your environment**

* **ESLint Version:** 4.12.1
* **eslint-plugin-vue Version:** 4.0.0-beta.0

**Please show your full configuration:**
**What did you do? Please include the actual source code causing the issue.**

See [playground](https://mysticatea.github.io/vue-eslint-demo/#eyJjb2RlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwidGVzdD5IZWxsbyE8L2Rpdj5cbjwvdGVtcGxhdGU+XG4iLCJydWxlcyI6eyJ2dWUvaHRtbC1lbmQtdGFncyI6MiwidnVlL25vLXBhcnNpbmctZXJyb3IiOjJ9fQ==).

**What did you expect to happen?**

Autofix does not change the code.

**What actually happened? Please include the actual, raw output from ESLint.**

The autofix of `vue/html-end-tags` added many `</template>` tags.
The rule should do nothing if an `eof-in-tag` error exists.

**Comment by PLQin** [comment]
@michalsnik  so, How is the problem solved?

**Comment by PLQin** [comment]
> @michalsnik so, How is the problem solved?

What should I do ?

**Comment by michalsnik** [comment]
This has been fixed one year ago, so if you use recent version of eslint-plugin-vue, this should no longer be the case. If you're having problems please create new issue with detailed description @PLQin
