### ISSUE TITLE
Appropriate webpack loader to handle <template>

### ISSUE THREAD

**Issue by lcaprini** [vuejs/eslint-plugin-vue#270]
**Tell us about your environment**

* **ESLint Version:**4.12.1
* **eslint-plugin-vue Version:**4.0.0-beta.0
* **Node Version:**7.9.0

**Please show your full configuration:**

```
{
    "extends": [
        "standard",
        "plugin:vue/base"
    ],
    "plugins": [
        "standard",
        "promise",
        "vue"
    ],
    "rules": {
        "indent": ["error", 4],
        "space-before-function-paren": ["error", "never"],
        "key-spacing": ["error", {
            "beforeColon": true,
            "afterColon": true,
            "mode": "minimum",
            "align": {
                "beforeColon": true,
                "afterColon": true,
                "on": "colon"
            }
        }],
        "semi": ["error", "always"],
        "keyword-spacing": ["error", {
            "before": true,
            "after": true
        }],
        "brace-style": ["error", "stroustrup"]
    }
}
```

**What did you do? Please include the actual source code causing the issue.**
I'm trying to use this plugin with webpack with this configuration:
```
module : {
    rules : [{
        test    : /\.(js|vue)?$/,
        exclude : /node_modules/,
        loader  : 'eslint-loader',
        enforce : 'pre',
        options : {
            fix : true
        }
    }
...
```
I'm not using `eslint-plugin-html` plugin
**What did you expect to happen?**
Webpack lints correctly JS and HTML of every `.vue`files.
**What actually happened? Please include the actual, raw output from ESLint.**
The JS is correctly linted, but I have the following error for HTML template:
```
You may need an appropriate loader to handle this file type.
| <template>
|     <div class="main">
.....
```

**Comment by mysticatea** [comment]
Thank you for this issue.

I'm not familiar with `webpack` and `eslint-loader`.
But I guess that the message shows if `webpack` couldn't parse the code in order to analyze dependencies. To make sure, do you have `vue-loader` in your config?

**Comment by lcaprini** [comment]
In another project I used vue-loader but it doesn't lint anything, perhaps I was trying to use it with eslint-plugin-vue. I'll try to use only vue-loader.
Thank you

**Comment by michalsnik** [comment]
Hey @lcaprini I set up eslint in new app using official webpack template and it works as expected. Recently I even did a fork of `webpack` template here: https://github.com/michalsnik/vue-template You can use it to create new app with correctly pre-set eslint-plugin-vue to see for yourself :) Let us know if you'll have any more questions and feel free to reopen this issue.
