### ISSUE TITLE
[meta] Discussion: remove `Ready for review` label

### ISSUE THREAD

**Issue by mysticatea** [vuejs/eslint-plugin-vue#277]
I propose that we remove `Ready for review` label.

Because contributors (except the team) can't control labels, I don't think proper if we represent issue's status by labels. I think that we can use the prefix `[WIP]` in PR subject instead if it hasn't finished.

What do you think?

/cc @michalsnik

**Comment by michalsnik** [comment]
It makes sense, I removed it. Now I think it's time to improve contribution guidelines.
