### ISSUE TITLE
Problems with identation rule

### ISSUE THREAD

**Issue by Los** [vuejs/eslint-plugin-vue#279]
**Tell us about your environment**
Since I'm new on Vue, I'm running some testing with Components to see how it works. Right now I'm testing Flickity plugin with the default code.

* **ESLint Version:** 4.12.1
* **eslint-plugin-vue Version:** 4.0.0-beta.0
* **Node Version:** 8.1.4

**Please show your full configuration:**

```
module.exports = {
	extends: [
		'plugin:vue/essential'
	],

	rules: {
		'vue/html-indent': ["error", "tab", {
			"attribute": 1,
			"closeBracket": 0,
			"ignores": []
		}],

		'indent': ["error", "tab"],
		'no-tabs': 0
	}
}
```

**What did you do? Please include the actual source code causing the issue.**
[playground](https://mysticatea.github.io/vue-eslint-demo/#eyJjb2RlIjoiPHRlbXBsYXRlPlxuXHQ8ZGl2IGlkPVwiU2xpZGVyXCI+XG5cdFx0PGZsaWNraXR5IHJlZj1cImZsaWNraXR5XCIgOm9wdGlvbnM9XCJmbGlja2l0eU9wdGlvbnNcIj5cblx0XHRcdDxkaXYgY2xhc3M9XCJjYXJvdXNlbC1jZWxsXCI+MTwvZGl2PlxuXHRcdFx0PGRpdiBjbGFzcz1cImNhcm91c2VsLWNlbGxcIj4yPC9kaXY+XG5cdFx0XHQ8ZGl2IGNsYXNzPVwiY2Fyb3VzZWwtY2VsbFwiPjM8L2Rpdj5cblx0XHRcdDxkaXYgY2xhc3M9XCJjYXJvdXNlbC1jZWxsXCI+NDwvZGl2PlxuXHRcdFx0PGRpdiBjbGFzcz1cImNhcm91c2VsLWNlbGxcIj41PC9kaXY+XG5cdFx0PC9mbGlja2l0eT5cblx0PC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0PlxuXHRpbXBvcnQgRmxpY2tpdHkgZnJvbSAndnVlLWZsaWNraXR5J1xuXG4gICAgZXhwb3J0IGRlZmF1bHQge1xuICAgICAgICBuYW1lOiAnU2xpZGVyJyxcblxuICAgICAgICBjb21wb25lbnRzOiB7XG4gICAgICAgICAgICBGbGlja2l0eVxuICAgICAgICB9LFxuXG4gICAgICAgIGRhdGEgKCkge1xuICAgICAgICAgICAgcmV0dXJuIHtcbiAgICAgICAgICAgICAgICBmbGlja2l0eU9wdGlvbnM6IHtcbiAgICAgICAgICAgICAgICAgICAgaW5pdGlhbEluZGV4OiAzXG4gICAgICAgICAgICAgICAgfVxuICAgICAgICAgICAgfVxuICAgICAgICB9LFxuXG4gICAgICAgIG1ldGhvZHM6IHtcbiAgICAgICAgICAgIG5leHQoKSB7XG4gICAgICAgICAgICAgICAgdGhpcy4kcmVmcy5mbGlja2l0eS5uZXh0KCk7XG4gICAgICAgICAgICB9LFxuXG4gICAgICAgICAgICBwcmV2aW91cygpIHtcbiAgICAgICAgICAgICAgICB0aGlzLiRyZWZzLmZsaWNraXR5LnByZXZpb3VzKCk7XG4gICAgICAgICAgICB9XG4gICAgICAgIH1cbiAgICB9XG5cbjwvc2NyaXB0PiIsInJ1bGVzIjp7InZ1ZS9hdHRyaWJ1dGUtaHlwaGVuYXRpb24iOjIsInZ1ZS9odG1sLWVuZC10YWdzIjoyLCJ2dWUvaHRtbC1pbmRlbnQiOjIsInZ1ZS9odG1sLXF1b3RlcyI6MiwidnVlL2h0bWwtc2VsZi1jbG9zaW5nIjoyLCJ2dWUvanN4LXVzZXMtdmFycyI6MiwidnVlL21heC1hdHRyaWJ1dGVzLXBlci1saW5lIjoyLCJ2dWUvbXVzdGFjaGUtaW50ZXJwb2xhdGlvbi1zcGFjaW5nIjoyLCJ2dWUvbmFtZS1wcm9wZXJ0eS1jYXNpbmciOjIsInZ1ZS9uby1hc3luYy1pbi1jb21wdXRlZC1wcm9wZXJ0aWVzIjoyLCJ2dWUvbm8tY29uZnVzaW5nLXYtZm9yLXYtaWYiOjIsInZ1ZS9uby1kdXBlLWtleXMiOjIsInZ1ZS9uby1kdXBsaWNhdGUtYXR0cmlidXRlcyI6MiwidnVlL25vLW11bHRpLXNwYWNlcyI6MiwidnVlL25vLXBhcnNpbmctZXJyb3IiOjIsInZ1ZS9uby1yZXNlcnZlZC1rZXlzIjoyLCJ2dWUvbm8tc2hhcmVkLWNvbXBvbmVudC1kYXRhIjoyLCJ2dWUvbm8tc2lkZS1lZmZlY3RzLWluLWNvbXB1dGVkLXByb3BlcnRpZXMiOjIsInZ1ZS9uby10ZW1wbGF0ZS1rZXkiOjIsInZ1ZS9uby10ZXh0YXJlYS1tdXN0YWNoZSI6MiwidnVlL25vLXVudXNlZC12YXJzIjoyLCJ2dWUvb3JkZXItaW4tY29tcG9uZW50cyI6MiwidnVlL3JlcXVpcmUtY29tcG9uZW50LWlzIjoyLCJ2dWUvcmVxdWlyZS1kZWZhdWx0LXByb3AiOjIsInZ1ZS9yZXF1aXJlLXByb3AtdHlwZXMiOjIsInZ1ZS9yZXF1aXJlLXJlbmRlci1yZXR1cm4iOjIsInZ1ZS9yZXF1aXJlLXYtZm9yLWtleSI6MiwidnVlL3JlcXVpcmUtdmFsaWQtZGVmYXVsdC1wcm9wIjoyLCJ2dWUvcmV0dXJuLWluLWNvbXB1dGVkLXByb3BlcnR5IjoyLCJ2dWUvdGhpcy1pbi10ZW1wbGF0ZSI6MiwidnVlL3YtYmluZC1zdHlsZSI6MiwidnVlL3Ytb24tc3R5bGUiOjIsInZ1ZS92YWxpZC10ZW1wbGF0ZS1yb290IjoyLCJ2dWUvdmFsaWQtdi1iaW5kIjoyLCJ2dWUvdmFsaWQtdi1jbG9hayI6MiwidnVlL3ZhbGlkLXYtZWxzZS1pZiI6MiwidnVlL3ZhbGlkLXYtZWxzZSI6MiwidnVlL3ZhbGlkLXYtZm9yIjoyLCJ2dWUvdmFsaWQtdi1odG1sIjoyLCJ2dWUvdmFsaWQtdi1pZiI6MiwidnVlL3ZhbGlkLXYtbW9kZWwiOjIsInZ1ZS92YWxpZC12LW9uIjoyLCJ2dWUvdmFsaWQtdi1vbmNlIjoyLCJ2dWUvdmFsaWQtdi1wcmUiOjIsInZ1ZS92YWxpZC12LXNob3ciOjIsInZ1ZS92YWxpZC12LXRleHQiOjJ9fQ==)

**What did you expect to happen?**
It should work as a simple page with a slider

**What actually happened? Please include the actual, raw output from ESLint.**
I've got 33 errors with identation problems

``` ✘  https://google.com/#q=vue%2Fhtml-indent  Expected "\t" character, but found " " character    
  src\components\global\Slider.vue:2:1
      <div id="Slider">
   ^

  ✘  https://google.com/#q=vue%2Fhtml-indent  Expected "\t" character, but found " " character    
  src\components\global\Slider.vue:3:1
          <flickity ref="flickity" :options="flickityOptions">
   ^

  ✘  https://google.com/#q=vue%2Fhtml-indent  Expected "\t" character, but found " " character    
  src\components\global\Slider.vue:4:1
              <div class="carousel-cell">1</div>
   ^

  ✘  https://google.com/#q=vue%2Fhtml-indent  Expected "\t" character, but found " " character    
  src\components\global\Slider.vue:5:1
              <div class="carousel-cell">2</div>
   ^

  ✘  https://google.com/#q=vue%2Fhtml-indent  Expected "\t" character, but found " " character    
  src\components\global\Slider.vue:6:1
              <div class="carousel-cell">3</div>
   ^

  ✘  https://google.com/#q=vue%2Fhtml-indent  Expected "\t" character, but found " " character    
  src\components\global\Slider.vue:7:1
              <div class="carousel-cell">4</div>
   ^

  ✘  https://google.com/#q=vue%2Fhtml-indent  Expected "\t" character, but found " " character    
  src\components\global\Slider.vue:8:1
              <div class="carousel-cell">5</div>
   ^

  ✘  https://google.com/#q=vue%2Fhtml-indent  Expected "\t" character, but found " " character    
  src\components\global\Slider.vue:9:1
          </flickity>
   ^

  ✘  https://google.com/#q=vue%2Fhtml-indent  Expected "\t" character, but found " " character    
  src\components\global\Slider.vue:10:1
      </div>
   ^

  ✘  https://google.com/#q=vue%2Fhtml-indent  Expected "\t" character, but found " " character    
  src\components\global\Slider.vue:11:1
      </template>
   ^

  ✘  http://eslint.org/docs/rules/indent      Expected indentation of 0 tabs but found 4 spaces   
  src\components\global\Slider.vue:14:5
      import Flickity from 'vue-flickity'
       ^

  ✘  http://eslint.org/docs/rules/indent      Expected indentation of 0 tabs but found 4 spaces   
  src\components\global\Slider.vue:16:5
      export default {
       ^

  ✘  http://eslint.org/docs/rules/indent      Expected indentation of 1 tab but found 8 spaces    
  src\components\global\Slider.vue:17:9
          name: 'Slider',
           ^

  ✘  http://eslint.org/docs/rules/indent      Expected indentation of 1 tab but found 8 spaces    
  src\components\global\Slider.vue:19:9
          components: {
           ^

  ✘  http://eslint.org/docs/rules/indent      Expected indentation of 1 tab but found 12 spaces   
  src\components\global\Slider.vue:20:13
              Flickity
               ^

  ✘  http://eslint.org/docs/rules/indent      Expected indentation of 0 tabs but found 8 spaces   
  src\components\global\Slider.vue:21:9
          },
           ^

  ✘  http://eslint.org/docs/rules/indent      Expected indentation of 1 tab but found 8 spaces    
  src\components\global\Slider.vue:23:9
          data () {
           ^

  ✘  http://eslint.org/docs/rules/indent      Expected indentation of 1 tab but found 12 spaces   
  src\components\global\Slider.vue:24:13
              return {
               ^

  ✘  http://eslint.org/docs/rules/indent      Expected indentation of 0 tabs but found 12 spaces  
  src\components\global\Slider.vue:24:13
              return {
               ^

  ✘  http://eslint.org/docs/rules/indent      Expected indentation of 1 tab but found 16 spaces   
  src\components\global\Slider.vue:25:17
                  flickityOptions: {
                   ^

  ✘  http://eslint.org/docs/rules/indent      Expected indentation of 1 tab but found 20 spaces   
  src\components\global\Slider.vue:26:21
                      initialIndex: 3
                       ^

  ✘  http://eslint.org/docs/rules/indent      Expected indentation of 0 tabs but found 16 spaces  
  src\components\global\Slider.vue:27:17
                  }
                   ^

  ✘  http://eslint.org/docs/rules/indent      Expected indentation of 0 tabs but found 12 spaces  
  src\components\global\Slider.vue:28:13
              }
               ^

  ✘  http://eslint.org/docs/rules/indent      Expected indentation of 0 tabs but found 8 spaces   
  src\components\global\Slider.vue:29:9
          },
           ^

  ✘  http://eslint.org/docs/rules/indent      Expected indentation of 1 tab but found 8 spaces    
  src\components\global\Slider.vue:31:9
          methods: {
           ^

  ✘  http://eslint.org/docs/rules/indent      Expected indentation of 1 tab but found 12 spaces   
  src\components\global\Slider.vue:32:13
              next() {
               ^

  ✘  http://eslint.org/docs/rules/indent      Expected indentation of 1 tab but found 16 spaces   
  src\components\global\Slider.vue:33:17
                  this.$refs.flickity.next();
                   ^

  ✘  http://eslint.org/docs/rules/indent      Expected indentation of 0 tabs but found 12 spaces  
  src\components\global\Slider.vue:34:13
              },
               ^

  ✘  http://eslint.org/docs/rules/indent      Expected indentation of 1 tab but found 12 spaces   
  src\components\global\Slider.vue:36:13
              previous() {
               ^

  ✘  http://eslint.org/docs/rules/indent      Expected indentation of 1 tab but found 16 spaces   
  src\components\global\Slider.vue:37:17
                  this.$refs.flickity.previous();
                   ^

  ✘  http://eslint.org/docs/rules/indent      Expected indentation of 0 tabs but found 12 spaces  
  src\components\global\Slider.vue:38:13
              }
               ^

  ✘  http://eslint.org/docs/rules/indent      Expected indentation of 0 tabs but found 8 spaces   
  src\components\global\Slider.vue:39:9
          }
           ^

  ✘  http://eslint.org/docs/rules/indent      Expected indentation of 0 tabs but found 4 spaces   
  src\components\global\Slider.vue:40:5
      }
       ^


✘ 33 problems (33 errors, 0 warnings)


Errors:
  23  http://eslint.org/docs/rules/indent
  10  https://google.com/#q=vue%2Fhtml-indent
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0&bustCache!./src/App.vue 16:0-48
 @ ./src/App.vue
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8000 webpack/hot/dev-server ./src/main.js```

**Comment by michalsnik** [comment]
I tested your case with the same eslint settings. It seems to be working fine. Please make sure your editor uses actual tabs, not spaces. Perhaps your `.editorconfig` file has still `space` setting set on and your configuration mentions tabs.

I see you also have problems with core `indent` rule, so it's definitely something with your editor throwing spaces on tab click, instead of tabs. Use spaces in eslint configuration or change your editor's config.

The playground uses default settings - that's why above example throws errors - default settings are of 2 spaces per indentation level.
