### ISSUE TITLE
Question: Configure `vue/order-in-components` to play nice with `sort-keys`?

### ISSUE THREAD

**Issue by Xotic750** [vuejs/eslint-plugin-vue#286]
I have [`vue/order-in-components` ](https://github.com/vuejs/eslint-plugin-vue/blob/master/docs/rules/order-in-components.md) set, but I also have [`sort-keys`](https://eslint.org/docs/rules/sort-keys) enabled for natural sort order.

I wanted to know if there is some configuration that I can use to make the two rules play nicely together? 

Currently when I sort `vue` components in order, then `sort-keys` errors about natural sort order. I know that I can litter my components with `eslint` disable comments, but I would prefer no to do that if it is at all possible?

**Comment by michalsnik** [comment]
I'm afraid we can't do anything about that. One rule does not know anything about any other, and we can't interfere with what other rules should or shouldn't lint. You have to either disable `sort-keys` per component or disable it completely.

**Comment by Xotic750** [comment]
That's a pity. Thanks for the reply.

**Comment by Xotic750** [comment]
Thanks, I am also able to do this with eslint comments but that is something that we wish to avoid.

**Comment by cantoute** [comment]
or disable the rule for *.vue

.eslintrc.js

    overrides: [
        {
            files: ['*.vue'],
            rules: {
                'sort-keys': 'off',
            },
        },

**Comment by Xotic750** [comment]
Thanks, but not the solution we were looking for as then the rule is off for standard objects.

**Comment by Emoko-Uy** [comment]
I haven't found a bettor option... most of my code is in imported from .js files where the filter works

**Comment by cantoute** [comment]
I haven't found a bettor option... most of my code is in imported from .js files where the filter works.
And as the rule sort-keys don't --fix it's not such a use full rule.

**Comment by Xotic750** [comment]
We disabled the rule a while back after, and a colleague wrote a sorter using jscodeshift.
