### ISSUE TITLE
Won't lint both .js and .vue files

### ISSUE THREAD

**Issue by dland512** [vuejs/eslint-plugin-vue#296]
**Tell us about your environment**
macOS 10.13.1

* **ESLint Version:**
4.13.1

* **eslint-plugin-vue Version:**
4.0.0-beta.3

* **Node Version:**
node v6.11.0 
npm 3.10.10

**Please show your full configuration:**

```
{
    "env": {
        "browser": true,
        "commonjs": true,
        "es6": true
    },
    "plugins": [
        "vue"
    ],
    "extends": [
        "eslint:recommended",
        "plugin:vue/strongly-recommended"
    ],
    "parserOptions": {
        "parser": "babel-eslint",
        "ecmaFeatures": {
            "experimentalObjectRestSpread": true
        },
        "sourceType": "module"
    }
}
```

**What did you do? Please include the actual source code causing the issue.**
I'm running this command
`./node_modules/.bin/eslint .`

**What did you expect to happen?**
I expect that running `eslint .` will lint both .js and .vue files recursively down from the currently directory.

**What actually happened? Please include the actual, raw output from ESLint.**
Running

`./node_modules/.bin/eslint .`

only lints the .js files. Why is that? The only way I can get it to lint the .vue files is by running

`./node_modules/.bin/eslint ./**/*.vue`

**Comment by michalsnik** [comment]
Hey @dland512,

Please try:
```
./node_modules/.bin/eslint . --ext .vue,.js
```

**Comment by dland512** [comment]
Yes, thank you!

**Comment by michalsnik** [comment]
I'm glad I could help :)
