### ISSUE TITLE
Make order-in-components rule fixable

### ISSUE THREAD

**Issue by ifraixedes** [vuejs/eslint-plugin-vue#299]
**Tell us about your environment**

* **ESLint Version:** 3.19.0
* **eslint-plugin-vue Version:** 4.0.0-beta.3
* **Node Version:** 9.3.0

**Question**

I'm wondering if the rule [order-in-components](https://github.com/vuejs/eslint-plugin-vue/blob/master/docs/rules/order-in-components.md) could not be auto fixable by `--fix`

**Comment by michalsnik** [comment]
Hey @ifraixedes 👋  It probably is. Maybe not that easy but should be doable.
Though we have slightly different priorities now, so not every rule have been written with `fix` functionality unfortunately. If you'd like to help us with this one, feel free :) Pull Requests are always welcome 🙌

**Comment by ifraixedes** [comment]
@michalsnik I totally understand that isn't a priority and it was never my intention, in case that my initial comment looked like that.

My question had the goal to poll if it could or not be doable rather than requesting this feature in high priority; although I could imagine that the rule could be auto fixable, I've never developed anything for ESLint, so I wanted to confirm that the rule could be auto fixable.

I don't currently have time now for this, but having the issue labeled as accepted proposition and enhancement is a way to let to the others, not just me 🙂 , that doing so, would be accepted without having to spend time doing a PR without a previous confirmation that it's a nice feature to have.

Cheers!
