### ISSUE TITLE
Add `Vue.extend` as valid component rule trigger

### ISSUE THREAD

**Issue by blake-newman** [vuejs/eslint-plugin-vue#319]
> All component-related rules are being applied to code that passes any of the following checks:
> - Vue.component() expression
> - export default {} in .vue or .jsx file

**Suggestion**

Add `Vue.extend` to the triggers for for applying the component related rules. It is a commonly used api fo creating components in a raw formats without SFC.

**Comment by michalsnik** [comment]
Good idea @blake-newman On it :)

**Comment by blake-newman** [comment]
Nice, cheers. Was doing it myself you beat me to it.
