### ISSUE TITLE
Plugin does not properly handle disabling max-lines rule.

### ISSUE THREAD

**Issue by bozzaj** [vuejs/eslint-plugin-vue#339]
* **ESLint Version: 4.14.0**
* **eslint-plugin-vue Version: 4.1.0**
* **Node Version: 8.9.1**

**Please show your full configuration:**

```
rules: {
    "max-lines": ["error", {
        "max": 300,
        "skipBlankLines": true,
        "skipComments": true
    }],
}
```

**What did you do? Please include the actual source code causing the issue.**

See [Vue eslint online demo](https://mysticatea.github.io/vue-eslint-demo/#eJztWc1unDAQfhXEpW207ko9rlaVqkp9gfaYi4EB3Bibju3Nkijv3rEBYyCV+gAcsmG+sT1/34z35zUvdQX5JT8/ZGCkUJZVwvBCQtbxOyMATPZwflRXC10vuYWvjyrLrpW4hYfxMTsfwiEcwiEcwiEcwiEcwiEcwiEcwiEcQhSu5yp8cL6ek4/TV1Oi6C09wb3XaLMKau6kzV79FsU7uGQfvvX9h9Oj8kgHttWVuYz6LNPquxTl08dPM5Bl53NW6cxov1So5vOIv/l/9PLmHZiM5qccnQSTX17zUitj0ZVWIzOuB8wvX065UBUoGx7jVwJBUpqV3ACroJQcuRW0PSokN4bRn2hUxHTXcwSmoGEvgHrBVbVbqoyWkIr2nSWWKxu2C2880VjUkiE0cJ/BCgrXNFNIQZZggd34glDEjGNjVsAYSAddAbjWPMGQAlQCKmfIyIxSie3AypaSU1rA8ay1sueWNGoFRuG+CRnuFjkrNGWGK2/JrjUGOjEjNZfStqhd00bIqXJzYiN1weUGFEqRs+9VVagbl6IaM9tHFEl2tJg9t8KC6XkZU9CJO1QsQEQHqrPlRTxOwTMzQ1doOSO6+E1xSRmX6NLyqEUYnYIFID+m02fMgKw3AdECNL62yJeSUWMYVkCtiZEL2UnhiO/1IlCgQNWrWEctKTz7Fx0Cp+oWMoEMr4HVQlEQwwYl3vOUp045Q+dKXsAS8AQSLxeIQgIiIZiS96MpyhM5xUxL46KltAYQ4Y8TFM0gQI4I7WTCKD6aHGtnhx70GN/NwZn4h6JwxNx26FtQi4de29pOMghlm/oioslYiNgfpy1s1oV6lFIbmkNR89vcfVhmidOjfrxEfwyjmrCY76B31PFlSzEpappey+BsqH96uJ+YrEdN+3378ZVlyic3AzWCUGEgOV/aabFIfB/nSO38ZnZjRBN6FXWqX0+BBZwmwRJJqg8sSik74Z6i3hQgakwVCAbwRk5uLRmaKwT7ILQC/8Utt3y1QFTAoK6JKeY/wp1vJG9ojd8tWeJsTn+q3NLVwxorqtxkMLi26GaOLl6LvXK6/4KfO6UHA4n3+5CYSpYRrEO1045FTIOLmtAY/7Dqz3ove8sxYZLQijmBUXFjBXUJM3aQKegpu4bGxpzzj1rbjW48aQdSW/GnHUrTBFKqpvgOrBO2zZjv2x34zoGdplt0hybjY4HKveUe9xgNtOcd6AlI4Nv8VuSneIHkncmvwQ/FfLx2TjnQmwGNE+h/3Pimqh/+Fvruf+g45eEuoJhzuqgQIH/7C5XiQT0=)

**What did you expect to happen?**
Expected the max-lines rule to be disabled for the document.

See [Eslint demo](https://eslint.org/demo/#eyJ0ZXh0IjoiLyogZXNsaW50LWRpc2FibGUgbWF4LWxpbmVzICovXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbiIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6OCwic291cmNlVHlwZSI6Im1vZHVsZSIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6eyJtYXgtbGluZXMiOjJ9LCJlbnYiOnt9fX0=)

I can't use the same  document as the Eslint demo will fail on a Vue document that starts with <template>, but in this case, we're looking at just the fact that the document is greater than 300 lines.

**What actually happened? Please include the actual, raw output from ESLint.**
`1:1     File must be at most 300 lines long. It's 315 lines long. (max-lines)`

**Comment by mysticatea** [comment]
Thank you for this issue.

I understand your intention: currently, we have no way to disable errors on the outside of `<template>` and `<script>`. And the error of `max-lines` is one of [vue-eslint-parser's known limitations](https://github.com/mysticatea/vue-eslint-parser#%EF%B8%8F-known-limitations).

I don't think JS style comments make sense on the outside of `<script>` element.
And currently, we ignore HTML comments on the outside of `<template>` element, too. (#338 is a bit related)

I'm not sure the best solution... :thinking:

**Comment by bozzaj** [comment]
Ah, I missed the known limitations. That makes sense unfortunately.

As for comments outside of `<template>` and `<script>`, that kind of makes sense as well, Technically, neither option (JS style or HTML style) is a perfect solution, though I expected the HTML style to work in this case, which was why I originally filed the issue under comment-directive. 

eslint-plugin-html skipped `<template>` so I was able to disable max-lines at the beginning of the script since that was technically considered the first line.

Looking at Vue docs under Single File Components. See [this link](https://vuejs.org/v2/guide/single-file-components.html#What-About-Separation-of-Concerns).

If you look at the example code, there's an HTML comment before the `<template>` tag. If you use the "following by example" decision, this would lead me to believe that comment-directive should be able to take care of the issue.

Hope you can come to some sort of decent resolution! eslint-plugin-vue is a major plus in building consistent code! In the meantime, I can use "warn" for max-lines and deal with them accordingly.

**Comment by michalsnik** [comment]
I remember there was a proposal for this kind of rule that would support setting max lines for each block of code separately, as in terms of single Vue components rule for checking lines in entire component might not be really relevant. See #202 
But in terms of disabling rule for entire file I'm not the is a proper solution atm. For now I guess we'll have to live with some limitations. I'll rather continue this discussion in the proposal #202 as solely `max-lines` rule is not very useful in Vue components as is.
