### ISSUE TITLE
Missing script-indent rule when installed

### ISSUE THREAD

**Issue by donnysim** [vuejs/eslint-plugin-vue#342]
* **ESLint Version:** 4.15.0
* **eslint-plugin-vue Version:** 4.1.0
* **Node Version:** 8.7.0

I can see that there is a `script-indent.js` file in rules folder on the git, but after installing the package with yarn, the file is missing and it complains that rule `script-indent` could not be found.

**Comment by michalsnik** [comment]
Hey @donnysim It has just been released :) Enjoy 4.2.0!
