### ISSUE TITLE
Adjacent JSX elements must be wrapped in an enclosing tag

### ISSUE THREAD

**Issue by zouhangwithsweet** [vuejs/eslint-plugin-vue#354]
"eslint": "^4.15.0",
"eslint-plugin-vue": "^4.0.0",
node: v8.9.3
![image](https://user-images.githubusercontent.com/21095710/35208067-58d7b6fe-ff81-11e7-80fd-29a064432db3.png)
i never use JSX. it is just a .vue file.
![image](https://user-images.githubusercontent.com/21095710/35208091-726a4cda-ff81-11e7-9d0f-0f43c487f275.png)
how to solve this problem?  ths

**Comment by mysticatea** [comment]
Would you answer issue template?

**Comment by zouhangwithsweet** [comment]
sorry sir. this problem is just like the #188 ,but i do not how to solve this. There is no problem in old vue project,but in the new vue project.

**Comment by mysticatea** [comment]
Would you answer issue template? Especially, I think there is the cause in your `.eslintrc.*` file.

**Comment by zouhangwithsweet** [comment]
thank you so much,sir.  i made over my `.eslintrc.js` file. it works now. thank you so much.

**Comment by riccardoravaro** [comment]
I have solved this by adding .eslintrc.js in the root of the project :

`module.exports = {
    "env": {
        "es6": true,
        "node": true
    },
    "extends": "eslint:recommended",
    "parserOptions": {
        "sourceType": "module"
    },
    "rules": {
        "indent": [
            "error",
            "tab"
        ],
        "linebreak-style": [
            "error",
            "unix"
        ],
        "quotes": [
            "error",
            "double"
        ],
        "semi": [
            "error",
            "never"
        ]
    }
};`

**Comment by ZhenZY** [comment]
`// package.json
"dependencies": {
    "vue": "^2.6.8"
  },
"devDependencies": {
    "babel-eslint": "^10.0.1"
  }


// .eslintrc.js
// https://eslint.org/docs/user-guide/configuring

module.exports = {
  root: true,
  parserOptions: {
    parser: 'babel-eslint',
  },
  env: {
    browser: true,
  },
  extends: 'elemefe',
  // required to lint *.vue files
  plugins: [
    'html'
  ],
  // add your custom rules here
  rules: {
    'eqeqeq': 0,
    'no-undef': 1,
    'no-new': 0,
    // allow debugger during development
    'no-debugger': process.env.NODE_ENV === 'production' ? 2 : 0
  }
}
`
`Parsing error: Adjacent JSX elements must be wrapped in an enclosing tag`
How can I solve this problem?
