### ISSUE TITLE
How to set vue-eslint-parser when using yaml config?

### ISSUE THREAD

**Issue by rightaway** [vuejs/eslint-plugin-vue#357]
My ~/.eslintrc is a yaml file and I'd like to set the parser, but when I do `parser: vue-eslint-parser`, I get an error. In https://github.com/vuejs/eslint-plugin-vue/blob/master/lib/configs/base.js it's `parser: require.resolve('vue-eslint-parser')`, how can I do that same `require.resolve` in the yaml file?

**Comment by LinusBorg** [comment]
You can't use require.resolve in a yaml file - yaml is static, it can't run javascript code inside it.

What error do you receive? you likely would have to install eslint-plugin-vue globally and then give the absolute path to this package in the config.

**Comment by rightaway** [comment]
Setting an absolute path worked thank you.
