### ISSUE TITLE
Allow no quotes in html-quotes

### ISSUE THREAD

**Issue by rightaway** [vuejs/eslint-plugin-vue#358]
Could we have an option to enforce no quotes in html quotes? And in cases where quotes are necessary due to the attribute value having a space, then it should be possible to set whether you want single or double quotes.

**Comment by mysticatea** [comment]
Thank you for this issue.

Currently, we don't have such option. It would need a concrete proposal to add.

Note: unquoted attribute values can't have some characters.

> This error occurs if the parser encounters a U+0022 ("), U+0027 ('), U+003C (<), U+003D (=), or U+0060 (`) code point in an unquoted attribute value.
> https://html.spec.whatwg.org/multipage/parsing.html#parse-error-unexpected-character-in-unquoted-attribute-value

**Comment by rightaway** [comment]
The way I use attributes is to omit the quote in all cases except when it is necessary (the cases you gave where it contains one of those unallowed characters). The rule I'm suggesting would check that all attributes are unquoted, but if it encounters quotes, it checks that the quotes exist because within the attribute is one of those unallowed characters.

**Comment by michalsnik** [comment]
Due to low interest in this proposal I'm going to close this issue. Thanks for raising an idea though!
