### ISSUE TITLE
eslint --fix broken <script> target

### ISSUE THREAD

**Issue by moersing** [vuejs/eslint-plugin-vue#367]
**Tell us about your environment**

* **ESLint Version:** 4.10.0
* **eslint-plugin-vue Version:** 4.2.2
* **Node Version:** 8.7.0

**Please show your full configuration:**

```
{
  "extends": [
    "plugin:vue/essential",
    "standard"
  ],
  "plugins": [
    "vue"
  ],
  "parserOptions": {
    "parser": "babel-eslint",
    "ecmaVersion": 2017,
    "sourceType": "module"
  },
  "rules": {
    "indent": "off",
    "vue/script-indent": [
      "error",
      2,
      {
        "baseIndent": 1
      }
    ]
  }
}




```

**What did you do? Please include the actual source code causing the issue.**

```vue
<script >export default {
    data () {
      return {
        msg: 'hello vue',
        logo: require('images/logo.png')
      }
    },
    methods: {
      printDemo () {
        console.log(this.msg)
      }
    }
  }
</script >

```

**What did you expect to happen?**
```
<script >
export default {
    data () {
      return {
        msg: 'hello vue',
        logo: require('images/logo.png')
      }
    },
    methods: {
      printDemo () {
        console.log(this.msg)
      }
    }
  }
</script >
```
**What actually happened? Please include the actual, raw output from ESLint.**
```
/// Here was missing......
  export default {
    data () {
      return {
        msg: 'hello vue',
        logo: require('images/logo.png')
      }
    },
    methods: {
      printDemo () {
        console.log(this.msg)
      }
    }
  }
</script >
```
I want use `eslint --fix` to format my code , But I found an error , Just the `script` was missing.

**Comment by mysticatea** [comment]
Thank you for the report.

I confirmed it on [online demo](https://mysticatea.github.io/vue-eslint-demo/#eJw1jUEKwjAURK8is44IXYYilIIX0AuEZBYBScP/aVFL726CcTdvBt7s8EsgLEb1EnO5bk5Obrx0goGsTyrsjm1lr88xBaYCOxwGv3yPn2oZ/vh45ybV7DyrgyGWRXrZDqcUbvHFMLdzg+xEKXWjZiFxfAFldDPz).

I had forgotten the possibility that there is no linebreak after the `<script>` tag.
