### ISSUE TITLE
How to find eslint-plugin-vue behind the scene even if I didn't install it?

### ISSUE THREAD

**Issue by Jiaaa1014** [vuejs/eslint-plugin-vue#368]
**Tell us about your environment**

* **ESLint Version: none**
* **eslint-plugin-vue Version: none**
* **Node Version: 9.4.0**

package.json here
```js
{
  "name": "starbase-router",
  "description": "A Vue.js project",
  "version": "1.0.0",
  "author": "Jiaaa1014 <linao264590000@gmail.com>",
  "license": "MIT",
  "private": true,
  "scripts": {
    "dev": "cross-env NODE_ENV=development webpack-dev-server --open --hot",
    "build": "cross-env NODE_ENV=production webpack --progress --hide-modules"
  },
  "dependencies": {
    "vue": "^2.5.11"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8"
  ],
  "devDependencies": {
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.2",
    "babel-preset-env": "^1.6.0",
    "babel-preset-stage-3": "^6.24.1",
    "cross-env": "^5.0.5",
    "css-loader": "^0.28.7",
    "file-loader": "^1.1.4",
    "vue-loader": "^13.7.0",
    "vue-router": "^3.0.1",
    "vue-template-compiler": "^2.4.4",
    "webpack": "^3.6.0",
    "webpack-dev-server": "^2.9.1"
  }
}
```

**What did you do? Please include the actual source code causing the issue.**
I know how to use `eslint` or other related plugin as I played React. Now I've been learning `Vue` for these days. As init I do `vue init webpack-simple my-project` and get default configs, there's no `eslint` keyword at `package.json` neither at `node_module`. But it works as I do something syntax(or other) wrong.

Is there anyone know where it lives behind the scene?

**What did you expect to happen?**
Find `eslint`

**Comment by michalsnik** [comment]
Templates for vue-cli@2 doesn’t hide anything. If it’s not there then it’s probably your editor linting your code somehow. Try to do a mistake and run: ‘./node_modules/.bin/eslint . —ext .js,.vue’if you’ll get message that there is no eslint it’ll confirm my assumptions

**Comment by HerringtonDarkholme** [comment]
>  But it works as I do something syntax(or other) wrong.

What do you mean by `it works`? Do you mean editor gives you warning?

**Comment by Jiaaa1014** [comment]
@HerringtonDarkholme 
![screenshot here](https://github.com/Jiaaa1014/Debugging/blob/master/eslint.png)

---
@michalsnik
```bash 
npm ERR! missing script: ./node_modules/.bin/eslint

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Jiaaa\AppData\Roaming\npm-cache\_logs\2018-01-30T09_12_23_660Z-debug.log
```
you're right, I guess there's a extension `Vetur` at VScode doing so.

**Comment by HerringtonDarkholme** [comment]
Hi @Jiaaa1014 
You can read more vetur's configuration here. 

https://vuejs.github.io/vetur/linting-error.html

**Comment by Jiaaa1014** [comment]
THANK U SO MUCH @HerringtonDarkholme Have a nice day!
