### ISSUE TITLE
Prettier uses different indentation rule

### ISSUE THREAD

**Issue by Jurgyte** [vuejs/eslint-plugin-vue#369]
My configuration file:
```{
  "extends": [
    "vue",
    "airbnb",
    "plugin:vue/recommended",
    "standard",
    "prettier"
  ],
  "plugins": [
    "vue",
    "standard",
    "prettier"
  ],
  "rules": {
    "indent": "off",
    "vue/script-indent": [
      "error",
      2,
      {
        "baseIndent": 1
      }
    ],
    "prettier/prettier": [
      "error",
      {
        "singleQuote": true,
        "trailingComma": "es5"
      }
    ],
  },
  "settings": {
    "html/indent": "+2"
  },
  "env": {
    "es6": true,
  }
}
```

And this is a result I get:
```
error  Delete `··`                       prettier/prettier
```

Template:
```
<template>
  <div></div>
</template>

<script>
  import smth from 'Smth';

  export default {
    props: {
      show: {
        required: true,
      },
    },
    mounted() { ... },
  };
</script>
```

None other plugins are failing, or anything.

**Comment by mysticatea** [comment]
Would you disable `vue/script-indent` rule as similar to `"indent": "off"`?

**Comment by Jurgyte** [comment]
So there is no way to use `vue/script-indent` at the moment?

**Comment by mysticatea** [comment]
Doesn't prettier format indentation? As far as I know, prettier is a formatter.

**Comment by mysticatea** [comment]
Both `vue/script-indent` and prettier change the indentation of your code. Both are formatter. You can't use both together but you can choose which formatter you use.

**Comment by Jurgyte** [comment]
```
    "vue/script-indent": [
      "error",
      2,
      {
        "baseIndent": 1
      }
    ],
```
If I leave this part only. It does not work with prettier. Prettier does not pick up `baseIndent`.

**Comment by mysticatea** [comment]
`baseIndent` is the option of `vue/script-indent`, not `prettier`'s.

**Comment by lerit** [comment]
i face the same problem.
i think we should not use prettier and eslint-plugin-vue together,
but i do not konw how to disable prettier for vue file.

**Comment by mysticatea** [comment]
Closing since this looks a matter in prettier.
