### ISSUE TITLE
Linting on the fly with Atom issues

### ISSUE THREAD

**Issue by miljan-aleksic** [vuejs/eslint-plugin-vue#371]
Hei guys is [this](https://github.com/vuejs/vue-cli/issues/749) issue related with `eslint-plugin-vue`? 

If it's not, any clue where to look next?

**Comment by mysticatea** [comment]
Do you configure `linter-eslint` to lint `.vue` files?

**Comment by miljan-aleksic** [comment]
I have tested it with the current `vue-cli` alpha version which yes, [does it](https://github.com/vuejs/vue-cli/blob/next/packages/%40vue/cli-plugin-eslint/eslintOptions.js#L2).

**Comment by mysticatea** [comment]
I'm not familiar with `vue-cli`, but I guess that it's not config of Atom's `linter-eslint`.

**Comment by miljan-aleksic** [comment]
This is an old issue I run into trying to lint vue files that I just remembered now as trying out vue-cli. vue-cli just setups the project with eslint configuration for vue file as well. If that were wrong, there would be no lint on those files, and you can see on the video that's not the case.

**Comment by mysticatea** [comment]
That template looks to set up ESLint CLI.
But it doesn't look to set up editor plugins. What kind of files that Editor plugins check is the configuration of editor plugins.

**Comment by miljan-aleksic** [comment]
I never heard of that configuration, only about .eslintrc, which Atom `linter-eslint` plugin expect. If missing, its probably trying to lint the file as raw html and thus all the issues.

We may conclude that vue-cli project, not having eslintrc, are not mean to be linted on the fly, at least at this moment. Any other conclusion?

**Comment by mysticatea** [comment]
I'm not familiar with Atom, but I know this at least.

> you need to turn "Lint HTML Files" option in linter-eslint atom package settings. 
> https://github.com/vuejs/eslint-plugin-vue/issues/105#issuecomment-317256351

Ah, indeed, `.eslintrc.*` file is needed as well.

**Comment by miljan-aleksic** [comment]
Thanks, @mysticatea for your time and interest :)

**Comment by derhedwig** [comment]
I had similiar problems with "Lint HTML Files" turned on in Atom. But then I found this:

From https://github.com/BenoitZugmeyer/eslint-plugin-html:
> Initially, eslint-plugin-vue was using eslint-plugin-html to lint code inside script tags. Since v3, eslint-plugin-vue is using its own parser, so it is incompatible with eslint-plugin-html. You should remove eslint-plugin-html from your dependencies if you still have this.

So, one shouldn't use "Lint HTML Files". But how do we make Atom lint our vue files?

From https://alligator.io/vuejs/vue-eslint-plugin/:
> Go into Settings -> Packages -> linter-eslint and add text.html.vue to the “List of scopes to run eslint on” option. You may need to restart Atom.

**Comment by mysticatea** [comment]
@derhedwig I'm not familiar with Atom. Would you ask the question on Atom's repo?

**Comment by miljan-aleksic** [comment]
Thanks @derhedwig for your comments. That's not the case in this particular situation but may help somebody else.
