### ISSUE TITLE
Using with xo instead of eslint

### ISSUE THREAD

**Issue by OmgImAlexis** [vuejs/eslint-plugin-vue#382]
I'm trying to get this working with [xo](https://github.com/sindresorhus/xo) which is a wrapper around eslint.
If I remove the vue plugin everything works fine.

**Tell us about your environment**

* **XO Version:** 0.18.2
* **ESLint Version:** 4.9.0
* **eslint-plugin-vue Version:** 4.2.2
* **Node Version:** v9.5.0

**Please show your full configuration:**

```
{
  "xo": {
    "extends": [
      "plugin:vue/base"
    ],
    "settings": {
      "import/core-modules": [
        "vue"
      ]
    },
    "semicolon": true,
    "space": "2",
    "overrides": [{
      "parserOptions": {
        "parser": "babel-eslint",
        "ecmaVersion": 2017,
        "sourceType": "module"
      }
    }]
  }
}
```

**What did you do? Please include the actual source code causing the issue.**

```js
return new Promise(async (resolve, reject) => {
  try {
    const res = await this.$http.post('/', {
      body: {
        ...creds
      }
    });
    localStorage.setItem('token', res.body.token);
    commit(LOGIN_SUCCESS);
    resolve();
  } catch (err) {
    reject(err);
  }
});
```

**What did you expect to happen?**
```
➜  slim git:(master) ✗ xo store/index.js

  store/index.js:15:25
  ✖  15:25  localStorage is not defined.  no-undef
  ✖  42:11  localStorage is not defined.  no-undef
  ✖  51:7   localStorage is not defined.  no-undef

  3 errors
```

**What actually happened? Please include the actual, raw output from ESLint.**
```
➜  slim git:(master) ✗ xo store/index.js

  store/index.js:35:50
  ✖  35:50  Parsing error: Unexpected token =>  

  1 error
```

**Comment by mysticatea** [comment]
ES2017 doesn't include spread property syntax. You have to use ecmaVersion 2018.

**Comment by OmgImAlexis** [comment]
Should it really be throwing the error at the arrow function though? Isn't that supported in 2017?

Also even with it changed to 2018 I still get the same issue.

**Comment by mysticatea** [comment]
Ah, I missed the error message.

Hm, `overrides[0].parserOptions` doesn't look to affect. I don't know xo, but does xo support it?

**Comment by OmgImAlexis** [comment]
From what I can tell xo just passes the option in that down to eslint.

Is there anything I can test to see what is or isn't working?

**Comment by OmgImAlexis** [comment]
For anyone finding this you need to add the `files` property. This works perfectly. Thank you.

```
    "overrides": [
      {
        "files": [
          "**/*"
        ],
        "parserOptions": {
          "parser": "babel-eslint",
          "ecmaVersion": 2018,
          "sourceType": "module"
        }
      }
```
