### ISSUE TITLE
Unexpected end of expression on  close of JS multi-line comment within template

### ISSUE THREAD

**Issue by mhldtna** [vuejs/eslint-plugin-vue#398]
(Sigh, I noticed in the "Preview" view that the code that I copy/pasted into the code sections is all messed up.  I have attached screen shots below so you can see what I have.)

Environment:
   eslint@4.18.0
   eslint-plugin-vue@4.2.2
   eslint-config-airbnb-base@12.1.0
   eslint-loader@1.9.0
   eslint-plugin-import@2.8.0
   node v6.11.3
   VSCode version 1.20.0

.eslintrc.json:

```json
{
    "root": true,
    "extends": [
         "airbnb-base",
         "plugin:vue/recommended"
    ],
    "rules": {
        "no-undef": 1,
        "no-unused-vars": 1,
        "vue/no-unused-vars": "error",
        "linebreak-style": ["error", "windows"],
        "eol-last": 0,
        "no-underscore-dangle": 0,
        "quotes": 0,
        "no-restricted-syntax": 0,
        "no-multi-spaces": 0,
        "no-trailing-spaces": 0,
        "no-plusplus": 0,
        "prefer-destructuring": 0,
        "padded-blocks": 0
    }
}
```

I have the following template in a .vue component.  Notice the JS-style comment in the middle.

```vue
<template>
  <div>
    <b-table 
      small
      striped
      hover
      foot-clone
      :items="solutions" 
      :fields="columns"
      :filter="filter"
      @row-clicked="rowClicked">
      <template
        slot="top-row"
        slot-scope="{columns, fields}">
        {{ /* columns and fields are properties passed in from the table to the template.
            columns is the number of columns.
            fields is an array of column names
        */ }}
        <td
          v-for="(column) of fields"
          :key="column.key">
          <ColumnFilter :column="column" />
        </td>
      </template>
    </b-table>
  </div>
</template>
```

![eslintrc](https://user-images.githubusercontent.com/32778184/36455799-aeef8594-1656-11e8-81a3-c2e38d0be5aa.jpg)
![eslint parsing error](https://user-images.githubusercontent.com/32778184/36455801-af1845f6-1656-11e8-8319-f36c294e31a6.jpg)
![eslintrc](https://user-images.githubusercontent.com/32778184/36455823-c59e4bea-1656-11e8-9419-fcc9a2212ae8.jpg)
![eslint parsing error](https://user-images.githubusercontent.com/32778184/36455824-c5c1e000-1656-11e8-9ecb-9be4d92a1888.jpg)

I am getting the following error from eslint, referencing the last line of the comment.

`Parsing error: Unexpected end of expression. (vue/no-parsing-error) (25,12)`

The squiqqly error indicator is under the first "}" character of the closing "}}".

I believe this is not an error.

**Comment by mhldtna** [comment]
Looks like the .jpgs that I attached got inserted directly into my issue!  I've attached them again.

![eslintrc](https://user-images.githubusercontent.com/32778184/36455848-e87da3c2-1656-11e8-8be9-bc68b29d37cb.jpg)
![eslint parsing error](https://user-images.githubusercontent.com/32778184/36455849-e8ae2560-1656-11e8-88bb-50adde124d09.jpg)

**Comment by mysticatea** [comment]
Thank you for this report. I confirmed it: https://jsfiddle.net/zuyjom9m/18/ doesn't output error in devtool's console.

This is a bug in [vue-eslint-parser](https://github.com/mysticatea/vue-eslint-parser).
