### ISSUE TITLE
issues with attribute-hyphenation

### ISSUE THREAD

**Issue by lifeiscontent** [vuejs/eslint-plugin-vue#408]
within the context of SVG elements such as `filter` the attributes `filterUnits` and `stdDeviation` are valid attribute names.

**Comment by michalsnik** [comment]
Thanks for posting this. Indeed it looks like we need to add whitelist with attributes like those you mentioned, as well as `viewBox` and probably some others.

**Comment by michalsnik** [comment]
I just checked the rule, and current implementation already handles this case very well. It doesn't check any properties on elements that are in scope of SVG. But.. The template in which those elements are present must have an `svg` wrapper for the parser to set proper namespaces on children nodes. In other cases you might just need to disable the rule on per-file basis, as this is clearly an edge case - SVG content with no `svg` wrapper. I we were to overcome this inconvinience we had to whitelist bunch of different SVG properties, which might sometimes become regular props' names on other elements.
