### ISSUE TITLE
vue/require-default-prop doesn't recognized quoted property name.

### ISSUE THREAD

**Issue by nchutchind** [vuejs/eslint-plugin-vue#416]
**Tell us about your environment**

* **ESLint Version:** 4.18.1
* **eslint-plugin-vue Version:**   4.3.0
* **Node Version:** 8.9.4

**Please show your full configuration:**

```
"plugin:vue/recommended"



```

**What did you do? Please include the actual source code causing the issue.**

```vue

props: {
        isWorking: {
            type     : Boolean,
            required : false,
            'default': true,
        }
    },



```

**What did you expect to happen?**
No error.

**What actually happened? Please include the actual, raw output from ESLint.**
When not quoted, I get an eslint error: `Unquoted reserved word 'default' used as key. (quote-props)`.
When quoted, I get `Prop 'isWorking' requires default value to be set. (vue/require-default-prop)`.

**Comment by michalsnik** [comment]
Thanks for posting this issue @nchutchind We can handle this case indeed. We did it already in several places :)
