### ISSUE TITLE
A strict script-indent compatible with indent

### ISSUE THREAD

**Issue by mitar** [vuejs/eslint-plugin-vue#418]
It seems that script-indent has much less configuration options than indent? I like the strict indent nature.

It seems you cannot use vue/script-indent just for `<script>` tags, while keeping indent for all other code?

**Comment by LukeShu** [comment]
> It seems you cannot use vue/script-indent just for <script> tags, while keeping indent for all other code?

Is this what you are looking for?  Turn "indent" off only for .vue files?

```
module.exports = {
	rules: {
		"indent": ["warn", "tab"],
	},
	overrides: [
		{
			files: ["*.vue"],
			rules: {
				"indent": "off",
				"vue/script-indent": ["warn", "tab"],
			}
		}
	]
};
```

**Comment by mitar** [comment]
Interesting. I didn't know this. Thanks!

I think this resolved this issue. There will still be an issue that code inside `<script>` tags will have less strict indent nature. :-(

**Comment by michalsnik** [comment]
Cool! If you have proposition regarding what we could add in this rule just post another issue and we can discuss it there @mitar :)
