### ISSUE TITLE
Rule proposal: `style-indent`

### ISSUE THREAD

**Issue by godforger** [vuejs/eslint-plugin-vue#451]
Please, add style-indent rule for <style>

**Comment by enocmontiel** [comment]
+1

**Comment by woolson** [comment]
+1

**Comment by michalsnik** [comment]
Thanks for the proposal, but I'm afraid this is a no-go.

We'd have to additionally parse `<style>` tag and figure out idendation based on custom AST. We went already far with linting vue template using eslint, whereas this tool is clearly meant to lint javascript and jsx.

For linting styles there is a great `stylelint`. Although it doesn't support changing base indentation it's still the preferable way of linting styles also in `.vue` files and we're not going to replace it's responsibilities in here unfortunately.

Thanks for understanding!

**Comment by pedzed** [comment]
I had this in my `.eslintrc.js` rules:
```js
"indent": ["error", 4],
"vue/html-indent": ["error", 4],
"vue/script-indent": ["error", 4],
```
I thought: my style indentation is probably not linting because I should add this:
```js
"vue/style-indent": ["error", 4],
```
But clearly now, that isn't a thing. :disappointed:

**Comment by mpw0311** [comment]
me too!

**Comment by mpw0311** [comment]
me too!

**Comment by zeid0ne** [comment]
you can use stylelint with the following config as a fallback :

```
{
  "extends": [
    "stylelint-config-standard-scss", 
    "stylelint-config-recommended-vue"
  ],
  "plugins": [
    "@stylistic/stylelint-plugin"
  ],
  "rules": {
    "@stylistic/indentation": [2, { "baseIndentLevel": 0 }]
  }
}
```

**Comment by Mourdraug** [comment]
> Thanks for the proposal, but I'm afraid this is a no-go.
> 
> We'd have to additionally parse `<style>` tag and figure out idendation based on custom AST. We went already far with linting vue template using eslint, whereas this tool is clearly meant to lint javascript and jsx.

Could that be reconsidered now that eslint officially supports css? https://eslint.org/blog/2025/02/eslint-css-support/
