### ISSUE TITLE
can't lint vue src imports files

### ISSUE THREAD

**Issue by EnjoyChan** [vuejs/eslint-plugin-vue#470]
"eslint": "^3.19.0"
"eslint-plugin-vue": "^4.5.0
----------------------------------
I found that eslint does't lint files that are imported by src in * vue file like this:
```
<template src="./template.html"></template>
<style src="./style.css"></style>
<script src="./script.js"></script>
```
none of files above are linted

**Comment by EnjoyChan** [comment]
just need to config the vue-loader options with eslint, by default use the babel-loader only to parse script

**Comment by quanglam2807** [comment]
I face the same issue. Would you mind sharing the solution in more details?
