### ISSUE TITLE
Lint .html templates

### ISSUE THREAD

**Issue by viktor-ku** [vuejs/eslint-plugin-vue#490]
Hi,

How can I help to make this plugin support `.html` files that I am using for templates. That is possible with [vue-template-loader](https://github.com/ktsn/vue-template-loader).

Very similar issue #489 was created recently and maybe it is the same but I don't know for sure since I don't want to have `.vue` file at all.

Thanks

**Comment by abeMedia** [comment]
I have the feeling this needs to happen upstream on https://github.com/mysticatea/vue-eslint-parser

**Comment by zfeher** [comment]
Hi'

We also need support for this scenario. We are recently migrated our code base from Vue 1 to Vue 2 and we created simple vue files like this for now:
```HTML
<!-- component.vue -->

<template src="./template.html"></template>
<style src="./style.scss"></style>
<script src="./index.js"></script>
```

This works well. But eslint plugin vue won't check the referenced `template.html` nor the `index.js`. 
The latter can be fixed though via adding the `// @vue/component` comment above the component definition. Maybe the same can be done with templates as well eg:

```HTML
<!-- template.html -->

<!-- @vue/component -->
<div>
  your template
</div>
```

If this could be supported that would be really helpful. 

The best option would be (if possible) to check vue files _as is_ no matter if it uses references or the content defined there.

**Comment by kuroljov** [comment]
@zfeher you can change `.js` to `.jsx` for your components and then you won't need to add `// @vue/component`. I am using it.

**Comment by zfeher** [comment]
Nice trick, thanks.

**Comment by zfeher** [comment]
Thank you for the update.

**Comment by michalsnik** [comment]
Sorry guys, but due to technological concerns and potential problems discovered in [here](https://github.com/mysticatea/vue-eslint-parser/issues/28) we have to postpone this request indefinitely, thus I'm going to close this issue for now.

**Comment by zfeher** [comment]
No problem, thanks for considering it in the first place.

Hopefully we will be able to upgrade to `.vue` files this year and new stuff could be written in `.vue` files. Old stuff will be wired via links into `.vue` files at first then they will be refactored later incrementally as we need to touch them. And hopefully one day we will have full linting in our codebase.

**Comment by RyochanUedasan** [comment]
I'm using vue-cli-service and able to lint `.html` (like below) templates.

```index.html
<v-app-bar color="light-blue darken-4" dense fixed>
  <v-btn color="white" text @click="toTasks">Tasks</v-btn>
  <v-spacer></v-spacer>
  <v-icon large color="white">account_box</v-icon>
</v-app-bar>
```

To add parser options for `.html` files in prettier configuration, you can format `.html` files.

```.prettierrc
{
  "semi": false,
  "singleQuote": true,
  "overrides": [
    {
      "files": "*.html",
      "options": {
        "parser": "html"
      }
    }
  ]
}
```

if you use `vue-cli-service lint`, add `--ext` option  like `vue-cli-service lint --ext .js,.jsx,.ts,.tsx,.vue,.html` and you can lint them.

Is this a good way to do that?

**Comment by goatandsheep** [comment]
@RyochanUedasan this is misleading. I get the error `Property options is not allowed.`
