### ISSUE TITLE
Does attributes-order work with Pug?

### ISSUE THREAD

**Issue by LeCoupa** [vuejs/eslint-plugin-vue#493]
Quick question, does [this rule](https://github.com/vuejs/eslint-plugin-vue/blob/master/docs/rules/attributes-order.md) work with Pug? (does not work in my single-file component)

**Comment by kuoruan** [comment]
#310

**Comment by michalsnik** [comment]
Duplicate of #310 We don't support PUG yet, and we don't have a plan to support it in the near future.
