### ISSUE TITLE
Is `vue/jsx-uses-vars` only used for actual JSX?

### ISSUE THREAD

**Issue by barraponto** [vuejs/eslint-plugin-vue#5]
Is there any reason to enable that rule if the project doesn't use JSX render functions?

**Comment by chrisvfritz** [comment]
There's no downside to having it enabled and it keeps you from having to chase down the source of ESLint errors if you ever decide to use some JSX. Fewer false positive errors = happier developers. 😄

**Comment by barraponto** [comment]
Does it require `ecmaFeatures: {jsx: true}` in the parser options, then?
