### ISSUE TITLE
show error when using spread operator on array in computed properties

### ISSUE THREAD

**Issue by radislaw** [vuejs/eslint-plugin-vue#500]
**Tell us about your environment**

* **ESLint Version:** 4.19.1
* **eslint-plugin-vue Version:** 4.5.0
* **Node Version:** 9.4.0

**What did you do? Please include the actual source code causing the issue.**

```vue

data() {
  return {
   arr: [1,2,3]
  }
},
computed: {
  reversedArr() {
    return [...arr].reverse()
  }
}
```
**What did you expect to happen?**
There is actually no side effect, because I created a copy of the array

**What actually happened? Please include the actual, raw output from ESLint.**
ESLint: Unexpected side effect in " reversedArr" computed property. (vue/no-side-effects-in-computed-properties)

**Comment by michalsnik** [comment]
Please check `v4.7.0`. I fixed this rule recently :)
