### ISSUE TITLE
Sorted copy of array triggering no-side-effects-in-computed-properties

### ISSUE THREAD

**Issue by Korijn** [vuejs/eslint-plugin-vue#509]
* **ESLint Version: 4.19.1**
* **eslint-plugin-vue Version: 4.5.0**
* **Node Version: 8.11.1**

The following computed property returns a sorted copy of a list, which triggers a linting error that I don't think is justified.

```
  computed: {
    orderedCopy() {
      return [...this.unordered].sort((a, b) => a.zIndex > b.zIndex);
    },
  },
```

Triggers `57:14  error  Unexpected side effect in "orderedCopy" computed property  vue/no-side-effects-in-computed-properties`

**Comment by michalsnik** [comment]
Please check `v4.7.0` I was fixing this rule recently :)
