### ISSUE TITLE
Warn when mapGetters et. al. are used in the wrong property

### ISSUE THREAD

**Issue by tomers** [vuejs/eslint-plugin-vue#510]
### What problem does this feature solve?
I've spend couple of hours debugging an issue which caused by me mistakenly writing _mapGetters_ under _computed_ instead of under _methods_.
It would be so much helpful that the _Vuex_ code could notify the user if one of the following happens:

- _mapState_ is not under _computed_ property
- _mapGetters_ is not under _methods_ property
- _mapActions_ is not under _methods_ property
- _mapMutations_ is not under _methods_ property

### What does the proposed API look like?
n/a

**Comment by tomers** [comment]
Related to: https://github.com/vuejs/vuex/issues/1329

**Comment by michalsnik** [comment]
Hey @tomers ! Thanks for posting this issue, however we don't plan to extend this plugin with libraries-related rules just yet. Also vuex is going to change soon quite a bit, so I'd rather wait until things settle in.
