### ISSUE TITLE
Empty `context.parserServices` entry when installing dependency with NPM (no problem with Yarn).

### ISSUE THREAD

**Issue by shulard** [vuejs/eslint-plugin-vue#517]
**Tell us about your environment**

* **ESLint Version:** `"@vue/cli-plugin-eslint": "^3.0.0-rc.3"`
* **eslint-plugin-vue Version:** `"@vue/cli-plugin-eslint": "^3.0.0-rc.3"` => `4.5.0`
* **Node Version:** v8.11.3

**Please show your full configuration:**

The configuration is included in the `package.json` file.

```
{
    "eslintIgnore": [
        "jest.config.js",
        "vue.config.js"
    ],
    "eslintConfig": {
        "root": true,
        "parserOptions": {
            "ecmaVersion": 8,
            "sourceType": "module"
        },
        "extends": [
            "plugin:vue/essential",
            "eslint:recommended"
        ],
        "rules": {
            "semi": [
                "error",
                "always"
            ],
            "indent": [
                "error"
            ]
        }
    }
}
```

**What did you do? Please include the actual source code causing the issue.**

```js
  //es-lint-plugin-vue/lib/utils/index.js
  defineTemplateBodyVisitor (context, templateBodyVisitor, scriptVisitor) {
    if (context.parserServices.defineTemplateBodyVisitor == null) {
      context.report({
        loc: { line: 1, column: 0 },
        message: 'Use the latest vue-eslint-parser. See also https://github.com/vuejs/eslint-plugin-vue#what-is-the-use-the-latest-vue-eslint-parser-error'
      })
      return {}
    }
    return context.parserServices.defineTemplateBodyVisitor(templateBodyVisitor, scriptVisitor)
  },
```

**What did you expect to happen?**

Actually, I use Yarn to compile / manage my project dependency pipeline. My customer asks to change to use NPM. We haven't any error on Yarn so we expect the same behaviour for NPM...

**What actually happened? Please include the actual, raw output from ESLint.**

The full process to reproduce the error :

* Create a fresh copy of the project,
* Run `npm install`
* Run `npm run serve` (from the `vue-cli` tools)

Then the asset compilation process fail with the following error :

```
ERROR  Failed to compile with 1 errors                                                                                                                                                                                               

Module build failed (from ./node_modules/eslint-loader/index.js):
TypeError: Error while loading rule 'vue/no-duplicate-attributes': Cannot read property 'defineTemplateBodyVisitor' of undefined
    at Object.defineTemplateBodyVisitor (/Users/shulard/Code/ExoSkills/Engie/Darwin/node_modules/eslint-plugin-vue/lib/utils/index.js:34:32)
    at Object.create (/Users/shulard/Code/ExoSkills/Engie/Darwin/node_modules/eslint-plugin-vue/lib/rules/no-duplicate-attributes.js:76:18)
    at /Users/shulard/Code/ExoSkills/Engie/Darwin/node_modules/eslint/lib/eslint.js:826:61
    at Array.forEach (<anonymous>)
    at EventEmitter.module.exports.api.verify (/Users/shulard/Code/ExoSkills/Engie/Darwin/node_modules/eslint/lib/eslint.js:799:16)
    at processText (/Users/shulard/Code/ExoSkills/Engie/Darwin/node_modules/eslint/lib/cli-engine.js:263:31)
    at CLIEngine.executeOnText (/Users/shulard/Code/ExoSkills/Engie/Darwin/node_modules/eslint/lib/cli-engine.js:761:26)
    at lint (/Users/shulard/Code/ExoSkills/Engie/Darwin/node_modules/eslint-loader/index.js:229:17)
    at transform (/Users/shulard/Code/ExoSkills/Engie/Darwin/node_modules/eslint-loader/index.js:212:18)
    at /Users/shulard/Code/ExoSkills/Engie/Darwin/node_modules/loader-fs-cache/index.js:127:18
    at ReadFileContext.callback (/Users/shulard/Code/ExoSkills/Engie/Darwin/node_modules/loader-fs-cache/index.js:31:14)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
```

It seems to be related to the `context` variable injected in the function. The `parserServices` property is `undefined` in my case and I can't figure out why...

**Comment by michalsnik** [comment]
Hey @shulard It looks like you're using an old eslint that doesn't have `parserServices`. Can you check what exact version of eslint do you have installed in your project and try to run eslint directly in the terminal? You can use `npx eslint` or `./node_modules/.bin/eslint`

**Comment by michalsnik** [comment]
You can run eslint with `--debug` flag to get more info

**Comment by shulard** [comment]
Hello,

Thanks for your answer. I tried the different commands but it seems that my environment is clean now and I can install it without any trouble...
I also updated some of the dependencies so I suspect that there was a problem between specific versions.

I close that issue since the problem is solved.
