### ISSUE TITLE
How to prevent `vue/valid-v-on` on custom modifiers?

### ISSUE THREAD

**Issue by mesqueeb** [vuejs/eslint-plugin-vue#519]
Having set
`Vue.config.keyCodes = { 'enter-strict': 13 }`
Gives me the `vue/valid-v-on` error for `enter-strict`. How can prevent this?

Best regards,

**Comment by michalsnik** [comment]
Hey @mesqueeb 

At this moment you can either use built-in `enter` modifier, or disable this rule.

You can also create a PR with an extra option to extend allowed modifiers with a custom list :)

**Comment by disitec** [comment]
I am facing this as well.

Whats the right way to disable this rule? setting `vue/valid-v-on: 0` is not working for me :(
