### ISSUE TITLE
Virus in eslint-scope

### ISSUE THREAD

**Issue by arkhamRejek** [vuejs/eslint-plugin-vue#520]
this is an FYI 
https://github.com/eslint/eslint-scope/issues/39

- Summary: 
malicious package in eslint-scope. Following the recommendations in the post either lock this plugin to 3.7.1 or lock it at 4.0.0 just to be safe

**Comment by michalsnik** [comment]
The issue has already been resolved, 3.7.2 has been unpublished and 3.7.3 was published with 3.7.1 code so I think we can close it. Thanks for the care though! :)
