### ISSUE TITLE
eslint 5 compatibility

### ISSUE THREAD

**Issue by zevdg** [vuejs/eslint-plugin-vue#521]
**Tell us about your environment**

* **ESLint Version:** 5.1.0
* **eslint-plugin-vue Version:** 4.5.0
* **Node Version:** 8.11.3

**Please show your full configuration:**
N/A

**What did you do? Please include the actual source code causing the issue.**
yarn add -D eslint@latest eslint-plugin-vue@latest

**What did you expect to happen?**
installation without errors

**What actually happened? Please include the actual, raw output from ESLint.**
```
warning " > eslint-plugin-vue@4.5.0" has incorrect peer dependency "eslint@^3.18.0 || ^4.0.0".
```

I'd also expect to be seeing a message like
```
DeprecationWarning: The 'parserOptions.ecmaFeatures.experimentalObjectRestSpread' option is deprecated. Use 'parserOptions.ecmaVersion' instead.
```

like eslint-config-standard had before [this commit](https://github.com/standard/eslint-config-standard/commit/6a89a51a2a0993e3e6f37f72eb4a461f754a593b#diff-1761f4f4ee815f0c4156b931d737ff32), but for reasons I do not understand, eslint-plugin-vue doesn't seem to be triggering that warning despite using the same deprecated option.

**Comment by zevdg** [comment]
The fix might be as simple as updating your peer dependencies.  IDK if any changes in eslint 5 actually broke this plugin

**Comment by michalsnik** [comment]
Hey @zevdg 
We're aware of this, please take a look at #504

**Comment by Berkmann18** [comment]
I'm also having this issue
```cli
peer dep missing: eslint@^3.18.0 || ^4.0.0, required by eslint-plugin-vue@4.7.0
```

Here's the complete output of `npm ls --depth=0`:
```cli
├── @vue/cli-plugin-babel@3.0.0-rc.5
├── @vue/cli-plugin-e2e-nightwatch@3.0.0-rc.5
├── @vue/cli-plugin-eslint@3.0.0-rc.5
├── @vue/cli-plugin-unit-jest@3.0.0-rc.5
├── @vue/cli-service@3.0.0-rc.5
├── @vue/eslint-config-standard@3.0.0-rc.5
├── @vue/test-utils@1.0.0-beta.20
├── autoprefixer@9.0.1
├── babel-core@7.0.0-bridge.0
├── babel-jest@23.4.0
├── eslint@5.2.0
├── node-sass@4.9.2
├── sass-loader@7.0.3
├── vue@2.5.16
├── vue-router@3.0.1
└── vue-template-compiler@2.5.16
```

If I downgrade the eslint version I'll get this:
```cli
peer dep missing: eslint@>=5.0.0-alpha.2, required by eslint-config-standard@12.0.0-alpha.0
```
