### ISSUE TITLE
What is the difference between vue/no-confusing-v-for-v-if and vue/no-use-v-if-with-v-for?

### ISSUE THREAD

**Issue by mingelz** [vuejs/eslint-plugin-vue#525]
In the version 4.6.0, a new rule has been added: `vue/no-use-v-if-with-v-for`, but there is already another rule: `vue/no-confusing-v-for-v-if`, which makes me confusing.
What is the difference between them?

**Comment by michalsnik** [comment]
Hey @mingelz Sorry for the confusion. The current `vue/no-confusing-v-for-v-if` will be depracated in favor of `vue/no-use-v-if-with-v-for` that introduces extra setting `allowUsingIterationVar` and is better aligned with the styleguide.
