### ISSUE TITLE
attribute-hyphenation doesn't accept regular expressions for ignores

### ISSUE THREAD

**Issue by palfrey** [vuejs/eslint-plugin-vue#536]
* **eslint-plugin-vue Version:** 4.7.1

I'd like to disallow attribute hyphenation for all v-bind attributes, but allow it for others (as some things like the BootstrapVue bits require hyphenation). Ideally I could do this by having a regex for the ignore to just ignore anything not starting with ":", but apparently only strings are allowed as ignores for attribute-hyphenation.

**Comment by michalsnik** [comment]
Hey @palfrey I think you should probably be consistent and if BoostrapVue requires hyphenation you should use it everywhere and enable this rule in your project. Having mixed conventions usually don't end up well.
