### ISSUE TITLE
Likely option to respect Eslint hanging indentation rule in Variable Declaration?

### ISSUE THREAD

**Issue by maogongzi** [vuejs/eslint-plugin-vue#548]
**Tell us about your environment**

* **ESLint Version:5.1.0**
* **eslint-plugin-vue Version:4.7.0**
* **Node Version:v8.11.3**

**Please show your full configuration:**

```
{
  root: true,

  "parserOptions": {
    // 使用 babel 引擎解析 es6 语法
    "parser": "babel-eslint",
    "ecmaVersion": 6,
    "sourceType": "module",
    "ecmaFeatures": {
      "jsx": false,
      "modules": true
    }
  },

  env: {
    es6: true,
    node: true,
    browser: true
  },

  extends: [
    "eslint:recommended",
    "plugin:prettier/recommended",
    "plugin:vue/recommended"
  ],

  rules: {
    // TODO: 是否支持 mustache 左右空格？

    // 禁止行内注释
    "no-inline-comments": ["error"],

    // 组件 name 属性必须小写连字符形式
    "vue/name-property-casing": ["error", "kebab-case"]
  },

  // 添加例外规则
  overrides: [
    {
      files: ["*.vue"],
      rules: {
        indent: "off",
        // vue 组件内部 script 整体缩进 2 空格
        "vue/script-indent": ["error", 2, {
          baseIndent: 1
        }]
      }
    }
  ]
}
```

**What did you do? Please include the actual source code causing the issue.**

```js
    methods: {  
      // @params dataIndex Number 当前渲染的echart 点击的哪个柱图
      levelMenuSub(fieldName, dataIndex) {
        let accName = this.activeAccordionName,
          dept = [],
          group = [],

          accordionObj = this.accordionList.find((item) => {
            return accName === String(item[fieldName]);
          });
```

**What did you expect to happen?**

I want the `let` declaration above not to use hanging indentation(which keeps `accName`, `dept` and `group`, `accordionObj` in the same vertical line), instead it should use simply 2 spaces for indentation before/after running `eslint --fix` command.

**What actually happened? Please include the actual, raw output from ESLint.**

After running `eslint --fix`, it does use hanging indentation:

```js
    methods: {  
      // @params dataIndex Number 当前渲染的echart 点击的哪个柱图
      levelMenuSub(fieldName, dataIndex) {
        let accName = this.activeAccordionName,
            dept = [],
            group = [],

            accordionObj = this.accordionList.find((item) => {
              return accName === String(item[fieldName]);
            });
```

Would someone please help me point out if I'm doing wrong in my config or is there any way to not use hanging indentation in `Variable Declaration` Node, thanks in advance!

**Comment by michalsnik** [comment]
Hello @maogongzi ! Thanks for posting this issue.
If you want to ignore VariableDeclarators you can do so by using `ignores` setting:
```
"vue/script-indent": ["error", 2, {
  "ignores": ["VariableDeclarator"]
}]
```
Unfortunately the rule will completely ignore these following nodes after that, but I guess it's a fair trade-off.
