### ISSUE TITLE
Parsing error: Cannot read property 'startOffset' of null

### ISSUE THREAD

**Issue by biehu** [vuejs/eslint-plugin-vue#55]
**Tell us about your environment**

* **ESLint Version:4.1.1
* **eslint-plugin-vue Version:3.2.0
* **Node Version:6.10.2

**Please show your full configuration:**

```

'env': {
        'browser': true
    },
    'extends': [
        'plugin:vue/base'
    ],


```

**What did you do? Please include the actual source code causing the issue.**

```vue

<table>
  <tr>
    <td>

	{{message}}		
   </td>			
  </tr>
</table>



```

**What did you expect to happen?**
tbody ？

**What actually happened? Please include the actual, raw output from ESLint.**

**Comment by michalsnik** [comment]
Released as `v3.2.1` 🚀
