### ISSUE TITLE
conflict with the eslint-config-standard

### ISSUE THREAD

**Issue by fancyboynet** [vuejs/eslint-plugin-vue#553]
**Tell us about your environment**

* **ESLint Version:*^5.3.0*
* **eslint-plugin-vue Version:*^5.0.0-beta.2*
* **Node Version:**

**Please show your full configuration:*v8.11.1*

```

"eslintConfig": {
    "parserOptions": {
      "parser": "babel-eslint",
      "sourceType": "module"
    },
    "extends": [
      "plugin:vue/recommended",
      "standard"
    ]
  }


```

**What did you do? Please include the actual source code causing the issue.**

```vue

alert(1)



```

**What did you expect to happen?**

throw error like `'alert' is not defined                         no-undef`

**What actually happened? Please include the actual, raw output from ESLint.**
just ignore

**Comment by fancyboynet** [comment]
I just want the `<script> part code` also can be checked by the standard rules like other `.js` files

**Comment by ota-meshi** [comment]
@fancyboynet Hello!
 I think that you can solve this issue by making the following settings.

```diff
  "eslintConfig": {
+    "env":{
+      "browser": false
+    },
    "parserOptions": {
      "parser": "babel-eslint",
      "sourceType": "module"
    },
    "extends": [
      "plugin:vue/recommended",
      "standard"
    ]
  }
```

**Comment by ota-meshi** [comment]
@fancyboynet I'm glad that your issue has been resolved!

The config provided by this plugin does not override anything other than the rule added by this plugin.
In other settings, this plugin set `parser`, `parserOptions` and `env` as in the following source code. If there is a problem for you, you need to overwrite each with your settings.

https://github.com/vuejs/eslint-plugin-vue/blob/master/lib/configs/base.js

(The `parser` is the setting required to work with this plugin.)

**Comment by fancyboynet** [comment]
@ota-meshi OK,I got it.Thanks again.
