### ISSUE TITLE
Multiple attributes not being fixed correctly with line breaks - vue/max-attributes-per-line not working right

### ISSUE THREAD

**Issue by szalapski** [vuejs/eslint-plugin-vue#557]
It seems I can't get vue/max-attributes-per-line to auto-fix correctly.

For example, with vue/max-attributes-per-line set to 'off', and I try to add line breaks manually it corrects it to always have every element on no more than one line, no matter if it is 81, 120, 200, or more characters wide.  **How can I figure out what is forcing my markup elements onto exactly one line?**

I am using ESLint version 5.1.0 and Visual Studio Code (without the Prettier Extension), with Prettier 1.14.2.  

Here's the example in a .vue file-- I cannot make this go on multiple lines no matter what I do, when  `'vue/max-attributes-per-line': 'off'`.  Every time I save, it forces the long line of markup to be all on one line.

```
<template>
  <font-awesome-icon v-if="statusOptions.icon" :icon="statusOptions.icon" :spin="statusOptions.isIconSpin" :class="['saving-indicator', 'pl-1', 'pt-1', statusOptions.iconClasses]" />
</template>
```

If I set `'vue/max-attributes-per-line': 2`, it formats like so (which is quite wrong as well).

```
      <font-awesome-icon v-if="statusOptions.icon" 
:icon="statusOptions.icon" :spin="statusOptions.isIconSpin" :class="['saving-indicator', 'pl-1', 'pt-1', statusOptions.iconClasses]" />
```

If I try to reformat it manually, it just reverts to the above when I save.

Additionally, it seems to reformat twice when I hit Ctrl+S: first it reformats to put it all on one line, then a half-second later the formatting above results.  **Any ideas**?  What is causing this weirdness--are there multiple reformatters running? How do I figure out what the first one is to disable it?

.eslintrc.js: 

```
module.exports = {
  parserOptions: {
    parser: 'babel-eslint'
  },
  env: {
    browser: true,
    node: true,
    jest: true
  },
  globals: {
    expect: true
  },
  extends: [
    'prettier',
    'plugin:vue/recommended',        // /base, /essential, /strongly-recommended, /recommended
    'plugin:prettier/recommended',   // turns off all ESLINT rules that are unnecessary due to Prettier or might conflict with Prettier. 
    'eslint:recommended'
  ],
  plugins: ['vue', 'prettier'],
  rules: {
    'vue/max-attributes-per-line': 'off',
    'prettier/prettier': [            // customizing prettier rules (not many of them are customizable)
      'error',
      {
        singleQuote: true,
        semi: false,
        tabWidth: 2
      },
    ],
    'no-console': 'off'
  }
}
```

**Comment by michalsnik** [comment]
Hey @szalapski ! Thanks for posting this issue.

I created new application using `@vue/cli` and used exactly your eslint config. It works fine 🤔 That is - `max-attributes-per-line` is disabled and attributes stay at the same line.

Can you please try to run `eslint` through the terminal to see whether it's not problem with your vscode configuration?

Also "auto-fix" in VSC works a bit differently than `eslint --fix`. VSC fixes only one thing at a time so if you have several reports, it'll fix one by one - and you might need to save the file few times to get everything sorted out, whereas `eslint --fix` fixes rules in a loop, until everything is fixed or once it reaches 10 loops.

**Comment by michalsnik** [comment]
Also you might try these settings in VSC:
```
"vetur.validation.script": false,
"vetur.validation.template": false,
"eslint.validate": [
        "javascript",
        "javascriptreact",
        { "language": "vue", "autoFix": true },
        "vue-html"
  ],
```

**Comment by szalapski** [comment]
Yes, without changing any settings, ESLint --fix does indeed format properly.  So any ideas how I whip VS Code into shape?  The above settings didn't help, but I am at a loss how as to even know what is interfering.  Any ideas?

To emphasize, when I save in VS Code, a long HTML element will collapse to **one** line then break to **two** lines a half a second later, all from one save operation.  I'm expecting it instead to break it up into **many** lines.  It would be okay if it took several saves, but instead the first save shows this behavior as well as every subsequent save.

**Comment by szalapski** [comment]
If I set` "editor.formatOnSave": false, `it no longer formats on save at all, which is worse.  Did you somehow get it to format on save without  `"editor.formatOnSave": true`?

**Comment by szalapski** [comment]
asking here: https://stackoverflow.com/questions/52102705/cant-get-correct-autoformat-on-save-in-visual-studio-code-with-eslint-and-prett

**Comment by michalsnik** [comment]
Yes, I have `"editor.formatOnSave": false` and `"vetur.validation.template": false` and I'm fully dependant on ESLint and how it fixes my code on save. I also use prettier as an integration with ESLint, hence I don't have any formatters running in parallel causing problems.

I also see you found a solution in SO thread 👍

**Comment by szalapski** [comment]
Short answer: I needed: "editor.formatOnSave": false, "javascript.format.enable": false.

I finally found the magical combination of settings, thanks to this thread from Wes Bos on Twitter. I was right in my suspicion that there seem to be multiple conflicting formatters. Though I'm not sure what they actually are, I was able to turn off all but eslint as follows:

In the VS Code settings, I need:
```

  "editor.formatOnSave": false,
  "javascript.format.enable": false,
  "eslint.autoFixOnSave": true,
  "eslint.alwaysShowStatus": true,
  "eslint.options": {
    "extensions": [ ".html", ".js", ".vue", ".jsx" ]
  },
  "eslint.validate": [
    { "language": "html", "autoFix": true },
    { "language": "vue", "autoFix": true },
    { "language": "javascript", "autoFix": true },
    { "language": "javascriptreact", "autoFix": true }
  ]

```
In .eslintrc.js, then I can use the settings in my original post and then also change 'vue/max-attributes-per-line' as desired. Then VS Code's ESLint plugin will format code one step at a time on every save, much as kenjiru wrote. One last snag: HMR won't pick up these changes, so rebuild from scratch.

**Comment by SebastianMieszczanczyk** [comment]
It is not working for me - now some options are deprecated:

- `"eslint.autoFixOnSave": true`  Use editor.codeActionsOnSave instead with a source.fixAll.eslint member. So I tried:
`"editor.codeActionsOnSave": {
    "source.fixAll.eslint": true
  }` and still formating to a single line. Do you have any idea why?
