### ISSUE TITLE
props在哪里设置呀请问

### ISSUE THREAD

**Issue by xiaomizhou66** [vuejs/eslint-plugin-vue#565]
什么意思呀，这样 写为什么报错
 name: 'Home',
  props: ['here'],  这怎么写
  data () {}

eslint props should at least define their types

**Comment by Justineo** [comment]
你已经把错误提示都贴出来了，请仔细阅读一遍……

**Comment by michalsnik** [comment]
Please read the documentation: https://github.com/vuejs/eslint-plugin-vue/blob/master/docs/rules/require-prop-types.md
