### ISSUE TITLE
eslint execute extra config files when run the  npm run-srcript "test"

### ISSUE THREAD

**Issue by EugeneJao** [vuejs/eslint-plugin-vue#570]
**Tell us about your environment**
macos 10.13.6
* **ESLint Version:**
eslint 5.5.0
* **eslint-plugin-vue Version:**
eslint-plugin-vue 5.0.0-beta.3
* **Node Version:**
nodejs v9.8.0
**Please show your full configuration:**

```
"scripts": {
    "start": "npm run test:base -- --watch --growl",
    "test:base": "mocha \"tests/lib/**/*.js\" --reporter dot",
    "test": "nyc npm run test:base -- \"tests/integrations/*.js\" --timeout 60000",
    "lint": "eslint . --rulesdir eslint-internal-rules",
    "pretest": "npm run lint",
    "preversion": "npm test && npm run update && git add .",
    "version": "npm run lint -- --fix && git add .",
    "update": "node ./tools/update.js"
  }
```

**What did you do? Please include the actual source code causing the issue.**

```vue





```

**What did you expect to happen?**
i want to run the test npm run-script to test this project.
**What actually happened? Please include the actual, raw output from ESLint.**
But, it throw an error--error msg below. After i had added a debug option on the test script, the debug info show that eslint has loaded all the eslint config file in this project, however, the config file in the test/integrations/eslint-plugin-import dir contains the eslint-plugin-import, it could not work well before the running of  javascript file named eslint-plugin-import.

``` bash
Oops! Something went wrong! :(

ESLint: 5.5.0.
ESLint couldn't find the plugin "eslint-plugin-import". This can happen for a couple different reasons:

1. If ESLint is installed globally, then make sure eslint-plugin-import is also installed globally. A globally-installed ESLint cannot find a locally-installed plugin.

2. If ESLint is installed locally, then it's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm i eslint-plugin-import@latest --save-dev

Path to ESLint package: /Users/raoyijun181/Project/eslint-plugin-we5ue/node_modules/eslint

If you still can't figure out the problem, please stop by https://gitter.im/eslint/eslint to chat with the team.
```

**Comment by michalsnik** [comment]
Thanks for posting an issue, however I think it is a problem specific to your case and not the plugin itself @EugeneJao 

I did a fresh install on the same Node.js version as follows and it all works fine:
```
git clone git@github.com:vuejs/eslint-plugin-vue.git
cd eslint-plugin-vue
npm install
npm test
```

Feel free to reopen this issue if the above fails ☝️
