### ISSUE TITLE
Request for change: Emit error, not warning on side-effects in computed properties

### ISSUE THREAD

**Issue by infintesimal** [vuejs/eslint-plugin-vue#576]
I am using eslint version 5.6.0
I am using eslint-plugin-vue version 3.0.3
I am using node 10.10.0

What I did?
What I did: I created code that has (or had) a side effect in computed properties.
What I would like to happen: I receive a warning, not an error.
What actually happened: the linter put red-ink on my console that read:
```
Module Warning (from ./node_modules/eslint-loader/index.js):
error: Unexpected side effect in "sortedRows" computed property (vue/no-side-effects-in-computed-properties) at src/App.vue:80:14:
```
My take on the "correct" behavior:
I think the correct behavior is to label this violation a warning, not an error. When I use linters, I expect errors to be fatal and warnings to be everything else related to either style or good programming form. Red ink on the console triggers within me a twitch of "this is never acceptable." The more I think about it, for things that are neither compile-time errors or run-time errors, "never acceptable" perhaps never applies.

Side note: some clarity around definition of side effect would be helpful. I managed to side step the warning by doing the following
```
...
data: {
    someArray: [{...},{...},...]
},
computed: {
    sortedRows: function(someArray) {
        //code that emitted linter error did not pass someArray into the function, rather,
        //it had called this.someArray.sort() where slice() was not viable to maintain proper app state
        //effectively, do a simple sort of parent data this way b/c it was passed into function to get rid
        //of linter error
        someArray.sort()
        ...
    }
}...
```

**Comment by armano2** [comment]
@infintesimal but this is run-time error, because `sort()` mutates value of `someArray` and its triggered in uncontrolled way and may lead to errors due to cache.

if you want to `someArray` to be sorted or you want to modify it you should use `watch` eg.
```
  watch: {
    // whenever someArray changes, this function will run
    question: function () {
      this.someArray.sort()
    }
  },
```

:>
`sortedRows: function(someArray) {` is incorrect, computed properties has no parameters.

**Comment by michalsnik** [comment]
I see your point @infintesimal And I agree not all of the rules should probably throw an error, but rather a warning and I'll work on making it more semantic. However in this case we really want user to know that there is a serious problem in the code and they shouldn't ignore it. The way I understand it warning is that it's more of a heads up, but here having side effect in computed property might lead to really hard to catch bugs, so we want to be really explicit that is is dangerous.
