### ISSUE TITLE
Intellij setup for eslint-plugin-vue

### ISSUE THREAD

**Issue by peripateticus** [vuejs/eslint-plugin-vue#594]
There are installation instructions for various IDE/editors but none for Intellij/Webstorm. I haven't had any luck getting eslint running for any Vue components using Intellij's eslint plugin along with the eslint-plugin-vue. Has anyone had any luck around this, if so, can you document?

* **ESLint Version:**
4.19.1

* **eslint-plugin-vue Version:**
4.7.1

* **Node Version:**
8.11.2
**Please show your full configuration:**

```
{
  "extends": ["airbnb-base", "plugin:vue/recommended"],
  "env": {
    "node": true,
    "mocha": true,
    "browser": true
  },
  "plugins": [
    "vue"
  ],
  "rules": {
    "comma-dangle": [ "error", {
      "arrays": "always-multiline",
      "objects": "always-multiline",
      "imports": "always-multiline",
      "exports": "always-multiline",
      "functions": "ignore"
    } ]
  }
}

```

**Comment by peripateticus** [comment]
It's configured in IntelliJ in Preferences -> Languages & Frameworks -> JavaScript -> Code Quality Tools -> ESLint. (As opposed to just the Preferences -> ESLint area.)

**Comment by michalsnik** [comment]
Feel free to submit a PR if you have a solution @peripateticus :) I haven't used this editor

**Comment by peripateticus** [comment]
Thanks @michalsnik, it'd likely just be some documentation in the README.

**Comment by armano2** [comment]
> **IntelliJ IDEA / JetBrains WebStorm**
> 
> In the **Settings/Preferences** dialog (`Ctrl+Alt+S`), choose JavaScript under **Languages and Frameworks** and then choose **ESLint** under **Code Quality Tools**. On the **ESLint page** that opens, select the *Enable* checkbox.
> 
> If your ESLint configuration is updated (manually or from your version control), open it in the editor and choose **Apply ESLint Code Style Rules** on the context menu.
> 
> read more: [JetBrains - ESLint](https://www.jetbrains.com/help/idea/eslint.html)

That's all what you have to do and it should work correctly: tested on `IntelliJ IDEA 2018.2.5`
