### ISSUE TITLE
Proposal for rule style-indent

### ISSUE THREAD

**Issue by jojoob** [vuejs/eslint-plugin-vue#619]
A wish there would be a "style-indent" rule like the rules for html and script indent.

**Comment by michalsnik** [comment]
Sorry @jojoob but because Vue supports lots of different CSS preprocessors we'd probably have to create separate rules for each one of them. You should rather stick to existing CSS linters and leave intentation as is.

**Comment by ota-meshi** [comment]
I think that you can solve this issue by using [prettier](https://prettier.io/) or [stylelint](https://stylelint.io/).

**Comment by jojoob** [comment]
@ota-meshi thank you for the hints. :)

**Comment by nolimitdev** [comment]
Can be done with https://www.npmjs.com/package/stylelint-config-recommended-vue

> npm install --save-dev postcss-html stylelint-config-recommended-vue

> Set your stylelint config to:
> 
> {
>     "extends": "stylelint-config-recommended-vue"
>      "indentation": [4, { "baseIndentLevel": 1 }],
> }
> 

Optional: Add to VSCode settings.json:
> {
>   "stylelint.validate": [
>       ...,
>       // ↓ Add "vue" language.
>       "vue"
>   ]

**Comment by Revadike** [comment]
> Can be done with [npmjs.com/package/stylelint-config-recommended-vue](https://www.npmjs.com/package/stylelint-config-recommended-vue)
> 
> > npm install --save-dev postcss-html stylelint-config-recommended-vue
> 
> Set your stylelint config to:
> 
> > {
> > "extends": "stylelint-config-recommended-vue"
> > "indentation": [4, { "baseIndentLevel": 1 }],
> > }
> 
> Optional: Add to VSCode settings.json:
> 
> > {
> > "stylelint.validate": [
> > ...,
> > // ↓ Add "vue" language.
> > "vue"
> > ]

Does this work for ESLint ^9.0.0 with the new flat configuration files?

**Comment by FloEdelmann** [comment]
Stylelint has nothing to do with ESLint. eslint-plugin-vue UST compatible with ESLint v9, see the docs on how to configure it.

**Comment by nickofthyme** [comment]
If you found this issue trying to indent `styles` in vue SFC, allow me help...

1. There is no `vue/style-indent` rule and there never will be.
2. There is no `indentation` rule in `stylelint`, it was [deprecated in version 15](https://stylelint.io/migration-guide/to-15/#deprecated-stylistic-rules) and [removed in version 16](https://stylelint.io/migration-guide/to-16#removed-deprecated-stylistic-rules).
3. `Prettier` is the _only_ way to enable this functionality. You can set this by enabling the [`vueIndentScriptAndStyle `](https://prettier.io/docs/en/options#vue-files-script-and-style-tags-indentation) option.
4. Prettier is not integrated with the IDE so you will not see the red squiggles  `~~~~` for errors, like with `eslint` and `stylelint`.
5. The best you can do is configure prettier in your IDE to fix each file on save, see [docs](https://prettier.io/docs/en/editors.html).
6. The `vueIndentScriptAndStyle` option has no optionality such as configuring the `baseIndent` as you can do with [`vue/script-indent`](https://eslint.vuejs.org/rules/script-indent) and [`vue/html-indent`](https://eslint.vuejs.org/rules/html-indent), just on or off.
7. Best of luck 🍀
