### ISSUE TITLE
[FR] `inheritAttrs: false` when using `v-bind="$attrs"`

### ISSUE THREAD

**Issue by privatenumber** [vuejs/eslint-plugin-vue#626]
Components that inherit `$attrs` into a nested element in the component typically wouldn't want to get duplicated attributes applied to the top-level element. Might be a good linting rule to warn to apply `inheritAttrs: false` when it detects `v-bind="$attrs"` being used.

**Comment by michalsnik** [comment]
I'm not sure about this rule. It might lead to false-positives, the `inheritAttrs` might not be explicitly set on the component if it uses a mixin. And having it reporting in one scenario and not in the other seems not very consistent and might actually be misleading in my opinion. WDYT @chrisvfritz ?

**Comment by chrisvfritz** [comment]
As long as we can avoid false positives (e.g. by just turning the rule off if we detect a mixin or `Object.assign`/spread on the component object), I think it could be useful. From what I've seen, it's very rare for `inheritAttrs: false` to come from an external source, so this would still catch 99% of cases.
