### ISSUE TITLE
Indent inside pre tag incorrectly applied

### ISSUE THREAD

**Issue by aldarund** [vuejs/eslint-plugin-vue#653]
**Tell us about your environment**	
* **ESLint version:**	5.9
* **eslint-plugin-vue version:** 5 beta 4	

**Please show your full configuration:**
https://github.com/nuxt/nuxt.js/blob/dev/.eslintrc.js

**What did you do?**	
https://github.com/nuxt/nuxt.js/blob/dev/examples/routes-meta/pages/about.vue

**What did you expect to happen?**
No error for indent inside pre tag, because it will change the result in browser

**What actually happened?**
https://circleci.com/gh/nuxt/nuxt.js/15089?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by ota-meshi** [comment]
Thank you for this issue.
I will look into this cause.
