### ISSUE TITLE
vue/html-indent rule is impossible to follow, how to turn it off completely?

### ISSUE THREAD

**Issue by thariddler** [vuejs/eslint-plugin-vue#664]
Let's say I have this code

```html
<no-ssr>
      <portal to="modals"> 
        <fullscreen-menu/>
      </portal>
</no-ssr>
```
I want to comment out everything but `fullscreen-menu`. 

```html
<!--     <no-ssr>
      <portal to="modals">  -->
        <fullscreen-menu/>
<!--       </portal>
    </no-ssr> -->
```
This is what Sublime is doing for me. 
Even if I choose each line separately I now have this

```html
    <!-- <no-ssr> -->
      <!-- <portal to="modals">  -->
        <fullscreen-menu/>
      <!-- </portal> -->
    <!-- </no-ssr> -->
```
Which is ALSO not following this aweful rule.

The only way to do this by this rule is first to make **each** line on same level and then to comment line **every line** separately which is **ridiculous**

How to turn this rule completely and how to make eslint-plugin-vue less **fascist**?

**Comment by armano2** [comment]
Maybe we should add ignore option for comment or ignore comments by default?

**Comment by armano2** [comment]
You can turn off each rule by setting it to `off`
```json
{
   "vue/html-indent": "off"
}
```

https://eslint.org/docs/user-guide/configuring#configuring-rules

**Comment by thariddler** [comment]
@armano2 thanks. Turn off is working (didn't know how to do it).

But still option to turn of `vue/html-indent` rule for commented code would be awesome!
