### ISSUE TITLE
vue/no-use-v-if-with-v-for - wrong rule

### ISSUE THREAD

**Issue by mkapiczy** [vuejs/eslint-plugin-vue#665]
eslint: 5.9.0
eslint-plugin-vue: 5.0.0-beta.4
node: 9.11.2

I think the rule vue/no-use-v-if-with-v-for is no longer valid, as Vue documentation supports their combination -> [https://vuejs.org/v2/guide/list.html#v-for-with-v-if](https://vuejs.org/v2/guide/list.html#v-for-with-v-if )

**Comment by ota-meshi** [comment]
Hello!
As you say, Vue supports it, but it is recommended not to use it in the Vue Style Guide.
https://vuejs.org/v2/style-guide/#Avoid-v-if-with-v-for-essential

If you do not need this rule, you can turn this rule off, or you can change the [option](https://github.com/vuejs/eslint-plugin-vue/blob/master/docs/rules/no-use-v-if-with-v-for.md#wrench-options).

**Comment by bq-hentai** [comment]
@armano2 if the iteration is the nested iteration, and need to use the outer iteration var, this method is useless?
