### ISSUE TITLE
Allow multiple lines after opening an element (multiline-html-element-content-newline)

### ISSUE THREAD

**Issue by Jones-S** [vuejs/eslint-plugin-vue#683]
Hi there.
This is neither a rule proposal nor a bug. I would just like to know if there is a possibility to tailor [the rule](https://github.com/vuejs/eslint-plugin-vue/blob/v5.0.0-beta.3/docs/rules/multiline-html-element-content-newline.md) `multiline-html-element-content-newline` to my needs.

I really like to insert empty lines in longer markup files to group some of the code for better readability. Now my eslint warns me that it found 2 lines instead of 1.
I think the rule itself is useful, but I would like it to not warn me if there are more than 1 lines found.

https://github.com/vuejs/eslint-plugin-vue/blob/07a7d9f6bc7dafe6db0bf8644f35109f3c4efd3c/tests/lib/rules/multiline-html-element-content-newline.js#L425

Thanks for your input on this issue.
Cheers

J

**Comment by korya** [comment]
I've just come here to open an issue for the same request.

But I would like to propose to limit it to: `1 ≤ #line-breaks ≤ 2`. In my experience a single empty is a good way to visually group related lines, but multiple empty lines (≥2) create a mess.
