### ISSUE TITLE
Beta 5 brakes linter

### ISSUE THREAD

**Issue by Piterden** [vuejs/eslint-plugin-vue#691]
Beta 5 shows many errors. Looks like it not read the config file. Beta 4 is fine.

**Comment by mysticatea** [comment]
Hi. Please open an issue with our issue template. We cannot investigate problems if there are no reproduce.

**Comment by Piterden** [comment]
https://asciinema.org/a/7v6elbIiu2XyqMHgzMwIOAlAe

**Comment by Piterden** [comment]
https://asciinema.org/a/214596

**Comment by mysticatea** [comment]
Would you fill our issue template?
That video shows actual errors but it's not enough to reproduce it because it doesn't show configs and source codes.

**Comment by Piterden** [comment]
https://github.com/Piterden/vue-crossword

https://codesandbox.io/s/github/Piterden/vue-crossword/tree/master/

**Comment by armano2** [comment]
in beta.5 we enabled additional rules

- 8fd7ab841a42b25f1ce0b025063fb16bd41a9337 Update uncategorized rules' categories
  - strongly-recommended: 
    - [component-name-in-template-casing]
    - [multiline-html-element-content-newline]
    - [no-spaces-around-equal-signs-in-attribute]
    - [singleline-html-element-content-newline]
  - essential:
    - [use-v-on-exact]

**Comment by Piterden** [comment]
It broke our staging build

**Comment by mysticatea** [comment]
Thank you.

You have `plugin:vue/recommended` in your config, so this is expected behavior.
We have updated the recommended config in that version.

We don't change the recommended config without major version up, but we did in beta.

**Comment by Piterden** [comment]
Thank you for the explanation. Now it is clear enough.

**Comment by armano2** [comment]
> ✖ 16 problems (2 errors, 14 warnings)
>   0 errors and 14 warnings potentially fixable with the `--fix` option.

**Comment by Piterden** [comment]
`vue/component-name-in-template-casing` provides React style of component names. It is strongly recommended to use kebab-cased names.

**Comment by mysticatea** [comment]
I agree with you. I like kebab-case than PascalCase strongly because HTML is case-insensitive. However, the team seems to have a different preference. :(
