### ISSUE TITLE
Inconsistent results between node 10 and 11

### ISSUE THREAD

**Issue by armano2** [vuejs/eslint-plugin-vue#693]
**Tell us about your environment**	
* **ESLint version:**	latest
* **eslint-plugin-vue version:**	latest
* **Node version:**	11

Order in components rule reports different errors on node 11 and <11

--------------

this ticket is just for reference

**Comment by michalsnik** [comment]
Hey @armano2 Can you add more informations in this ticket? Does it happen for certain code only, or for any? How do these messages differ?

**Comment by armano2** [comment]
ohh i forgot to link it to #718
