### ISSUE TITLE
TSX cannot be parsed when using with typescript-eslint-parser in SFC

### ISSUE THREAD

**Issue by ktsn** [vuejs/eslint-plugin-vue#696]
**Tell us about your environment**	
* **ESLint version:**	5.9.0
* **eslint-plugin-vue version:**	5.0.0-beta.5
* **Node version:**	8.12.0

**Please show your full configuration:**

```js
module.exports = {
  root: true,
  extends: 'plugin:vue/base',
  parserOptions: {
    parser: 'typescript-eslint-parser',
    ecmaVersion: 2018,
    source: 'module',
    ecmaFeatures: {
      jsx: true
    }
  }
}
```

**What did you do?**	

```vue
<script lang="tsx">
const a = <div />
</script>
```

**What did you expect to happen?**
No errors are provided.

**What actually happened?**

Parsing error is provided on JSX.

Note that when I save the exact same code in the script block to individual `.tsx` file, there is no error.

You can confirm the behaviour with this repo: https://github.com/ktsn/eslint-vue-ts-jsx-repro

**Comment by mysticatea** [comment]
I guess that you are using `typescript-eslint-parser@21.x`. That version changed `parserOptions` and it doesn't have `ecmaFeatures.jsx`. Use `jsx` instead.

The `jsx` option enables JSX syntax on other than TypeScript files.

**Comment by ktsn** [comment]
Oh, you are right. Sorry, I completely missed that the option is changed.
Thank you for pointing it out!

---

Modified config that works:

```js
module.exports = {
  root: true,
  extends: 'plugin:vue/base',
  parserOptions: {
    parser: 'typescript-eslint-parser',
    ecmaVersion: 2018,
    source: 'module',
    jsx: true
  }
}

```

**Comment by DarknessChaser** [comment]
ecmaFeatures is still available, see [https://eslint.org/docs/latest/use/configure/language-options#specifying-parser-options](https://eslint.org/docs/latest/use/configure/language-options#specifying-parser-options)

```json
ecmaFeatures: {
  jsx: true
}
```
