### ISSUE TITLE
<Frame> component gives error

### ISSUE THREAD

**Issue by KoenPaas** [vuejs/eslint-plugin-vue#697]
Well when using Frame component it gives the error:
![schermafbeelding 2018-12-03 om 20 19 09](https://user-images.githubusercontent.com/36813373/49396165-c8916080-f738-11e8-9673-d724af7bd954.png)

Frame component is being used in combination with Nativescript.

**Comment by KoenPaas** [comment]
Straight from VS Code Vetur 0.14.3.

**Comment by armano2** [comment]
:( vetur is using version `^4.3.0`

**Comment by armano2** [comment]
@KoenPaas can you make ticket there instead? 
https://github.com/vuejs/vetur/issues

**Comment by KoenPaas** [comment]
Done, with the current version of eslint-plugin-vue it's not gonna give you an error?

**Comment by armano2** [comment]
you can try it here: https://mysticatea.github.io/vue-eslint-demo/

**Comment by boggddan** [comment]
Hello. I have the same mistake in VS Code. I use "eslint-plugin-vue": "5.0.0", "eslint": "5.10.0". Thanks

**Comment by michalsnik** [comment]
The #1013 have been merged. You can either wait for the next Vetur release, or disable template linting by it, and rely solely on ESLint (`vetur.validation.template: false`). More informations here: 
- https://vuejs.github.io/eslint-plugin-vue/user-guide/#editor-integrations
- https://vuejs.github.io/vetur/linting-error.html#linting
