### ISSUE TITLE
Recommended preset config

### ISSUE THREAD

**Issue by sunyang713** [vuejs/eslint-plugin-vue#7]
Is it possible to integrate [eslint-config-vue](https://github.com/vuejs/eslint-config-vue) with this package instead of having separate packages, and then accessing the recommended presets with:
```javascript
    "extends": ["plugin:vue/recommended"]
```
Many other eslint plugins follow this convention, including eslint itself.

**Comment by chrisvfritz** [comment]
I might be misunderstanding, but I can see cases where someone might want the plugin, but not the rules in eslint-config-vue, since it includes rules that extend far beyond just Vue-specific code. For that reason, I'm hesitant to combine them. Does that make sense?

**Comment by sunyang713** [comment]
@chrisvfritz ahh okay. Sorry, I should've looked more carefully at the rules themselves. I understand now, thanks for the explanation!
