### ISSUE TITLE
vue-cli-plugin applies different rules then eslint

### ISSUE THREAD

**Issue by georgeboot** [vuejs/eslint-plugin-vue#712]
**Tell us about your environment**	
* ESLint version: 5.9.0
* eslint-plugin-vue version:5.0.0
* Node version:11.0.0

**Please show your full configuration:**

```js
// .eslintrc.js
module.exports = {
    root: true,

    env: {
        node: true,
    },

    extends: ['plugin:vue/essential', 'plugin:prettier/recommended', '@vue/prettier'],

    rules: {
        'no-console': process.env.NODE_ENV === 'production' ? 'error' : 'off',
        'no-debugger': process.env.NODE_ENV === 'production' ? 'error' : 'off',
    },

    parserOptions: {
        parser: 'babel-eslint',
    },
}
```

```js
// .prettierrc.js
module.exports = {
    trailingComma: 'es5',
    tabWidth: 4,
    semi: false,
    singleQuote: true,
    printWidth: 150,
}
```

**What did you do?**	
I created a new project using `vue-cli-3` and opted for the eslint+prettifier option. Then, I installed the vscode plugin following the docs [here](https://vuejs.github.io/eslint-plugin-vue/user-guide/#editor-integrations).

**What did you expect to happen?**
The eslint plugin of vscode is configured to fix on save (`"eslint.autoFixOnSave": true`)

When I save, the eslint integration applies fixes to my file.

Then, when I manually run `yarn run lint`, I expect the linter to run without any fixes, as my plugin just applied them. It also reads from the same config so it should apply the same rules.

**What actually happened?**
The 2 ways to run style fixes (autoSave using eslint vscode plugin and `yarn run lint` produce different fixes, though subtile.

For example, vscode want the code piece to look like this:
```vue
<button
    v-on="
        ticketTypeQuantity(ticketType.id) > 0
            ? { click: decrementTicketTypeQuantity(ticketType.id) }
            : {}
    "
    :class="{ 'opacity-50 cursor-not-allowed': ticketTypeQuantity(ticketType.id) < 1 }"
    class="mx-4 bg-green text-white rounded-full p-2 block w-8 h-8 flex justify-center items-center"
>
```

Whereas, when I run `yarn run lint`, the file is changed to:
```vue
<button
    v-on="ticketTypeQuantity(ticketType.id) > 0 ? { click: decrementTicketTypeQuantity(ticketType.id) } : {}"
    :class="{ 'opacity-50 cursor-not-allowed': ticketTypeQuantity(ticketType.id) < 1 }"
    class="mx-4 bg-green text-white rounded-full p-2 block w-8 h-8 flex justify-center items-center"
>
```

**Comment by michalsnik** [comment]
Hey @georgeboot Have you turned off the `vetur` linting? `"vetur.validation.template": false`?

**Comment by michalsnik** [comment]
Please feel free to reopen the issue once you confirm the above concern :)
