### ISSUE TITLE
vue/order-in-components doesn't fix warnings

### ISSUE THREAD

**Issue by jean-moldovan** [vuejs/eslint-plugin-vue#724]
```
105:5  warning  The "computed" property should be above the "created" property on line 73  vue/order-in-components
```

Expected: vue/order-in-components is supposed to be fixable
(https://github.com/vuejs/eslint-plugin-vue/issues/299)
Current: not fixable

eslint-plugin-vue v5.0.0
node v9.11.1

Thanks!

**Comment by michalsnik** [comment]
Hi @jean-moldovan This rule is fixable actually, but not in all cases. We explicitly disable auto-fix, when we detect that some of the nodes might contain side-effects. We want you to be safe and not break your app in hard to debug way - so we suggest you to consciously fix order by yourself.

**Comment by jean-moldovan** [comment]
Thanks, @michalsnik. Mind sharing an example of a possible side-effect when "computed" goes above "created"?

Thanks again!

**Comment by armano2** [comment]
we are not auto sorting it because there spread operator. [live demo](https://mysticatea.github.io/vue-eslint-demo/#eJx1UstOwzAQ/JXFQkor2anEsaq4coILSBwoUqNkU4zih/wILVH+nXWcNnDAB1uenZ2dXXtgtWmQbdnO107acL/XAFJZ4wIMoCr7gCGg8zBC64yCoo94KvY60fA00Rpsq9gRPWEAykQdsIHV+oIA1EZ702EpdWtW4UP68gu72ih89EcOE9BTEWk0AeucNfJ8Es1GEtwucmVZLs5Wb0WiVPr8VCksOFnMUsX7mmejaS0F/zgDcBii03B4zQQIBm6HydIv2fEGDpeUizGAxfM/mv2sNBPHRWPuMR207Tbz9BlnLnbo2XZgNOkNWVCog2ikwzrInl7qjk+RT38S0aMXfeX8FdVG0Kzb6KU+il60xtEu22vcuAadkFqk3owm6ZQ7ciZ1Q5dn+Z0r5OvL2aav4W1VIzmzVAkdAeitQ2TjD1nOvPw=)

**Comment by deka** [comment]
Why this issue is closed ?

> We explicitly disable auto-fix, when we detect that some of the nodes might contain side-effects. 

Can you explain more ? update doc ? or fix side effects ?

**Comment by kaantureyyen** [comment]
> @jean-moldovan we are not auto sorting it because of spread operator. [live demo](https://mysticatea.github.io/vue-eslint-demo/#eJx1UstOwzAQ/JXFQkor2anEsaq4coILSBwoUqNkU4zih/wILVH+nXWcNnDAB1uenZ2dXXtgtWmQbdnO107acL/XAFJZ4wIMoCr7gCGg8zBC64yCoo94KvY60fA00Rpsq9gRPWEAykQdsIHV+oIA1EZ702EpdWtW4UP68gu72ih89EcOE9BTEWk0AeucNfJ8Es1GEtwucmVZLs5Wb0WiVPr8VCksOFnMUsX7mmejaS0F/zgDcBii03B4zQQIBm6HydIv2fEGDpeUizGAxfM/mv2sNBPHRWPuMR207Tbz9BlnLnbo2XZgNOkNWVCog2ikwzrInl7qjk+RT38S0aMXfeX8FdVG0Kzb6KU+il60xtEu22vcuAadkFqk3owm6ZQ7ciZ1Q5dn+Z0r5OvL2aav4W1VIzmzVAkdAeitQ2TjD1nOvPw=)

What is the side effect caused by the spread operator? Sorry if this is a newbie question 😅

**Comment by wrabit** [comment]
I for 1 would really find this feature useful.

I'm guessing if you use spread operator to set the component properties themselves, which let's face it is probably so rarely done.

**Comment by clustersnake** [comment]
@jean-moldovan @wrabit I found it! I was fooling with typescript and wrapped my component with Vue.extend and voila!
`export default Vue.extend({
  name: "BasicLayout",
...
})
`
please give it a try. I'm using eslint-plugin-vue@6.2.2 with the recommended rules

**Comment by clustersnake** [comment]
I extracted my javascript code to a .js file visual studio code fixes the code aplying the recommended rules, I just had to wrap my component with Vue.extend(
``` 
export default Vue.extend({
  name: "PageIndex",
  mixins: [ClienteHttp],
...
});
```
I know it's not a real fix, but... it's something! ¯\_(ツ)_/¯

**Comment by Tofandel** [comment]
The spread operator doesn't create side effects.. IMHO this is a bug an this should be fixed, it's very frequent to use `...mapGetters`

Having added this rule on an already created app, I now have to fix all the order by hand whenever there is a spread operator (which is.. everywhere)

**Comment by disarticulate** [comment]
ran into this problem also. It's an annoying bug mostly because the 'order' and the 'error' suggestion creates almost a cascading of reordering that it's easier to just turn this feature off.

I also can't imagine who is writing SFC where something like the spread operator would cause side effects. It'd be nice if someone demonstrated a code sample that is effected by the order of the properties in a module.

**Comment by carl-jin** [comment]
If you have ton of files need to re-order, you can try with gogocode, here is the example that I used in my project [gogocode example](https://play.gogocode.io/#code/N4IglgdgDgrgLgYQPYBMCmIBcIA8c0C2UANgIb4B8AOhAAS04pgBuFOA9E6zR-kWZRo8AzgGMATmChxaZCAHMAvFRBxhK6hDBEk4mcFroAZpDTIdENBBkBfWkfFICtFcxhoVAbhpoAHlF0ZY1IYYiC0E0tzAMtrAApgGhc6WlEnGKs1TFpgGwAaJNooRyhhbNyClJRyUjiAShzC+nE0OBhxOlzvFPymiFICNGyVfGE4FUr6NKJ4NBRyptoxgE9iNAARGvrGlPpm1vbOm2692l6eydoCJBhrOe2KwsG4AAtUMp3TgDofglIoACCojgYCQEGEcRgwjQAKgUAAynBdGg8rQANoqFrXZgwuETFwgFAwEhgUTkXFQfEqYnVfCwqAASQgRiQKgAunVLlNiKSANb0h7nehC2gAd3Iohe5RFhDAWXRKklpAUHhAbMqNjq3Q4Ykk0k0IDyIFFul5yHQWBARluwNBdDg4mVwhZ4gIcRMayZLNR-zAqKQ0jtwgaiRSaXBMgAJLRFLRfV95EhE2l0IVw2MljdxKI0DH7GBPcykF9hFmc2mwRnSBnY5G4qX2jnUaHTlBSOJoQB5QOV8qyZXyGCkeRDWgAcjcaDHqIb2bQABVllBR2PrkS1mOzpdNRWI0sJFIZLHq3AvpEUHExzhdYe2Owb-qx3VCg-xrtaF8WiRSDnL34AnohgRCEYRAZEZjpGCmQJJGsGatOtBxH8cCSg0igUJ8pxXBKLxomOsGwWObIloEcRxGsRhwKikjyC8cBoRhLZYVMlYyLo6AdnmxQBsInbiBx9SLKcawyBRcAAHIDLmsZiV8vJoMsXz9IMQl7CJtA0XRkmDHmmmnvJinKR477Ca0sgRHATLoL4ebsWgHZfJA1mdkY5EWdpaDPiZalmXpVl+LZ-H2cIjkQM5rl6R5XmqfsbQdOZlH+TZAC0GlgLRllhX4qk7hAqnqdxpTmtJ2Eobh+EEURXx-FAZGFQxtB1vVCZWPZ5L1NF3ktHFdAAAb-oEYEgeE4HRFB8TAJGwCFcIxVfAAVkgkBxDF455GOql1DYmq9YsuXfCOliOvggkpOw7AaQc8XLFmtAOk6LqDCgqSoLmLz2cZsWHHGYwtUd7VeTYQjMjaIJgkUJS8UF4gPIU530HRcClJg53yHKLwwAARl80zsJO83COwaDCDy1jJSQMBoxAyWTuwmPEEgmPsAAjAATAALKIogAMwAOzMwAbOzACsKCY5jwsC6QAAcAAMKAoKImOiNLmNGHzpBGALERcygsvs+z7A8kz4ihMT7B2eIyWQMl0wZNYIUEwAxAAMsz7OFN130Yu+8PwmA6C0AAokYRhoMCwiIQ66UjpxERhxHtA3GoAe5q8uZ2+N9GLGOaDENOwOnPDADiDOY6QxC0AC4otJYwiR3ELQAI4wGALSR7yEBIKKawoCOtCYwpYLPenL0WJkXmnGORkF++Y4GQh8MurQ4kwL4b5T22tdwLPizw2NsQyIuy6IUqKqR6PcBLrmSBGHd71j-b2dz9aEC2mCFe777F3zoQ374LQAAsqgMAJhgqnxeAOYm99czimWHdP+AhoHtgzukAscxJ57DwugHkBA5TBQQmOaYgwHZEUqHvH+iDyS0HWGgZcWU35gGgXEas0I1C0ChHMWgkAYEIP4OSTB9A8KZ0PsIQhTAWi2hxGI1EY4PT4A7GQwuex96QWEHKO0iFBjiBHJHQq9kQTQMgEiXhAYwbgkEeOPw+AwoyJzng3wkA7HvjwtxZgqdCGQHmuHHe6paBL10LQAAau4BakdWZfAibLAA1Mo+g8MAAKw5czdnMQ3ERmRLpZRaM9ascYNLJ3skUZJlixwACVOwAFV5xBzKQAfWLpUgEZT1jwkXhdZeITcxlMKeIHOZAbrwHafYQJq9172IDigNYNcpyogCeIFea8N57AnBXAO5JhnLzGcs+gY5dRIGIMQecSBjlQE2aMpZOd7rgg0WCc5Cztn9KQKQJgCh7mLPGXlb+tAmQKKMD+XMcRR7GPsv8nMd0kC8IydYUpkB3qSDgACOADpnFTzXHnWepxXGQ0ITNTYcBSBKLnrKNQ7yulhNoNzL4vg4n+IuuJJA+BMAUNoPOB+vU2HEl6knHsdAwCR0gKIYgMB0DPR4aPFQY11HmJUKkckiZxDLC5HSge8BeGD0ge4wJt9eEcoOFAblZjNHN1bu3XhxhIC3LoDqlQvzQUAomCy0sYpczFAiEUkxsAZCjz1W0A1PLzFxkoh6h+tq7jiDBaqL4OdOVnLmR0wJXTKXUtpfDF2SAySV0RNQ8iGaK6XR-CCHEEMAwGKYcGHO1Zlhv3xYS+NIyHmXLnrSOtOcw5lXeY8ue70XmdqbVPO2swUBfyLhdIOOIHanwrsQcuoheQXxorHLhmN4EtELSwXMaAJ1qFKeKDtyqxx7slAARXcIqvtnysWqTHIPF0Zg134ExVhIhD65hPqnre5EwDbg72Vbs64P631-vHJ+lolSoC0lmdemk5Jh3AbHOu5gsH30rPQIh5D8HQNoEqRAAD1gyWhIJsmml3kxy3Dw-gODKrOmEcjlSkjzEb0RGRLQsYjhlgod2egNjSBlhAevbXDi85HRzqA9RxNtHiMCasEJxdH0qPzOCZJ+j177KOHEAgf4cUxOKfJURiJwsvgxMWOqVN9KwTJTKWgRDuYEklDLcwpxBK36uvs3oct3Csr0PQNYJOd9R5rqkXKeBwhlhjEIKU54bwUDOJZVZ7JkB5BRwfugIV7ZyAbqAq+TROrR7QrYvAL1li8J8H-rM8cgn7JEqnpV8QQdxDqafcRIwAhTpAwgIacA0B4AuwHJaScnXIHCDs60Qx4gsAOncEaO2KDOyFfgBN02KIQDCCxkEphopj4YGwDNloIAbBAA)

**Comment by jongwoo328** [comment]
Redefining a computed property with the same name as one brought in via `...mapGetters` can cause unexpected issues. That might be the root cause here. In this case, changing the order arbitrarily may lead to inconsistent behavior compared to before.

**Comment by Tofandel** [comment]
The reordering affects the parent keys (mounted, computed methods), not the nested ones under computed, the order of the computed declaration is not modified. So there is no risk of breaking anything there.
