### ISSUE TITLE
html-indent not working for indentation issues

### ISSUE THREAD

**Issue by pallavisingh1511** [vuejs/eslint-plugin-vue#744]
**Tell us about your environment**
Mac OS X 10.13.2
Visual Studio Code 1.30.1

ESLint Version: 3.19.0
eslint-plugin-vue Version: 5.0.0
Node Version: 8.9.3

**Please show your full configuration:**
```
module.exports = {
	root: true,
	parser: "babel-eslint",
	parserOptions: {
		sourceType: "module"
	},
	env: {
		browser: true
	},
	extends: ["standard", "eslint:recommended", "plugin:vue/recommended"],
	plugins: ["html", "vue"],
	rules: {
		"vue/html-indent": [
			"error",
			"tab",
			{ alignAttributesVertically: true }
		],

		indent: ["error", "tab"],
		"arrow-parens": 0,
		"generator-star-spacing": 0,
		"no-debugger": process.env.NODE_ENV === "production" ? 2 : 0
	}
}
```
**What did you expect to happen?**
indentation error logs

**What actually happened? Please include the actual, raw output from ESLint.**
vue/html-indent did not log any indentation errors, while there were many

**Comment by michalsnik** [comment]
Hey @pallavisingh1511 Please take a look at the documentation here: https://vuejs.github.io/eslint-plugin-vue/user-guide/#why-doesn-t-it-work-on-vue-file
