### ISSUE TITLE
What does the "wrench" mean on the Available Rules page of the docs?

### ISSUE THREAD

**Issue by NathanKleekamp** [vuejs/eslint-plugin-vue#749]
On the [Available Rules](https://eslint.vuejs.org/rules/) page of the docs, the tables have a third column that doesn't include a heading. Some of the rules have a "wrench" (🔧) next to them. What does that indicate? Thanks!

**Comment by LinusBorg** [comment]
It indicates that this rule is fixable, meaning eslint can correct the problem that this rule reports.

**Comment by michalsnik** [comment]
I added legend on top of the rules' listing. Should be more clear now :)
