### ISSUE TITLE
html attribute in vue : eslint raises error "defined but never used"

### ISSUE THREAD

**Issue by liteultom** [vuejs/eslint-plugin-vue#781]
**Tell us about your environment**

* **Platform: Linux Ubuntu 16.04LTS**
* **VS Code version: 1.29.1**
* **ESLint Plugin vue Version: 4.7.1**
* **ESLint Version: 1.7.2**
* **Node Version: 8.12.0**
* **npm Version: 6.4.1**

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
  root: true,
  parserOptions: {
    parser: 'babel-eslint',
    sourceType: 'module'
  },
  env: {
    browser: true
  },
  extends: [
    // https://github.com/vuejs/eslint-plugin-vue#priority-a-essential-error-prevention
    // consider switching to `plugin:vue/strongly-recommended` or `plugin:vue/recommended` for stricter rules.
    'plugin:vue/essential',
    // https://github.com/standard/standard/blob/master/docs/RULES-en.md
    'standard'
  ],
  // required to lint *.vue files
  plugins: [
    'vue'
  ],
  globals: {
    'ga': true, // Google Analytics
    'cordova': true,
    '__statics': true
  },
  // add your custom rules here
  'rules': {
    // allow async-await
    'generator-star-spacing': 'off',

    // allow paren-less arrow functions
    'arrow-parens': 0,
    'one-var': 0,

    'import/first': 0,
    'import/named': 2,
    'import/namespace': 2,
    'import/default': 2,
    'import/export': 2,
    'import/extensions': 0,
    'import/no-unresolved': 0,
    'import/no-extraneous-dependencies': 0,

    // allow debugger during development
    'no-debugger': process.env.NODE_ENV === 'production' ? 2 : 0
  }
}

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

Note : it's in a `.vue` file, in the template part
```html
<template slot="top-left" slot-scope="props">
    <div>Hello there</div>
</template>
```

**What did you expect to happen?**
No error
Note : it was note raising any error the last time I opened this project about 2 month ago. the ` slot-scope="props"` is necessary for quasar-framework to know where to put the element, but I  don't use `props` myself

**What actually happened? Please include the actual, raw output from ESLint.**
[eslint-plugin-vue]
[vue/no-unused-vars]
'props' is defined but never used

**Comment by Eflet** [comment]
you can change like this
```
<template slot="top-left" slot-scope="{}">
    <div>Hello there</div>
</template>
```

**Comment by ota-meshi** [comment]
@Eflet. Thank you for suggesting a solution.

If destructuring assignment is not available in your environment, use the ignorePattern option.
