### ISSUE TITLE
what is the difference between eslint-plugin-html and this one?

### ISSUE THREAD

**Issue by zzzgit** [vuejs/eslint-plugin-vue#8]
Hello,I found that `eslint-plugin-html` can support `.vue` files as well.
So,what is the difference between the two plugins?

**Comment by chrisvfritz** [comment]
We also include a rule for JSX and will potentially include others useful for Vue in the future.

**Comment by znck** [comment]
It depends on `eslint-plugin-html` and adds support for jsx. If you're not using jsx, then you can use any of these.

**Comment by zzzgit** [comment]
thanks very much
