### ISSUE TITLE
@vue/cli-plugin-eslint does not install latest version of eslint-plugin-vue

### ISSUE THREAD

**Issue by guanzo** [vuejs/eslint-plugin-vue#831]
I have a vue project created with `@vue/cli`. How do I ensure that `eslint-plugin-vue` is always up to date? I want to use the latest rules.

 I just installed `"@vue/cli-plugin-eslint": "^3.4.1",` which is the latest version, but it installs an old version of `eslint-plugin-vue@4.7.1`. The current version is `eslint-plugin-vue@5.2.2`.

**Comment by mysticatea** [comment]
Thank you for this report.

But please open an issue on `@vue/cli`'s repository.
