### ISSUE TITLE
Conflict with eslint-plugin-prettier

### ISSUE THREAD

**Issue by blowsie** [vuejs/eslint-plugin-vue#832]
**Tell us about your environment**	
* **ESLint version:** ^5.14.1	
* **eslint-plugin-vue version:** ^5.2.2	
* **Node version:**	v10.10.0

**Please show your full configuration:**

```js
module.exports = {
  root: true,
  env: {
    browser: true,
    node: true
  },
  parserOptions: {
    parser: 'babel-eslint'
  },
  extends: ['@nuxtjs', 'plugin:vue/recommended', 'plugin:prettier/recommended'],
  plugins: ['prettier', 'vue'],
  // add your custom rules here
  rules: {}
}
```
Generated by `create-nuxt-app`.

**What did you do?**	

Both of these will show cause eslint to error when using 
 'plugin:prettier/recommended' and  'plugin:vue/recommended'

```<img src="one.jpg" />```
```<img src="one.jpg">```

![image](https://user-images.githubusercontent.com/308572/53407278-b3347700-39b3-11e9-9c82-039f885a9455.png)
![image](https://user-images.githubusercontent.com/308572/53407291-bf203900-39b3-11e9-98bc-f42ae8c81b95.png)

**What did you expect to happen?**
To be able to format an image without error

**What actually happened?**

Impossible to format image without error.

--- 
Its worth noting that this conflict on appears on certain versions (current latest included)

A snippet of my versions from `package.json`
```
    "eslint": "^5.14.1",
    "eslint-config-prettier": "^4.0.0",
    "eslint-config-standard": ">=12.0.0",
    "eslint-loader": "^2.1.2",
    "eslint-plugin-import": ">=2.16.0",
    "eslint-plugin-jest": ">=22.3.0",
    "eslint-plugin-node": ">=8.0.1",
    "eslint-plugin-prettier": "3.0.1",
    "eslint-plugin-promise": ">=4.0.1",
    "eslint-plugin-standard": ">=4.0.0",
    "eslint-plugin-vue": "^5.2.2",
```

**Comment by blowsie** [comment]
https://github.com/prettier/eslint-plugin-prettier/issues/167

**Comment by mysticatea** [comment]
Thank you for the report.

If you are using a code formatter, I recommend disabling ESLint rules which format code. It's duplicated work.

**Comment by blowsie** [comment]
So to be clear, `eslint-plugin-vue` does not plan to be compatible with prettier?

**Comment by mysticatea** [comment]
Everyone can configure ESLint rules as they like.
