### ISSUE TITLE
Seems to be linting outside of `<template/>` and `<script/>`

### ISSUE THREAD

**Issue by ohbadiah** [vuejs/eslint-plugin-vue#856]
**Tell us about your environment**	
* **ESLint version:** v4.19.1
* **eslint-plugin-vue version:** 4.3.0
* **Node version:* 5.6.0

**Please show your full configuration:**

```
module.exports = {
  root: true,
  parserOptions: {
    parser: 'babel-eslint'
  },
  env: {
    browser: true,
  },
  extends: [
    // https://github.com/vuejs/eslint-plugin-vue#priority-a-essential-error-prevention
    // consider switching to `plugin:vue/strongly-recommended` or `plugin:vue/recommended` for stricter rules.
    'plugin:vue/recommended',
    // https://github.com/standard/standard/blob/master/docs/RULES-en.md
    'standard'
  ],
  // required to lint *.vue files
  plugins: [
    'vue'
  ],
  // add your custom rules here
  rules: {
    // allow async-await
    'generator-star-spacing': 'off',
    'max-len': [2, 100, 2],
    'no-var': 2,
    // allow debugger during development
    'no-debugger': process.env.NODE_ENV === 'production' ? 'error' : 'off'
  }
}
```

I'm introducing the [vue-i18n plugin](https://kazupon.github.io/vue-i18n/), which has [a custom loader](https://github.com/kazupon/vue-i18n-loader/) that [allows internationalization copy to be placed in custom `<i18n/>` blocks within the single component file](https://kazupon.github.io/vue-i18n/guide/sfc.html#basic-usage). The contents of these blocks must be pure json.

```vue
<i18n>
  "en": {
    "translation-key": "A realllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllly long string"
  }
</i18n>
```

**What did you expect to happen?**
I expected vue-eslint to only lint the `<template/>` and `<script/>` tags of the component file, ignoring the `<i18n/>` tag above.

**What actually happened?**
```
/app/src/components/MyComponent.vue
  5:1  error  Line 5 exceeds the maximum line length of 100  max-len
```

**Comment by mysticatea** [comment]
Yes, this is [a known limitation](https://github.com/mysticatea/vue-eslint-parser#%EF%B8%8F-known-limitations) of `vue-eslint-parser` because the `max-len` rule doesn't based on AST.

**Comment by Justineo** [comment]
Shall we use an option to allow certain custom blocks to be skipped? Or we can only handle known blocks by default and let users specify more custom blocks to be linted.

**Comment by mysticatea** [comment]
Unfortunately, plugins cannot change the behavior of core rules.

**Comment by ohbadiah** [comment]
So shall i close the issue? Perhaps with some sort of `can't fix` label?

**Comment by ChristianStornowski** [comment]
You could use:

```
<!-- eslint-disable -->
<i18n>
  "en": {
    "translation-key": "A realllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllly long string"
  }
</i18n>
<!-- eslint-enable -->
```

**Comment by ota-meshi** [comment]
I have added the [vue/max-len](https://eslint.vuejs.org/rules/max-len.html#vue-max-len) rule to the latest version. Please use [vue/max-len](https://eslint.vuejs.org/rules/max-len.html#vue-max-len) rule.
