### ISSUE TITLE
no-unused-components  with class-components does not work

### ISSUE THREAD

**Issue by D3-FC** [vuejs/eslint-plugin-vue#857]
**.eslintrc.js:**

```js
module.exports = {
  root: true,
  env: {
    node: true
  },
  'extends': [
    'plugin:vue/essential',
    '@vue/standard',
    '@vue/typescript'
  ],
  rules: {
    'no-console': process.env.NODE_ENV === 'production' ? 'error' : 'off',
    'no-debugger': process.env.NODE_ENV === 'production' ? 'error' : 'off',
  },
  parserOptions: {
    parser: '@typescript-eslint/parser'
  }
}

```
**eslint-plugin-vue version: ** `^5.0.0`

**Node version:** `v8.12.0`

#### My Actions:
**1. Created new vue-cli project**

**2. Created component**

```vue
<template>
  <div>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator'
import TestComponent from '@/components/TestComponent.vue'
@Component({
  components: { TestComponent }
})
export default class HelloWorld extends Vue {

}
</script>
```

3. Ran linter with command: 'vue-cli-service lint'

#### What actually happened?: 
linter log: ` DONE  No lint errors found!`

#### Expecting Error:
Component `TestComponent` was registered, but never used

**Comment by negibouze** [comment]
@D3-FC Here is my workaround.
https://github.com/negibouze/customize-no-unused-components-rule

**Comment by tomiiide** [comment]
Any official fix for this ?

**Comment by ota-meshi** [comment]
No progress has been made on this so far.

**Comment by beit46** [comment]
do you still plan to support this?

**Comment by NikhilVerma** [comment]
@negibouze Has a great solution but it didn't work for me because I was using the following ESLint config

```
{
        parser: require.resolve("vue-eslint-parser"),
	parserOptions: {
		parser: "@typescript-eslint/parser"
        }
}
```

So I updated his rule and the updated code is here - https://gist.github.com/NikhilVerma/7613191dfffb38011ebb3c95468a423a

Follow his repo example to see how to use it : https://github.com/negibouze/customize-no-unused-components-rule
