### ISSUE TITLE
prop-name-casing autofix removes $ in prop name

### ISSUE THREAD

**Issue by privatenumber** [vuejs/eslint-plugin-vue#862]
**Tell us about your environment**	
* **ESLint version:** 5.15.3
* **eslint-plugin-vue version:** 5.2.2
* **Node version:**	8.12.0

**What did you do?**	
`eslint --fix`

**What did you expect to happen?**
For renaming to happen on non-camelCase props.

**What actually happened?**
My prop name `$actionEl` (which I know has another problem of it's own) was renamed to `actionEl`.

**Comment by mysticatea** [comment]
Thank you for the report.

I could reproduce it on [our online demo](https://mysticatea.github.io/vue-eslint-demo/#eJw9j8FqwzAMhl9FiJ1KTKBHU3rYHmG7NT0YRy6GTDKSU9qGvPtsxgbiR/8H0i9tGGUm9HiyqLnU88TjAciWzBXuK41FpTgO3+RisMw3DxdSFR0gNrh8BKMrHMaJ6VFEK8yUwrpU2CYG6MPmf3uAtyTyHrT5vYMmrU7jfzAOqOtChn7DHs3ionBae6y7uyTaNCf0x33AzDNx/cyvdvzxz349S//FSojUtpWgRtoAWVEi3H8AgedR/A==).

**Comment by hirokiosame** [comment]
In addition to fixing the autofix logic here, it might be worth introducing a rule to prevent non-alphanumerical characters in prop names.
