### ISSUE TITLE
Validate rule options

### ISSUE THREAD

**Issue by rightaway** [vuejs/eslint-plugin-vue#866]
**What category should the rule belong to?**

- [ ] Enforces code style
- [x] Warns about a potential error
- [ ] Suggests an alternate way of doing something
- [ ] Other (please specify:)

I'm using yaml to specify rules and if I misspell the name of an option or the term `error` it doesn't give an error. Or if I misspell the name of the rule itself it doesn't fail the eslint command immediately like it would if I misspelled a core eslint rule. Instead every .vue file gets an error saying that rule can't be found. Vue rules should be validated and handled the same way as core rules because right now I have no idea if my rules are working as they should because if I've misspelled anything.

**Comment by rightaway** [comment]
It's working for options now. But still not for the rule name itself. If I type `vue/arrow-spacing` as `vue/arrow-spacin` should the eslint command fail? It just gives `Definition for rule 'vue/arrow-spacin' was not found  vue/arrow-spacin` error next to every file.

**Comment by ota-meshi** [comment]
Thank you for your response.
Probably your problem is about the ESLint engine, so please suggest it in the ESLint repository. The existence check of the rule cannot be done from the plugin.
