### ISSUE TITLE
Issues based on core eslint rules should document options

### ISSUE THREAD

**Issue by rightaway** [vuejs/eslint-plugin-vue#867]
Rules like brace-style that come from core eslint rules should have their options documented rather than referring to the options in the corresponding core rules, because if eslint changes their options if the code hasn't been updated in these rules to reflect them then the eslint core documentation doesn't apply to these rules. So options should be documented separately to reflect what's in the latest stable set of rules for this plugin.

**Comment by ota-meshi** [comment]
Thank you for this issue.

However, the options depend on the version of ESLint you are using.
So I don't think we need to document the options.
