### ISSUE TITLE
Documentation link "Use together with custom parsers" goes nowhere

### ISSUE THREAD

**Issue by bbugh** [vuejs/eslint-plugin-vue#868]
In the [FAQ section of the user guide](https://vuejs.github.io/eslint-plugin-vue/user-guide/#faq), there's a link that says "Use together with custom parsers". The link doesn't seem to work, presumably because that section no longer exists (sadly, as that is what I'm looking for).

The invalid link is: https://vuejs.github.io/eslint-plugin-vue/user-guide/#use-together-with-custom-parsers

**Comment by ota-meshi** [comment]
Thank you. I will fix this.
