### ISSUE TITLE
Error using JSX

### ISSUE THREAD

**Issue by rohmanhm** [vuejs/eslint-plugin-vue#9]
Software: vscode 1.11.0
OS: macOS

Hi, I followed your instruction on README file, but I got this error.

![screen shot 2017-04-06 at 2 34 35 pm](https://cloud.githubusercontent.com/assets/7524911/24742857/397106b6-1ad6-11e7-942d-116682bae81c.png)

Here's my eslint config 
```javascript
module.exports = {
  root: true,
  parser: 'babel-eslint',
  parserOptions: {
    ecmaVersion: 6,
    sourceType: 'module',
    ecmaFeatures: {
      jsx: true
    }
  },
  // https://github.com/feross/standard/blob/master/RULES.md#javascript-standard-style
  extends: ['vue', 'standard'],
  // required to lint *.vue files
  plugins: [
    'vue',
    'html'
  ],
  // add your custom rules here
  'rules': {
    // allow paren-less arrow functions
    'arrow-parens': 0,
    // allow async-await
    'generator-star-spacing': 0,
    // allow debugger during development
    'no-debugger': process.env.NODE_ENV === 'production' ? 2 : 0,
    'no-use-before-define': 0
  }
}

```
Any solution please

**Comment by chrisvfritz** [comment]
Just getting to this now, but not able to reproduce this issue. Is this something you only notice in VS Code or do you also see these errors when running ESLint from the command line?

**Comment by rohmanhm** [comment]
As you can see in `Problem` tab.
eslint run without erros.

It's vetur bugs.
