### ISSUE TITLE
vue/singleline-html-element-content-newline autofix inserts semantic whitespace

### ISSUE THREAD

**Issue by peterwj** [vuejs/eslint-plugin-vue#906]
Related to #827 

**Tell us about your environment**	
* **ESLint version:**	5.16.0
* **eslint-plugin-vue version:**  5.2.2	
* **Node version:**	  v8.10.0

**Please show your full configuration:**

```js
module.exports = {
    "env": {
        "browser": true,
        "commonjs": true,
        "es6": true,
        "node": true
    },
    "extends": [
        "airbnb-base",
        "plugin:vue/recommended",
        "plugin:jest/recommended"
    ],
    "parserOptions": {
        "ecmaVersion": 2018
    },
    "globals": {
        "bus": true, // TODO: reduce reliance on bus and remove this from window.
    },
    "rules": {
        "indent": [
            "error",
            4,
            {
                "MemberExpression": 0,
                "CallExpression": {
                    "arguments": "first"
                }
            }
        ],
        "vue/html-indent": ["error", 4],
    },
};

```

**What did you do?**	

```vue
<style lang="scss">
</style>

<template>
    <div>
        In the meantime you can return to <router-link to="/">home</router-link>.
    </div>
</template>

<script>
export default {
    name: 'Error404',
};
</script>
```

**What did you expect to happen?**
I'm not sure what I expect to happen.

**What actually happened?**
eslint reports a violation with the above code.  When run with `--fix`, eslint inserts a newline between `home` and `</router-link>`.  This newline is meaningful in this context, as it causes the browser to render the component with a space between "home" and the period.  Changing `router-link` to `a` causes eslint to not report a violation.
```
± % ./node_modules/.bin/eslint  client/views/error-404.vue

/home/peterwj/src/project/client/views/error-404.vue
  6:63  warning  Expected 1 line break after opening tag (`<router-link>`), but no line breaks found    vue/singleline-html-element-content-newline
  6:67  warning  Expected 1 line break before closing tag (`</router-link>`), but no line breaks found  vue/singleline-html-element-content-newline

✖ 2 problems (0 errors, 2 warnings)
  0 errors and 2 warnings potentially fixable with the `--fix` option.

```

**Comment by ota-meshi** [comment]
Hello!

You can extend the `ignores` option to exclude `<router-link>` from verification targets.

https://eslint.vuejs.org/rules/singleline-html-element-content-newline.html#options

**Comment by peterwj** [comment]
cool; thank you for pointing that out in the documentation!  That should resolve this issue.

**Comment by gavinhungry** [comment]
@ota-meshi,

Is there some to extend the default `ignores` option in my `.eslintrc` file, or do I need to copy every inline element from [inline-non-void-elements.json](https://github.com/vuejs/eslint-plugin-vue/blob/master/lib/utils/inline-non-void-elements.json)?
