### ISSUE TITLE
Conflict with the eslint-plugin-html

### ISSUE THREAD

**Issue by iGarym** [vuejs/eslint-plugin-vue#91]
- version: 3.5.1
- vue-cli: 2.8.2

```
// Copy from webpack-template
extends: 'airbnb-base',
plugins: [
  'html'
],
```
After adding the plugin to extends, as below, eslint has no effect on the js in the vue single file component.

```
// Copy from webpack-template
extends: [
  'airbnb-base',
  'plugin:vue/recommended',
],
plugins: [
  'html'
],
```

不算bug吧？ remove `html` 插件就好了。

**Comment by mysticatea** [comment]
Thank you for the report.

`eslint-plugin-html` seems to remove outside of `<script>` tags then it gives only inside of `<script>` tags to this plugin. However, this plugin requires the outside of `<script>` tags.

Please configure `eslint-plugin-html` to not strip source code on `.vue` files.

```js
{
    "plugins": [ "html" ],
    "settings": {
        "html/html-extensions": [".html"],  // don't include .vue
    }
}
```

> https://github.com/BenoitZugmeyer/eslint-plugin-html#settings

**Comment by prograhammer** [comment]
@mysticatea Adding the settings as you mention still doesn't fix the problem. Vue files seem to not be getting the linting as the .js files are. Here is a basic Hello example: https://github.com/prograhammer/hello

I'm using VS Code. If you `npm install` and then open the project in VS Code you'll see that adding extra spaces in `doc.js` lints perfectly. But adding extra spaces in `app.vue` does not lint. 

BTW, this is my VS Code settings.json:

```
// Place your settings in this file to overwrite the default settings
{
    "[javascript]": {
        "editor.tabSize": 2,
        "editor.insertSpaces": true,
		"eslint.options": {
			"extensions": [
				".html",
				".js",
				".vue",
				".jsx"
			]
		},
		"eslint.validate": [
			{
				"language": "html",
				"autoFix": true
			},
			{
				"language": "vue",
				"autoFix": true
			},
			{
				"language": "javascript",
				"autoFix": true
			},
			{
				"language": "javascriptreact",
				"autoFix": true
			}
		]
	}
}
```

**Comment by armano2** [comment]
You have to add configuration for `[vue]`

_Sent from my Xiaomi Redmi 4A using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by prograhammer** [comment]
@armano2 What do you mean? I've installed the vetur extension for Vue if that's what you mean.

**Comment by prograhammer** [comment]
Ok, solved!

I updated my settings.json (file > preferences > settings) to look like this:

```
// Place your settings in this file to overwrite the default settings
{
    "[javascript]": {
        "editor.tabSize": 2,
        "editor.insertSpaces": true
    },
    "[vue]": {
        "editor.tabSize": 2,
        "editor.insertSpaces": true
    },
    "eslint.options": {
        "extensions": [".html", ".js", ".vue", ".jsx"]
    },
    "eslint.validate": [
        {
            "language": "html",
            "autoFix": true
        },
        {
            "language": "vue",
            "autoFix": true
        },
        {
            "language": "javascript",
            "autoFix": true
        },
        {
            "language": "javascriptreact",
            "autoFix": true
        }
    ]
}
```
Works beautifully!

**Comment by jinalskothari** [comment]
I came to face the same issue. My .eslintrc was generated by `vue-cli init webpack [name]`.

I am guessing many people new to the ecosystem would use that template and may come across the issue. A small section in the README may be worthwhile.

**Comment by flaviojs** [comment]
Encountered this problem and found that placing `"vue"` before `"html"` in `"plugins"` fixed it for me.
```
{
    "plugins": [
        "vue",
        "html"
    ]
}
```
