### ISSUE TITLE
Script-indent need to ignore the base indent, or to support both baseIndent: 0 and baseIndent:1

### ISSUE THREAD

**Issue by hzsrc** [vuejs/eslint-plugin-vue#918]
**Tell us about your environment**	
**"eslint": "5.16.0",**
**"eslint-plugin-vue": "5.2.3",**	
**node : v 11**

**Please show your full configuration:**

```js
module.exports = {
    root: true,
    parserOptions: {
        parser: 'babel-eslint',
        sourceType: 'module'
    },
    env: {
        browser: true,
    },
    extends: [
        // https://github.com/vuejs/eslint-plugin-vue#priority-a-essential-error-prevention
        // consider switching to `plugin:vue/strongly-recommended` or `plugin:vue/recommended` for stricter rules.
        'plugin:vue/essential',
        // https://github.com/standard/standard/blob/master/docs/RULES-en.md
        'standard'
    ],
    // required to lint *.vue files
    plugins: [
        'vue'
    ],
    // add your custom rules here
    'rules': {
        'indent': ['error', 2],
        'vue/script-indent': ['error', 2, { 'baseIndent': 1 }],
    },
    'overrides': [
        {
            'files': ['*.vue'],
            'rules': {
                'indent': 'off'
            }
        }
    ]
}

```

**What did you do?**	

```vue
<script>
const a = 1;
export default {
  render(h) {
    return '<div></div>'
  }
}
</script>
```

**What did you expect to happen?**

#### We have different editors in our team, some editors indent the script tag, and some do not. So whatever we set the `baseIndent` option to `1` or `0` ,  always there are someone have eslint errors while formatting code in their own editors .

 We can't force all the developers to use a same editor. So we suggest that the `script-indent` need to ignore the base indent, or to support both baseIndent: 0 and baseIndent:1( like `baseIndent: [0, 1]` )

**What actually happened?**

 error  Expected indentation of 2 spaces but found 0 spaces

**Comment by akoidan** [comment]
Any updates?

**Comment by ota-meshi** [comment]
The script-indent rule aims to enforce consistent indentation. Therefore, we will not make any changes to accept the two styles.
