### ISSUE TITLE
The "no-irregular-whitespace" rule prevents proper typography

### ISSUE THREAD

**Issue by iamvdo** [vuejs/eslint-plugin-vue#926]
In French, double punctuation marks (;, :, ! and ?) take a non-breakable space before them. Writing in French inside `<template>` returns the `no-irregular-whitespace` error.

Test for yourself:
```vue
<template>
  <div>
    Bonjour !
  </div>
</template>
```

Is it a usecase `eslint-plugin-vue` can handle? Allowing whitespaces inside `<template>`?

Or, how am I supposed to deal with that?

Thanks!

**Comment by Samuelfaure** [comment]
I would love more informations on this. For now I am forced to ignore completely the `no-irregular-whitespace` rule.

**Comment by ota-meshi** [comment]
Thank you for this issue.

I think we need to add a new rule `vue/no-irregular-whitespace` dedicated to vue files to this plugin.
The `vue/no-irregular-whitespace` rule requires additional options to ignore inline values ​​of attributes, and ignore HTML text content.
