### ISSUE TITLE
vue-eslint-parser version mixup

### ISSUE THREAD

**Issue by backbone87** [vuejs/eslint-plugin-vue#929]
on [master](https://github.com/vuejs/eslint-plugin-vue/blame/master/package.json#L49) the vue-eslint-parser version is `^6.0.2` (changed in february), but in latest tag [`5.3.2`](https://github.com/vuejs/eslint-plugin-vue/blame/v5.2.3/package.json#L49) (released in june) the dep is on version `^5.0.0` (changed in january).

-> vue-eslint-parser 5.x will be installed

how can a release from june, contain a change from january, but not the one from february?

can we pls have this fixed?

**Comment by ota-meshi** [comment]
Thank you for this issue.

`eslint-plugin-vue@6` has been released. Please use `eslint-plugin-vue@6`.
