### ISSUE TITLE
is there a tslint plugin similar to what vuejs/eslint-plugin-vue did

### ISSUE THREAD

**Issue by zhoulang27426405** [vuejs/eslint-plugin-vue#934]
i want to lint my vue file in ts,but i connot find a plugin similar to what vuejs/eslint-plugin-vue did

**Comment by sem4phor** [comment]
With `vue-eslint-parser` and `@typescript-eslint` you can lint vue in ts.

example config: 

```
module.exports = {
  parser: 'vue-eslint-parser',
  extends: [
    'plugin:vue/recommended',
    '@vue/standard',
    '@vue/typescript',
    'plugin:@typescript-eslint/eslint-recommended',
    'plugin:vue-a11y/base'
  ],
  parserOptions: {
    parser: '@typescript-eslint/parser',
    project: 'tsconfig.json'
  }
}
```

For more information see:
https://www.npmjs.com/package/vue-eslint-parser
https://github.com/typescript-eslint/typescript-eslint

**Comment by IlCallo** [comment]
Check [Quasar TypeScript extension](https://github.com/quasarframework/app-extension-typescript/tree/dev/extension/src/templates) to see how to setup it properly.

Expecially `base/tsconfig.json` and `noprettier/eslintrc.js`

**Comment by ota-meshi** [comment]
I'm not familiar with tslint, but I think the same is possible using `@typescript-eslint`, as others have answered. I close this question because I think it has been answered.
