### ISSUE TITLE
vue/html-self-closing rule is against vuejs docs style guide recommendation 

### ISSUE THREAD

**Issue by luckylooke** [vuejs/eslint-plugin-vue#965]
vue/html-self-closing prohibits self-closing elements and this rule is [recommended by linters](https://github.com/vuejs/eslint-plugin-vue/blob/master/docs/rules/html-self-closing.md#vuehtml-self-closing)... but I agree with [vuejs docs](https://vuejs.org/v2/style-guide/#Self-closing-components-strongly-recommended) where it is strongly recommended. It is more readable and clean. Argument that it is not HTML spec is IMHO irrelevant as vue templates are compiled into render functions so it is up to Vue framework to output valid HTML according specs.

I am open to discussion.

Thanks

**Comment by SebastianNiemann** [comment]
There might be a misunderstanding. The VueJS recommendation is only focused on custom components. This is already set as default:

> html.component ("always" by default) ... The style of Vue.js custom components.

However, the VueJS documentation is not stating to self-close standard HTML components, only custom components.

I also don't see the benefit of opposing the standard HTML over this. Reusing existing solutions would then require additional effort (without adding any additional functionality), just to see a few less characters in the pre-build source file.

**Comment by luckylooke** [comment]
Yes it seems to me as misunderstanding too.. I have read it all again and it sees they are not against each other but they agree on forcing self closing. I remember to get "vue/html-self-closing" error in SFC for my custom component, which is strange. But maybe I have used something like `<my-component>` like for void elements, instead of  self-closing`<my-component />` and misunderstood the rule. I cannot reproduce this anymore... I have had different setup (using symfony encore), now I am on Vue CLI and I cannot reproduce this. So closing. Thanks anyway and happy coding ;)
