### ISSUE TITLE
 wrong output in vue-eslint-parser

### ISSUE THREAD

**Issue by Mister-Hope** [vuejs/eslint-plugin-vue#981]
**Tell us about your environment**	
* **ESLint version:**	6.6.0
* **eslint-plugin-vue version:**	6.0.0
* **Node version:**	12.13.0

When installing

```
npm WARN vue-eslint-parser@6.0.4 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
```

It should not be displayed since you said `eslint-plugin-vue` support eslintV6

**Comment by ota-meshi** [comment]
Thank you for this issue.

As you say, `vue-eslint-parser` defines `eslint@^5.0.0` in `peerDependencies`.

`vue-eslint-parser` still needs to be updated to officially support ESLint@6. However, a new version of `vue-eslint-parser` has not been released yet.

Also, currently a message is displayed on `npm install`, but `eslint-plugin-vue` works fine with ESLint@6.

https://github.com/vuejs/eslint-plugin-vue/issues/920#issuecomment-550401428

**Comment by luzik** [comment]
Then how to install it ?
On fresh install i got such line in dependency tree:
`UNMET PEER DEPENDENCY eslint@^5.0.0`
and eslint shows `ESLint couldn't find the plugin "eslint-plugin-vue".`
