### ISSUE TITLE
cannot recognize "Lazy Loading Routes" syntax

### ISSUE THREAD

**Issue by congzhou09** [vuejs/eslint-plugin-vue#991]
★Tell us about your environment
vue@2.6.10
eslint@5.16.0
eslint-plugin-vue@5.2.3
node@10.15.3

★Please show your full configuration:
".eslint.js" file as follows:
module.exports = {
    root: true,
    extends: ['plugin:vue/recommended', 'plugin:prettier/recommended'],
    env: {
      "browser": true,
      "commonjs": true,
      "es6": true,
      "node": true
    },
};

★What did you do?
run eslint to lint the file:    eslint --fix src/router/index.js

★What did you expect to happen?
lint the file

★What actually happened?
an error generated:    Parsing error: Unexpected token import

The error is reported from eslint, but eslint-plugin-vue have installed and configurated. Seems that eslint-plugin-vue cannot recognize "Lazy Loading Routes" syntax.

![图片](https://user-images.githubusercontent.com/6285483/69331094-24793000-0c8f-11ea-9361-f933066ce1bd.png)

![图片](https://user-images.githubusercontent.com/6285483/69331369-9782a680-0c8f-11ea-8a26-b9c0fafd95c8.png)

**Comment by congzhou09** [comment]
"Lazy Loading Routes" syntax is explained in the [offical website](https://router.vuejs.org/guide/advanced/lazy-loading.html#grouping-components-in-the-same-chunk) , which works smoothly.

**Comment by sodatea** [comment]
Dynamic import wasn't in the ECMAScript standard when ESLint 5 came out.
So you have to use `babel-eslint` to parse such syntax.
Or you can upgrade to ESLint 6.

**Comment by sodatea** [comment]
To use `babel-parser`, see https://eslint.vuejs.org/user-guide/#usage
