### ISSUE TITLE
Simple prop declaration replaces "" with nothing when auto-fixing

### ISSUE THREAD

**Issue by carestad** [vuejs/eslint-plugin-vue#993]
**Tell us about your environment**	
* **ESLint version:**	v6.7.1
* **eslint-plugin-vue version:**	v6.0.1
* **Node version:** v12.13.0

**Please show your full configuration:**

```json
{
    "extends": [
        "eslint:recommended",
        "plugin:vue/recommended"
    ],
    "plugins": [
        "vue"
    ]
}
```

**What did you do?**	

```vue
<template>
  <div>
    <h1>Hello</h1>
  </div>
</template>

<script>
export default {
  name: 'Test',
  props: {
    foo: "",
  },
};
</script>
```

Running `eslint test.vue` gives me the following:

![image](https://user-images.githubusercontent.com/65263/69540888-1b86a800-0f88-11ea-8083-5abfbe162eda.png)

And then after running `eslint --fix test.vue`

![image](https://user-images.githubusercontent.com/65263/69540904-26413d00-0f88-11ea-8a5c-6b62fbbf877b.png)

**What did you expect to happen?**

Not sure what I expected, but did not expect it to just replace `""` with nothing, leaving the JS invalid.

**What actually happened?**

```js
{
  props: {
    foo: "",
  }
}
```

was turned into

```js
{
  props: {
    foo: ,
  }
}
```

**Comment by LinusBorg** [comment]
I'd say this error isn't really be `--fix`-able , as we can only guess that you meant it to be a string and should be `foo: String` instead of `foo: ""`.

**Comment by carestad** [comment]
> I'd say this rule isn't really be `--fix`-able , as we can at best take an educated guess that you meant it to be a string and should be `foo: String` instead of `foo: ""`.

Would that be possible? Or maybe rather assume that `foo: ""` could be rewritten to `foo: null` at least. Or just skip these declarations altogether.

**Comment by LinusBorg** [comment]
Since the developer intent can't be properly inferred, silently assuming null when he developer may expect the prop validation to fail when something besides a string is passed would be dangerous.

**Comment by carestad** [comment]
> Since the developer intent can't be properly inferred, silently assuming null when he developer may expect the prop validation to fail when something besides a string is passed would be dangerous.
> 
> The developer appearantly wanted to define the prop (likely to be a String), but failed to do so in the correct way/syntax, so it should simply fail and not be corrected, leaving that to the developer.

Yeah, I agree on that.

But why is `""` even removed in the first place and not just left as-is? It would at least still work afterwords.

**Comment by ota-meshi** [comment]
Thank you for this issue.

I think it is a bug that the code is deleted.
